### ISSUE TITLE
Use composable to fetch image based on theme and add component testing.

### ISSUE THREAD

**Issue by cquinn540** [activist-org/activist#1008]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

There is a repeated pattern in the Vue components of appending the strings '_dark' or '_light' to the filename to conditionally reference images based on the theme.  I think this logic could be refactored into a composable.

I also think a small refactor like this is a good opportunity to start incorporating component-level testing, which would help with progress for https://github.com/activist-org/activist/issues/432.

My plan is to use [vitest](https://vitest.dev/) since it looks like it is already on the roadmap, and [vue testing library](https://testing-library.com/docs/vue-testing-library/intro/) to test my refactor.  For the scope of this issue, I will focus on running the component tests locally and not add them to the CI/CD pipeline.

I have used the React version of `testing-library` to professionally, and I think it's good balance of being powerful but also relatively easy to learn.

### Contribution

I plan to work on this.

**Comment by andrewtavis** [comment]
Thanks for the issue, @cquinn540! Let us know if you need any assistance :)

**Comment by cquinn540** [comment]
@andrewtavis  I've been able to get the boilerplate down to 1 line of code for color mode mocking.  The relevant file is here is `vitest-setup.ts` which vitest will run before each component test.  I think I might be able to reset the pinia store between tests too in the `afterEach` function.

https://github.com/cquinn540/activist/tree/composable-testing

Planning on taking a break today and looking into pinia and cleaning up the branch with the new main tomorrow.

**Comment by cquinn540** [comment]
I decided to the the sign-in component before the ModalEditAboutOrganization one because it is simpler.  Had to do some serious troubleshooting, but I think I finally got Pinia and I18n working in the tests.

Subsequent tests with these plugins should be much easier to write.

Bit exhausted to fix up the branch and open a PR after that.  I plan on doing that tomorrow.

**Comment by andrewtavis** [comment]
All sounds wonderful, @cquinn540! Thanks for the persistence! Happy to hop on a call tomorrow evening after work to check it all out and merge it in quick 😊

**Comment by andrewtavis** [comment]
Closed by #1015 😊 Thanks for the call earlier and some amazing contributions, @cquinn540! 🙌
