### ISSUE TITLE
Switch to relative links in markdown docs.

### ISSUE THREAD

**Issue by cquinn540** [activist-org/activist#1016]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently the markdown docs use hard coded links to activist's main branch.  This makes it hard to add / change links and see if they work in your fork before merging.

Github supports [relative links](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#relative-links-and-image-paths-in-readme-files).

This would basically be a find and replace where you search for `https://github.com/activist-org/activist/blob/main/` in the markdown files and replace it with the relative file path.

**Comment by andrewtavis** [comment]
This is a great suggestion, @cquinn540! Normally I've done absolute links for projects as if the docs are migrated to another platform they don't work. Kind of an old habit for PyPI for Python where they load your docs into the package index and then the relative links within it don't work. What are your thoughts on this? :) Maybe not as much of a requirement for us.

**Comment by cquinn540** [comment]
Yeah, I see that making sense for a package for PyPI where you know that limitation exists.

But for this project I think you'd be more likely to migrate the docs to a static site generator or hosting service intended for documentation and in that case relative links are more likely to be portable.

**Comment by andrewtavis** [comment]
Closed by #1018 :) Thanks for a great first contribution, @YoSoyAlexElPine! 🚀
