### ISSUE TITLE
Theme menu translations not working

### ISSUE THREAD

**Issue by cquinn540** [activist-org/activist#1022]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Behavior

The aria-labels for the theme menu show raw translated keys.  Also, the `aria-label` attribute appears as `arialabel` in the menu options.

**Comment by andrewtavis** [comment]
Closed by #1023 :) Appreciate you opening this up and getting to it so quickly, @cquinn540! 😊
