### ISSUE TITLE
Modify the Organization Model to Return Related Data on API Request

### ISSUE THREAD

**Issue by momanyisamuel** [activist-org/activist#1028]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Description

The current implementation of the Organization API does not include related data such as org_text and locations in its response. This makes it difficult for the front-end to retrieve complete information in a single request.

The task is to modify the Organization model and API view to return related data seamlessly, ensuring a more efficient and user-friendly response.

**Comment by andrewtavis** [comment]
Closed by #1029 🚀 Thanks for the issue and being so persistent that we need a better solution, @momanyisamuel, and thanks for the implementation, @to-sta!
