### ISSUE TITLE
Switch base mobile view background with theme change

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#103]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that I just realized in playing around with theme selection on mobile is that after the theme is changed the top bar doesn't directly react and still stays the same color as before. Only when the page is reloaded does the top bar then react to the new theme. Beyond this, the color of the base view for dark mode appears to be content background instead of the header background, so there's a different color that's behind the battery indicator and other information than the header. On light mode it's correct where the color behind the battery indicator is the same as the header :)

This is at least happening on Safari. Not sure on other mobile browsers.

### Contribution

Will work on this soon, but also happy to support someone who wants to give it a try! 😊

**Comment by DaniKline** [comment]
If you haven't already started working on it, I'd like to take this on

**Comment by andrewtavis** [comment]
Hi @DaniKline! 👋 Sounds great 😊 Will assign you now, and let me know if you need any assistance on it.

**Comment by andrewtavis** [comment]
Thanks for your efforts and the documentation, @DaniKline! So long as this doesn’t change the background color of the pages it could definitely work :) I’m not 100% sure myself, but we could try to open a PR and then check how it looks in the Netlify preview? 🤔

**Comment by andrewtavis** [comment]
Post c199e1a the mobile header background is changing with the system color change, but on Safari it still needs a page reload. This isn't ideal, but works for now. Thank you @DaniKline for the contribution and the discussion to find the current solution!
