### ISSUE TITLE
Pin versions of testing dependencies

### ISSUE THREAD

**Issue by cquinn540** [activist-org/activist#1032]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Description

I realize I forgot to have the new component test dependencies pinned to specific versions like the rest of them.  Given that people are occasionally having installation issues, having everything pinned reduces the amount of updates to `yarn.lock` which makes it easier to notice unexpected changes to it.

This was inspired by this potential installation issue: https://github.com/activist-org/activist/issues/1025

**Comment by cquinn540** [comment]
Not sure what the appropriate label for this is

**Comment by andrewtavis** [comment]
I guess we can do `dependencies` for issues like this in the future, @cquinn540 :) Appreciate you making it and getting to it so quickly!
