### ISSUE TITLE
Change sidebar collapse control to bar with arrow

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#104]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In checking out the [Superset](https://superset.apache.org/) UI a bit I was really happy with how their sidebar collapse is styled. Rather than our circle and arrow they have a bar and arrow that fits nicely into the sidebar UI without extending outside its bounds. I've updated the [sidebar components in Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?node-id=1606%3A585&t=E3DkGZjORnkA1TsJ-1) to reflect these changes. This issue would simply be replacing the circle and arrow within [frontend/components/Sidebar/SidebarHeader.vue](https://github.com/activist-org/activist/blob/main/frontend/components/Sidebar/SidebarHeader.vue) with a bar and arrow variation 😊

We'll need to find a functioning icon for this from [icones](https://icones.js.org/) :)

### Contribution

Happy to work on this myself or support someone who has interest 😊

**Comment by om-ray** [comment]
@andrewtavis Hi, I'm new to the codebase, and I think this would be a great first issue. Please assign this to me when you can!

**Comment by andrewtavis** [comment]
Closed via 833edea :)
