### ISSUE TITLE
SidebarLeftMainSectionSelectors doesn't have route highlighting for localized routes

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#1042]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Description

Something that's been noticed on a call with @Aya-Abdel-Hamid, @shgxshg and others is that the route highlighting within the left sidebar doesn't work on localized routes. This can be seen by switching the localization of the platform to French or German, and then visiting an organization or event route. The expectation is that the route would be highlighted as below:

![Screenshot 2024-12-07 at 12 34 34](https://github.com/user-attachments/assets/d8cc65d0-9bd5-4a4c-a777-77e9ac818bbe)

But what we're seeing is:

![Screenshot 2024-12-07 at 12 35 03](https://github.com/user-attachments/assets/c3c9a156-6f38-45d6-908e-1327a0fc8b77)

The file for this change is [frontend/components/sidebar/left/SidebarLeftMainSectionSelectors.vue](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftMainSectionSelectors.vue), with `isRouteActive` from [frontend/utils/routeUtils.ts](https://github.com/activist-org/activist/blob/main/frontend/utils/routeUtils.ts) being the function that isn't working if the route is localized (/en, /de or /fr in the route).

### Contribution

Happy to assist and review as needed 😊 Note that this issue is reserved for a group of students :)

**Comment by andrewtavis** [comment]
We could get the route via `console.log(`Route: ${JSON.stringify(route)}`);` within `isRouteActive` of [frontend/utils/routeUtils.ts](https://github.com/activist-org/activist/blob/main/frontend/utils/routeUtils.ts) :)

**Comment by Aya-Abdel-Hamid** [comment]
Issue resolved. 
<img width="707" alt="image" src="https://github.com/user-attachments/assets/0f2a9f52-31b2-4e6e-be9c-881777fa57cd">

**Comment by andrewtavis** [comment]
Fantastic, @Aya-Abdel-Hamid! Do you want to open a PR for it? :)

**Comment by Aya-Abdel-Hamid** [comment]
Thank you @andrewtavis ! Yes I would like to open a PR for it.

**Comment by andrewtavis** [comment]
Let us know if you need any help with sending the PR along, @Aya-Abdel-Hamid 😊

**Comment by andrewtavis** [comment]
Closed by #1053 🚀 Thanks for the great work here, @Aya-Abdel-Hamid! 😊

**Comment by andrewtavis** [comment]
Assigning so you have a bit more credit, @Aya-Abdel-Hamid :) Thanks again!
