### ISSUE TITLE
Fix sidebar icon positioning

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#107]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

An issue with the sidebar that can be found on the [home page](https://activist.org/home/) is that the icons are not centered properly. Especially when the sidebar is collapsed it's apparent that the two icons that are in [components/Sidebar/SidebarMainSectionSelectors.vue](https://github.com/activist-org/activist/blob/main/frontend/components/Sidebar/SidebarMainSectionSelectors.vue) are slightly to the right and the three that are in [components/Sidebar/SidebarFooter.vue](https://github.com/activist-org/activist/blob/main/frontend/components/Sidebar/SidebarFooter.vue) are slightly to the left within their respective containers. It'd be great if these could be centered 😊

This is a `good first issue` and help is welcome for those who want to work on this. I'm happy to support someone who wants to give this a go :)

**Comment by momanyisamuel** [comment]
Hi @andrewtavis I can take a look at this I think

**Comment by andrewtavis** [comment]
Thanks, @momanyisamuel! Will assign you now 😊 Let me know if there are any questions. The edits to the footer icon positions should go right into [components/Sidebar/SidebarFooter.vue](https://github.com/activist-org/activist/blob/main/frontend/components/Sidebar/SidebarFooter.vue) and for the `MainSectionSelectors` it should be editing the [components/MenuSelector.vue](https://github.com/activist-org/activist/blob/main/frontend/components/MenuSelector.vue) :)

**Comment by momanyisamuel** [comment]
@andrewtavis this seems to affect the transition timing slightly but the is no overlapping as before. Maybe you could assist with the transition timing??

**Comment by andrewtavis** [comment]
@momanyisamuel, 599712b does some final adjustments for this. The icons are note perfectly centered, but for me they're maybe a pixel off in certain places. More to the point they look centered 😅 Also we should note that for the future the activist `a` can't be centered on the other icons and should be as it is now - a few pixels over to the left so that the curvature of the `a` can be displaced a bit.

Thanks again for your support! Lots of more issues coming soon as we'll be making the ones for the hackathon next Wednesday in the coming days :D

**Comment by momanyisamuel** [comment]
Nice glad i was able to assist.
