### ISSUE TITLE
Click to expand mockup images

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#108]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Mockup images have been added to the following pages in #84:

- https://activist.org/en/docs/get-active
- https://activist.org/en/docs/get-organized
- https://activist.org/en/docs/grow-organization

Some of the features for the mockups are pretty small, so it would be great if a visitor was able to click the image and it would expand. This is only needed for desktop as the user can scroll into the image on mobile :)

### Contribution

Would be happy to support someone with this if there's interest! This should be a relatively manageable `good first issue`. Also happy to work on it myself 😊

**Comment by Zwnow** [comment]
I can give it a shot, this sounds manageable!

**Comment by andrewtavis** [comment]
Wonderful, @Zwnow! Thanks so much for your interest in activist 😊 Will assign you now. Generally I think that some kind of a centered pop up on click or something similar would be great for this, but also open to your suggestions :)

**Comment by andrewtavis** [comment]
Sounds great! :)

**Comment by Zwnow** [comment]
Quick update:
Never worked with Vue.js but I am getting the hang of it (as it is quite similar to React). 
Created a popup component and extended the script on the according views. Unfortunately I do not know any Vue best practices so I just try to do it as clean as possible. 

Todays result:
Mockup popup works but needs some tweaks and styling. I will continue tomorrow.

Approach: 
Created a popup component which i implemented into the according views. I toggle the "hidden" class with a v-on:click trigger which I added to the images, so the popup components visibility gets toggled.

Is this a good approach? 

Thanks again for giving a chance with this!

**Comment by andrewtavis** [comment]
> Created a popup component which i implemented into the according views. I toggle the "hidden" class with a v-on:click trigger which I added to the images, so the popup components visibility gets toggled.
>
> Is this a good approach?

Makes sense to me 😊😊 There doubtless will be a styling discussion, but I think we’ll be good to start a PR and talk over how it all should look 🚀 

> Thanks again for giving a chance with this!

Thank you for contributing! Really happy to have this up and running so soon after I got the mockups all finished up :) :)

**Comment by andrewtavis** [comment]
@Zwnow, just FYI, #109 also focussed on these images, so keep an eye out that there are changes for you to pull :)

**Comment by Zwnow** [comment]
Got you, I'll take a look if I can solve that too. 😁

**Comment by andrewtavis** [comment]
Already solved :) Just the pages that you’re working on have some changes that are potentially not noticeable (was a bit broken on Safari below the small break point).

**Comment by Zwnow** [comment]
Ok I sent a PR! I messed up the first PR as I never created one. I filled out the according PR template but somehow I can not see it in the created PR, hopefully you can see everything.

The PR was a bit messy but I hope everything else is fine!

**Comment by andrewtavis** [comment]
Will do a minor commit tomorrow with some changes to fine tune all this that I'd like to be able to play around with rather than ask you to change and change back, @Zwnow 😊 Will let you know what the changes are and close the issue after that :)

**Comment by Zwnow** [comment]
Sounds good to me, thanks for letting me know! :D
