### ISSUE TITLE
Add Information about Docker Desktop under Environment Setup in README

### ISSUE THREAD

**Issue by TeddyGavi** [activist-org/activist#117]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Continuing the conversation from #113  

Update Documentation:

Re:  @andrewtavis 
>  I agree as well that an initial commit to the readme and contributing markdown files that references Docker Desktop for those new to Docker would be a great idea and a simple way to get @TeddyGavi his first commit :) :)

:rocket: 

### Contribution

I will add one or two sentences to README.md that point to the [Docker Desktop ](https://docs.docker.com/desktop/install/ubuntu/ ) install.

**Comment by andrewtavis** [comment]
Thanks @TeddyGavi! Would be great to also include the point about Docker Desktop in the [development env section of the contributing file](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#dev-env) :)

**Comment by TeddyGavi** [comment]
@andrewtavis Right! no problem.

**Comment by andrewtavis** [comment]
Closed via #123. Thanks again @TeddyGavi! 😊
