### ISSUE TITLE
Hide search bar hotkey indicators when user starts typing

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#118]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to hide the hotkey indicators for `/` and `^ / ⌘k` in the search bar once the user starts typing. activist is going for a condensed menu design, but because of this we don't have as much real estate to work with. We thus need these icons to disappear so that the user can see the full search prompt for longer entries. The changes for this issue would be made in [frontend/components/SearchBar.vue](https://github.com/activist-org/activist/blob/main/frontend/components/SearchBar.vue).

Note that currently the search bar can only be seen on [activist.org/home/](https://activist.org/home/). We'll have a longer search bar on the landing page for non-logged in users, and maybe this version of it wouldn't need this to happen, but this is something to consider in the future :)

### Contribution

Happy to work on this with someone or get to it myself in the future! 😊

**Comment by andrewtavis** [comment]
> We'll have a longer search bar on the landing page for non-logged in users, and maybe this version of it wouldn't need this to happen, but this is something to consider in the future :)

Would be interesting if we could solve this within this issue as well. Maybe would be as simple as checking whether the parent of the `SearchBar` component is the `Sidebar`.

**Comment by samcdonovan** [comment]
Hello @andrewtavis, I am happy to help work on this issue

**Comment by andrewtavis** [comment]
Hey @samcdonovan! Thanks for your interest in activist and you’re willingness to help :) Really happy to assign 😊 Let me know if I can assist in any way!

**Comment by samcdonovan** [comment]
@andrewtavis thank you very much for assigning me to this issue! I have finished working on it and pushed it to my fork, and the commit can be found here: eb30b9bc4b92ef2b699490bafa9966e48eb23097. Should I open a pull request now?

**Comment by andrewtavis** [comment]
You’re very welcome to open a PR and we can then take a look at how it’s working on the Netlify preview :) Thanks for the hard work, @samcdonovan!! 🙏
