### ISSUE TITLE
Events search result component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#121]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create parts of the search result component that is being made in #119. We want the features made in this issue to be conditionally switched to based on the whether `event` is passed to the aforementioned component's props :)

The designs for this component can be found on the [Components tab in Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1606%3A585&t=5CR5mIoy4P0OjwjS-1) and can further be seen below:

![Mode=Light, Mobile=False, Type=Event, Reduced=False](https://github.com/activist-org/activist/assets/24387426/2efcc6e5-c1df-4328-846c-1077407a373d)

Mobile:

![Mode=Light, Mobile=True, Type=Event, Reduced=False](https://github.com/activist-org/activist/assets/24387426/b7ae4fa4-558a-43da-955c-67701e725df2)

- This issue is blocked by #119 that makes the baseline component

### Contribution

Happy to provide to support to someone with interest in working on this, or will also get to it eventually 😊

**Comment by andrewtavis** [comment]
Assigning myself to hold this issue for the team working on it for Code Night 🌙😊

**Comment by andrewtavis** [comment]
I'll also make a component for the event icon that has the type color indicator on the left :)

**Comment by andrewtavis** [comment]
@james-jenkinson, FYI there's a component for the event icon now as seen on the [home page](https://activist.org/home/). Basically fills whatever `div` it's put into vertically and is centered at 85% width with the intent being that we'll put it into square containers :)

**Comment by andrewtavis** [comment]
@anthonyshibitov, can you write in here so I can assign this to you? The changes on my end will be going out later this evening :)

**Comment by anthonyshibitov** [comment]
Gotcha

**Comment by andrewtavis** [comment]
Post pull you're good to start working on this, @anthonyshibitov :) Your template event icon is also found in [frontend/components/Icon/IconEvent.vue](https://github.com/activist-org/activist/blob/main/frontend/components/Icon/IconEvent.vue). Let me know if you have any questions!

**Comment by anthonyshibitov** [comment]
Awesome thanks :D (get some sleep!!!!!)

**Comment by anthonyshibitov** [comment]
Is there a specific folder this component should go into?

**Comment by andrewtavis** [comment]
Editing the `CardsSearchResult` component would be fine for this so we can just pass what kind of result it is :)

**Comment by andrewtavis** [comment]
In that component we have `searchResultType: "organization" | "event" | "resource"`, so your implementation would be based on `v-if=“searchResultType”‘ event’”` 😊

**Comment by andrewtavis** [comment]
Thanks for the work on this, @anthonyshibitov! Something similar for #122 would be great, if you have time :) Feel free to write in the issue and I'll assign 🙃
