### ISSUE TITLE
Add transition to search bar icon hide/appear

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#125]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

After #118 the hotkey indicators are hid when the search bar is focused. This issue is a very simple one to add a transition duration to this change so that it’s no so immediate. The change for this would go into [frontend/components/SearchBar.vue](https://github.com/activist-org/activist/blob/main/frontend/components/SearchBar.vue). 

### Contribution

This issue is a `good first issue` and perfect for someone who wants to get a bit of experience with the code base :) Would be happy to support someone who’s interested!

**Comment by TeddyGavi** [comment]
Hello! Considering @samcdonovan did #118 I don't want to step on any toes, but I would like to take this one on.

**Comment by andrewtavis** [comment]
All good, @TeddyGavi! I realized that a bit of a transition would be good only after merging #118 :) You’re welcome to work on this 😊

**Comment by andrewtavis** [comment]
Assigned and looking forward to the contribution, @TeddyGavi!

**Comment by andrewtavis** [comment]
Closed by #132 😊 Thanks, @TeddyGavi! 🙏 Again pleasure talking to you :) :)
