### ISSUE TITLE
Mobile navigation bar component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#131]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create the mobile navigation bar component - `MobileNavBar.vue` - that will be used to switch main sections within the app. Deigns for the component can be found in the [Figma design components](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=766%3A214&t=PSp94OrmSUKXQVUK-1) and further can be seen below:

![Mode=Light, Buttons=3](https://github.com/activist-org/activist/assets/24387426/b1f699d8-b634-41e0-b48a-7101ce5651a5)

The icons should come from [Bootstrap Icons in Icones](https://icones.js.org/collection/bi). We'll develop the organizations icon in another issue :)

### Contribution

Happy to work on this or support someone who'd like to work on it! 😊

**Comment by DalvisL** [comment]
Hey! Thanks for holding it for me.

**Comment by andrewtavis** [comment]
Very happy to, @DalvisL! Thanks for your interest in activist! Let me know if you need some support with this 😊

**Comment by andrewtavis** [comment]
We can do a call this evening sometime if you'd like :) We're doing Code Night 😊 Feel free to write here or email me in the email that's in my GH profile.

**Comment by andrewtavis** [comment]
Hey @DalvisL 👋 Was quite busy over the last two days with Code Night and all the review it created yesterday. I’m off today and have time for a call tomorrow as well. Let me know and we can set something up!

**Comment by andrewtavis** [comment]
@DalvisL - just FYI I'm gone this weekend and have a crazy busy week coming up, but maybe the following weekend we could do the call if you're still interested 😊

**Comment by andrewtavis** [comment]
@DalvisL, I'm gonna unassign for now so that others can have an opportunity to work on this, but let me know if you still have interest :)

**Comment by Mradosi** [comment]
@andrewtavis  I can work on it but does this task only involve creating a bottom-placed menu on the page - only this element you shared on the screenshot? I'm asking because I see that top menu and mobile sidebar also aren't implemented yet.

**Comment by andrewtavis** [comment]
@Mradosi, this would only be the bottom menu for now, yes :) We can make another issue for the top menu.

**Comment by andrewtavis** [comment]
Assigning you now!

**Comment by andrewtavis** [comment]
Closed via 8fbb41a 🥳 That commit's mostly code formatting for this issue and also includes some minor changes to make sure that the routes that you laid out are working properly, @Mradosi :) Thanks again so much for all this! Looking forward to working with you again soon 😊
