### ISSUE TITLE
Connect card component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#133]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create a card component that will house the means of connecting with an organization or event organizers. The component should make use of the custom `card-style` Tailwind CSS class to provide colors, corner rounding and width. An example of this component can be found in the [Figma designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=766%3A214&t=2a7k5T7ji0MelYTs-1) and can further be seen below:

![Connect](https://github.com/activist-org/activist/assets/24387426/684778b0-5ec1-4b3f-9010-5b2e948e1b07)

Mobile:
![Connect](https://github.com/activist-org/activist/assets/24387426/563c3dbe-4371-4062-bb0b-7c7f75b2777a)

Whether the new account button is always available for admins or they need to hit the edit key is still up for discussion :)

### Contribution

Happy to work on this or assist someone with interest in working on it! 😊

**Comment by guaregua19** [comment]
Hi @andrewtavis happy to work on this feature, can you assign it to me?

**Comment by andrewtavis** [comment]
Hey @guaregua19! Thanks for your interest in activist :) Just assigned. Please let me know if you need any support!
