### ISSUE TITLE
Sidebar menu component for organizations

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#134]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is currently blocked by #85, but I'll be working on this shortly. We'd like to take the base component being worked on in #85 and add the parts of it that will be inserted for organization pages. This component can be seen in the [designs in Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=766%3A214&t=2a7k5T7ji0MelYTs-1) and further is shown below:

![Section Selectors](https://github.com/activist-org/activist/assets/24387426/aeabfb11-b2df-43d9-8cbb-0587c24a66de)

Note that there shouldn't be a background for the component and it should be transparent over the sidebar background.

### Contribution

Happy to work on this myself or support someone with interest in creating this component 😊

**Comment by momanyisamuel** [comment]
just been wondering @andrewtavis this component has several elements we have created why not make them reusable here so the sidebar transition is not affected??

**Comment by andrewtavis** [comment]
Assigning myself to hold this issue for the team (of one 👏) working on it for Code Night 🌙😊

**Comment by andrewtavis** [comment]
Hey @Masa-99, FYI you're not showing up in the contributors as of now as there appears to be a mismatch between the email/account you did the commits with and the one you have for Git. The [email that you use for GitHub](https://github.com/settings/emails) should be the same that you have for `git config --global user.email` or locally for the repo :) Hopefully if you fix that you'll be added to the contributors graph 😊

**Comment by andrewtavis** [comment]
Also, @Masa-99, I'm thinking that the problem you were running into for not being able to access the tech from below logo .svg file was because it was in `frontend/assets` instead of `frontend/public/...` :) That's the convention for Nuxt 🙃 For that you'd just need to do `"/images/tech-from-below.svg"` as everything within public is accessible via strings in this way 😊

**Comment by andrewtavis** [comment]
I've made tons of progress on formatting and some other things for this and #135. Will commit later this evening 😊

**Comment by andrewtavis** [comment]
Closed via https://github.com/activist-org/activist/commit/bf029de799df6f38c96bc987ff255eaf014f08bf 😊 Thanks so much, @Masa-99! Let me know on the points I raised above - specifically on the potential Git email issue :)

**Comment by andrewtavis** [comment]
Closed via https://github.com/activist-org/activist/commit/bf029de799df6f38c96bc987ff255eaf014f08bf 😊 Thanks so much, @Masa-99! Let me know on the points I raised above - specifically on the potential Git email issue :)
