### ISSUE TITLE
Topic marker component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#136]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create a component for topic markers for activist. Topic markers will be how we show what movements the event or organization are related to. These markers can be seen in the [designs in Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1986%3A1046&t=2a7k5T7ji0MelYTs-1) and an example can also be seen below:

![Topic Tag](https://github.com/activist-org/activist/assets/24387426/2434c749-0eef-4195-987b-f1f205b27393)

This is a great `good first issue` for someone wanting to contribute to activist :)

### Contribution

Happy to work on this eventually or support someone who wants to give this a try 😊

**Comment by samcdonovan** [comment]
Hey @andrewtavis, I'd love to work on this issue! I know you're doing a Code Night today, so does this need to be finished by then?

**Comment by andrewtavis** [comment]
You’d be welcome to work on this, @samcdonovan! We don’t need it to be finished by the end of code night, so no stress :) :)

Assigning you now 🙃

**Comment by samcdonovan** [comment]
@andrewtavis thanks for assigning me! Just a quick question: I know these markers will have different text based on the type of organisation but will the icon and colour also differ?

**Comment by andrewtavis** [comment]
Closed via #141 😊
