### ISSUE TITLE
Image carousel page media component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#137]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to work on the image carousel that will be present on organization pages. On large screens this will be found to the right of the about section for the organization and will have images that the organization has added to represent their team/work. An example can be seen in the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1998%3A2577&t=sYF0QkAOBUxfAMJd-1) as well as the image below:

![Page Media](https://github.com/activist-org/activist/assets/24387426/12ba5f4a-67b0-4b20-911e-10e387252672)

### Contribution

Happy to work on this or support someone who has interest in contributing! 😊

**Comment by andrewtavis** [comment]
Hey @nikhilagastya! Thanks for your interest in activist :) :) Want to check with you quickly on what your experience is to make sure that this issue is within your abilities. There will be a bunch more `good first issues` available in the coming days that you could also do. Just want to make sure I’m not putting undue pressure on you 😊

**Comment by andrewtavis** [comment]
Sounds good, @nikhilagastya :) Hopefully similar code can be applied within this issue 😊

**Comment by nikhilagastya** [comment]
hey @andrewtavis i have a problem launching up the application, could you help me out with that 
![Screenshot 2023-05-18 152445](https://github.com/activist-org/activist/assets/72994295/87448fe9-9b32-40dd-b65e-3795eea9ef0d)

**Comment by andrewtavis** [comment]
This is a common issue, @nikhilagastya. I think there should be an answer to it in #113, but if it persists please let me know 😊

**Comment by andrewtavis** [comment]
Hopefully we can get the setup a bit more fluid going forward. Sorry that you ran into problems :(

**Comment by nikhilagastya** [comment]
alright and another thing @andrewtavis the figma says the route has /organizations, but then that route doesn't exist ,can you tell me where exactly do we need the carousel

**Comment by andrewtavis** [comment]
Yes we're just hard coding things right now, sadly. Will start on backend work momentarily. A basic place that you could put the component for testing would be on https://activist.org/home/ :) Aside from that we were working on making an organization page yesterday at our Code Night, with that page being https://activist.org/organizations/tech-from-below/. That page would need the carousel as seen in the designs 😊

**Comment by nikhilagastya** [comment]
alright @andrewtavis ,thanks for your help !!

**Comment by andrewtavis** [comment]
Very welcome! Thanks for checking in 😊

**Comment by andrewtavis** [comment]
You're welcome to just put the carousel on the page beneath the other elements for now, and from there we can add it to the page and reduce the width of the about card once #129 is done :) :)

**Comment by nikhilagastya** [comment]
hey @andrewtavis can u please check the PR .

**Comment by andrewtavis** [comment]
Closed via #155 🥳 Is looking good [on the website](https://activist.org/organizations/tech-from-below/), @nikhilagastya! Just need to get some more components done and then we make the layout that'll put it where it needs to go in #139 :)

Thanks again!
