### ISSUE TITLE
Event about page layout

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#138]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create the layout that will be used to populate event about pages. The layout should include the sidebar, the footer, and the cards to describe the event including about, a page media map (a placeholder is fine for now), connect, join, etc. There also should be a title and an optional tagline (without a tagline the page elements should still be in the same place).

An example of this layout can be seen in the [designs in Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=766%3A214&t=sYF0QkAOBUxfAMJd-1) as well as below:

![Event About](https://github.com/activist-org/activist/assets/24387426/52f3dc00-3034-422b-a5b5-9aa432a999ec)

### Contribution

Would be great to work on this issue with someone!

**Comment by andrewtavis** [comment]
This issue is blocked until some of the components needed are finished :)

**Comment by andrewtavis** [comment]
Assigning myself to hold this issue for the team working on it for Code Night 🌙😊

**Comment by andrewtavis** [comment]
Hey @samcdonovan! The required components aren't finished as of now, but you could start working on the basics of this like including the sidebar, header, tagline and the various buttons at the top?

**Comment by andrewtavis** [comment]
If you're in the mood for something more ambitious, the map view is something that's definitely not finished :) We'd need to find a module or another kind of dependency to get it all up and running, so some research into that would also be super helpful 😊 Whatever sounds most fun 🙃

**Comment by samcdonovan** [comment]
Sure, I'll do the basic layout for now and once all of the required components are done, I can put it all together.

Yeah, I'd also definitely be up for doing the map view! I guess the most obvious choice would be to use the [Google Maps API](https://developers.google.com/maps/documentation) (which I have a bit of experience with) but if you're against using that I can research other options?

**Comment by andrewtavis** [comment]
Wonderful :) :) Let me know if there's anything that I can do to help with the layout. You have most of the base components, and we're just waiting on people to finish the work from Code Night 😊 Will assign you now 🥳

As far as the map component, let me make an issue for it shortly so we can take up the discussion there. My preference would be to use [OpenStreetMap](https://www.openstreetmap.org/#map=6/51.330/10.453) so we keep to open source :) Obviously not as flashy as Google Maps, but then it'd be great if we could also make a connection with the OSM community. My involvement in Wikidata will doubtless help as there's tons of interactions between the two communities 😊

**Comment by samcdonovan** [comment]
Hey @andrewtavis, I've been super busy this past month and haven't made much progress with this. I hope you've been well! I've just noticed that the Organisation about page (#139) is currently being worked on and is also very similar to the Event about page. I have more time now to work on this now if you still want me to, but if you'd rather give this issue to the contributor working on the Organisation about page, I'm more than happy for you to do that!

**Comment by andrewtavis** [comment]
Hey @samcdonovan! No stress whatsoever on timing :) Pleasure to talk with you again 😊 Let’s loop @momanyisamuel into this discussion and maybe both of you can discuss who takes both from this as I agree that the work is very similar. There are other issues you can pick up, or he’s also working on #176, so maybe he’d be fine with you taking the layouts :) :)

**Comment by momanyisamuel** [comment]
yeah sure no problem with me @andrewtavis feel free to reassign this to @samcdonovan as i work on #176

**Comment by andrewtavis** [comment]
Hey @samcdonovan :) Just a quick checkin on this and #139. Let me know if you need any help with them! Also, if you're free would be great to have you in a call this Saturday with the rest of the dev team! Time is 15:00 UTC 🙃 I'll send details for it to the chat later on today :)

**Comment by samcdonovan** [comment]
Hey @andrewtavis, sorry again for the delays. I finished the page today and was wondering if you wanted the file to be in `/pages/events` ?

And sorry for missing the call!

**Comment by andrewtavis** [comment]
Hey @samcdonovan! No stress on the delays! :) Glad to hear that there's progress here 😊 I think that it generally would go in  the [layouts](https://github.com/activist-org/activist/tree/main/frontend/layouts) directory of the frontend, and then we can just call it for all pages in that directory when we're populating from the backend :)

Looking forward to connecting on a call! Also happy to do a quick one to introduce ourselves at some point if you have some availability next week :)

**Comment by samcdonovan** [comment]
Oh okay, I've just realised that this should be a layout and not a page. I originally built it as if it were a page, but I am not too familiar with Vue layouts so I'm not sure how to go about changing it to be a layout. If you want, I could create a pull request with what I've got and you could have a look and instruct me further?

**Comment by andrewtavis** [comment]
To be honest I'm not too familiar myself, so it's a learning process for both of us 😊 I'd say if you wanted switch what you have over to `layouts/event.vue` and then send it along that'd be fine! We can then talk it over in the PR and make the necessary edits :)

**Comment by andrewtavis** [comment]
I'd assume that we want to be able to populate everything we need for the various components via the layout, so the `<script>` block will need to account for that. We can check the [docs](https://nuxt.com/docs/guide/directory-structure/layouts) a bit as well. I read them a few months ago and it seems easy enough 😊

**Comment by andrewtavis** [comment]
Will close this so we can focus on #139 now :) Thanks @samcdonovan!

**Comment by andrewtavis** [comment]
Hey @samcdonovan, quick reminder that there's the dev sync in an hour and a half! Info is in the [Development](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org?via=matrix.org&via=acter.global&via=chat.0x7cd.xyz) channel on Matrix 😊
