### ISSUE TITLE
Organization about page layout

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#139]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create the layout that will be used to populate organization about pages. The layout should include the sidebar, the footer, and the cards to describe the organization including about, a page media image carousel, connect, join, etc. There also should be a title and an optional tagline (without a tagline the page elements should still be in the same place).

An example of this layout can be seen in the [designs in Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=766%3A214&t=sYF0QkAOBUxfAMJd-1) as well as below:

![Organization About](https://github.com/activist-org/activist/assets/24387426/fdeeb489-293a-444e-9582-6267f5adbe96)

### Contribution

Happy to discuss and work on this with someone!

**Comment by andrewtavis** [comment]
This issue is blocked until some of the components needed are finished :)

**Comment by andrewtavis** [comment]
Assigning myself to hold this issue for the team working on it for Code Night 🌙😊

**Comment by momanyisamuel** [comment]
Hi @andrewtavis happy to work on this if all components are ready

**Comment by andrewtavis** [comment]
I think they generally are :) Let me merge/close the PR #134 and #135 and we can start in on this once we have the sidebar menu up and running 😊

**Comment by andrewtavis** [comment]
@momanyisamuel, now that we have https://github.com/activist-org/activist/issues/134 and https://github.com/activist-org/activist/issues/135 closed we're good to start on the layouts :) Should be similar to the current sidebar layout, but we can add in the other needed components and handle reactive styling within one file. Lots will be repeated in #138 as generally at least the top of event and organization pages should be consistent 😊

**Comment by andrewtavis** [comment]
Just assigned. Hope you're having a nice weekend!

**Comment by andrewtavis** [comment]
@samcdonovan, as discussed in #138, you'd be welcome to work on this one as well :) Feel free to write in here and I'll assign. The work that went in to #208 with the image carousel rather than the map and some other minor edits should be what we're looking for 😊

**Comment by andrewtavis** [comment]
As a part of this we can also implement the layout for the demo pages we have for events and organizations, i.e. `Brandenburg Gate Climate Demo` and `tech from below` :) Also happy to do that after a review for the PR for this issue.

**Comment by andrewtavis** [comment]
Closed via f95ec65 and 6e2e611. Event and organization about layouts are now in `[id]/about.vue` within their respective `/pages` directories 😊
