### ISSUE TITLE
Feed card component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#142]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create a card component in `Cards` for groups that can then be shared within a "Get involved template" or on other page elements :) For the get involved we'd have working groups that the user could join, for example.

Generally this would look like the following:

![Feed Element](https://github.com/activist-org/activist/assets/24387426/74e9fc81-c440-4b55-bd9a-eb4e71f99787)

We need a name and then a short description, and for now we can just do a rectangle for an image placeholder.

### Contribution

Happy to get some support on this, @momanyisamuel 😉😉😉

**Comment by andrewtavis** [comment]
@momanyisamuel, I think that making this more a general feed element makes sense :) This could also be a social media element like below:

![Feed Element (1)](https://github.com/activist-org/activist/assets/24387426/0f42a857-2f04-4be5-b3c8-2018fec2c746)

**Comment by momanyisamuel** [comment]
working on this @andrewtavis , will fix the changes in the morning and do another PR

**Comment by andrewtavis** [comment]
Assigned! Thanks @momanyisamuel :)

**Comment by andrewtavis** [comment]
Closed via #145 🥳 Thanks @momanyisamuel!
