### ISSUE TITLE
Add h1 and h2 tags for landing page header and section headers

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#149]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This is a simple and very good `good first issue` where the goal is to make sure that the elements on the landing page are accessible. We want the main header "Where we start" within [LandingPage/LandingPageSplash.vue](https://github.com/activist-org/activist/blob/main/frontend/components/LandingPage/LandingPageSplash.vue) to be `<h1>` and each of the headers within [LandingPage/LandingPageContent.vue](https://github.com/activist-org/activist/blob/main/frontend/components/LandingPage/LandingPageContent.vue) to be `<h2>`.

### Contribution

Would be happy to support someone who wants to contribute!

**Comment by thefloofe22** [comment]
Am interested. Is this still up for grabs? Pleasure to meet you @andrewtavis

**Comment by andrewtavis** [comment]
Hey @thefloofe22! Pleasure to meet you too and thanks for your interest in activist 😊 Yes this is still open :) Will assign you now, and please let me know if you have any questions!

**Comment by thefloofe22** [comment]
Hi @andrewtavis!! Thanks so much for the prompt response. Excited to contribute. Took a quick skim through the files linked in the original description after forking the repo. The changes seem straightforward, but I just wanted to clarify before making the changes. For the first file(LandingPage/LandingPageSplash.vue), was the idea that the landing-header on line 9 should be <h1>, and for the second file(LandingPage/LandingPageContent.vue), every mention of header such as line 25 should be <h2>? Thanks again for the prompt and warm response.

**Comment by andrewtavis** [comment]
Hey again @thefloofe22! Thanks for checking in :) Your understanding is correct. Currently there are `<p>` tags around those elements, and it would be great if they were replaced by h1 and h2 as you described :)

**Comment by thefloofe22** [comment]
Sorry for the delay!!! Took a while setting up docker on my laptop, and getting the project setup. Just submitted a PR that addresses the issue titled "header changes(Add h1 and h2 tags for landing page header and section headers )".

**Comment by andrewtavis** [comment]
Thank you, @thefloofe22! Really excited to have this contribution in :) Thanks for helping us make the platform more accessible 😊

**Comment by andrewtavis** [comment]
Closed via #158 😊 Thanks @thefloofe22 for the great first contribution! Also thanks @anthonyshibitov for the reference there and making my life easier 🙏
