### ISSUE TITLE
OpenStreetMap media component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#152]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would focus on creating the map media component for events on activist.org. The preference would be that this would make use of the [OpenStreetMap api](https://wiki.openstreetmap.org/wiki/API) so that activist can continue to align its technology with free, open-source communities. It'll also make it easier to work with Wikidata later 🙃

Deisgns for this component can be found in the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=62%3A2&t=ydwzf7PjjXr9DPuW-1) and can further be seen below:

![Page Media](https://github.com/activist-org/activist/assets/24387426/1297f8cf-698e-43d1-8434-ff03913efe64)

Generally I'm thinking this component could be called `MediaMap`, but am open to suggestions.

### Contribution

Would be really great to get some help with this! Happy to support as I can 😊

**Comment by andrewtavis** [comment]
@samcdonovan 🙃

**Comment by samcdonovan** [comment]
I think using the OpenStreetMap API is a great idea! And for now I think `MediaMap.vue` is a good name for the component too. I'll get working on it right away!

**Comment by andrewtavis** [comment]
🔥🔥🔥🔥

Thanks, @samcdonovan! Let me know if you need some help! :)

**Comment by samcdonovan** [comment]
So it seems like `OpenStreetMap` doesn't currently offer a way to embed a map on the frontend. I have seen solutions that use either [Leaflet](https://leafletjs.com/) or [OpenLayer](https://openlayers.org/) to create the map using an OpenStreetMap URL. I think I'll look into that later today when I have more time

**Comment by andrewtavis** [comment]
Thanks for the initial research, @samcdonovan! [Leaflet](https://leafletjs.com/) is the one that I've seen before, but let me check both again right now. The ability to map out routes is something to consider in this for a feature that would be really useful and might not be as intuitive in one as it is in the other. So by this I mean that say we want to put the route of a protest onto a map so that people know where they're walking/biking (driving protests where I am are not really the kind we'd want on the platform 😅), and further would be able to more easily catch up if they come late or fall behind.

**Comment by andrewtavis** [comment]
Looks like we'd be able to do custom vectors in any of the above as well for the routes, so let's just discuss what you find out :) Between the original two mentioned I guess I'd side with [Leaflet](https://leafletjs.com/), and it might still also win out over [mapbox](https://www.mapbox.com/) as the whole get an account thing seems to indicate that it might not be what we're looking for.

**Comment by samcdonovan** [comment]
Okay I think I'll experiment with Leaflet and OpenStreetMap (OMS) and just do the basic Map component with that. After that's done I'll try looking into the route feature :)

**Comment by samcdonovan** [comment]
I finally got round to doing this! I'm just wondering how you want it to function. On the picture you provided, there's two pins so my question is, do you want the map to be editable or do you want the user/organisation to provide location(s) by typing in addresses which then get displayed on the map? Currently, the MediaMap component takes just one address and displays it as a pin on the map (see below)
![image](https://github.com/activist-org/activist/assets/57863161/fd894780-3a44-407f-be2e-e4806e6e212e)

Other than that, I think the map is pretty much done!

**Comment by andrewtavis** [comment]
Awesome, @samcdonovan! Really amazing stuff here 😊 The general idea is that the map will not be editable. The example I provided has two pins because that particular event would have two locations, and in cases where we’re using `Leaflet` as a map view for event search results we’d then also need it to show more than one pin, but again it’s just coming from the eventual backend in this case :) For events the organizer wouldn’t be editing via the map itself, but rather setting the location(s) and having them be displayed.

As far as documentation is concerned, great point 🙏 As of now for docs we just have the `README` and `CONTRIBUTING` files and I’ll be pushing a `STYLEGUIDE` file later today. What would you say would be the best way to go about documenting the dependencies/modules we’re using?

**Comment by samcdonovan** [comment]
Alright, I'll change it so that there can be multiple pins on the map then. I'm quite busy this weekend so I'll commit and create a PR when I get the time, sorry for the wait!

I think for now, a list of dependencies is good, and I'll add `Leaflet` to that list and maybe `OpenStreetMap` too? GitHub already has the [Dependency Graph](https://github.com/activist-org/activist/network/dependencies) feature which will allow anyone to look at every dependency, so a list of the key dependencies in the `README` makes sense to me. Maybe in the future as the dependency list grows we can look at other options!

**Comment by andrewtavis** [comment]
Thanks @samcdonovan, and no stress on the wait! Super excited to get this up and running 😊 And I guess a section on dependencies within [Tech Stack in the Readme](https://github.com/activist-org/activist#tech-stack-) would be good then? Maybe a dropdown?

**Comment by andrewtavis** [comment]
Thanks again! Next step for this is to add in the red and blue markers for `act` and `learn` events. I can make an issue for that tomorrow 😊

**Comment by andrewtavis** [comment]
Ah I'm realizing that I made a directory for this :) There's now the [frontend/components/Media](https://github.com/activist-org/activist/tree/main/frontend/components/Media) directory. Do you want to move it in there? If you have interest in adding the bit for coloring the markers then we could combine that?

**Comment by andrewtavis** [comment]
7928f54 did some super minor changes to the media map and added [activist.org/events/demo-at-brandenburg-gate](https://activist.org/events/demo-at-brandenburg-gate/) for testing. Map isn't showing up there atm. Is that us needing an API key for it, or what do you think? Was working for me locally.

Really great stuff! 😊

**Comment by samcdonovan** [comment]
Yeah, I can do the red and blue markers as well as moving MediaMap.vue into the media folder as one isssue/PR!

I'm having the same issue with the public site and it's running fine locally. Below is the error that is causing this:
![image](https://github.com/activist-org/activist/assets/57863161/e6fe6818-caad-4ed2-8b7a-5cb61c02187f)
This looks to be an issue with HTTPS (see [Mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)). I'll look into solving this now! It could be as simple as changing the OpenStreetMap URL to be https instead of http (`http://nominatim.openstreetmap.org/...` to `https://nominatim.openstreetmap.org/...`) but to test that would probably require running it through the public URL. Another solution would be proxying the API request through the backend which would bypass the HTTP issue but obviously we can't really do that right now.

**Comment by andrewtavis** [comment]
Sounds great in the markers, @samcdonovan! Feel free to also open a PR and we can check in the development preview if the HTTPS routing is working :) Backend work will be starting soon anyway, so if it needs to sit there for a bit that’d also be fine. For now we can just work on the components and get the layout files ready 😊

**Comment by andrewtavis** [comment]
@samcdonovan, wanted to check with you that the change in ef73f70 to remove the Leaflet attribution is ok. I'd prefer to keep the map UI as simple as possible, but also beyond that it's not just `Leaflet` that's being removed but also `🇺🇦`. I personally have no issue with the flag being there, but my general feeling is that we shouldn't as a platform put a focus on a single issue as there are sadly conflicts all over the world and many of our future events wouldn't be explicitly related to the Russian invasion. Your feedback on this would be appreciated though :)

**Comment by samcdonovan** [comment]
So sorry for the late response @andrewtavis, I've been super busy! I realise you've merged the PR and closed the issue, but I thought I'd still respond. 

Yeah I think removing the attribution is okay, and I also understand the feeling of not wanting to focus on a single issue. 

On another note, I think what you did with the markers is a great solution! At least now there's no need to rely on any external resources and the colours can be changed to whatever the situation calls for. The only addition I would consider is displaying the address when hovering over the marker but I'm not sure if that's something that you want.

**Comment by andrewtavis** [comment]
No need to apologize about being busy, @samcdonovan! Glad that the choice on the attribution makes sense. 

I think that displaying the address would be good too! There’s actually a component for that that would have the image and other information. I’ll make that issue soon, or please remind me if I forget 😊

**Comment by andrewtavis** [comment]
I made #176 to discuss this, @samcdonovan  :) Will add screens of the component when I’m back in Berlin 😊
