### ISSUE TITLE
Add Tailwind style guide

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#157]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue would be to create a Tailwind style guide for activist. We have the colors within [frontend/tailwind.config.ts](https://github.com/activist-org/activist/blob/main/frontend/tailwind.config.ts) and the responsive text sizes and padding within [frontend/assets/css/tailwind.css](https://github.com/activist-org/activist/blob/main/frontend/assets/css/tailwind.css). The styles within each of these files should be combined into a markdown file that explains their use, with this markdown file then being referenced in the project’s readme and contribution guidelines.

**Comment by momanyisamuel** [comment]
Yeah definitely

**Comment by andrewtavis** [comment]
@momanyisamuel, I actually decided to go with your original suggestion for the style guide as I think that it's important that we get the reminder that a `responsive-h1` needs to go in an `<h1>` tag so that we don't need to consistently be fixing `<p>` tags as in #149 :) Generally I'm thinking that I'll rename the current tags to their `responsive-h1`, etc equivalents, and will also potentially make a few classes with fewer breakpoint variations for `responsive-text-base`, etc. This work will be done in #159.

**Comment by andrewtavis** [comment]
Am sending along the style guide shortly! Would appreciate your thoughts 😊

**Comment by andrewtavis** [comment]
@momanyisamuel, 4c5a1e6 sent along the [style guide](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md). Let me know what you think! :)

**Comment by momanyisamuel** [comment]
awesome looks great, we will definitely grow with it 💯

**Comment by samcdonovan** [comment]
Hey @andrewtavis and @momanyisamuel, I remember having an issue with setting the opacity of a custom background colour.
For example, I tried:
- ```bg-light-cta-orange opacity-50``` 
 which didn't work and the solution was this:
- ```bg-light-cta-orange/50```

I don't know if it's worth adding that to the style guide somewhere but I just thought I'd let you know :)

**Comment by andrewtavis** [comment]
Hey @samcdonovan! 👋 That was actually one of the main things that I included in the [colors section of the style guide](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md#colors). Thanks for the feedback and glad we're on a good path with it! 😊

**Comment by andrewtavis** [comment]
Added a section on icon usage in ca3397f :) I think we're good to let this fly free and be a living document from here 😊 Will close, but comments are welcome for potential additions.
