### ISSUE TITLE
Add missing custom icons to activist

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#161]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Many of the icons that we use in the [designs in Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=805%3A231&t=BeCZi4tYh3hdozJX-1) are custom icons. It would be good to add versions of these icons to the project so that they can start being used. Specifically we need to add icons for:

- Organizations
- Groups
- Join
- Resources
- FAQ
- Affiliates
- Location

### Contribution

I'll work on this soon 😊

**Comment by andrewtavis** [comment]
A part of this issue will be replacing all current instances of placeholder icons with the custom versions that are added.

**Comment by nikhilagastya** [comment]
hey @andrewtavis would u like any help on this issue ?

**Comment by andrewtavis** [comment]
Hey @nikhilagastya 👋😊 Thanks for reaching out :) All the icons are technically included in the Figma designs already, and I think that [nuxt-icon](https://github.com/nuxt-modules/icon) would be what we’re using for this. I haven’t looked into making custom icons from SVGs with that yet though 🤔 We could take a look together, I could send along the SVGs and you could make sure they’re hooked up to the icons or do some replacements? :)

**Comment by nikhilagastya** [comment]
hey @andrewtavis i was thinking to contribute to something involving adding some new features or something like that.

**Comment by andrewtavis** [comment]
Hey @nikhilagastya :) Ya this one’s a bit more on the overhead side of things and not so much something new. Lots of stuff is already being worked on right now, but a general thing we could do is say a list view for search results? How does this sound? Would be something that would define the distances between `CardsSearchResult` components and would include a `Load more` link text after say 20 results? We could also work on some testing for the frontend, or other components like ones for organization or event settings?

**Comment by andrewtavis** [comment]
Happy to make an issue for any of the above or also feel free to suggest something!

**Comment by nikhilagastya** [comment]
> Hey @nikhilagastya :) Ya this one’s a bit more on the overhead side of things and not so much something new. Lots of stuff is already being worked on right now, but a general thing we could do is say a list view for search results? How does this sound? Would be something that would define the distances between `CardsSearchResult` components and would include a `Load more` link text after say 20 results? We could also work on some testing for the frontend, or other components like ones for organization or event settings?

You mean like an organization search page sort of thing ?But to implement that dont we need the backend running or we need to hardcode organizations in a json and render the details from there ,I feel this is a good feature that can be implemented.

**Comment by andrewtavis** [comment]
Ya this would specifically be to just make the component that would house those results from the backend. I want to get a few more components done and we can migrate to the backend in a few weeks :)

**Comment by andrewtavis** [comment]
Or not fully migrate, but shift the focus a bit 😊

**Comment by andrewtavis** [comment]
Other ideas @nikhilagastya would be to work on some things for the home page, which as of right now we just have search results for. The designs for that are [here](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2475%3A19102&t=AzvMGQjA8CpapC04-1) :) If you wanted to go for something big then the calendar, or for small elements just the marker that shows how many new events and new organizations there are.

**Comment by nikhilagastya** [comment]
I will check them once and let you know on it @andrewtavis

**Comment by andrewtavis** [comment]
Sounds good, @nikhilagastya!

**Comment by andrewtavis** [comment]
Calendar component would be something that we’d need to do some research for as far as which dependencies we want to use. It doesn’t need to look like in the designs either as that’s more or a placeholder.

**Comment by nikhilagastya** [comment]
we might need the calendar component when companies want to set some event date or anything ig ??

**Comment by andrewtavis** [comment]
Yes exactly. I think the main use of it for now would be to have it on the home page so that a person can see when they have upcoming events (dot on a day means you’re attending something). But also as you said, we want it so that when people are making events they can also easily select when it’s happening including multiple days and all other kinds of scenarios :)

**Comment by andrewtavis** [comment]
Lemme know if I should make an issue for it :)

**Comment by andrewtavis** [comment]
@nikhilagastya, just made #169 for the calendar 😊

**Comment by andrewtavis** [comment]
Closed in b4a97f2 😊
