### ISSUE TITLE
Calendar component for event creation / home page

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#169]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This event focuses on the creation of a calendar component that can be used in event creation to select the date or dates of an event and can also be displayed on a home page to indicate when a user has upcoming events.

Designs for this component can be seen in the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2475%3A19102&t=MDQbwmpLwutjdUXH-1) and can also be seen below:

![Page Media](https://github.com/activist-org/activist/assets/24387426/f12afade-00ec-46e4-950a-60d30eca76a2)

Note that the exactly functionality of the component is not set yet. This will be determined based on dependency that we choose to use, with a discussion of which would be best first taking place 😊 Note further that this component should be put in the [frontend/components/Media](https://github.com/activist-org/activist/tree/main/frontend/components/Media) directory :)

### Contribution

Happy to discuss what dependencies could be best for this and also to work on this myself or support someone with interest :)

**Comment by andrewtavis** [comment]
Note that the above image would be what's on the home page and the one below could be an example of what's shown during event creation:

![Mode=Light](https://github.com/activist-org/activist/assets/24387426/ad5e588a-bf13-4600-b3c0-98a9b6297337)

**Comment by rohram04** [comment]
I was looking at what dependency could be used and the options I seem to be finding are completed components with a UI. Are there options for dependencies that provide just the calendar functionality that this component's UI can be built on top of?

**Comment by andrewtavis** [comment]
Thanks for looking into this, @rohram04!! I'll check it out soon :) Almost out of my busy period and then can start attacking some of the issues here with you all 😊 Let me know if you have interest in implementation :)

**Comment by rohram04** [comment]
I would be interested in implementation once these details are ironed out

**Comment by rohram04** [comment]
Hello, just wondering if you got a chance to look at this so I can start working on an implementation?

**Comment by andrewtavis** [comment]
Hey @rohram04! Sorry busy week. I’m looking at the package you mentioned it doesn’t seem to be actively maintained - last release 2019. Maybe we could find something from the Vue or Nuxt ecosystem or a JS/TS package that’s a bit more active?

**Comment by andrewtavis** [comment]
Hey @rohram04 :) Looking at this a bit more, I think that [v-calendar](https://github.com/nathanreyes/v-calendar) might be a good option, and aside from that [vue-simple-calendar](https://github.com/richardtallent/vue-simple-calendar) could be considered 🤔 Let me know what you think on either of those!

**Comment by rohram04** [comment]
I think v-calendars smaller component is more suited for the requirements. Should the calendar theme just be changed to match activists theme or should css be added to look like the component above?

**Comment by andrewtavis** [comment]
Sounds great, @rohram04! And no the calendar does not need to look like the one above. We can just change the theme and make it work given our light and dark mode coloration as stated the [styleguide](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md) and defined in [tailwind.config.ts](https://github.com/activist-org/activist/blob/main/frontend/tailwind.config.ts) :)

**Comment by rohram04** [comment]
Hello, I was busy with work so I am just getting to this component. Now that I am looking at it. Applying the activist theme is a little messy. The way v-calendar works is it has a set of colors defined like the following:

`.vc-blue {
  --vc-accent-50: #f0f9ff;
  --vc-accent-100: #e0f2fe;
  --vc-accent-200: #bae6fd;
  --vc-accent-300: #7dd3fc;
  --vc-accent-400: #38bdf8;
  --vc-accent-500: #0ea5e9;
  --vc-accent-600: #0284c7;
  --vc-accent-700: #0369a1;
  --vc-accent-800: #075985;
  --vc-accent-900: #0c4a6e;
}`

To change or add colors I would have to make a similar palette based on the predefined rgba values for cta-orange, act-red, etc. Those values are a single rgba value not a set of tints and hues so we would have to generate a pallet accordingly to fill out --vc-accent-50 through --vc-accent-900. In addition, varying between light and dark modes would mean adding another set of colors to match the dark colors defined in activists tailwind.config.ts and then overriding the dark settings in the given v-calendar [css stylesheet](https://github.com/nathanreyes/v-calendar/blob/v3/src/styles/theme.css). All of these changes would be made in a new css stylesheet. I'm wondering if there's any easier way to do this or an alternative that doesn't require as much fiddling.

**Comment by andrewtavis** [comment]
No stress, @rohram04! Glad to hear from you :) As it looks like we can eventually do the color definitions later, let’s maybe just stick with the default for now and then we can do a separate issue to get to the coloration? Unless we can find a different dependency that’s JS/TS based, it sounds like this is the route to take. 

Thanks for all the research!

**Comment by andrewtavis** [comment]
Looks like a good option to me! Thanks for the suggestion, @teschiopol! What do you think about this, @rohram04? :)

**Comment by rohram04** [comment]
It provides a lot of customizability but it doesn't seem like there is an easy way to display a calendar with events. It is solely a date picker. Let me know what your thoughts are @andrewtavis. Also, should we make a decision on the exact functionality?  My understanding is two components need to be made one is of course a display and the other, is an event picker. Both these components are easy to display but the logic behind the component is where implementation details arise. Are the events going to be stored in a backend, how should they be formatted, etc?

**Comment by andrewtavis** [comment]
I agree, @rohram04 :) Sorry just checked it out really quick during work 😇

> Are the events going to be stored in a backend, how should they be formatted, etc?

The events are going to be stored in a backend, yes. We're working on the basic connections right now in #207. The format of the dates should follow general global standards - by this I basically mean no US ordering of things - so `yyyy-mm-dd hh:mm:ss` where obviously the seconds would not actively be in use for this. W're going for Postgres for the database, which might be information of use. Anything else you can think of?

> In addition, varying between light and dark modes would mean adding another set of colors to match the dark colors defined in activists tailwind.config.ts and then overriding the dark settings in the given v-calendar [css stylesheet](https://github.com/nathanreyes/v-calendar/blob/v3/src/styles/theme.css). All of these changes would be made in a new css stylesheet. I'm wondering if there's any easier way to do this or an alternative that doesn't require as much fiddling.

To reiterate the answer on this, let's not worry to much about the exact styles now. Will doubtless be a bit of work to get things looking exact, but this seems to have the features we need, and I'm happy to make another issue that focuses on styling it all :)

**Comment by rohram04** [comment]
Sounds good. Ill get something started and open a PR so we can at least get this moving and then work on refining it. I expect it will take a couple of iterations and back and forth to dial down this feature.

**Comment by andrewtavis** [comment]
Fantastic, @rohram04! Looking forward to the PR 😊

**Comment by rohram04** [comment]
Hello this is what I have done so far:
[Codesandbox](https://codesandbox.io/p/sandbox/late-firefly-t2llp4?file=%2Fsrc%2Fcomponents%2FCalendar.vue%3A5%2C18)

I am also creating a PR so you can view this. It is just an input for the events. I need to implement the dark mode, fix fonts, and more things but I just wanted to get your thoughts on it so far. Creating a repeated event will need some additional inputs which I will add soon. Once the input is created I figured I could move to actually displaying the events on the calendar which again is the simpler part of this.

**Comment by andrewtavis** [comment]
Hey @rohram04, quick reminder that there's the dev sync in an hour and a half! Info is in the [Development](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org?via=matrix.org&via=acter.global&via=chat.0x7cd.xyz) channel on Matrix 😊 I'll look more into the PR after that :)

**Comment by rigojr** [comment]
Can I help on this issue ?

**Comment by andrewtavis** [comment]
Hey @rigojr 👋 Really appreciate the quick action here to help out 😊 8cbb4f7 sent through a bunch of changes that really simplifies down what it is that we're doing here to just a date picker atm and makes sure that it deploys properly. You can see the result at [activist.org/home](https://activist.org/home/). I've been running into some minor annoying things for a bit now as far as getting our custom backgrounds and colors to work for dark mode. I think it's just late and will be something that's easier in the coming days :) If you wanted to try to get some of it done, things I'm thinking are:

- Making sure that for dark mode we have the header background so it's brand colored
- Getting the border color to be our section div color for light and dark mode

Another question is on what it should look like when things are selected. To be design-wise it'd make sense to maybe reflect the cta buttons such that for light mode we have black text on orange backgrounds and for dark mode we have orange text over an orange background with a high alpha. Feedback would be great! Other suggestions would also be welcome 😇

**Comment by andrewtavis** [comment]
I've made #454 to work on the coloration of the date picker. I'd say that we're good to close this and future work can be covered by other issues. We also need the calendar component, but this can be worked on once this one is finalized during work in the upcoming issues 😊 Thanks for the work here, @rohram04, and thanks for the help in reviewing it all, @rigojr!
