### ISSUE TITLE
GitHub community shields for landing page

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#170]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create the GitHub community shields for the GitHub that we can display on the landing page. The designs for these can be seen on the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=517%3A3258&t=MDQbwmpLwutjdUXH-1) and can further be seen below:

![GitHub Stats](https://github.com/activist-org/activist/assets/24387426/1d2bde12-d770-4b58-a812-8dd7e7250397)

Each of these shields can be an option for a general component that would be in the [icons directory of the frontend](https://github.com/activist-org/activist/tree/main/frontend/components/Icon). For now we can call it `IconGitHubShield` 😊 We'd need to access the GitHub API to get the information for the shields, with how we exactly do this being open for discussion.

### Contribution

Happy to work on this myself or support someone who has interest :) This should be a relatively doable `good first issue` with another section being added to the landing page to show them off and talk about open source development :upsi

**Comment by rohram04** [comment]
Hello I would be willing to work on this. In terms of accessing the github api - would a simple fetch request work. If you make a request to   https://api.github.com/repos/activist-org/activist it gives the following json result:

`{
    "id": 332064599,
    "node_id": "MDEwOlJlcG9zaXRvcnkzMzIwNjQ1OTk=",
    "name": "activist",
    "full_name": "activist-org/activist",
    "private": false,
    "owner": {
        "login": "activist-org",
        "id": 79784013,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjc5Nzg0MDEz",
        "avatar_url": "https://avatars.githubusercontent.com/u/79784013?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/activist-org",
        "html_url": "https://github.com/activist-org",
        "followers_url": "https://api.github.com/users/activist-org/followers",
        "following_url": "https://api.github.com/users/activist-org/following{/other_user}",
        "gists_url": "https://api.github.com/users/activist-org/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/activist-org/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/activist-org/subscriptions",
        "organizations_url": "https://api.github.com/users/activist-org/orgs",
        "repos_url": "https://api.github.com/users/activist-org/repos",
        "events_url": "https://api.github.com/users/activist-org/events{/privacy}",
        "received_events_url": "https://api.github.com/users/activist-org/received_events",
        "type": "Organization",
        "site_admin": false
    },
    "html_url": "https://github.com/activist-org/activist",
    "description": "Open-source, nonprofit activism platform",
    "fork": false,
    "url": "https://api.github.com/repos/activist-org/activist",
    "forks_url": "https://api.github.com/repos/activist-org/activist/forks",
    "keys_url": "https://api.github.com/repos/activist-org/activist/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/activist-org/activist/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/activist-org/activist/teams",
    "hooks_url": "https://api.github.com/repos/activist-org/activist/hooks",
    "issue_events_url": "https://api.github.com/repos/activist-org/activist/issues/events{/number}",
    "events_url": "https://api.github.com/repos/activist-org/activist/events",
    "assignees_url": "https://api.github.com/repos/activist-org/activist/assignees{/user}",
    "branches_url": "https://api.github.com/repos/activist-org/activist/branches{/branch}",
    "tags_url": "https://api.github.com/repos/activist-org/activist/tags",
    "blobs_url": "https://api.github.com/repos/activist-org/activist/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/activist-org/activist/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/activist-org/activist/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/activist-org/activist/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/activist-org/activist/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/activist-org/activist/languages",
    "stargazers_url": "https://api.github.com/repos/activist-org/activist/stargazers",
    "contributors_url": "https://api.github.com/repos/activist-org/activist/contributors",
    "subscribers_url": "https://api.github.com/repos/activist-org/activist/subscribers",
    "subscription_url": "https://api.github.com/repos/activist-org/activist/subscription",
    "commits_url": "https://api.github.com/repos/activist-org/activist/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/activist-org/activist/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/activist-org/activist/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/activist-org/activist/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/activist-org/activist/contents/{+path}",
    "compare_url": "https://api.github.com/repos/activist-org/activist/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/activist-org/activist/merges",
    "archive_url": "https://api.github.com/repos/activist-org/activist/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/activist-org/activist/downloads",
    "issues_url": "https://api.github.com/repos/activist-org/activist/issues{/number}",
    "pulls_url": "https://api.github.com/repos/activist-org/activist/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/activist-org/activist/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/activist-org/activist/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/activist-org/activist/labels{/name}",
    "releases_url": "https://api.github.com/repos/activist-org/activist/releases{/id}",
    "deployments_url": "https://api.github.com/repos/activist-org/activist/deployments",
    "created_at": "2021-01-22T21:17:28Z",
    "updated_at": "2023-06-04T19:28:53Z",
    "pushed_at": "2023-06-02T21:23:22Z",
    "git_url": "git://github.com/activist-org/activist.git",
    "ssh_url": "git@github.com:activist-org/activist.git",
    "clone_url": "https://github.com/activist-org/activist.git",
    "svn_url": "https://github.com/activist-org/activist",
    "homepage": "https://activist.org",
    "size": 34645,
    "stargazers_count": 37,
    "watchers_count": 37,
    "language": "Vue",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 33,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 38,
    "license": {
        "key": "agpl-3.0",
        "name": "GNU Affero General Public License v3.0",
        "spdx_id": "AGPL-3.0",
        "url": "https://api.github.com/licenses/agpl-3.0",
        "node_id": "MDc6TGljZW5zZTE="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
        "activism",
        "app",
        "backend",
        "climate-change",
        "community",
        "django",
        "frontend",
        "javascript",
        "learning",
        "nuxt",
        "open-source",
        "politics",
        "python",
        "social",
        "social-network",
        "tailwindcss",
        "typescript",
        "vue",
        "web",
        "webapp"
    ],
    "visibility": "public",
    "forks": 33,
    "open_issues": 38,
    "watchers": 37,
    "default_branch": "main",
    "temp_clone_token": null,
    "organization": {
        "login": "activist-org",
        "id": 79784013,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjc5Nzg0MDEz",
        "avatar_url": "https://avatars.githubusercontent.com/u/79784013?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/activist-org",
        "html_url": "https://github.com/activist-org",
        "followers_url": "https://api.github.com/users/activist-org/followers",
        "following_url": "https://api.github.com/users/activist-org/following{/other_user}",
        "gists_url": "https://api.github.com/users/activist-org/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/activist-org/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/activist-org/subscriptions",
        "organizations_url": "https://api.github.com/users/activist-org/orgs",
        "repos_url": "https://api.github.com/users/activist-org/repos",
        "events_url": "https://api.github.com/users/activist-org/events{/privacy}",
        "received_events_url": "https://api.github.com/users/activist-org/received_events",
        "type": "Organization",
        "site_admin": false
    },
    "network_count": 33,
    "subscribers_count": 5
}`

I believe the forks_count and stargazers_count are all we need for those icons. Would this work?

**Comment by rohram04** [comment]
Hello I created a PR for these shields. Please note that it is probably better to separate each of these icon shields into their own component files - I can do that if you would like. Also I used the options API of vue.js as I was having some trouble using composition and the normal setup API.

**Comment by andrewtavis** [comment]
@rohram04, fded0de similarly does some edits for proportions and changes the colors to ones that are defined in [frontend/tailwind.config.ts](https://github.com/activist-org/activist/blob/main/frontend/tailwind.config.ts) 😊 The new components are now on the landing page at [activist.org](https://activist.org/)! Let me know if you have any comments, and thanks so much for your efforts!
