### ISSUE TITLE
At a glance metric component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#171]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to work on a component that can go on the home page for quick metrics about organizations and events at a glance. The designs for this component can be seen on [Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2475%3A19102&t=MDQbwmpLwutjdUXH-1) and can further be checked out below:

![Events This Week](https://github.com/activist-org/activist/assets/24387426/3ec6d8ef-d771-4912-a088-3a2bd4c5bf03)

Note that this issue focuses on the rounded squares and a the text within them. One component should be made to that has properties that then determine what the text within is as well as the colors :) Would be really great to have this so that we can continue to build up needed components for the home page. Note that this card component and a separate one for a grid to house them could go within the [grid component directory in the frontend codes](https://github.com/activist-org/activist/tree/main/frontend/components/Grid).

### Contribution

Happy to support someone who has interest in making this or work on it myself at some point 😊

**Comment by rohram04** [comment]
Would be interested in working on this card component. I am a beginner to open source contributions but would love to give this a try :).

**Comment by andrewtavis** [comment]
Sounds great, @rohram04! Great to have you 😊 Will assign you now, and let me know if I can help in any way :)

**Comment by andrewtavis** [comment]
9a72d8b did some minor edits to colors and renamed the files based on some ideas I had post merging, @rohram04 😊 They can now be seen at [activist.org/home](https://activist.org/home/)! For future reference the brand colors can be found at [frontend/tailwind.config.ts](https://github.com/activist-org/activist/blob/main/frontend/tailwind.config.ts). Nothing you have to follow during your first commit :) Hope to have more contributions from you in the future! 🚀
