### ISSUE TITLE
Map pin pop up component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#176]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The is issue is to discuss and code the implementation of a popup component for maps on activist. The designs for this component are available on Figma, but a specific question at the start is how to implement custom pop ups within a Leaflet and OpenStreetMap context. The finished pop up component would go in the Popup directory in the frontend. 

### Contribution

Happy to discuss this and work on the implementation! :)

**Comment by andrewtavis** [comment]
Thanks, @momanyisamuel! Assigning you now :) Let’s do a call soon so we can meet one another finally, btw 😊😊

**Comment by momanyisamuel** [comment]
Hey @andrewtavis as discussed added the popup to the MediaMap component, for now any dynamic information can be passed via props to the popup. Just let me know if this works for now.

**Comment by andrewtavis** [comment]
Thanks, @momanyisamuel!! 🙌 Will check it tonight odds are :) :)

**Comment by andrewtavis** [comment]
3bc2aa9 does some final edits to the pin popup, @momanyisamuel :) We can close this issue as I'd say that it makes sense to keep this as an example as we prepare to adopt the solution for maps that you talked about. Particularly problematic in the current case is that because we can't use custom components in the pin, we thus can't use `<NuxtLink />` to allow us to pass localized paths to event pages.

To get the information in one place, we were talking [vue3-openlayers](https://github.com/MelihAltintas/vue3-openlayers) as a potential solution 😊 Tagging @samcdonovan here as maybe the three of us can chat a bit more about this 🚀
