### ISSUE TITLE
Coloration of sidebar and main scrollbars

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#184]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to color the main and sidebar scrollbars based on whether the user is in light mode or dark mode. First trying to do this globally would be good, which should not require any further extensions. If needed we can also look into [tailwind-scrollbar](https://www.npmjs.com/package/tailwind-scrollbar) for this :)

The colors for the scrollbars in each mode can be seen in the [designs in Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1606%3A585&t=ebX1xK9a6qRlhXOA-1).

### Contribution

This is a `good first issue` and thus great for someone who doesn't have much experience with activist. Happy to support, or can also get to it in the coming weeks if needed :)

**Comment by Mradosi** [comment]
Hi, I can work on that :)

**Comment by andrewtavis** [comment]
Hi @Mradosi! Great to see you here so quickly 😊 Assigning you, and please let me know if you have further questions!

**Comment by andrewtavis** [comment]
Closed via #193 😊 Thanks @Mradosi!! Will look into the other PR later :)
