### ISSUE TITLE
Fix hot reloading for activist frontend within Docker

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#192]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

As of now hot reloading isn’t working within the Nuxt frontend, meaning we need to reload the page to see the changes reflected in the UI. This issue is to investigate the cause of this and make the necessary changes in Docker and Nuxt/Vue config files to get hot reloading working again :) :)

**Comment by andrewtavis** [comment]
@Mradosi, 0a07fd9 seems to have fixed this on my end 😊 Let me know if it's working on your end 🙃

**Comment by anthonyshibitov** [comment]
This is working on my end!

**Comment by andrewtavis** [comment]
Awesome! Thank you, @anthonyshibitov 😊 Closing this then :)
