### ISSUE TITLE
Add mobile header component and apply below sm breakpoint

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#196]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to add in the mobile header component for activist as detailed in the images below:

![Mode=Light, Search=False, Blank=False](https://github.com/activist-org/activist/assets/24387426/ef8d5b7a-b179-4f92-86a9-0a5adb782071)
![Mode=Light, Search=True, Blank=False](https://github.com/activist-org/activist/assets/24387426/a201bb52-139c-4e78-a7fe-5241a16478e7)

The header would include the following components:

- [SearchBar](https://github.com/activist-org/activist/blob/main/frontend/components/SearchBar.vue)
- [IconActivist](https://github.com/activist-org/activist/blob/main/frontend/components/Icon/IconActivist.vue)
- [MenuMeatball](https://github.com/activist-org/activist/blob/main/frontend/components/Menu/MenuMeatball.vue)

Generally I'm thinking that we can name the component `MenuMobileHeader` within the [Menu components directory](https://github.com/activist-org/activist/tree/main/frontend/components/Menu) :) I've added some props to [SearchBar](https://github.com/activist-org/activist/blob/main/frontend/components/SearchBar.vue) to help with this: specifically `location` that can be used to define it as a header search bar, and `expanded` has also been added. I've also removed the sidebar below the small breakpoint for the screens that have it so that we can test this new component. Beyond this I've also made some simple additions into [SearchBar](https://github.com/activist-org/activist/blob/main/frontend/components/SearchBar.vue) for `v-else`, meaning `location='header'` as well as added a text input that's controlled by whether the `expand` prop is true.

- This issue is related to #131, so some of the work done in #194 could be used as these two components will be applied in tandem.

### Contribution

This issue has already been spoken for by a new community member. Assigning to myself for now until he claims it 😊 Happy to assist as needed!

**Comment by andrewtavis** [comment]
1f8363e fixes a minor error I made while preparing this issue :)

**Comment by andrewtavis** [comment]
Thanks for your offer, @momanyisamuel! This one is reserved for @dean123 for his first issue for activist :) We discussed it in a call 🙃 

I wrote back to you on Element about where some support could come :) Also happy to try to schedule another call 😊

**Comment by dean123** [comment]
Great timing :)  @andrewtavis 
I just created the pull request

**Comment by andrewtavis** [comment]
Great, @dean123! I’ll check it soon :)

**Comment by andrewtavis** [comment]
5a9c2c9 finalizes all of this for the time being, @dean123 😊 Thanks for all your help! Let's be in touch on future issues and if you'd like to meet for a coffee :) :)
