### ISSUE TITLE
Responsive implementations for card components for mobile and other break points

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#198]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to edit the current components in the [Card](https://github.com/activist-org/activist/tree/main/frontend/components/Card) directory to make them reactive to break points and thus mobile friendly :)

- This issue is blocked by #196 as we'll first add in the header and then we can make sure that the cards work on mobile

### Contribution

I'll be working on this after I merge in a few of the issues that we have :)

**Comment by luuu-xu** [comment]
Hi, is this issue available? I would love to work on this project since it has many features waiting to be implemented. Although I haven't used Vue.js before, I can work on issues while learning it too. Please let me know if there is an open issue now for me. :)

**Comment by andrewtavis** [comment]
Hi @luuu-xu! Thanks for your interest in activist :) :)

I was planning on doing this one myself as I’ll likely be a bit particular about how it’s done. I’m going to reopen #151 now if that would be of interest to improve the accessibility as a first issue, and then we can find new issues for you from there?

**Comment by andrewtavis** [comment]
I'm temporarily blocking this as I think it makes more sense to do the layout in #139 before we jump into this :)

**Comment by andrewtavis** [comment]
Note that I'm blocking this until work is done on #270 :)

**Comment by andrewtavis** [comment]
Closed via d2242ee 🚀
