### ISSUE TITLE
Add documentation on `yarn nuxi typecheck` to STYLEGUIDE and CONTRIBUTING.

### ISSUE THREAD

**Issue by TeddyGavi** [activist-org/activist#199]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Following issue #148 and PR #188 

This issue is to add documentation to the [STYLEGUIDE](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md) and [CONTRIBUTING](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md) on the command `yarn nuxi typecheck` in lieu of enabling TypeScript `strict mode` in `nuxt.config.ts`. More information can be found on [Nuxt](https://nuxt.com/docs/guide/concepts/typescript)

This will enable local TS error checking. For any new code written, I suggest running a typecheck locally to ensure type safety

 :smiley:

### Contribution

Please Assign me to this issue. I will update the documentation accordingly. :smile:

**Comment by andrewtavis** [comment]
Thank you, @TeddyGavi!! Great to have you taking this from start to finish :)

**Comment by andrewtavis** [comment]
Closed by #203! Thank you, @TeddyGavi!
