### ISSUE TITLE
Convert meatball dropdown to hamburger right side menu

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#201]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would convert the current component and menu feature for mobile views at [frontend/components/Menu/MenuMeatball.vue](https://github.com/activist-org/activist/blob/main/frontend/components/Menu/MenuMeatball.vue) to a hamburger menu that triggers a right side menu. In looking at current UI trends — GitHub's new one, for example — the use of right side menus feels to me at this point to be a better choice than a dropdown. All the current options would be within the right side menu, but would pop out from the side and cover roughly 80-90% of the screen. Clicking outside of the sidebar would close it, and there should also be an `x` in the top right corner to close the sidebar.

### Contribution

Would be happy to work on this in the coming days or support someone!

**Comment by andrewtavis** [comment]
@Mradosi, would this be something you have interest in?

**Comment by Mradosi** [comment]
> @Mradosi, would this be something you have interest in?

Sure :) Assign me, please :)

**Comment by andrewtavis** [comment]
Thank you, @Mradosi! 😊

**Comment by andrewtavis** [comment]
Hey @Mradosi 👋😊 Just doing a quick checkin here and in your other issue :) Let me know if there's anything I can do to support!

**Comment by Mradosi** [comment]
@andrewtavis  
What should be included inside the menu? Only what is currently there (language switcher and theme) or something else?

**Comment by andrewtavis** [comment]
Hi @Mradosi 👋 I think that for this issue we can just include what’s in there now :) We can make further issues later to add more functionality 😊

**Comment by andrewtavis** [comment]
@Mradosi, a quick note on this is that it could also be good to think in terms of the eventual right side bar that will be in play for things like search results where there will be a list in the right side of the map, for instance. I guess these would be different components, but maybe we want a meta sidebar one that then has some sub versions?

**Comment by andrewtavis** [comment]
Generally speaking we could put this into the ‘Sidebar` components directory and rename some files (`SidebarLeft`) there to reflect that they’re on the left and the new ones are on the right 🤔

**Comment by andrewtavis** [comment]
Or maybe it’d be best to rename the directory to `LeftSidebar` and make a new one `RightSidebar`? This seems more sensible to me :)

**Comment by Mradosi** [comment]
> @Mradosi, a quick note on this is that it could also be good to think in terms of the eventual right side bar that will be in play for things like search results where there will be a list in the right side of the map, for instance. I guess these would be different components, but maybe we want a meta sidebar one that then has some sub versions?

The content in the sidebar is displayed using slots, making it flexible and allowing for reuse with different components.

> Or maybe it’d be best to rename the directory to `LeftSidebar` and make a new one `RightSidebar`? This seems more sensible to me :)

Yes, I think so, I went with this approach :)

**Comment by andrewtavis** [comment]
Thank you for this, @Mradosi! I should be able to get to this and #202's PR this weekend :)

We have the dev sync later today at [15:00 UTC](https://zonestamp.toolforge.org/1689433242). Meeting link for that is https://call.element.io/activist-dev-sync. Obviously no stress if you'd prefer to not join at this time, but I wanted to take a moment to stress that you're very welcome to join in planning and other community functions 😊

I'm also not seeing you in the development channel on Matrix, so maybe that could be a first step? Link to the space is [this one here](https://matrix.to/#/#activist_community:matrix.org), with you then being able to join the [Development](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org?via=matrix.org&via=acter.global&via=chat.0x7cd.xyz) and [General](https://matrix.to/#/!uIGQUxlCnEzrPiRsRw:matrix.org?via=matrix.org&via=effektio.org&via=acter.global) rooms :) :)

**Comment by andrewtavis** [comment]
Sorry sorry - am remembering that you did reach out in there already and talked about the hot reload among other things 😊 Has been a bit of a long week in prep for all this and with a grant application :)

**Comment by andrewtavis** [comment]
Final formatting finished in ef6c63e, @Mradosi 😊 That's a massive commit with lots of formatting, but the big changes were some spacing for the icons, making sure that the focus was a full ring during tab accessibility access, extending the options for localization options that weren't spanning the dropdown, and other minor fixes for things like how localization is setup :)

Thanks again so much for the help!
