### ISSUE TITLE
Search filters for sidebar menu

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#202]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would implement the search filters for the sidebar for various activist entities :) We'd need search filters for events, organizations and resources, which are defined in the [Figma designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1922%3A1416&mode=design&t=4cXqY0llnGLim2nM-1). Examples of the search components can be seen below:

Events:
![Mode=Dark, Category=Event, MVP=True, Admin Open=False, Home=False](https://github.com/activist-org/activist/assets/24387426/7303222a-9adb-41c4-892f-9a3105847e73)

Organizations:
![Mode=Dark, Category=Organization, MVP=True, Admin Open=False, Home=False](https://github.com/activist-org/activist/assets/24387426/869a4370-2928-447e-aa79-f770d344c39d)

Resources:
![Mode=Dark, Category=Resource, MVP=True, Admin Open=False, Home=False](https://github.com/activist-org/activist/assets/24387426/4243fbde-5cca-4b2e-b27e-0789787200c1)

I feel like these should be more than one component, so happy to separate this issue out if someone would like to take it :)

### Contribution

Happy to work on this in the coming days or support someone who wants to work on this!

**Comment by Mradosi** [comment]
> @Mradosi, is this something you'd have interest in working on? :)

Yes, I will work on it :)

**Comment by andrewtavis** [comment]
Hey @Mradosi 👋😊 Just doing a quick checkin here and in your other issue :) Hope you're doing well!

**Comment by Mradosi** [comment]
> Hey @Mradosi 👋😊 Just doing a quick checkin here and in your other issue :) Hope you're doing well!

Sure, everything is fine, thanks. I will complete the PR by the end of this week :)

**Comment by andrewtavis** [comment]
Wonderful to hear and looking forward to checking out the new work! 😊

**Comment by andrewtavis** [comment]
8c456e3, work done by @rigojr in #260 and now d8b1cb9 close this up :) Finally 😅 Sorry that it took so long to finalize all this, @Mradosi! Have had all kinds of things to get to, but we're getting closer to implementing backend hydration and will thus need the filters now 🚀 

I personally learned a lot from working on your code :) Again thanks so much for these contributions! Looking forward to seeing the filters in action and using them to check out organizations and events 😊

Hope you're well!
