### ISSUE TITLE
`yarn nuxi typecheck` shows TypeScript errors in multiple files

### ISSUE THREAD

**Issue by TeddyGavi** [activist-org/activist#211]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Multiple TypeScript errors exist. 

To replicate:

1. From project root `cd` into `frontend`
2. Run `yarn nuxi typecheck`

This issue will be ongoing until all errors are resolved. Currently `strict` mode is disabled. See the TypeScript [STYLEGUIDE](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md#typescript-) for more information.

**Comment by andrewtavis** [comment]
Thanks for making this, @TeddyGavi! Looking forward to getting all this fixed and transitioning to `strict` 😊

**Comment by andrewtavis** [comment]
Based on a suggestion from @TeddyGavi, we could create an action to run `yarn nuxi typecheck` on PRs :) How we'd save the output and read it would be a question, but checking this would be included in the maintainers checklist.

**Comment by andrewtavis** [comment]
I promise I'll take TS errors more seriously when we get this first main bunch taken care of 😅

```
Found 64 errors in 22 files.

Errors  Files
     2  components/card/CardAbout.vue:70
     1  components/card/CardConnect.vue:96
     1  components/card/CardFeedItem.vue:41
     2  components/card/CardGetInvolved.vue:64
     3  components/card/CardSearchResult.vue:183
     4  components/form/FormButtonStyledCheckbox.vue:14
     3  components/form/FormButtonStyledRadio.vue:16
     3  components/form/FormCheckbox.vue:7
     6  components/form/FormCheckboxGroup.vue:9
     3  components/form/FormRadio.vue:5
     6  components/form/FormRadioGroup.vue:6
     3  components/form/FormSearch.vue:8
     1  components/landing/LandingContent.vue:162
     4  components/modal/ModalImage.vue:9
     9  components/PageBreadcrumbs.vue:53
     2  components/selector/SelectorLanguage.vue:76
     4  components/sidebar/left/SidebarLeftFooter.vue:17
     1  pages/events/[id]/about.vue:75
     1  pages/events/index.vue:33
     3  pages/home/index.vue:43
     1  pages/organizations/[id]/about.vue:69
     1  pages/organizations/index.vue:33
```

Would be great if the both of you could confirm where you're at given the current state of things :) From there, how do we want to split these up? Based on directory/sub-directory where we'd have an issue for everything in `components/card`?

**Comment by TeddyGavi** [comment]
64! I'll keep an eye on this but I won't be able to help out until after August 7th when I am back from holiday 🏄

**Comment by andrewtavis** [comment]
@TeddyGavi, would you be able to do a `yarn nuxi typecheck` run and post the results? I'm starting to get errors from it on my end, but I feel like Time Machine potentially corrupted some files that are used for it. It had done the same for Git earlier today, and I'm seeing `export const LazyMarkdownVueD 2: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue.d 2")['default']` where the ` 2"`s in there are pretty indicative that copies were made 🤦‍♂️ Main warning I'm getting is `[nuxt] Could not resolve /DIRECTORY_PATH/activist/frontend/.nuxt/components.plugin.mjs`

Would be great to get the current list so we can start making issues for them!

**Comment by andrewtavis** [comment]
Added `vue-tsc` to dev dependencies in 8c3e904 and we're back up and running, @TeddyGavi 😊 I'm going to make all the TS errors now :)

**Comment by andrewtavis** [comment]
Issues are made 😊 I think that the breakdown of the directories and one misc components issue will work out well :)

**Comment by andrewtavis** [comment]
I think we can close this issue now though, @TeddyGavi. Let's get to the issues that are made now, and then as we go we can have review be more stringent for TS errors when #228 is done and can also make new issues when and if new errors are introduced into the codebase :)

**Comment by TeddyGavi** [comment]
Hey @andrewtavis I'm just getting to reading this now! My apologies. It looks like things are moving nicely. I'll take a look today and check in with the other issues. :+1:

**Comment by andrewtavis** [comment]
No apologies needed, @TeddyGavi! Glad that we're on to the next stage of finishing all these errors :) :)
