### ISSUE TITLE
Convert PopupImage to use Headwind popover

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#213]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The current version of the [frontend/components/Popup/PopupImage](https://github.com/activist-org/activist/blob/main/frontend/components/Popup/PopupImage.vue) component is generally exactly what we'd like for UI, but is lacking some points for accessibility. It would be great if this component could be refactored to make use of [Headless UI's popover](https://headlessui.com/vue/popover) command.

### Contribution

Would be happy to support someone on this issue or get to it myself eventually 😊

**Comment by luuu-xu** [comment]
Let me give it a try as my first proper dig into Vue components! I don't think it will be too hard for me. 😗

**Comment by luuu-xu** [comment]
@andrewtavis As I was reading into Headless UI's documentation, I thought that maybe we should use [modal(dialog)](https://headlessui.com/vue/dialog) instead of [popover](https://headlessui.com/vue/popover)? We would want out user to focus on the enlarged floating picture right? What do you think?

**Comment by andrewtavis** [comment]
Yes, @luuu-xu, this actually makes more sense :) Let's continue to keep it in the `Popup` directory, but I agree that a model would work better for this :)

**Comment by luuu-xu** [comment]
@andrewtavis Hi, please review my PR submitted just now. I had fun converting the component and would like to work with more issues!

But I do have an issue that I did not find any solutions or reasons, so when I am using `<script setup lang="ts">` with my ModalImage component to declare types, my VSCode is yelling at my codes saying `Property 'imageURL' does not exist on type '{}'.ts(2339)` and `Property 'imageURL' does not exist on type '{}'.ts(2339)`. 

I tried solving it but was not successful, here is a screenshot of all these nasty yells I got: 
<img width="645" alt="image" src="https://github.com/activist-org/activist/assets/97932191/8003530f-9063-40c0-9270-ccf1750556da">

Let me know if you recognize this issue, maybe it's my VSCode... Thanks!

**Comment by andrewtavis** [comment]
Hey @luuu-xu! I’ll try to get to this review by tomorrow :) Thanks for the efforts here, and glad you had a good time 😊

The errors you’re experiencing are very likely TS errors related to #211. In that issue we’ll have an overview of all the errors, and then we’ll potentially make file level issues to fix all the errors in them. Feel free to join the discussion in #211! :) :)

**Comment by andrewtavis** [comment]
Closed via #222! Thank you, @luuu-xu! 🙌
