### ISSUE TITLE
Social Media Links Opening on Same Page as Footer/Hero Section

### ISSUE THREAD

**Issue by firtysh** [activist-org/activist#225]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

I have noticed an issue on the website where the social media links in both the footer and hero section are opening on the same page instead of opening in a new tab or window. This behavior is inconsistent with user expectations and can lead to a poor user experience.

### Contribution

I would like to contribute to this issue.

**Comment by andrewtavis** [comment]
Hey @firtysh! I can confirm this behavior on my end and also that it's definitely something that should be changed 😊 Thanks so much for the initiative in making the issue and wanting to work on it!

**Comment by andrewtavis** [comment]
Issue resolved by @232 :) :) Thanks again, @firtysh!
