### ISSUE TITLE
First steps as a contributor documentation

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#227]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue would add a section to [CONTRIBUTING.md](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md) above `Learning the tech stack` that would detail the things that contributors should do when first interacting with the community. Ideas include:

- Quick welcome message
- Unordered list
  - Matrix (linked)
    - We should explain that it's decentralized and suggest that they use Element
    - Maybe also specifically link the [Development channel](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org?via=matrix.org&via=acter.global&via=chat.0x7cd.xyz) as well?
    - If you’re comfortable
      - Introduce yourself and what your coding skills/interests are
      - Consider joining our bi-weekly sync
  - Check the styleguide (linked) where we provide helpful hints of how to write your code
  - Check the Figma (linked) so you understand the goals direction
  - Check good first issues (linked) for issues that are introductions to working on activist
  - Check the project board (linked) to better understand our workflow and priorities

Would be happy to get to this eventually or support someone who has interest in working on it!

**Comment by andrewtavis** [comment]
@anthonyshibitov, made the issue for the task you had from [last dev sync](https://etherpad.wikimedia.org/p/activist-dev-sync-2023-7-1) (new pad notes doc that I transferred the doc to). Just making it so we remember to do it 🙃 Feel free to claim it or someone else can work on it 😊

Hope the move's going well! 🚚

**Comment by andrewtavis** [comment]
Another thing to add in here would be the VS Code extensions that people should install, as some of them would be very important to make sure TS is working properly :)

**Comment by andrewtavis** [comment]
@anthonyshibitov, I took this one over as we needed the extensions documentation sooner than I expected as the number of errors we're experiencing is variable 😅 Hoping that getting everyone's VS Code setup standardized will help with this!

**Comment by luuu-xu** [comment]
@andrewtavis Great addition to the documentation! Do you think if it's better to add steps 1, 2, 3 to the "Development Environment" section too? Just like the "Pull Request" section.

**Comment by andrewtavis** [comment]
I do indeed think the numbers would be helpful, @luuu-xu! Will add numbered steps to the contribution guide and readme when I get home. Having the steps as numbers would make the sections more distinct and put an end in sight 😊 Thanks for the suggestion!

**Comment by andrewtavis** [comment]
Changes made in 740be5a, @luuu-xu 😊
