### ISSUE TITLE
Add `yarn nuxi typecheck` to `package.json`

### ISSUE THREAD

**Issue by TeddyGavi** [activist-org/activist#228]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The goal would be to display the output of `yarn nuxi typecheck` in the Netlify deploy logs. 

The suggestion by @wkyoshida was to add the command to the `postinstall` script in `package.json`

This is an extension of issue #211 

### Contribution

I will add this command to line 9 and test it locally.

**Comment by andrewtavis** [comment]
@TeddyGavi, another thing that @wkyoshida and I were discussing is that I could also add this to the Netlify build directly such that the errors would just be logged in there. As of now we have a build command that is `CI= npm run generate`, which could then be changed to `CI= yarn nuxi typecheck && npm run generate`.

We'd just need to make sure that this wouldn't break the build if there are TS errors. I could add this in and send along a PR after some of these PRs are merged 🙃

I think we can also include changing the [pr_maintainer_checklist.yaml](https://github.com/activist-org/activist/blob/main/.github/workflows/pr_maintainer_checklist.yaml) file in this issue as well :)

**Comment by TeddyGavi** [comment]
I am thinking about this a bit more, should we be adding a config file for Netlify builds? If we are moving away from Netlify in the future perhaps not? 

After reading a bit more about `generate` it creates static files for static hosting. So it runs `build` afterwards. Reading the build logs, everything file I see is `*.js` from the `/dist` So I believe we would also need to include `nuxt prepare` [to generate the types first](https://nuxt.com/docs/api/commands/prepare), as I am not sure if they are autogenerated for static hosting or by `build`. I will need to try some options out, to make sure the build doesn't fail :worried:

**Comment by TeddyGavi** [comment]
@andrewtavis circling back to this in regards to #242  
 > Hey @TeddyGavi! Thanks for the efforts here :) It seems like there’s no option for the type check tests to fail quietly in this way. Should I try a PR that edits the Netlify run?
 
 Or should we close this and create a new issue completely?

**Comment by andrewtavis** [comment]
I’ll do this within this issue, @TeddyGavi! Thank you for reminding me! :) I’ll get to this early next week hopefully 😊

**Comment by andrewtavis** [comment]
Ah, @TeddyGavi, I’m realizing that also adding a checkbox to the maintainer checklist was included in this :) Do you want to maybe send one along? We could make a separate issue for this as I think it’d be nice to reference the PR number such that we can tell someone to go to - for example for #313 - https://github.com/activist-org/activist/pull/313/checks to see the output 😊 Would also be more descriptive of what’s going on for a new contributor 😇

**Comment by andrewtavis** [comment]
- I made #314 to document the need above, @TeddyGavi 😊
