### ISSUE TITLE
Mark `imageURL` and `altText` props in `LandingPageContent` as optional

### ISSUE THREAD

**Issue by TeddyGavi** [activist-org/activist#234]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Continuing #233 and #211 

As noted by @luuu-xu. 

In `LandingPageContent.vue` mark both `imageURL` and `altText` props as optional.

**Comment by luuu-xu** [comment]
@TeddyGavi Shall I make an PR regarding changing props for our `BtnLabeled` and `LandingPageContent` now? As we just discussed, although it seems like there are a lot of problems with TS now, but we can at least fix these two components first.

**Comment by TeddyGavi** [comment]
@luuu-xu Sure thing. The `withDefault` is the better approach either way. It appears there are differences in the local configs between our two environments (at least), which needs some investigation. :+1:

**Comment by andrewtavis** [comment]
Closing this issue as it was handled in #235, but will keep #233 open so we can continue the TS discussion :)
