### ISSUE TITLE
TS prop errors of `GridGithubShields.vue` and `ImageGithubShield.vue`

### ISSUE THREAD

**Issue by luuu-xu** [activist-org/activist#236]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Continue looking into our TS prop situations and I've found that we have some type errors from both `GridGithubShields.vue` and `ImageGithubShield.vue`. Specifically:

1. For `ImageGithubShield.vue`:
   - the types in `defineProps<>` will be preferably changed to `string` from `String`, as TS says _"Type 'String' is not assignable to type 'string'. 'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.ts(2322)"_
   - `count` needs to be changed to `number` because it is receiving a **number** type.
   - `loading` is missing when this component is first initialized or after fetched data? See details of this Vue error, open the console and reload the landing page. _"[Vue warn]: Missing required prop: "loading" 
  at <ImageGithubShield >"._

2. For `GridGithubShields.vue`:
   - right now this component does not have a `props` declaration method, but only the `data()` method with some initial values. This makes `result.forks_count` to have an error _"Property 'forks_count' does not exist on type '{}'.ts(2339)"._
   - `this.error` has an error too since `error` has no type (unknown) and we have an initial value of null, thus the error is _"Type 'unknown' is not assignable to type 'null'.ts(2322)"_.

We need to correct these props and eliminate TS errors, should be an easy fix.

@andrewtavis @TeddyGavi  What do you guys think? We have been after TS errors this whole day. 🤣

**Comment by andrewtavis** [comment]
The top two changes for `ImageGithubShield.vue` make total sense. Once we merge the PRs that we have right now we could potentially just do a full sweep to switch `String` to `string`. Just me not understanding this on first usage and it doubtless propagating 😊 

> `loading` is missing when this component is first initialized or after fetched data? See details of this Vue error, open the console and reload the landing page. "[Vue warn]: Missing required prop: "loading"
at ".

For this would it be as simple as adding `:loading="loading"` to the `ImageGithubShield`? It doesn't seem to be being passed.

What would you two suggest for `GridGithubShields.vue`?

**Comment by TeddyGavi** [comment]
Passing loading via `:loading="loading"` worked for me, in each instance of `ImageGithubShield` in `GridGithubShields.vue`

@luuu-xu @andrewtavis Correct me if I am wrong but capitalized uses like `String` and `Boolean` are actually objects and not primitives. Therefore they are coerced to primitive values in JS yet TS does not. So TS would see that as an object? So I agree with this 

> Once we merge the PRs that we have right now we could potentially just do a full sweep to switch String to string
---
regarding `GridGithubShields.vue`
> right now this component does not have a props declaration method, but only the data() method with some initial... 

There are other instances of different styles for declaring props I have noticed. For example in `MediaImageCarousel.vue` Eventually, I would recommend that we stick with a consistent style, that being `defineProps` (with defaults as needed)

For now I would recommend that `GridGithubShields.vue` should be refactored to use `defineProps`

**Comment by andrewtavis** [comment]
> Correct me if I am wrong but capitalized uses like String and Boolean are actually objects and not primitives. Therefore they are coerced to primitive values in JS yet TS does not. So TS would see that as an object?

Looking at it, this seems right to me :)

> For now I would recommend that `GridGithubShields.vue` should be refactored to use `defineProps`

I agree, and will also make an issue for the final conversion now :)

**Comment by andrewtavis** [comment]
- See https://github.com/activist-org/activist/issues/237

**Comment by luuu-xu** [comment]
So I played with these two components and I found these changes need to be added for `ImageGithubShield.vue`:

1. `count` needs to be optional since our first usage does not need it.
2. `text` also needs to be optional for the same reason above.

For `GridGithubShields.vue`:

1. pass `loading` to each of three `ImageGithubShield` components inside.

I am not sure whether we should/need to refactor its `<script>` to `<script setup>` as Vue's recommending the use of the latter according to [TypeScript with Composition API ](https://vuejs.org/guide/typescript/composition-api.html) rather than [TypeScript with Options API](https://vuejs.org/guide/typescript/options-api.html).

Since I don't have much experience with Vue, I am looking forward hearing back from experienced to chime in!

**Comment by TeddyGavi** [comment]
Nice work @luuu-xu ! I have been told that `defineProps` only works when using `<script setup lang="ts">` I have never tested this myself, but the docs do reference that same pattern. I am new to Nuxt/Vue as well, it is great we can learn together!

**Comment by andrewtavis** [comment]
`<script setup lang="ts">` would be what we’re looking for here 😊 And just checking that we understand that `text` and `count` for `ImageGithubShield.vue` are only not “needed” in that they come post load :) `count` specifically. Maybe there’s another way for it to be implemented relating to the GitHub API though :) This will come in handy for #231 if we can find a better way 🙃

**Comment by andrewtavis** [comment]
I think we’re ready for a PR for this one as well 😊

**Comment by luuu-xu** [comment]
@andrewtavis I have just submitted a PR for you to review. Let me know how it goes.

> And just checking that we understand that text and count for ImageGithubShield.vue are only not “needed” in that they come post load :) count specifically.

I am sorry if I misunderstand you on this. But when I say `text` and `count` need to be optional, I am referring to the fact that the first `ImageGithubShield` component we used in `GridGithubShields`, does not need these two props, it is a link to our github repo. Is it the best way to do it though? Maybe we should have two components, where one does not require them, the other does?

**Comment by andrewtavis** [comment]
Ahhhh, yes :) @luuu-xu, I totally misunderstood 😊 Yes the one that’s just for GitHub does not use these props. 

For me, I think the current implementation is fine as if we do for some reason need to change the style then we can do it in one place. Is the “the best”? No, but no use in spending time switching it if it makes it a bit easier for us later :)

**Comment by andrewtavis** [comment]
Another day, another closed TS issue 😊 Resolved via #238! Thanks @luuu-xu and @TeddyGavi! :) :)
