### ISSUE TITLE
Standardize all TS prop declarations

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#237]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is to convert all TS prop declarations within `.vue` files to `defineProps`. We'll first need to note all files where changes should occur. A PR with changes for the remaining non-standardized prop declarations can then be prepared after a short discussion of potential difficult conversions 😊

Happy to work on this with folks!

Tagging @TeddyGavi and @luuu-xu

**Comment by luuu-xu** [comment]
So I went ahead and did a full scan of our components and I made this list of components that are either not using ts or not using Composition API:

1. All **7** components inside `/Form` are not using **ts** `lang="ts"`.
2. `/Media/MediaImageCarousel` is not using **Composition API** so it needs a refactoring.
3. `/Menu/MenuMeatBall` is not using **ts**.
4. `/Selector/SelectorLanguage` and `/Selector/SelectorTheme` are not using **ts**.
5. `/WebsiteHeader` is not using **Composition API** so a refactoring is needed.

I am not sure whether we need to apply the same standards for `/pages`?

**Comment by andrewtavis** [comment]
For `/Pages` as well, I’d say :) I’ll make some of the changes above in the current commits I’m working on, @luuu-xu 😊 We can then check it again after :)

**Comment by andrewtavis** [comment]
Deleted `MeatballMenu` as we're not using it anymore and added TS to those files that needed it in 6b1993b :)

**Comment by andrewtavis** [comment]
Closing this as aa3781c handles the lack of `lang="ts"`, @RyanPaulGannon covered the header in #252 and I've made #258 that will cover the MediaImageCarousel component :) Let me know if something's missing and we can make a quick fix or issue!
