### ISSUE TITLE
Directory breadcrumb component for top of page

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#239]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would implement a component that would read the directory path at the top of pages. The purpose of this would be to show uses where they are within the website and also to provide convenient back links. This component would be called `PageBreadcrumbs.vue` and could be located in the [default components directory](https://github.com/activist-org/activist/tree/main/frontend/components).

Specifications:

- The text should be in `special-text` colors for light and dark mode
- The hover color for links would be `text` colors
- Text elements should be separated by spaces and slashes
- The links would be page titles, not the exact directory path
  - ex: `/ Organizations / tech from below` for the [example org page](https://activist.org/organizations/tech-from-below/) (currently not mobile responsive)

Examples of this component can be seen in the [prototypes on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1986%3A1046&t=eYUWYpmFm2aRuNcv-1). 

### Contribution

Happy to support someone on this who has interest or work on it myself :blush

**Comment by luuu-xu** [comment]
I can work on this. 🙂

**Comment by andrewtavis** [comment]
Assigned, @luuu-xu! Let me know if I can help somehow :) :)

**Comment by luuu-xu** [comment]
@andrewtavis So while I was thinking about how to implement this breadcrumbs, I realize that I am not sure whether I should parse URL and make links accordingly, or should I pass category (/Organization, /Events) and specific name (event name, organization name), sub-category (/Organization/tech-from-below/About) as props into my `PageBreadcrumbs`? Because I am also thinking about how our back-end is going to work and sending back data to frontend when user clicks on a organization...

**Comment by andrewtavis** [comment]
Hey @luuu-xu! There are going to be multiple names for organizations and events possible, so parsing the URL should be fine such that you'll get the ID of the org or event and then can generate the name from the DB (eventually). This might be something that we can just pass dummy variables to now and then we can pass the actual variables from the backend via a layout fine later :)

Big thing is we want the name, not the part of the url. So for the example you talked about it'd be `tech from below` as the name of the organization, not `tech-from-below`.

**Comment by andrewtavis** [comment]
There's also a potential for lower levels for the pages as well - such as in settings for orgs or events or types of affiliates within that section (supports, allies or supporting).

**Comment by luuu-xu** [comment]
@andrewtavis Hi, I just submitted the PR. There're two points though:

1. Maybe we should make the current page's breadcrumb different than the rest so it indicates to the users that they are on this page? So maybe for `/ Organizations / tech from below`, we can make `tech from below` having `text` colours just as it has for hovering.
2. The top margin of this component, I only added 1px because I wanted to align with the collapse button on the left sidebar. But in Figma, I feel like both of them need to be moved down a bit so we can align them and have larger top margins.

**Comment by andrewtavis** [comment]
Hey @luuu-xu! Answers to your questions 😊

1. Is the last element a link as well? If so it should function the same as other links as far as its color changing on hover. I feel like the standard is let the user reload the page by clicking a link that leads them back. With that being said, I do agree it should be different looking 🤔 I just tried it out in the designs and I feel like bolding the last element isn't too bad?

![Screenshot_2023-07-28 21 56 10](https://github.com/activist-org/activist/assets/24387426/84723b1c-f5f0-42f4-b4ca-0ef9723c93af)

What do you think? Happy to discuss further!

2. I totally agree that it should be aligned with the collapse button of the sidebar, and will keep this in mind when I go through and touch up the designs for the color changes! Thanks for pointing this out!

**Comment by andrewtavis** [comment]
Just added a note to align the breadcrumbs and the collapse button 🙃 Not sure when it's going to happen, but hopefully next week is when I'd get some time for the color adjustments. Or maybe Sunday :)

**Comment by andrewtavis** [comment]
Closed via #243 and 1b35c40. I switched the font to `font-display`, but wasn't able to figure out making the last link bold... If you can figure out a way to do this, @luuu-xu, then that'd be great! If not we can also make an issue for this if you think it would also help :)

**Comment by andrewtavis** [comment]
75f6a6b did some final edits for this, @luuu-xu. I did a minor workaround to get the name of the event or organization in for those pages - see [activist.org/events/123](https://activist.org/events/123) - but then this will need to be changes later as it's hacky checking to see if there's in integer and then replacing the name. I also removed the first slash as I think it looks more appealing, and also did check to see if the bold text could work via Firefox (I was apparently experiencing a bug with Chrome), but ended up deciding against it.

I think we're good for now 😊 Thanks again!

**Comment by luuu-xu** [comment]
> and also did check to see if the bold text could work via Firefox (I was apparently experiencing a bug with Chrome), but ended up deciding against it.

Thank you for your fixes and it looks and works great! So we are not going to bold the last breadcrumb for now? No problem at all!

**Comment by andrewtavis** [comment]
No, just didn’t look right to me, @luuu-xu :)
