### ISSUE TITLE
Create brand loading animation

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#245]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of right now on page load if there's a delay we're seeing the default Nuxt loading animation. This issue is to create one for ourselves. Based on a discussion in the most recent dev sync, it would be best for it to be something simple like the activist `a` pulsating via opacity.

### Contribution

I've already done a basic implementation of this locally and will send it along with the changes for #129 :) This issue will document if the changes are reflected on production or not.

**Comment by andrewtavis** [comment]
f95ec65 did not fix this issue... @Mradosi, do you maybe have an idea on this? As of now we have the Nuxt loading screen on the website and I'm really trying to convert it to something branded. I made the [frontend/components/Loading.vue](https://github.com/activist-org/activist/blob/main/frontend/components/Loading.vue) component that's the activist `a` blinking over the header background, and this is supposed to be applied on load. Maybe the `global-loader` needs to be setup? I was thinking it's something that's default 🤔

**Comment by luuu-xu** [comment]
So I played around with this and when I add a timeout to the hook "page:finish" `setTimeout(() => {
    show.value = false;
  }, 1000);`
I can actually see the brand loading screen for a sec and disappear, so I think it is working as expected?

**Comment by andrewtavis** [comment]
It is working as expected in those regards, but when you’re on the website in production I still see the Nuxt loading animation from time to time. Goal at this point is that that goes away.

I’d assume that your deduction is the case here. For now it would be great if we could just find a way to swap out the Nuxt loading screen with this, and we can then revisit when we have the backend up and running that we’re making calls to :)

**Comment by Mradosi** [comment]
@andrewtavis Do you mean the loading screen with the logo and hover animation that appears during the application launch? ![Zrzut ekranu 2023-07-30 225814](https://github.com/activist-org/activist/assets/135969056/e94a34a9-dcb0-4ce4-aab5-db4a969b3d51)
 It should only be displayed during local development. Or are you referring to the screen with logo/loader?
![Zrzut ekranu 2023-07-31 090544](https://github.com/activist-org/activist/assets/135969056/be8dd55a-1822-48bd-8f4f-5524c43f869f)
This is the spaLoadingTemplate and it can be changed by creating an app/spa-loading-template.html
https://nuxt.com/docs/api/configuration/nuxt-config#spaloadingtemplate

**Comment by andrewtavis** [comment]
> This is the spaLoadingTemplate and it can be changed by creating an app/spa-loading-template.html

I knew that you would know, @Mradosi 😊😊 Was searching and saw a bit about an HTML template, but I thought it was maybe something that a .vue file could also work for. Makes sense that we need just a base HTML file that’s there before the JavaScript gets loaded in. I’ll make an HTML file that matches `Loading.vue` such that that can be a baseline and the animated Vue file can come in later when we need it for further loads (hopefully as little as possible) :)

**Comment by andrewtavis** [comment]
a376b20 adds [app/spa-loading-template.html](https://github.com/activist-org/activist/blob/main/frontend/app/spa-loading-template.html) :) Let me know how it's looking. I think that if the page does take a bit to load it looks nice, and when it's quick it's a bit jerky, but overall it's definitely better than the Nuxt loading screen 😅

**Comment by andrewtavis** [comment]
Closing this so we can focus on some of the new issues, but please let me know if there should be any improvements!
