### ISSUE TITLE
Upcoming feature header/marker for WIP pages

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#246]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This feature would add a tooltip to options that are not currently available in the left sidebar. For instance for events we have `Tasks` and `Discussions` that aren't currently being worked on and won't be for some time, but we'd like to include them so that people have a better understanding of the scope of activist. These options are currently disabled as seen below:

<img width="263" alt="Screenshot_2023-07-30 13 12 33" src="https://github.com/activist-org/activist/assets/24387426/f49f03e5-ec0b-4d1e-bddb-ee4f478d763c">

There's no indication to the user as to why they're disabled though. It would be nice if we had a tooltip that's similar to the ones that we have for the search bar hotkeys like `/` that would tell the user that the feature is planned. Copy like the following could appear in the tooltip:

> {MENU_OPTION_NAME} is currently not an available feature. Please consider [supporting activist's development](https://activist.org/supporters/join) so we can add it in the future.

The link above would take the user to [activist.org/supporters/join](https://activist.org/supporters/join).

### Contribution

Happy to support someone who wants to work on this issue! This would be a `good first issue` for someone new to the activist development community :)

**Comment by andrewtavis** [comment]
I'm also noticing that these options are not yet disabled, so doing that would also be a part of this issue 😊

**Comment by luuu-xu** [comment]
@andrewtavis Let's wait to see if someone new would like to take this issue, if not, I can do it. 😁

**Comment by andrewtavis** [comment]
Sounds good, @luuu-xu! Will be other issues made soon that you can work on 😊😊

**Comment by thefloofe22** [comment]
Still up for grabs? Would be happy to work on if it is. Let me know!!!

**Comment by andrewtavis** [comment]
Is still up for grabs, @thefloofe22 😊 Assigning you now 🚀 

The place to test this feature locally would be on an example event page like [activist.org/events/123](https://activist.org/events/123) (isn’t mobile ready, FYI). The same code that you’re seeing for the tooltip for the `/` on the search bar is the model for this :) We’d just need to add that in as something that gets displayed when hovering within the [SidebarLeftSelector component](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftSelector.vue) when `active` is `false` :)

Please let us know if you need any assistance!

**Comment by m-sushant** [comment]
I want to contribute for the above mentioned issue.

**Comment by andrewtavis** [comment]
We’ll also be adding new issues in the coming week, @m-sushant! Keep an eye out and we’ll be happy to assign you to a new one!

**Comment by thefloofe22** [comment]
Awesome!!! Thank you @andrewtavis @luuu-xu

**Comment by andrewtavis** [comment]
Hey there @thefloofe22 👋 Checking in with you to see how the progress on this is :) As @m-sushant indicated that they also have interest, it'd be great if you could let us know if you still plan on working on this issue. No stress if you've had some things come up though, and please let us know if we can help 😊

**Comment by thefloofe22** [comment]
Hi @andrewtavis , So sorry work got a bit busy these last two weeks. Yes, I do want to work on the issue, still. Will do some investigating today, clear up any doubts I have tomorrow, and aim to be done by EOD on Sunday. Is that okay?

**Comment by andrewtavis** [comment]
Yes, sure thing @thefloofe22! Just checking on it :) :)

**Comment by thefloofe22** [comment]
Have done some playing around, and think I have a clear idea of the feature. Before I implemented it, just wanted to make sure my understanding was correct. Is it to just add a tooltips feature for features that are work in progress i.e. tasks and discussions? And also, should all code for this be within [SidebarLeftSelector component](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftSelector.vue) file?

**Comment by thefloofe22** [comment]
Also, sorry, last question. Which file has the tooltip code for the / on the search bar?

**Comment by andrewtavis** [comment]
You can ask as many questions as you need to, @thefloofe22 😇

> Is it to just add a tooltips feature for features that are work in progress i.e. tasks and discussions? And also, should all code for this be within [SidebarLeftSelector component](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftSelector.vue) file?

Yes to both of these questions. If `active` is false, then we want the tooltip to be there and we also want to disable the button to not be clickable.

> Which file has the tooltip code for the `/` on the search bar?

That code can be found in [SearchBar.vue](https://github.com/activist-org/activist/blob/main/frontend/components/SearchBar.vue), specifically at the following place:

https://github.com/activist-org/activist/blob/93de9deecf8239920181d701a217eb7d47a5e91a/frontend/components/SearchBar.vue#L15C11-L15C11

You need to have `has-tooltip` on the parent class and the tooltip `<span>` needs to have `tooltip` custom class. These are defined in the [frontend/assets/css/tailwind.cs](https://github.com/activist-org/activist/blob/93de9deecf8239920181d701a217eb7d47a5e91a/frontend/assets/css/tailwind.css#L34) file :)

Also, @m-sushant, as you'd been hoping to work on an issue for activist, I wanted to point out that we have tons of new [good first issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) now that you could work on!

**Comment by andrewtavis** [comment]
Hey @thefloofe22 👋 Just a quick checkin on the status of this :) Let me know if you need any assistance!

**Comment by andrewtavis** [comment]
Hey @thefloofe22 😊 Checking in to see where you're at on this :) Happy to help out if you need some assistance! We also have Code Night 🌙 tomorrow, so that might be a good chance to get some help if you need it.

Hope you're well!

**Comment by thefloofe22** [comment]
So sorry about the delay. Got stuck on the issue. When is the Code night? I'll try to come by.

**Comment by andrewtavis** [comment]
No need to apologize about the delay, @thefloofe22! Things take time, and sometimes time’s short :)

Code Night 🌙 is today (Saturday) at [15:00 UTC](https://zonestamp.toolforge.org/1695481256) :) Would be great to have you! The details are in the `Development` channel on our [public Matrix channel](https://matrix.to/#/%23activist_community%3Amatrix.org) 😊 We’ll do a call at the time mentioned to check on the status of things, then there will be time to assign issues, and then for the evening we’ll be available to ask questions while we work on things together :) If you can’t make it to the call time you could also join later or we could meet asynch!

**Comment by andrewtavis** [comment]
Hey @thefloofe22 👋 Checking in to see where you're at on this :) Let me know if you'd like to do a call at some point and we can problem solve on this!

**Comment by andrewtavis** [comment]
Based on a discussion today in the activist weekly, we're not going to be doing a tooltip if something isn't available, but will rather allow the user to go to a default page that then makes it clear that the page is still under development. This could be achieved via a prop that renders elements in [HeaderAppPage](https://github.com/activist-org/activist/blob/main/frontend/components/header/HeaderAppPage.vue). Happy to get to this myself as there are as of now no designs.

**Comment by andrewtavis** [comment]
Closed via 2c6ab54 :) There's now a marker at the top of the page on ones like [activist.org/events/123/team](https://activist.org/en/events/123/team). Thanks all for the help and consideration here!
