### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#249]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The burger menu is not centered in the y-direction.
![image](https://github.com/activist-org/activist/assets/49518857/97b5d4df-89ba-4efd-9a48-d4d8d6534cee)

The active searchbar is colliding with the burger menu.
![image2](https://github.com/activist-org/activist/assets/49518857/e8e3caab-e06e-4854-952e-5e6df2fc9d81)

**Comment by andrewtavis** [comment]
Hey @to-sta! Thanks for the issue! 🙏🚀

Big thing with these is we need to check them on multiple browsers as it does look good to me on chrome via shrinking the breakpoint to below `sm` :)

Do you have interest in working on this?

**Comment by to-sta** [comment]
I would like to work on that.

I have also used chrome and checked on my phone as well. But it's a good point, I should check at least firefox and edge.

**Comment by andrewtavis** [comment]
Sounds good, @to-sta! Assigned to you just now :) I'll make the issue for the footer right now 😊

**Comment by andrewtavis** [comment]
Closed via #256 :) Keep the suggestions coming, @to-sta! 🚀
