### ISSUE TITLE
Fix website footer spacing when next to sidebar

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#250]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The [WebsiteFooter](https://github.com/activist-org/activist/blob/main/frontend/components/WebsiteFooter.vue) components needs some edits so that its content is more responsive when its found next to a sidebar. As seen below, at various points the footer text is broken to different lines, and we need to switch the style to a the full `flex-col` approach where the content is stacked rather than `flex` where the content is on the left and right at an earlier breakpoint due to lack of space.

<img width="1347" alt="Screenshot_2023-08-05 08 52 53" src="https://github.com/activist-org/activist/assets/24387426/e5b00e53-acf8-454d-976a-4002f65ac57b">

### Contribution

I'd be happy to work on this or support someone who has interest 😊

**Comment by andrewtavis** [comment]
@to-sta, does it make sense to maybe make a `footer` directory and separate out some of the logic into different components? Maybe one that's `flex` and one that's `flex-col` with them being combined into a parent component? I feel like the current file is already long enough, and the fixes here will only add to its complexity.

**Comment by to-sta** [comment]
@andrewtavis i think that would make sense. I also thought that v-for could be used for the lists to get rid of a few lines of code.

**Comment by luuu-xu** [comment]
Maybe I should take on this issue since nobody is offering help for now? 😇

**Comment by andrewtavis** [comment]
You're more than welcome to, @luuu-xu! Assigning now :)

**Comment by andrewtavis** [comment]
@luuu-xu, does an initial split of `flex` vs. `flex-col` make sense to you? So we can have `footer/Flex.vue` with the version that has content to the left and right, and `footer/FlexCol.vue` that has all the content stacked, and then within a `footer/Footer.vue` we assign both based on window constraints defined within?

**Comment by luuu-xu** [comment]
@andrewtavis Yes, separating them to `flex` and `flex-col` makes sense to me. I agree this component is quite big now, we should do a refactor. I will make a new directory and 3 components accordingly.

And `v-for` makes sense too, I plan on doing it too.

But it seems like I can't reproduce the styling bug you initially posted when opening this issue. When I change screen width, the footer seems to be pretty responsive, not producing unwanted styles. Can you try reproducing it again and tell me what width you encountered it with?

**Comment by andrewtavis** [comment]
@luuu-xu, are you checking on pages where there’s also a sidebar, or just on the landing page and others where the footer spans the page? We have it set fairly well for when it spans the full page, but on my end there are issues at breakpoints as shown in the image when there’s a sidebar :)

**Comment by luuu-xu** [comment]
@andrewtavis Yes, when there's a sidebar. (/home page) So the threshold is 1024px, and above 1024, the footer is well spaced with `flex`, like this:

<img width="1024" alt="Screenshot 2023-08-08 at 22 25 32" src="https://github.com/activist-org/activist/assets/97932191/a2a9200d-8997-4d94-a048-401a5aede2e8">

And when it's below 1024px, it becomes `flex-col` which is working fine.

Let me know where went wrong for me. I can work on refactoring for now. 😁

**Comment by andrewtavis** [comment]
@luuu-xu, took a screen recording of what I'm seeing with the background set to `bg-breakpoint-test` so it changes colors as we pass breakpoints :)

https://github.com/activist-org/activist/assets/24387426/3aae6266-ab7b-466a-a02b-357abacb2b3d

What we're seeing in your screenshot is fine if say the "Open-source, nonprofit activism platform." needs to get broken to the next line a bit, but there are lots of instances where it starts looking bad when "Trademark policy" is on two lines. I think we need to jump to `flex-col` sooner when there's a sidebar in order to avoid this :)

**Comment by luuu-xu** [comment]
@andrewtavis So I was able to decouple our footer and used v-for to minimize duplications. 

But somehow I can't reproduce the styling issue in your video. I tried Chrome, Firefox and Safari, every one of them is looking great to me no matter if sidebar is present or not. I am confused now why I can't reproduce this issue.

**Comment by andrewtavis** [comment]
Super confused as well, @luuu-xu 🤔 Let's maybe just do the PR and I'll look at what it's doing on my end? I can merge that through and then if there's anything I'll do a commit from my side :)

Looking forward to the changes!

**Comment by andrewtavis** [comment]
The issues with text breaking to the next line are fixed via c51b98d, so this is now closed 😊 Thanks for the work @luuu-xu and for the ideas @to-sta!
