### ISSUE TITLE
Add Django REST framework to activist-org

### ISSUE THREAD

**Issue by momanyisamuel** [activist-org/activist#251]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Adding Django REST framework for the API. this is because Django REST framework offers the following features:

- The Web browsable API is a huge usability win for your developers.
- Authentication policies including packages for OAuth1a and OAuth2.
- Serialization that supports both ORM and non-ORM data sources.
- Customizable all the way down - just use regular function-based views if you don't need the more powerful features.
- Extensive documentation, and great community support.
- Used and trusted by internationally recognised companies including Mozilla, Red Hat, Heroku, and Eventbrite.

**Comment by momanyisamuel** [comment]
Terms

I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)

    I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

Description

This issue would add [Django REST framework](https://www.django-rest-framework.org) to activist repos.

**Comment by luuu-xu** [comment]
I wished that we could use node as backend so I can contribute much more to our backend. 🤣 I would also want to help using Django too!

**Comment by momanyisamuel** [comment]
@luuu-xu  You're welcome to join 👍 its pretty fun learning and using Django

**Comment by andrewtavis** [comment]
Closed via #253 :) :) From here the issue wave begins 🌊😅
