### ISSUE TITLE
Add shadow to UI cards

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#254]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This change would be to edit the [card-style](https://github.com/activist-org/activist/blob/8bc1759038c606b96389c8e77b8833abe1529ab4/frontend/assets/css/tailwind.css#L30) custom tailwind style to add in a slight shadow such that cards on the platform are coming out a bit. The line is the one below:

https://github.com/activist-org/activist/blob/8bc1759038c606b96389c8e77b8833abe1529ab4/frontend/assets/css/tailwind.css#L30

The shadow color should be the same as is being used for tooltips - `shadow-md shadow-zinc-700`. We can test this later though :)

### Contribution

I'd be happy to implement this or help someone who has interest in working on it!

**Comment by luuu-xu** [comment]
I'll wait a day or so, if no one is volunteering I'll take it.

**Comment by Vidhanvyrs** [comment]
I can volunteer for this issue, i am happy to help here

**Comment by andrewtavis** [comment]
Fantastic, @Vidhanvyrs! Assigning you now :) Please let us know if you have any questions 😊

**Comment by andrewtavis** [comment]
Thanks for the quick work, @Vidhanvyrs! Looking at it, I think that some general changes should come from this as we should have the following:

- [ ] A shadow on the right side of the left sidebar
- [ ] Light shadows for the BtnLabeled as well as looking at the UI they should also be similarly styled

I'll get to both of these before the dev sync! @Vidhanvyrs, we have a meeting today at 15:00 UTC that you'd be welcome to attend if you'd like :) Details for that are in the `Development` channel in our [public Matrix space](https://matrix.to/#/#activist_community:matrix.org).

I'll close this when those changes are through 😊

**Comment by andrewtavis** [comment]
5af2074 adds a light shadow for the sidebars, but I'll hold off on the buttons rework until the changes in #215 goes through :)
