### ISSUE TITLE
Convert MediaImageCarousel to Swiper Element

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#258]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The [Swiper Vue.js Component](https://swiperjs.com/vue) is going to be removed in future versions via their documentation. We thus need to switch over the [MediaImageCarousel.vue](https://github.com/activist-org/activist/blob/main/frontend/components/media/MediaImageCarousel.vue) component to use [Swiper Element](https://swiperjs.com/element). A part of this issue would also be to switch the component over to using the Vue composition API :)

### Contribution

Happy to work on this myself or support someone who has interest 😊

**Comment by anthonyshibitov** [comment]
I'll work on this

**Comment by luuu-xu** [comment]
Let me take on this issue, I would love to leave `good-for-first-issue` to new members of our community!

**Comment by andrewtavis** [comment]
Thanks, @luuu-xu! Would be really great to get this one finalized. Appreciate you taking it on :)

**Comment by andrewtavis** [comment]
Never mind the comments on switching the `<style>` elements to Tailwind, @luuu-xu. I can see this was the best way to do this now 😊 Thanks for the fix here! Excited to get some images in here soon!
