### ISSUE TITLE
Fix TS errors in components/card directory

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#259]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is related to #211 in which we've been documenting the current TS errors that activist is facing. As of now the [components/card](https://github.com/activist-org/activist/tree/main/frontend/components/card) directory has the following error output when running `yarn nuxi typecheck` in the `frontend` directory:

```
Errors  Files
     2  components/card/CardAbout.vue:70
     1  components/card/CardConnect.vue:96
     1  components/card/CardFeedItem.vue:41
     2  components/card/CardGetInvolved.vue:64
     3  components/card/CardSearchResult.vue:183
```

Would be great if we could fix the TS errors in each of these files :)

**Comment by andrewtavis** [comment]
CC @TeddyGavi and @luuu-xu 😊

**Comment by TeddyGavi** [comment]
@andrewtavis @luuu-xu  I would like to take this one on :smile:

I have some thoughts I wanted to run by everyone. 

In  `components/card/CardAbout.vue` the different sections `organization or event` are rendered dependent on the `about-type` whereas in `components/card/CardGetInvolved.vue` the `event or organization` is rendered explicitly with a `v-if`. 

In `CardAbout` this means that without first checking that `organization` or `event` is not empty, you could possibly get undefined values. Whereas in `CardGetInvolved` they are only rendered if they have data. 

Which methodology is preferred? I haven't yet run the project to see if there is a visual need to render `event` and `organization` in `CardAbout` despite having no data. If this is the case it would be a good call to use `withDefault` with useful default descriptions for the user.

**Comment by luuu-xu** [comment]
I took a look and think that there is definitely a need to render `CardAbout` even when `organization` or `event` is empty. So maybe it should render explicitly with `v-if` and some default placeholder text with a `v-else`? @andrewtavis What do you think though?

**Comment by andrewtavis** [comment]
Hey @TeddyGavi! Thanks for picking this up! Great question :) I’d say that we should use the style that’s in `CardGetInvolved` as it’s one less prop to worry about. It’s all explicit enough as it is, I’d say. But getting this defined and documented in the style guide would also be great 😊 Maybe we can include that in this issue 😇

**Comment by andrewtavis** [comment]
Reason for this is that this component is explicitly an about for events or organizations, so if we don’t have data then that means that there’s a problem…

**Comment by andrewtavis** [comment]
But let me know if I’m missing something here :) Big thing for me is let’s try to keep it consistent 😊

**Comment by TeddyGavi** [comment]
I discovered some other concerns while working on this. My PR now has crept away from just working on these files... @andrewtavis I have a PR incoming, you can review and let me know If I should scale back what I have changed. Most important to review would be the change to `tsconfig` (i believe this was causing the `node_modules` issue we spoke about in Matrix chat)

:fearful: :+1:

**Comment by andrewtavis** [comment]
Thanks for also checking out the `node_modules` issues, @TeddyGavi! Will look into all this now :)

**Comment by andrewtavis** [comment]
My local errors after the local merge:

```
Found 49 errors in 15 files.

Errors  Files
     4  components/form/FormButtonStyledCheckbox.vue:14
     3  components/form/FormButtonStyledRadio.vue:16
     3  components/form/FormCheckbox.vue:7
     6  components/form/FormCheckboxGroup.vue:9
     3  components/form/FormRadio.vue:5
     6  components/form/FormRadioGroup.vue:6
     3  components/form/FormSearch.vue:8
     1  components/landing/LandingContent.vue:162
     4  components/modal/ModalImage.vue:9
     7  components/PageBreadcrumbs.vue:70
     2  components/selector/SelectorLanguage.vue:76
     1  components/sidebar/left/SidebarLeft.vue:44
     4  components/sidebar/left/SidebarLeftFooter.vue:17
     1  pages/events/[id]/about.vue:96
     1  pages/organizations/[id]/about.vue:83
```

Same as what @TeddyGavi reported in #280 👍 Thanks for the fix, @TeddyGavi! Closing this now :) :)
