### ISSUE TITLE
Fix TS errors in components/form directory

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#260]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is related to #211 in which we've been documenting the current TS errors that activist is facing. As of now the [components/form](https://github.com/activist-org/activist/tree/main/frontend/components/form) directory has the following error output when running `yarn nuxi typecheck` in the `frontend` directory:

```
Errors  Files
     4  components/form/FormButtonStyledCheckbox.vue:14
     3  components/form/FormButtonStyledRadio.vue:16
     3  components/form/FormCheckbox.vue:7
     6  components/form/FormCheckboxGroup.vue:9
     3  components/form/FormRadio.vue:5
     6  components/form/FormRadioGroup.vue:6
     3  components/form/FormSearch.vue:8
```

Would be great if we could fix the TS errors in each of these files :)

**Comment by andrewtavis** [comment]
CC @TeddyGavi, @luuu-xu and @Mradosi 😊

**Comment by Mradosi** [comment]
> CC @TeddyGavi, @luuu-xu and @Mradosi 😊

Ok, I will handle it :)

**Comment by andrewtavis** [comment]
Thank you, @Mradosi! Hope you've been having a nice weekend so far :) :)

**Comment by to-sta** [comment]
I happy to help here with the simply ts errors 😄. There is a recurring  error caused by :id="uuid"

```bash
components/form/FormButtonStyledCheckbox.vue:14:7 - error TS2322: Type 'number' is not assignable to type 'string'.
14       :id="uuid"
```
`id` is expecting a `string` but `uuid` is a `number`. We could solve this by converting the UUID into a string. 

```ts
let UUID = 0;

export default function useUniqueID() {
  const getID = () => {
    UUID++;
    return UUID;
  };

  return {
    getID,
  };
}
```

**Comment by andrewtavis** [comment]
Thanks @to-sta! @Mradosi, do you have an estimate on this? Would be good to get this closed by Saturday so we can have the workflows being fully functional for the Code Night contributions :)

**Comment by andrewtavis** [comment]
I’m making ok progress on this along with the work I’m doing to finish #202 :) Thanks @to-sta for the suggestion for `uuid`! If anyone has suggestions on the `props` errors or the `option` errors within the `*Group` components it’d be really appreciated!

**Comment by rigojr** [comment]
Howdy, I have some comments about this issue,

About the `uuid` this could work `const uuid = useUniqueID().getID().toString();`, and what about using [uuid](https://www.npmjs.com/package/uuid) package. The `let UUID = 0;` is causing a minor memory leak.

---

I saw the `useFormSetup` linter issue, I suggest this change `props: Record<string, unknown>`
```javascript
export default function useFormInput(
  props: Record<string, unknown>,
  emit: any,
  isDebounceEnabled?: boolean
): { updateValue: (event: Event) => void } {
...
}
```
I guess that `emit: any` could be `emit: (event: string, ...args: unknown[]) => void`. And the `debounce?: false` could be change to `isDebounceEnabled?: boolean`.

At the end, should be something like this
```javascript
import { useDebounceFn } from "@vueuse/core";

export default function useFormInput(
  props: Record<string, unknown>,
  emit: any,
  isDebounceEnabled?: boolean
): { updateValue: (event: Event) => void } {
  const inputDebounce = useDebounceFn((val: any) => {
    emit("update:modelValue", val);
  }, 1000);

  const updateValue = (event: Event): void => {
    let val: any = (event.target as HTMLInputElement).value;

    if ((event.target as HTMLInputElement).type === "checkbox") {
      val = (event.target as HTMLInputElement).checked;
    }

    if ((event.target as HTMLInputElement).type === "radio") {
      val = props.value;
    }
    if (isDebounceEnabled) {
      inputDebounce(val);
      return;
    }
    emit("update:modelValue", val);
  };

  return { updateValue };
}
```
I did not change the emit since is not related to the linter issue.

---

I could have a solution for the others linter issues but I need more time, I do have a branch with this changes but I could not push it, @andrewtavis  can you help me with that?

**Comment by andrewtavis** [comment]
Hey there, @rigojr! 👋 This is one heck of a first message! Great to have you and thanks for helping with this!

My general thoughts on this are that what you’re suggesting sounds great. Thanks further for focussing on memory leaks and the like! I have some changes to these files that by the sounds of it are more bandaids than real fixes given your `uuid` suggestion and others. I think I’ll send those along all the same as it’s mixed with a lot of work for #202, and then we can work from that state to finalize the remaining errors?

Will go ahead and assign you 😊 As far as pushing, you need to make your own fork of the repo and send your changes there, and then you’ll be able to open a PR to this repository in the GitHub UI of your fork once the changes are there :) Happy to help further with this! The process is definitely complex. 

If you have time, we also have a development community Code Night 🌙 this “evening” at [15:00 UTC](https://zonestamp.toolforge.org/1695481256). Details for that are in the development channel on Matrix, which I see you’re already in! 🎉 Feel free to join later as well as we’ll be going for a while 😊

**Comment by rigojr** [comment]
@andrewtavis sounds like a plan, I have a 403 issue when I'm trying to push my branch (I could not have a lot of time last night to take a deep look about it, maybe today I could do it.), I'll contact you in Matrix to see if we can fix it.

**Comment by andrewtavis** [comment]
Sounds good, @rigojr! I’ll make my commit with my changes soon 😊

**Comment by rigojr** [comment]
Howdy, @andrewtavis I could solve the TS issue

<img width="887" alt="image" src="https://github.com/activist-org/activist/assets/22437427/751c24c3-52fc-4a6d-8fff-c2e9e744b234">

It seems to work perfect, it is building fine but I couldn't test it, I didn't find the way to test it in the web app. 😫

And I have no rights to push my branch, I think that you should add me as a contributor.

**Comment by andrewtavis** [comment]
That screenshot's a thing of beauty there, @rigojr! ✨🤩

We can test that all's working fine via a pull request. When that's made we'll then get a preview from our deployment server with Netlify that will say that everything's working or not. By the looks of it you as of now don't have a fork of activist, so first [create one](https://github.com/activist-org/activist/fork) (link to do that). From there could you send along the git steps that you're doing so that we can check them and help you get the pull request made?

Happy to add you as a contributor eventually and to the org as well after some contributions and if you'd like to work with us long term 😊 Let's make sure that you can go through the normal contributor flow at first though :)

**Comment by andrewtavis** [comment]
Formatting changes went through in a85b64f and.... We. Are. Done! 🚀🚀

![Screenshot_2023-10-07 11 23 23](https://github.com/activist-org/activist/assets/24387426/922b4530-3906-4a45-8b2e-1f3011d67748)

Lots of thanks to go around here 🙏 
- Thank you @rigojr for the amazing first contribution! My apologies again that the review took a bit, but then I needed to rest when ill and get back into work :) Really wonderful to have you here, and I'm sure I speak for the team when I say that we'd love to work with you again 😊 
- Thank you @Mradosi for the amazing initial contributions here and getting so much done before you started work! I hope the job's going well and I hope we hear from you again soon :)
- Thank you @TeddyGav, @luuu-xu and @to-sta for the persistence in getting us through all these issues! Really so happy to have this major step in the quality of our code finished up. Can't wait for the first pass of the workflow! 🚀 

A reminder to folks that we have the dev sync [today at 15:00 UTC](https://zonestamp.toolforge.org/1696690800)! Would be great to have any of you there to celebrate :) Details for that are in the [Development room](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org?via=matrix.org&via=acter.global&via=chat.0x7cd.xyz) on Matrix 🧑‍💻♻️
