### ISSUE TITLE
Fix TS errors in pages directory

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#261]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is related to #211 in which we've been documenting the current TS errors that activist is facing. As of now the [frontend/pages](https://github.com/activist-org/activist/tree/main/frontend/pages) directory has the following error output when running `yarn nuxi typecheck` in the `frontend` directory:

```
Errors  Files
     1  pages/events/[id]/about.vue:75
     1  pages/events/index.vue:33
     3  pages/home/index.vue:43
     1  pages/organizations/[id]/about.vue:69
     1  pages/organizations/index.vue:33
```

Would be great if we could fix the TS errors in each of these files :)

**Comment by andrewtavis** [comment]
CC @TeddyGavi and @luuu-xu 🙃

**Comment by TeddyGavi** [comment]
I can take this on as well :)

As of #259 it seems there are only:

![image](https://github.com/activist-org/activist/assets/102203363/4e8311d2-99fa-4ff3-b6ee-5f0c2d60ec6d)

Which relates to the typing of `event and organization` in the types directory. as `socialLinks?: [string]`. If we want more than one string it should be `string[]` or `Array<string>`. 

`Array<string>` is used elsewhere so we should continue with that?

**Comment by andrewtavis** [comment]
Thanks, @TeddyGavi! Can a part of this be that you’d switch over the `Array<string>` instances to `string[]` and do the same for other classes? Seems that the Nuxt folks are [using the latter](https://github.com/search?q=repo%3Anuxt%2Fhackernews%20string%5B&type=code). You could also do a quick update of the [TS section of the style guide](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md#typescript-) to direct people to do this and maybe remove the section about what’s needed for a `<script>` block if the Nuxt Options API is used?

**Comment by andrewtavis** [comment]
218d3cf did some minor cleanups to the styleguide so we get the code block for the composition API back in there. Sorry for poor directions on that, @TeddyGavi! Checking via `yarn nuxi typecheck` shows that we're done with the `pages` directory now 🥳 Thank you!
