### ISSUE TITLE
Fix TS errors in misc components

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#262]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is related to #211 in which we've been documenting the current TS errors that activist is facing. As of now the [components](https://github.com/activist-org/activist/tree/main/frontend/components/form) directory has a few miscellaneous `.vue` files that have the following error output when running `yarn nuxi typecheck` in the `frontend` directory:

```
Errors  Files
     1  components/landing/LandingContent.vue:162
     4  components/modal/ModalImage.vue:9
     9  components/PageBreadcrumbs.vue:53
     2  components/selector/SelectorLanguage.vue:76
     4  components/sidebar/left/SidebarLeftFooter.vue:17
```

Would be great if we could fix the TS errors in each of these files :)

**Comment by andrewtavis** [comment]
CC @TeddyGavi and @luuu-xu 😇  Too many CCs, but I figure you two would like to follow these and maybe help coordinate the work if someone wants to work on some of these :)

**Comment by luuu-xu** [comment]
Let me handle this TS issue since it has breadcrumbs which I consider as my baby now, haha 😛

**Comment by andrewtavis** [comment]
Thank you, @luuu-xu! Looking forward to getting all these TS finalized :) :)

**Comment by andrewtavis** [comment]
140e62d finalizes this, @luuu-xu :) :) Added back the name of the local, and I also fixed the issue where the local name would be broken onto two lines when it's in the header.

Thanks for the work here! Hope to see you in the sync, or if not as I wrote on Matrix let's set up a call!
