### ISSUE TITLE
Website footer as flex at large breakpoint when there's no sidebar

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#263]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

As of now the way that the [footer component group](https://github.com/activist-org/activist/tree/main/frontend/components/footer) works is that `FooterFlex` is only applied after the `xl` breakpoint so that it's not restricted when there's a sidebar. It would be great if we could check to see if the sidebar layout is being used, and if not such as for the landing page we could apply `FooterFlex` after the lg breakpoint. Reasoning for this is that `FooterFlex` is more of a desktop footer and thus fits better if it won't be restricted :)

**Comment by andrewtavis** [comment]
The screenshot below illustrates this a bit better. This is the footer at the large breakpoint on the desktop, which is currently `FooterFlexCol` and has tons of space to the left and right. It'd be great for it to be `FooterFlex` while still being like this when there's a sidebar.

![Screenshot_2023-08-13 01 58 55](https://github.com/activist-org/activist/assets/24387426/40803f79-923b-446d-b81d-82868df2c2e9)

**Comment by Vidhanvyrs** [comment]
hey @andrewtavis can i work on this

**Comment by andrewtavis** [comment]
Fantastic, @Vidhanvyrs! Thanks for picking this up, and please let me know if you have any questions :) :)

**Comment by Vidhanvyrs** [comment]
thanx for assigning me this issue
If I understand correctly, you want to adjust the behavior of the FooterFlex component based on whether a sidebar layout is being used and also the screen size breakpoints. You also want the FooterFlex to be applied at the lg breakpoint for the landing page when there's no sidebar right

**Comment by andrewtavis** [comment]
It's more just when `FooterFlex` is applied, @Vidhanvyrs. Something that could happen here is we rearrange [Footer.vue](https://github.com/activist-org/activist/blob/main/frontend/components/footer/Footer.vue) and its sub-components such that the Tailwind based `hidden` and `flex` classes to hide and show the footers are contained within `Footer`. Then from there we can add a boolean condition in for whether the sidebar is present ot not at any given point and then change the class based on this. What I mean would be something along the lines of:

```html
<div class="..." :class="{ 
  'hidden xl:flex': sidebarPresent, 
  'hidden lg:flex': !sidebarPresent
}"></div>
```

Let me do the first part of this so you can see where the changes would happen in [Footer.vue](https://github.com/activist-org/activist/blob/main/frontend/components/footer/Footer.vue) :)

**Comment by Vidhanvyrs** [comment]
okay so we can make a variable let say sidebarPresent and set it to false initially, and will change it based on your actual logic that determines whether the sidebar is present or not.
And then in our FooterFlexCol and FooterFlex component, we can use this sidebarPresent as a prop to conditionally apply the classes:
Right

**Comment by Vidhanvyrs** [comment]
> It's more just when `FooterFlex` is applied, @Vidhanvyrs. Something that could happen here is we rearrange [Footer.vue](https://github.com/activist-org/activist/blob/main/frontend/components/footer/Footer.vue) and its sub-components such that the Tailwind based `hidden` and `flex` classes to hide and show the footers are contained within `Footer`. Then from there we can add a boolean condition in for whether the sidebar is present ot not at any given point and then change the class based on this. What I mean would be something along the lines of:
> 
> ```
> <div class="..." :class="{ 
>   'hidden xl:flex': sidebarPresent, 
>   'hidden lg:flex': !sidebarPresent
> }"></div>
> ```
> 
> Let me do the first part of this so you can see where the changes would happen in [Footer.vue](https://github.com/activist-org/activist/blob/main/frontend/components/footer/Footer.vue) :)

okay then let me know if the change is done so i can start working on it

**Comment by andrewtavis** [comment]
Hey @Vidhanvyrs! af37998 does the changes I'd discussed that I'd do for this :) We now are controlling which footer type is displayed via the classes in the [Footer.vue](https://github.com/activist-org/activist/blob/main/frontend/components/footer/Footer.vue) component. From here we just need to detect the sidebar and change the current classes to conditional ones 😊

**Comment by Vidhanvyrs** [comment]
sorry to keep you waiting but i have come up with the solution to this i am going to add a PR and want to know about the changes and feedback on it

**Comment by andrewtavis** [comment]
Hey @Vidhanvyrs 👋 Sounds great! Send along the PR and we can discuss in there :)

**Comment by andrewtavis** [comment]
317cf26 closes this, @Vidhanvyrs. I actually ended up doing edits to it so that we can make this work where the transition from `flex-col` to `flex` happens after the `lg` breakpoint is passed. In implementing that the sidebar covers the content at the `lg` breakpont we thus have the space for `flex`. Thanks for the contributions and the thought process here!
