### ISSUE TITLE
Remove Twitter from the footer and community banner

### ISSUE THREAD

**Issue by wkyoshida** [activist-org/activist#264]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

As indicated by the commit [7875c8f](https://github.com/activist-org/activist/commit/7875c8f1c410c1de2a300d1f8ca0cc3be7676191) and discussion in https://github.com/activist-org/activist/issues/244#issuecomment-1656811749, should Twitter be removed from the `Connect` section of the footer?

**Comment by andrewtavis** [comment]
Thanks for the issue, @wkyoshida! I'd definitely agree 😊 The places it should be removed are the [footer components](https://github.com/activist-org/activist/tree/main/frontend/components/footer) as well as the [community banner for the landing page](https://github.com/activist-org/activist/blob/main/frontend/components/landing/LandingCommunityBanner.vue) :) I'll rename the issue to reflect this. You're welcome to work on this, or we can also leave it as a `good first issue`!

**Comment by andrewtavis** [comment]
Thing of beauty that there activist.org without a bird above the fold or in the footer ✨ Thanks for the issue, @wkyoshida, and thanks for the implementation, @tarunsamanta2k20!
