### ISSUE TITLE
Create user search result card

### ISSUE THREAD

**Issue by anthonyshibitov** [activist-org/activist#265]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Create the User search result card, per figma design specs under "Event Team"

I'll be working on this :)

**Comment by andrewtavis** [comment]
Closed via #266! Great to have you back, @anthonyshibitov! :) :)
