### ISSUE TITLE
Nuxt layout for a page with a header and sidebar

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#270]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

A very common layout that is needed is the one that's displaying content on organization and event pages. As can be seen in the [MVP designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=766%3A214&mode=design&t=pctNmHd3eWcrj6hc-1), this layout consists of a sidebar that would be inherited from the [sidebar layout](https://github.com/activist-org/activist/blob/main/frontend/layouts/sidebar.vue) and would further include a page header, a page tagline, a slot for CTA buttons on the top of the page and then page content would fall below the CTA buttons and tagline. Having one layout for this would allow us to consolidate breakpoint styling for many pages and then have individual components control how they appear at certain screen widths.

### Contribution

This is a major priority now to make sure that we are not repeating our page logic too much. I'll be working on this, and would appreciate ideas of how best to implement this :)

**Comment by luuu-xu** [comment]
I agree this is the major priority now. It seems like it's easy to implement since the layout is only consisted of header, tagline and main content. I imagine Event/Organization Settings page will also use this layout too? 

Make sure you assign yourself to this issue! 😁

**Comment by andrewtavis** [comment]
Thanks for the heads up, @luuu-xu! :)

**Comment by andrewtavis** [comment]
Thinking about this atm and looking into some documentation, I don't think it's advisable to make a layout in this way. There are no props for layouts, so we wouldn't be able to pass the needed text information to the layout and still have them formatted appropriately. If we want to make sure that all headers are correctly formatted and can just have strings passed, then the best way to do it would be to create a component :)

Will look into this now 😊

**Comment by andrewtavis** [comment]
1a9bcdf adds in [HeaderAppPage.vue](https://github.com/activist-org/activist/blob/main/frontend/components/header/HeaderAppPage.vue) that styles the header and tagline of a page. There's also a slot for right justified content that's inline with the tagline in which buttons and drop downs can be placed 😊 Using this will make the designs for future app pages much easier 🚀
