### ISSUE TITLE
Create IconOrganizationStatus component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#272]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would create the component that indicates whether an organization is approved or pending approval and would serve as the link to its application page to see what organizations supported it coming on to activist. An example of it can be seen on [this page of the MVP designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2408%3A4794&mode=design&t=hJRakNbmbK83mZ9P-1), and its options can be seen below:

![Organization Status](https://github.com/activist-org/activist/assets/24387426/4b7f6039-9c0d-4d7d-8537-39e7be79ca04)

This component would include:

- A required `status` prop
- The styling would be based on the colors that are defined in [tailwind.config.ts](https://github.com/activist-org/activist/blob/main/frontend/tailwind.config.ts)
- The size would react to certain breakpoints

### Contribution

This is a great `good first issue`! I'd be happy to support someone who wants to work on this 😊

**Comment by to-sta** [comment]
I would like give this issue a try. Is there any prefered icon package for the icons?

**Comment by andrewtavis** [comment]
There's no preferred icon set per say, @to-sta, but we generally have been using [Bootstrap Icons](https://icones.js.org/collection/bi) for most things :) Thanks for your interest in working on this!

**Comment by andrewtavis** [comment]
We're good to go now, @to-sta! Minor edits are in f49c3fd:

- As discussed removing the import
- For the Tailwind coloration we need to apply `dark:fill-FILL_COLOR` for the dark mode colors to be used
  - Didn't catch this in the review. My apologies!
- Made the space between the name and icon a bit bigger :)

Thanks again so much!

**Comment by andrewtavis** [comment]
Updated the styleguide with some documentation for the color mode in e2e7950 :) :)
