### ISSUE TITLE
Create base MediaVideo component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#273]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would create a baseline file for the `MediaVideo` component that could be used to either show a video on a page or link in to a video call if the event is online. This component is generally defined in the designs with the other [Page Media components](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2673%3A20111&mode=design&t=hJRakNbmbK83mZ9P-1) that are then created in the [components/media](https://github.com/activist-org/activist/tree/main/frontend/components/media) directory :) We do not need a full implementation for this task, but more a component that:

- Has a required `link` prop
- Is sized similar to other components in the [components/media](https://github.com/activist-org/activist/tree/main/frontend/components/media) directory
- Follows coloration as set out in [tailwind.config.ts](https://github.com/activist-org/activist/blob/main/frontend/tailwind.config.ts)

Later on we can add to this component where video links would lead to a popover or video links would direct the user to the call. An example of the basis we want for now is:

![Mode=Dark, Mobile=False, Type=Video](https://github.com/activist-org/activist/assets/24387426/f149a3fb-8a5b-4818-8763-3011af743f4f)

### Contribution

Happy to support someone on this issue or work on it myself :)

**Comment by otaree** [comment]
Since it is not assigned to anyone, I would like to give it a try.

**Comment by andrewtavis** [comment]
I'm seeing also that the component's file was really well formatted, @otaree 😊 Appreciate that as well :) Let me know if you'd like to get started on #303 and pleasure to meet you earlier today!

**Comment by otaree** [comment]
Great to meet you earlier! Excited to contribute to #303 and start working on it.
