### ISSUE TITLE
Create CardDangerZone component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#274]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would create the `CardDangerZone` component that would be used by the user to delete certain elements on the page. Designs for it can be seen on the [MVP page of Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2475%3A10600&mode=design&t=hJRakNbmbK83mZ9P-1). This component would include:

- A required `description` prop
- A required `ctaBtnText` prop
- Text entry for user names and passwords
- Styling using the colors found in [tailwind.config.ts](https://github.com/activist-org/activist/blob/main/frontend/tailwind.config.ts)

An example of the component can be seen here:

![Personal Information](https://github.com/activist-org/activist/assets/24387426/151995ee-33fb-4e47-bf66-935d5689e8da)

### Contribution

This is a great `good first issue` that I'd be happy to support someone in working on! Also happy to work on it myself if others don't have interest :)

**Comment by to-sta** [comment]
I would like to work on this issue.

**Comment by andrewtavis** [comment]
Thanks, @to-sta! Really great to get this done so we can do the settings pages 😊

**Comment by andrewtavis** [comment]
4eb4bd6 does some minor changes to finish this up, @to-sta! Thanks again! 🙏😊 Coloration changes were more based on getting a distinct color for light and dark mode, although all this will likely shift a bit given #215 and the coloration shift that will happen when I get to that :)
