### ISSUE TITLE
Create CardChangeAccountInfo component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#275]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would be to create the `CardChangeAccountInfo` component that can be seen in the [MVP designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2475%3A10600&mode=design&t=hJRakNbmbK83mZ9P-1). This would be a versitile card that could be used for actions like changing a user name or changing a password. It would include:

- A required `header` prop
- An optional `description` prop
- A required `infoType` prop that would have options of `username | password | email` (for users who are using email sign in rather than another method)
- A CTA btn with a `ctaLabel` prop
- Coloration based on the designs and coloration in [tailwind.config.ts](https://github.com/activist-org/activist/blob/main/frontend/tailwind.config.ts)

An example of this component can be seen below:

![Change Username](https://github.com/activist-org/activist/assets/24387426/0241d107-2977-45b6-92c1-1ee0bea423ac)

### Contribution

Happy to work on this with someone who's new to the community, support a prior contributor or work on this myself 😊

**Comment by RyanPaulGannon** [comment]
I'll have a crack at this if that's cool? I could do with keeping my hand in some OSS front end stuff 😅

**Comment by andrewtavis** [comment]
Thanks for your willingness to help, @RyanPaulGannon! Please let me know if you need any assistance with this :)
