### ISSUE TITLE
Allow the legal disclaimer field within CardGetInvolved to be expanded

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#277]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue focuses on the [CardGetInvolved](https://github.com/activist-org/activist/blob/main/frontend/components/card/CardGetInvolved.vue) component that for events has a legal disclaimer section. We need to change this component such that this section that as of now can just be clicked with some user feedback will open a dropdown. The text for this dropdown further needs to be added as a prop to the component.

### Contribution

Happy to work on this or support someone who'd like to work on it!

**Comment by to-sta** [comment]
Since this is not assigned to someone yet i would like give it try.

**Comment by andrewtavis** [comment]
Thank you, @to-sta! Looking at this, I think we can get rid of `getInvolvedType` and just change it based on whether `organization` or `event` are assigned. Beyond this, we need a `disclaimer` prop that would be required as this is something we're going to want to be doing for each event :)

**Comment by andrewtavis** [comment]
a18c703 includes a minor change that I missed, @to-sta: we needed to have a pointer on hover for the legal disclaimer. That commit and #302 closes this issue! Thanks for this, and have fun working on some backend 😊
