### ISSUE TITLE
Create mobile page menu options screen

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#278]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would focus on the creation of the page that would be displayed on `/events/EVENT_ID` and `organizations/ORG_ID` pages for mobile devices. An example of this page can be seen on the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2461%3A7036&mode=design&t=hJRakNbmbK83mZ9P-1) and below:

![Mobile Organization Navigation](https://github.com/activist-org/activist/assets/24387426/e20405b7-072d-4df9-8be6-40462f27f20d)

On desktop views above the `sm` breakpoint we'll be routing people directly to the `.../about` page, but for smaller views this would be the first thing the user would see so that they can more easily see an overview of the contents of the pages. Generally this page would inherit the image from the sidebar and would have the options found below, so inheriting this information someone might be best 🤔

### Contribution

Happy to discuss this and work on it with those who have interest! 😊

**Comment by felipolis** [comment]
I have a question about this issue. Since we still don't have endpoints to carry out requests to obtain organization or event data from the database, should the page be static for now?

**Comment by felipolis** [comment]
I would love to work on this issue. Could you assign me?

**Comment by andrewtavis** [comment]
Hey @felipolis! Yes it can be static for now 😊 We can do the routing to the various pages in #283 and hydrate the image later. For now we can use either the event or organization placeholders that are in `frontend/image` 🖼️

Assigning you now! Let me know if there's anything I can do to help :)

**Comment by felipolis** [comment]
Hi @andrewtavis, where is this frontend/image that you talked about?

**Comment by felipolis** [comment]
Hey @andrewtavis , how's it going? Regarding these buttons on both the /events/[id] and /organizations/[id] pages, do you think it would be a good idea for me to create a specific component for these buttons? That way, I won't have to copy and reuse button code. If yes, any suggestions for the name of this component? I was thinking of calling it BtnActivism since it would be used on both the organizations and events screens. What do you think?

**Comment by andrewtavis** [comment]
Hey @felipolis! Doing well :) How's all with you? :) I think that for this we can use [MenuLinkWrapper](https://github.com/activist-org/activist/blob/main/frontend/components/menu/MenuLinkWrapper.vue) as is done in [MenuMobileNavBar](https://github.com/activist-org/activist/blob/main/frontend/components/menu/MenuMobileNavBar.vue) and [SidebarLeftSelector](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftSelector.vue). That's used to style the buttons :) The way that the Tailwind is written on that component is a bit weird, but will be rewritten in #319 😊

**Comment by andrewtavis** [comment]
#347 and 802e24a close this 🥳 Thanks for the work here, @felipolis! Notes on what I changed:

- I got rid of the options that are not activated right now (I figure we can just diplay those for potential on desktop)
- I extracted the menu type into its own file [menu-selector.d.ts](https://github.com/activist-org/activist/blob/main/frontend/types/menu-selector.d.ts)
  - We can expand on this in #354 where this would be the type of the state that's shared between this screen, the mobile navigation dropdown and the left sidebar index :)
- I added a join now button for now, but we can discuss if this is useful 😊
- I applied the sidebar layout so we get the app header and the mobile nav bar
- Other random changes to fix things like shadows, etc :)

Thanks so much for the work here! Hope to see you tomorrow 😊
