### ISSUE TITLE
Left sidebar navigation between [id] sub pages

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#283]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue focuses on navigation on event and organization pages. We need to make it possible for the user to navigate between sub pages for events and organizations via the left sidebar. When a user clicks an option like `About`, `Events` or `Settings` they should be navigated to the corresponding page within the current `[id]` sub domain. The following would work on pages like [this placeholder event](https://activist.org/events/123/about).

### Contribution

Happy to work on this myself or support someone who has interest! We should definitely discuss how best to implement this before work begins though 😊

**Comment by luuu-xu** [comment]
Please assign me on this! It seems like a priority and let's make it happen.

**Comment by andrewtavis** [comment]
I was honestly thinking of doing the same, @luuu-xu 😊 Happy to assign!

**Comment by andrewtavis** [comment]
Let me know if there’s anything I can do to help :)

**Comment by andrewtavis** [comment]
Closed via #342 😊 Along with adding in the sidebar to the other pages, I'm realizing we should also highlight the current page as well. I'll make an issue that includes both of these so we can keep a record of it.

Thank you, @luuu-xu!
