### ISSUE TITLE
Localization of user-generated content

### ISSUE THREAD

**Issue by wkyoshida** [activist-org/activist#284]
### Terms

- [X] I have searched [open localization issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+is%3Aopen+label%3Alocalization)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

My guess is that #226 is more to address the localization of the platform itself. Wanted to throw an idea out there as well of something localization-like for user-generated content also. Should the platform have some features to help organizations post content in different languages? And then to also help display the more appropriate localized versions for users?

This issue could be simply to discuss this. Just something that came to mind as I was browsing activist.

**Comment by andrewtavis** [comment]
Yes, @wkyoshida, very much so! Giving organizations the ability to localize their content is definitely something we want to do, and having a place to discuss the options is great 😊 Thanks for opening the issue!

Some thoughts on this:
- From a discussion yesterday of potentially localized organization onboarding flows (at some point), I think that we should keep in mind that localizing all things for organizations might not help in that if they don’t have the ability to communicate in those languages, then sending people to them might not be the best
- With that being said, we won’t necessarily be able to stop them from localizing into whatever they want, so maybe just making them turn on the languages they want and making it clear that they need to consider fully before opening a language (we’ll see in analytics, but I’m hopeful this will help)
- To get them to only select a few, we can also show how the language use breaks down for the region they’re in and prompt them to choose things based on that (Maybe Wikidata or another linked open data source 😇)
- I’m not sure if resources should or should not be included in this potential scheme 🤔 Some resources will be locality based and thus not for all, whereas others could be more general use

The question of how to do this is also a question. Maybe there’s a software out there that we could imbed in the platform as this would inherently be something that users are doing. We need to be able to make calls to the database for the current continent and then send back the new ones. What kind of a table structure? Is the text content for each table being extracted to another table where we’d have an `id` as the primary key and then something like `description_en`, `description_pt`?

**Comment by andrewtavis** [comment]
I think that the conversation yesterday closed this question issue :) We can make other issues that are for specifics aspects of the text editing experience.

Note that the designs for localizable text edit modal can be seen on Figma [here](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=9485%3A20777&mode=design&t=d727LmwI7VisLSdL-1). Thanks all again so much for the great conversation!
