### ISSUE TITLE
Add needed strings to localizable JSON file

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#288]
### Terms

- [X] I have searched [open localization issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+is%3Aopen+label%3Alocalization)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to go through and add in the localizable strings that are currently not in [i18n/en-US.json](https://github.com/activist-org/activist/blob/main/frontend/i18n/en-US.json). All strings that are on the platform should be within this file such that they can be localized.

**Comment by felipolis** [comment]
Let me see if I understood. Should I look for strings within the project that are not in the i18n/en-US.json file and add these strings to this file? I'm interested in working on this issue

**Comment by andrewtavis** [comment]
Yes, @felipolis, that’s exactly what we’re looking for here. Feel free to send along whatever keys you think are best in a PR and I’ll fix them if they need to be 😊 Thanks for your willingness to help!

**Comment by felipolis** [comment]
Working on it. Thank you!!!

**Comment by andrewtavis** [comment]
Thank you, @felipolis!

**Comment by felipolis** [comment]
@andrewtavis I've just made a pull request. I would be grateful if you could take a look. I did my best :D

**Comment by andrewtavis** [comment]
@felipolis, let’s definitely remember to do an edit to the [contributing guidelines](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md) to account for the conventions we set out here :) I’d be happy to do this myself, but let’s just make sure it gets done as this will be important for others to understand 😊

**Comment by andrewtavis** [comment]
716c0a5 finishes this off, @felipolis 😊 Thanks for all the work here! Please let me know what you think of the [localization styleguide entry](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md#localization)!

Feel free to open another issue if you find some things, and we can used this closed issue to discuss the style guide if need be :) :)

**Comment by andrewtavis** [comment]
Thinking about the system one more time, @felipolis, I'm thinking some further changes might make the text keys a bit more understandable:

- Instead of `"section-#-paragraph-#-pt-#"` we can do `"section-#-paragraph-#-#"`
- Instead of `"section-#-list-#-item-#-subitem-#"` we can do `"section-#-list-#-item-#-#"`

I think this'd be more convenient and would still make sense pretty quickly, but please let me know what you think 😊

**Comment by andrewtavis** [comment]
0f6e891 did the changes [mentioned above](https://github.com/activist-org/activist/issues/288#issuecomment-1694870580), @felipolis :) Please let me know what you think of the system! :)
