### ISSUE TITLE
Header visibility reactive to scrolling

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#29]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

It would be great if [WebsiteHeader.vue](https://github.com/activist-org/activist/blob/main/frontend/components/WebsiteHeader.vue) was reactive to user scrolling. The ideality would be that there would be no shadow at first and that once the user scrolls the background of the header would get an alpha value. Beyond this, ideally the header would disappear when scrolling down and reappear upon scrolling up.

### Contribution

I'll work on this eventually, but would be happy to discuss or get some help with it 🙃

**Comment by andrewtavis** [comment]
@purupurupu, if you write in here I can assign the issue to you 😊 Let me know if you'd like me to look into possible solutions to this! Happy to support 🚀

**Comment by purupurupu** [comment]
@andrewtavis 
I would be happy to be assigned to Issue.

**Comment by andrewtavis** [comment]
Assigned! 😊 Here if you have questions or want to check your ideas :)

**Comment by purupurupu** [comment]
@andrewtavis 
Thank you for assign !!
I just fixed and pushed it.please check it.

**Comment by andrewtavis** [comment]
@purupurupu, hope it's ok that I finished the feature off :) I'm trying to keep the styling in Tailwind, so made sense to me 😊

Here's what changed in 6205822:
- Added `duration-500` to the header class, which thus moves the transition there from the `<style>`
- Tested the opacities a bit and decided to go with 0.8 for when we scroll up
- Used Tailwind `:class` and set the background colors so that they're responsive to light and dark mode as well as what the opacity value is
- Referenced the height of the header and used that as the cutoff point for when the header should be made transparent
    - Thus there's no case where we see the background color behind the header :)

Thanks so much for your work on this! Really enjoyed working with you 😊

**Comment by purupurupu** [comment]
@andrewtavis 
I see, your correction is spot on!
Thanks for being so accommodating! I learned a lot!

**Comment by andrewtavis** [comment]
Happy to have you contribute to more issues in the future, @purupurupu! 😊 Let me know if you have ideas or want to work on something :)
