### ISSUE TITLE
a11y: SidebarLeftFooter's tab control order needs to be fixed

### ISSUE THREAD

**Issue by luuu-xu** [activist-org/activist#291]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

While I was working on fixing TS errors in `SidebarLeftFooter`, I tried using tab and found out the tab order can be improved.

The current behaviour: when tab selects either "Create", "Info" and "Username", now presses enter key, the selected button is clicked, and expanded. but the tab focus is now focusing on the last button "Username".

The correct behaviour: when the selected button is entered, the **tab focus should instead focus on the first of these according sub buttons**. Example: when "Create" is entered, sub buttons "New Event", "New Organization", "New Group" and "New Resource" are shown, and the tab focus should be on "New Event".

### Contribution

I would love to work on this myself!

**Comment by andrewtavis** [comment]
Thanks for bringing this up, @luuu-xu! Assigned 😊 Let me know if you need any support :) :)

**Comment by andrewtavis** [comment]
Closed via #333! Thank you, @luuu-xu 🙌
