### ISSUE TITLE
 Implementing Swagger UI with OpenAPI 3.0 Specification using drf-spectacular in activist-org's core API

### ISSUE THREAD

**Issue by momanyisamuel** [activist-org/activist#294]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Swagger UI provides an intuitive and interactive way for developers to explore and interact with activist-org's API documentation. To enhance the developer experience and promote a standardized API documentation format, I propose implementing Swagger UI using the OpenAPI 3.0 specification in activist-org's Django Rest Framework (DRF) API. This can be achieved efficiently by integrating the drf-spectacular package into the project.

**Proposed Solution:**
The proposed solution involves integrating the drf-spectacular package to generate and display Swagger UI for activist-org's API documentation. This will provide developers with a user-friendly interface to explore endpoints, request/response structures, authentication requirements, and more.

### Contribution

Happy to support someone on this issue or work on it myself

**Comment by to-sta** [comment]
I would like to work on this issue.

**Comment by andrewtavis** [comment]
Looks like @momanyisamuel self assigned this, @to-sta :) I'll let him decide if he wants to give it up :)

**Comment by momanyisamuel** [comment]
Hey @to-sta sorry for the delay, you can work on this

**Comment by to-sta** [comment]
Thanks @momanyisamuel for assinging me. I can implement Swagger UI with the drf-spectacular package but i am not able to test it, since there are still errors while running django. Should i wait for these to be fixed and/or create an issue for it?
 
models.py related issues: (Prevents running the server, there is a fix for this in PR #334)
```bash
    value.contribute_to_class(cls, name)
  File "C:\Users\tobia\Documents\Projects\contrib\activist\activist\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 895, in contribute_to_class
    self.set_attributes_from_name(name)
  File "C:\Users\tobia\Documents\Projects\contrib\activist\activist\venv\Lib\site-packages\django\contrib\postgres\fields\array.py", line 104, in set_attributes_from_name
    self.base_field.set_attributes_from_name(name)
TypeError: Field.set_attributes_from_name() missing 1 required positional argument: 'name'
```

admin, authentication and url issues: 
```bash
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
<class 'entities.admin.OrganizationAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'application_id', which is not a callable, an attribute of 'OrganizationAdmin', or an attribute or method on 'entities.Organization'.
<class 'entities.admin.OrganizationAdmin'>: (admin.E108) The value of 'list_display[3]' refers to 'social_accounts', which is not a callable, an attribute of 'OrganizationAdmin', or an attribute or method on 'entities.Organization'.
authentication.Support.supported_type: (fields.E304) Reverse accessor 'SupportEntityType.support_set' for 'authentication.Support.supported_type' clashes with reverse accessor for 'authentication.Support.supporter_type'.
        HINT: Add or change a related_name argument to the definition for 'authentication.Support.supported_type' or 'authentication.Support.supporter_type'.
authentication.Support.supporter_type: (fields.E304) Reverse accessor 'SupportEntityType.support_set' for 'authentication.Support.supporter_type' clashes with reverse accessor for 'authentication.Support.supported_type'.
        HINT: Add or change a related_name argument to the definition for 'authentication.Support.supporter_type' or 'authentication.Support.supported_type'.

WARNINGS:
?: (urls.W002) Your URL pattern '/v1/organizations/' has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
?: (urls.W002) Your URL pattern '/v1/organizations/<int:organization_id>' has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.

System check identified 6 issues (0 silenced).
```

**Comment by to-sta** [comment]
The PR #351 fixes the issues address above. I will start working on this after its merged/resolved.

**Comment by andrewtavis** [comment]
Closed via #375 and a quick fix in cdd50eb 😊 Thanks for the work here @to-sta, and also @momanyisamuel for the detailed issue and planning here 🚀

**Comment by to-sta** [comment]
Just checked the endpoint for the Swagger UI after the merge of PR #378.

![image](https://github.com/activist-org/activist/assets/49518857/0cbd36f0-ef17-42b9-b4c7-30a7da879624)

**Comment by andrewtavis** [comment]
Looking beautiful 😍
