### ISSUE TITLE
Add reference to TS check to maintainers checklist

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#314]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Via a discussion in #228, it would be great to get a another checkbox in the [maintainers checklist](https://github.com/activist-org/activist/blob/main/.github/workflows/pr_maintainer_checklist.yaml) that tells the reviewer to also check the TypeScript errors via the TS check. Referencing the PR number in the maintainer checklist flow would be great so we can make a link to the checks with a URL like - for example for #313 - https://github.com/activist-org/activist/pull/313/checks. 

### Contribution

This issue’s reserved for @TeddyGavi at first, but then can go to others :) Happy to support!

**Comment by TeddyGavi** [comment]
@andrewtavis Sure I'll take this on! :+1:

**Comment by andrewtavis** [comment]
Thanks @TeddyGavi! The work here inspired some other workflows as well, if you haven't already seen #316 😊

**Comment by andrewtavis** [comment]
011e460 adds in a reference to the formatting workflow, @TeddyGavi! As of now it's just for the backend, but we'll add one for the frontend soon too :) We've got ourselves some great PR infrastructure now! 😊 Thanks for the help!
