### ISSUE TITLE
Black formatting check

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#316]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In the `styleguide` [black](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md?plain=1#L123) is mention for formatting python code. Would it make sense to add a github workflow for it to ensure its enforced. 

### Contribution

I could help with the implementation.

**Comment by andrewtavis** [comment]
Sounds interesting, @to-sta! Curious how this will work in a workflow :) Assigning you now 😊

**Comment by andrewtavis** [comment]
91af592 sends the minor edits I mentioned, @to-sta :) We can close this when we see it's working, and let me know what your thoughts are for a similar workflow for the frontend!

**Comment by to-sta** [comment]
@andrewtavis i will think about the frontend 😊. I also want to check [flake8](https://flake8.pycqa.org/en/latest/) additionally to `black` for the backend. Since black just checks the formatting but does not lint. Might be useful in the future to catch unused imports and so on.

I am also stoked to see the next PR 😃

**Comment by andrewtavis** [comment]
All sounds good, @to-sta! Once this is done I’ll edit the maintainer checklist point that @TeddyGavi is working on in #314 so that we have one that’s for confirming that all checks have passed :)

**Comment by to-sta** [comment]
@andrewtavis Iet's close this. I will make a new one for the frontend.

**Comment by andrewtavis** [comment]
Sounds good, @to-sta! Thanks for the work on this one and looking forward to the next!
