### ISSUE TITLE
View lower on back button press navigation

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#318]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

We have a minor bug that the view of the screen is shifting down when a user presses the back button - i.e. the user navigates to a new page, then goes back, and then their view on the original page is lower than it was before.

I think that the following could be related to the [Loading.vue](https://github.com/activist-org/activist/blob/main/frontend/components/Loading.vue) component. The height of the shift is roughly that of the screen, so maybe this component is loading, shifts the view down, and then disappears. 

Note: this is on Chrome and Firefox at least.

**Comment by henrque** [comment]
Hey, I'm new to the open source community. I'd like to take on this task. Could you assign it to me?

**Comment by andrewtavis** [comment]
Hey @henrque! Thanks for reaching out and for your interest in activist :) Assigning you now, and please let me know if you have any questions 😊

**Comment by andrewtavis** [comment]
Just checked it live as well and can confirm that #326 fixes this 😊 Thanks again, @henrque! 🚀
