### ISSUE TITLE
Standardize conditional class assignments

### ISSUE THREAD

**Issue by anthonyshibitov** [activist-org/activist#319]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We currently have a mixture of different conditional class assignments used throughout our components.

`:class="open ? 'rotate-180 transform' : ''"`
_SidebarLeftFooter.vue_

`:class="{ 'hidden translate-x-full': !isMenuOpen }"`
_SidebarRight.vue_

`:class="[
      'text-xl font-bold relative min-w-[3.4rem] h-11 min-h-[2.75rem] border border-light-interactive dark:border-dark-interactive border-r-0 last:border-r bg-light-header text-light-special-text dark:text-dark-special-text dark:bg-dark-header first:rounded-l-md last:rounded-r-md',
      {
        'bg-dark-header dark:bg-dark-menu-selection text-dark-interactive dark:text-dark-distinct border-dark-header dark:border-light-header':
          modelValue,
      },
    ]"`
_FormButtonStyledCheckbox.vue_

`:class="[isMobile ? 'w-24 h-6' : '', color]"`
_LogoActivist.vue_

In an effort to be consistent, we should decide on one style and change all of our current conditional class assignments to match this. If there is a standardized way to do this, or pros and cons to certain styles, we can discuss and decide which one to implement! :)

**Comment by andrewtavis** [comment]
Thanks @anthonyshibitov! 😊 Let me know if you want to work on this, or we can also leave it for a new contributor :)

(😴 -> 🛏️)

**Comment by luuu-xu** [comment]
I agree, now these different styles are messy. I think I like 1 and 4 better because the prop is at the front and I feel like it is more readable. But in the meantime 2 and 3 is shorter and cleaner if the classes are long and complex. Okay, I am gonna vote for 2 and 3 now.

**Comment by andrewtavis** [comment]
I’d vote for 2 personally as the syntax formatting is the best for this one. For 3 it gets a bit weird, and I feel like 2 is easier to organize than 1. I’m not really finding official guidelines on this though 🤔 I just saw a project that’s using a mix or 2 and 1 and I’d suggest we not do that though, as the conditions are enough without also having the `?` optionals for each :)

**Comment by luuu-xu** [comment]
> I’m not really finding official guidelines on this though 🤔 

I actually saw Vue documentations talking about binding HTML classes like [this](https://vuejs.org/guide/essentials/class-and-style.html#binding-html-classes). It is suggesting 2 in the article.

**Comment by andrewtavis** [comment]
Thanks for the research, @luuu-xu! Glad that we can go with 2 😊

**Comment by andrewtavis** [comment]
Closed by b5c4a13 😊 @luuu-xu, this opens up work on #339! Code quality 🙌
