### ISSUE TITLE
Right sidebar transition

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#321]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently we have the [right sidebar](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/right/SidebarRight.vue) for mobile that houses the theme and language selectors. Something that needs to be added is a transition that occurs when someone opens the sidebar. Whether or not there should be a transition for it being closed or it should be closed instantaneously is still up for discussion. For the transition we could use a similar transition as the [left sidebar component](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeft.vue) and its underlying components.

### Contribution

This is a great `good first issue` for someone who's new to the community. Happy to support someone who has interest in working on this!

**Comment by oneminch** [comment]
I can work on this. What kind of transition are looking to add? The website doesn't have a left sidebar for unregistered users.

**Comment by andrewtavis** [comment]
Hey @oneminch 👋 Thanks for offering to help and your interest in activist. We’re super early stage and don’t have registration yet anyway. You can see the left sidebar if you were to go to [activist.org/home](https://activist.org/home/) on a desktop browser :) We’re testing on this page and a few others.

As far as the transition, you can check [SidebarLeftHeader](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftHeader.vue) for the way we define the transition there :)

Assigning you now! Please let me know if you have further questions 😊

**Comment by andrewtavis** [comment]
Closed via #335 and b656ffe :) @oneminch, the big thing that went through in my changes is we needed to re-hide the menu options if the menu's not open as if they're not hidden then the tab controls reach them 😊 Thanks so much for the work here!
