### ISSUE TITLE
Refactoring Initial Django Project into Multiple Apps

### ISSUE THREAD

**Issue by momanyisamuel** [activist-org/activist#322]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The current structure of the Django project is monolithic, as the project grows and to enhance maintainability, readability, and modularity, as discussed in #174 activist-org proposes refactoring the project into multiple apps. This will involve splitting the existing backend codebase into several apps, each with its own dedicated responsibilities. The proposed structure is as follows:

1. Authentication App (Support, User):
Responsible for managing user authentication and support functionalities.

2. Contents App (Resource, Task, Topic):
Handles resources, tasks, and topics within the project.

3. Groups & Orgs App (Organization, Group, Movement):
Deals with organizational and group-related functionalities.

4. Events App (Format, Role):
Manages event formats and roles within the application.

Each app will follow a similar structure:

`
app_name/
│
├── migrations/
│
├── templates/
│ └── app_name/
│
├── admin.py
│
├── forms.py
│
├── apps.py
│
├── models.py
│
├── tests.py
│
├── views.py
│
├── urls.py
│
├── signals.py
│
└── serializers.py

`

### Contribution

Happy to support someone on this issue or work on it myself

**Comment by kurtisolo** [comment]
If you'd like, I can take care of it! Just one thing: should the 4 apps be placed in the project's main folder or contained within the "apps" subfolder? Typically, having them in the main folder is fine, but just these days, I had to modify the folder structure in another Django project, and it was a nightmare.

So, if we want the apps grouped in a folder, it's now or never!

**Comment by andrewtavis** [comment]
Thanks @kurtisolo! Assigning you now :)

To me putting them in the apps folder makes more sense to really mark that we’re using this structure 😊 If you’d suggest main, then we can go that route as well, but I have no particular preference for it.

**Comment by kurtisolo** [comment]
I'm almost done with this. I decided to keep the apps in the main directory, as this is thestandard practice so it's more suitable for an open source project.

I called the apps: 
- authentication
- contents
- entities (I was undecided on what to name this app, so I went for an inclusive term. If you have any other ideas or preferences, please let me know)
- events

If there are no objections, I can make the PR soon!

**Comment by andrewtavis** [comment]
Sounds good on main, @kurtisolo!

I was thinking on this and also thought that entities was a suitable name for it 😊 Can we do “content” instead of “contents” though? The latter sounds more like stuff in a box 📦😅

**Comment by kurtisolo** [comment]
I just noticed I missed a line in `settings.py`.

`"rest_framework",` should be added in the `INSTALLED_APPS` section.

Apart from this, let me know if there are any other fixes to be made!

**Comment by andrewtavis** [comment]
df2a2b0 sent through some changes like formatting and making sure that the models are generally alphabetized so it's a bit easier to find things. I didn't rename `OrganizationMember` as I feel like it resembles the other model names more than `Membership` :) It seems like a bit more needs to be done for the admin classes, but I think we're good with this issue for now! Thanks @kurtisolo for the work here and @momanyisamuel for creating the issue! 🚀

**Comment by andrewtavis** [comment]
Reopening until this is done :)

**Comment by andrewtavis** [comment]
06ed3d7 should close this :) Just wanted all the comments to be at the top of the files :) Thanks for the persistence on this, @kurtisolo!
