### ISSUE TITLE
Standardize frontend component prop declarations

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#328]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

As of now there are still some cases where frontend Vue component props are assigned with `kebab-case`. As we're using Tailwind that also extensively uses `kebab-case`, it would be best if we do a distinction in the component prop assignments such that they're all `camelCase`. This is in line with newly added guidelines in the [style guide](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md).

Personally speaking, I just find it easier to read when the props that need to be declared in `camelCase` based on the Vue styleguide are also assigned in the same case :)

Happy to support someone in this! I'm not sure how many instances there are, but it'd be good to check and then fix those that remain 😊

**Comment by yehoki** [comment]
Hey Andrew, I've had a look through and I couldn't find any that were non camelCase, would you be able to show me an example in case I completely missed the point?

I went through all frontend components which included 'props' in it:
![image](https://github.com/activist-org/activist/assets/77894099/8b295406-ef30-4c3c-8ea8-b19d7a4d16b3)

**Comment by andrewtavis** [comment]
Hey @yehoki, thanks for reaching out and your interest in activist! 😊

I also checked on this as well and couldn’t find barely anything :) I’d seen a few in the most recent commits and fixed them, but we seem to be mostly all good. The only two I could find were in the [MediaImageCarousel](https://github.com/activist-org/activist/blob/main/frontend/components/media/MediaImageCarousel.vue) component. Want to fix the two props there?

**Comment by andrewtavis** [comment]
Assigning you to hold it for you, @yehoki :)

**Comment by yehoki** [comment]
Thank you @andrewtavis, I will happily work on it but I'm not completely sure, but do you mean these two props on `swiper-container`:
```
    :slides-per-view="1"
    :space-between="30"
```

Apologies for the hassle, so in this case would it be moving the `swiper-container` out and adding in props to the MediaImageCarousel component with camelCase?

Let me know your thoughts on it, still relatively new with mostly React background.

**Comment by andrewtavis** [comment]
No stress whatsoever, @yehoki! I actually jumped back in to GitHub as I felt like my explanation wasn’t good enough. I think that just changing those two props to `camelCase` would be fine :) So `slidesPerView` and ‘spaceBetween`. Any other changes would likely get messy as we just switched over to that `swiper-container` component. A commit for updating those two lines would be welcome though!

**Comment by yehoki** [comment]
Ahh I see, for whatever reason I had the impression that it wasn't allowed in camelCase looking at Swiper docs, but it's all fine - ran it locally and was working fine from the container.

Submitted a pull request, happy to refactor anything else should you find it, thank you again for the guidance @andrewtavis  :)

**Comment by andrewtavis** [comment]
Will check out the PR and review soon, @yehoki!

**Comment by andrewtavis** [comment]
Closed via #336 😊 Thank you, @yehoki! Great first contribution to be checking all this for us :)
