### ISSUE TITLE
adding ruff, isort and black to backend

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#337]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Adding `ruff` and `isort` could help with readability and maintainability. `Ruff`, `isort` and `black` need to be configured to work well together since these tools do have overlapping feature with different default settings. 

Packages:
- [ruff](https://github.com/astral-sh/ruff)
- [isort](https://github.com/PyCQA/isort)
- [black](https://github.com/psf/black)

This topic was also mentioned in Issue #329

### Contribution

I can work on this and create an initial configuration in form of a `pyproject.toml` file. Might also make sense to include `mypy` instead of the seperated `mypy.ini` file. In the end i can add these tools to the GitHub backend workflow.

**Comment by andrewtavis** [comment]
Assuming that #371 closes this, @to-sta, but let me know if we need to reopen :) :)

**Comment by to-sta** [comment]
Add workflow

**Comment by andrewtavis** [comment]
Closed via #402 🌙🚀
