### ISSUE TITLE
Allow collapsed sidebar to tab to search bar and open when focussed

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#338]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now in the left sidebar that's present on [activist.org/home](https://activist.org/home) and other test pages it's not possible to tab to the search bar when the sidebar is collapsed. The ideal behavior would be that when tabbing the sidebar would open when the search bar is focussed and then would collapse again if the user tabs past it.

### Contribution

Happy to work on this myself or support someone who has interest!

**Comment by andrewtavis** [comment]
@luuu-xu, tagging you here for your opinion on this as I noticed this when I was reviewing #333 :)

**Comment by yetea** [comment]
I'd like to work on this issue

**Comment by andrewtavis** [comment]
Thanks for the interest in helping here, @yetea! Please let me know if there's anything I can do to assist 😊

**Comment by andrewtavis** [comment]
Hey @yetea 😊 Checking in to see if you need any assistance with this issue :) Please let me know if there's anything I can do to help out! 

Hope you're well :)

**Comment by andrewtavis** [comment]
Unassigning for now @yetea, but please let me know if you still have interest in working on this :)

**Comment by uyk23** [comment]
Hi! I'd like to take a try at this issue if possible :)

**Comment by andrewtavis** [comment]
Thanks for offering to help, @uyk23! Please let me know if there's something I can do to support :) :)

**Comment by uyk23** [comment]
Thank you!

**Comment by andrewtavis** [comment]
Hey @uyk23 👋 Checking in to see if you need some assistance here :) Please let me know if there's anything I can do to help!

**Comment by andrewtavis** [comment]
Ping @ahmedy00: this issue seems to be a bit tougher than I expected. Bringing you in for some support for @uyk23, and we can problem solve on it as well in case it's needed 😊

**Comment by ahmedy00** [comment]
Hey @uyk23, I would be happy to pair with you on this

**Comment by uyk23** [comment]
Hey @andrewtavis @ahmedy00! I think I would benefit from the help, thanks! :)
So far, I was able to figure out how to tab over to the search symbol and highlight it orange.

![minimized](https://github.com/activist-org/activist/assets/143029148/c1d850a6-6e89-4b49-a93e-d96a0a9fec3f) 

![expanded](https://github.com/activist-org/activist/assets/143029148/17c57fb2-0ade-4243-8ecb-db9b65e1e052)

However, I'm still working on trying to figure out how to expand it.

**Comment by andrewtavis** [comment]
Good progress so far, @uyk23 :) Likely we need to trigger something on focus 😊 What are your thoughts, @ahmedy00?

**Comment by ahmedy00** [comment]
@andrewtavis @uyk23, It is possible to create [custom directives](https://vuejs.org/guide/reusability/custom-directives.html) in Vue.js. I need some time to check code and give a clear opinion, but this might be inspiring

**Comment by uyk23** [comment]
@ahmedy00 @andrewtavis, I think the trigger on focus would be a good approach. Currently, I think the problem might be that the focus is on the parent div and not the transition element?

**Comment by andrewtavis** [comment]
Hey there, @uyk23 👋 Checking in to see how you're doing with this issue. We'll have a developer sync on Saturday if you'd like to join and discuss this. Details will be in the [Development channel on Matrix](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org?via=matrix.org&via=acter.global&via=chat.0x7cd.xyz).

**Comment by vipinnation** [comment]
This issue is completed or not. I want to work on this

**Comment by andrewtavis** [comment]
Still not done, @vipinnation! You'd be welcome to work on it :) Assigning you now, and let me know if you need any help with it!

**Comment by andrewtavis** [comment]
Hey @vipinnation 👋 Checking in on this issue. Is there anything we can do to support?

**Comment by vipinnation** [comment]
@andrewtavis I am sorry for this, I have not checked for a long time. I am requesting you to assign it to another user because I don't have any idea about vue js

**Comment by andrewtavis** [comment]
All good, @vipinnation 👍 Thanks for letting us know :)

**Comment by andrewtavis** [comment]
@lucianmurmurache, as discussed in #755, it'd be great if we also assure that the tabbing from the left sidebar to the activist logo would shift the focus to the activist icon as the latter disappears on sidebar collapse and we lose the focus. We can also make a new issue for this if need be :)

**Comment by lucianmurmurache** [comment]
@andrewtavis unfortunately I did not get a chance to make those changes to the left sidebar navigation but I will hopefully get it sorted in the next few days. We are making some great progress in terms of accessibility, thanks for the support and the reviews!
