### ISSUE TITLE
Refactor to make class the first attribute applied throughout codebase

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#339]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

As of right now the codebase is using different orders attributes for components and elements. We're generally doing a good job of applying the props in the order that they're defined within the component, but specifically `class="STYLE"` for Tailwind is applied almost at random throughout the code. I'd suggest that we make it so that `class="STYLE"` is the first attribute such that any discrepancies from how the element is normally styled will be directly apparent. This would then match a similar standard that will be coming with an upcoming commit where the `aria-label` is always the last attribute.

I'd say that even having it before `v-for`, `v-if`, etc makes sense :) With that being said, I'm very open for discussion on this!

**Comment by andrewtavis** [comment]
CC @anthonyshibitov and @luuu-xu as team members who are interested in code structure :)

**Comment by andrewtavis** [comment]
In working with it a bit more, I think that maybe having conditionals and other similar attributes come before the class makes sense. The order would thus be:

```html
<element
  conditionals=""
  class=""
  :class="{}"
  props=""
  aria-label=""
></element>
```

How does this look?

**Comment by luuu-xu** [comment]
@andrewtavis I like your snippet! It makes sense because conditional should be considered first, and then having classes right after it will look clean and organized. Aria-label at the end is great too.

I would love to work on this chore.

**Comment by andrewtavis** [comment]
Sounds great, @luuu-xu! I’ll take care of #319 :)

**Comment by luuu-xu** [comment]
@andrewtavis Great! I will go ahead and start woking this through our project. Should I also refactor CSS as well since I am going over everything anyways?

**Comment by andrewtavis** [comment]
Yes, that sounds good, @luuu-xu! Let me do a commit for the `:class` attributes though first so we avoid commits :) Will do that now.

**Comment by andrewtavis** [comment]
83e55bc puts the `@-attributes` as the second possible attribute and does a bunch of formatting of the frontend, @luuu-xu :) Thanks for all the efforts here! I'll jump over to #151 now :)
