### ISSUE TITLE
Search result actions meatball menu

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#340]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We're making great progress on the [search result components](https://github.com/activist-org/activist/tree/main/frontend/components/card/search-result). One thing that's missing is that we need to make a dropdown that's activated by the meatball menu to the right of the name. This would have functionality like supporting an organization or attending an event. This component would replace the current meatball menu icon and could use a good amount of the code for [selector components](https://github.com/activist-org/activist/tree/main/frontend/components/selector). This component could be named `SelectorActions`.

### Contribution

Happy to work on this or support someone who has interest in taking it on! 😊

**Comment by Tarctic** [comment]
Hey! I'd love to work on this issue. I looked through the code of the search result components and I checked the website, but I couldn't find the meatball menu you mentioned. 
But I did find a design on figma that might be what you're talking about:
<img width="184" alt="image" src="https://github.com/activist-org/activist/assets/85291498/8aac8539-4f57-4075-a92a-d6e12fd7b042">

Do I need access to the actual website to be able to see it? I just need to understand what it looks like so I can work on it.
Thanks!

**Comment by andrewtavis** [comment]
Hey @Tarctic 👋 Thanks for your interest in activist and being willing to help :) The component we're talking about is actually in that screenshot you have, but not the one you have circled. In the actual search result card you see an orange meatball menu surrounded by a circle. That's the component that should be remade. As of now that does nothing on the search results, and ideally on pressing it we'd see options like `Support`, `Join`, etc based on what the search result is (organization, event, etc). 

If this sounds interesting I'd be happy to define what the options should be, and then we look into some existing code that could be used as a basis 😊

Let me know, and thanks again for reaching out!

**Comment by Tarctic** [comment]
Yes, I'd love to be assigned this issue! Let me know about the options

**Comment by andrewtavis** [comment]
Thanks for your willingness to help, @Tarctic! As far as the options, for right now we can do:

- Organizations: Support, Join, Share
- Events: Support, Attend, Share
- Resources: Star, Share
- Users: Support, Share

**Comment by Tarctic** [comment]
Something came up, but I can do this after a few days. If someone else wants to do it, you may assign it to them, otherwise I shall complete it. Hope you understand!

**Comment by andrewtavis** [comment]
No stress, @Tarctic! I've been very busy myself :) :) Feel free to work on this and get to it when you can 😊

**Comment by andrewtavis** [comment]
Hey @Tarctic 👋 In working a bit on things I'm realizing that this component needed an update based on the color style changes that went through for #215. The new versions have been updated in the designs and can be found [here](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=6783%3A4547&mode=design&t=ic5rpiek7rGfDUKh-1). Also putting them below:

 
![Actions Icon](https://github.com/activist-org/activist/assets/24387426/07f60098-41de-4b1f-96d4-66c37c827385)

Would be happy to get your feedback on them! I figure that the orange on white background that was in the original was gonna be hard to see :)

**Comment by andrewtavis** [comment]
Hi there @Tarctic 👋 Checking in with you to see if you still plan to work on this issue :) Please let me know if there's anything I can do to support?

**Comment by Tarctic** [comment]
I apologize, I really would love to work on this project. Unfortunately, my workload has only increased in the past week :(
I'm not sure if I will be able to complete this, so I will be unassigning myself. If no one else is working on it, I'll try to take on it after things have gotten better on my end. Thank you for your patience.

**Comment by andrewtavis** [comment]
Not a problem at all, @Tarctic! Hope that things get a bit less hectic as soon as possible! Would be great to have you pick up another issue when you have a bit more time! All the best till then 😊

**Comment by andrewtavis** [comment]
Note that the designs on Figma have been updated with some components for this, which can be found [here](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=7259%3A26860&mode=design&t=kg4sKKtoxRKcHsH8-1) :)

**Comment by andrewtavis** [comment]
The basics of the button for this were just added and can be found at [SearchResultMeatball.vue](https://github.com/activist-org/activist/blob/main/frontend/components/SearchResultMeatball.vue) :)

**Comment by PabloSSena** [comment]
hey @andrewtavis, could u please assign me this one?

**Comment by andrewtavis** [comment]
Assigned! Thanks @PabloSSena! I'm heading to bed, but again I'm 100% able to review and close this by Wednesday :)

**Comment by andrewtavis** [comment]
Closed via #606 🥳 Thank you, @PabloSSena! Glad to have this finalized 😊
