### ISSUE TITLE
Update sidebar menu selection on page reload

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#346]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In #343 changes were made to [SidebarLeftIndex](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftIndex.vue) that updates the `selected` attribute on a menu option based on the URL: i.e. on [activist.org/events/123/about](https://activist.org/events/123/about) `About` is highlighted. A final step is to change this so that it updates when a person switches to a different page. As of now if a person selects another sub page within the sidebar then the old highlight is maintained.

### Contribution

This is a `good first issue` for someone relatively new to the platform or a regular contributor who wants to pick up a task. Would be happy to work on this myself or support someone!

**Comment by thiagogquinto** [comment]
Hey @andrewtavis, could I work on this issue?

**Comment by contiyo** [comment]
Hi @andrewtavis 

I am mainly a guy who writes Python scripts for the last couple of years, but I would like to start contributing to open source projects and this issue seems to fit what I had in mind for my 1st issue. 

Can I start working on that please ? 

Thanks,
Kostas

**Comment by andrewtavis** [comment]
Hey @contiyo 👋 Thanks for your interest in activist! Would be great to get some help with this issue 😊 I’ll assign you now, and please let us know if you need some assistance!

**Comment by andrewtavis** [comment]
Hey @contiyo 😊 Checking in with you to see if there's anything I can do to assist with this issue :) Let me know!

**Comment by Robert-Kovalcuk** [comment]
Hello, I'm looking for a an good-first-issue for my university class, is this still available?:)

**Comment by contiyo** [comment]
Hi @andrewtavis, 

Apologies, but I coulnd't fix that myself. Feel free to pass that to @Robert-Kovalcuk.

**Comment by andrewtavis** [comment]
No stress, @contiyo! Feel free to request another issue another time 😊 Sure @Robert-Kovalcuk, you'd be welcome to work on this! I'll assign you now, and please let me know if you have any questions!

**Comment by andrewtavis** [comment]
In looking at this again, I think that the best thing to do for this world potentially be working on #356 with this, @Robert-Kovalcuk. We could work on combining the state into a common component that's reflected, and while we're at it we can make sure that the state is updated in the menu? We can also just focus on this though if you'd prefer, or I could get the other issue done and ping you for this one :) 

Just for my info as well: what's the deadline for your assignment? I like to know this so I have a good understanding of when I might receive the PR, and also when to expect that you might need help/check in with you.

**Comment by Robert-Kovalcuk** [comment]
I sent you an email, and I'm down to work on anything you would suggest and if we manage to solve the 354 with this issue, better for us :P

**Comment by andrewtavis** [comment]
Will check that later and get back to you, @Robert-Kovalcuk! Looking forward to working with you :)

**Comment by Robert-Kovalcuk** [comment]
Thank you, I'm excited to work with you too!

**Comment by andrewtavis** [comment]
Hey there @Robert-Kovalcuk 👋 I'll assign this one to you as well as ideally the issue of things not reloading properly will be fixed by the common component functioning correctly. Let's be in touch on all this though!
