### ISSUE TITLE
Create `ModalQRCode` component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#353]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would be to create a modal similar to [ModalImage.vue](https://github.com/activist-org/activist/blob/main/frontend/components/modal/ModalImage.vue) that would serve to generate and display a QR code for the page. The `ModalImage` component is currently applied on pages like [activist.org/docs/get-active](https://activist.org/en/docs/get-active/) where the image can be expanded. We'd want a similar functionality that functions in a similar way to clicking the QR code icon in the [prototypes on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2673%3A21106&mode=design&t=dGTkLvORByiiQQWZ-1). How this component could look is further pictured below:

![QR Code Overlay](https://github.com/activist-org/activist/assets/24387426/eb2a429f-d94f-4f48-baf7-65bc6c354c13)

I think it would be best if the QR code is automatically generated though and the CTA is to download it :)

### Contribution

Happy to work on this myself or support someone with it! I think for this issue the basis of the modal can be created, and we can add further functionality to it later 😊

**Comment by VinnyHS2** [comment]
Hey, I would like to work on this feature

**Comment by andrewtavis** [comment]
Hey @VinnyHS2! Thanks for the offer to help with this 😊 Assigning you now, and let me know if you need any help!

**Comment by andrewtavis** [comment]
Hey @VinnyHS2 👋  Quick note that f7fb36a added a placeholder component for this at [frontend/components/modal/ModalQRCode.vue](https://github.com/activist-org/activist/blob/main/frontend/components/modal/ModalQRCode.vue) :) All the functionality is still needed, but I was going through and changes the colors/shadows for accessibility and figured I'd update this part of `CardAbout` as well 😊

**Comment by VinnyHS2** [comment]
Hey, I got this problem after sync my fork. Could you help me @andrewtavis? So I could work on this issue.

![image](https://github.com/activist-org/activist/assets/43623784/2dc3bb7d-3a08-4778-ac15-da98b2cecb60)

**Comment by andrewtavis** [comment]
Hey @VinnyHS2 👋 Talking with @to-sta in the Code Night 🌙 call and he's saying that it should be fixed based on #348. Have you tried to rebuild the docker container with `docker-compose up --build`?

**Comment by VinnyHS2** [comment]
It solved. After rebuild, I was getting connection problem with db, but was just cache problems. Thank you :D

**Comment by andrewtavis** [comment]
Great to hear 🥳🙌 Looking forward to seeing this component in action!

**Comment by targatonica** [comment]
Hi, is this issue still available? I would like to work on it.

**Comment by andrewtavis** [comment]
Hey @targatonica! Thanks for your interest in activist and helping out 😊 Let's give @VinnyHS2 a few days to confirm the progress on this and if you can work on it :) We'll be making more issues in the coming days, so please keep a look out for some new ones!

**Comment by VinnyHS2** [comment]
Hey sorry for taking so long, I am struggling with Vue (I got some time to learn it's my firts time working with it and tailwind), I was all this time trying to install a lib, but as you can see, with no success. Would you mind to help me with this @andrewtavis

**Comment by andrewtavis** [comment]
Sure thing, @VinnyHS2! Do you want to do a call in the coming days? You could reach out on Matrix or via the email in my profile. Also happy to help async if you want to send along more info on the problem :)

**Comment by VinnyHS2** [comment]
I sent you an email @andrewtavis, so we can talk more about it

**Comment by andrewtavis** [comment]
Heyo @VinnyHS2 👋 Thanks again for the call :) I updated the designs for the component, which can be found [here](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2673%3A21106&mode=design&t=mFFy34S97r9zK5jN-1). Here it is as well:

![Overlay Information](https://github.com/activist-org/activist/assets/24387426/c4332eb8-0e51-4b73-8760-50c763d8a70e)

For right now let's just focus on getting the QR code in there and assigned to the correct URL. We can work on the other parts of styling the code with colors, etc and allowing people to download it later 😊 For the button we can also just do a regular one without the extra options right now. Let's start with a PNG download and we can add in JPEG and others later :) Lastly we don't need the paragraph before the button that starts with `Be sure...`. Obviously there's no app right now, so we can add that in later when there is 😇

Stoked to see how this turns out!

**Comment by andrewtavis** [comment]
Ah btw, for the i18n codes it'd be good to have a version of the first sentence for events and for organizations and have a prop that lets us define which it's for (or we can have this be derived by the URL as well!). The sentence for organizations would be the same except for "... this organization in real..." :)

**Comment by VinnyHS2** [comment]
Got it, my next opponent will be the tailwind, but it's not that hard, so I guess there won't be problems here.
Thanks again for your help :D

**Comment by VinnyHS2** [comment]
@andrewtavis the browser component is done, but I need some help adapting it to mobile

**Comment by andrewtavis** [comment]
Nice @VinnyHS2! Great to hear it 😊 Sounds like maybe some Tailwind support so it reacts properly given breakpoints? Do you want to do another call?

**Comment by VinnyHS2** [comment]
If it's okay for you, would be great, I will send you an email to talk about it

**Comment by andrewtavis** [comment]
Hey @VinnyHS2! 401edcf closes this out except for some minor changes that I'll make for coloration :) :) I even added the icon into the center, although we'll need to figure out how to add that in to the download 🤔 Lemme know what you think! I'll wait for feedback from you and do the minor fix for the colors in dark mode that I'm realizing right now before closing.

**Comment by VinnyHS2** [comment]
Looking into the link you sent before, maybe could be possible depending of what we try to export, like the full div or something like that. I Will make some tests later.

**Comment by andrewtavis** [comment]
Sounds great, @VinnyHS2! We're all really happy to be checking this out in the call atm :)
