### ISSUE TITLE
Sidebar blur doesn't cover over footer at md and lg breakpoints

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#355]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

We have a bug right now that the blur for the `md` and `lg` breakpoints for when the left sidebar is covered doesn't also cover the footer. This can be seen by going to [activist.org/home](https://activist.org/home), going to one of the lower breakpoints where hovering over the sidebar causes the page elements to be blurred, and then from there we see that the footer is not blurred.

Would be great to get some support on this! This would also be a `good first issue` for someone new to the community 😊

**Comment by CdreKaputt** [comment]
I think I could help with this unless someone else is taking a look. From what I can see, hovering over the sidebar applies the "blur-sm" and "xl:blur-none" classes to the main page but not to the footer itself. 

I'm pretty new to this though, and it would be the first issue I've worked on.

**Comment by andrewtavis** [comment]
Feel free to give it a shot, @CdreKaputt! Happy to help out if you run into some issues :) Thanks for your interest in activist!

**Comment by andrewtavis** [comment]
Thanks for the quick work on this issue, @CdreKaputt! It's yet to deploy, but the code's what we need and the behavior was what it was supposed to be in the Netlify deploy preview 😊 Will be updated with the next deploy.
