### ISSUE TITLE
Implement DRF ViewSets for CRUD Operations on Activist Resources

### ISSUE THREAD

**Issue by momanyisamuel** [activist-org/activist#360]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This is an issue to optimize activist-org API structure by utilizing Django Rest Framework's (DRF) ViewSets for CRUD (Create, Read, Update, Delete) operations on activist resources. This will help streamline activist-org's codebase and enhance the maintainability of the API endpoints.

### Contribution

Happy to support someone on this issue or work on it myself

**Comment by kurtisolo** [comment]
I can work on this if no one steps up :)

**Comment by andrewtavis** [comment]
Happy to assign, @kurtisolo! :)

**Comment by kurtisolo** [comment]
In `entities/views.py`, there are some Django class-based views. For consistency, I would modify them to use DRF views. Is that okay?

**Comment by momanyisamuel** [comment]
@kurtisolo yes you can modify them, I created those before we added DRF to the project 👍

**Comment by andrewtavis** [comment]
Closed via #378 and a bit of formatting in 145d08a 😊 Thanks for the commit @kurtisolo and for the issue @momanyisamuel! 🙌 Would be great if the both of you could think of a few more issues for the backend for code night. I should be able to switch over and help out more soon, but this will likely be next week at the earliest :)
