### ISSUE TITLE
Expand workflows to run on all PR commits

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#364]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now we have the following setting for our workflows:

```
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
```

This means that specifically our workflows are only running when the PR is opened and then don't run on future commits. How we'd need to change this to account for further commits should be investigated and implemented :)

### Contribution

Happy to discuss this with folks! This would also be a simple change that could be made by a new contributor 😊

**Comment by andrewtavis** [comment]
Ping @to-sta for a workflow related topic :)

**Comment by andrewtavis** [comment]
This makes sense to me, @llambrecht 😊 Thanks for doing the research! Will assign you, and feel free to send along a PR for all the workflows :)

**Comment by andrewtavis** [comment]
I think having reopened at the very least would also make sense, @to-sta :) Synchronize was also suggested, so whether or not we include edited is the last question 😊

**Comment by andrewtavis** [comment]
Let’s define this and then we’re good for a PR :)

**Comment by llambrecht** [comment]
Thanks @to-sta for the table !
I think "edited" would have no use in that context because change in title, description or base branch would never change the outcomes.
Then the list would be :
`[opened, reopened, synchronize, edited]`

I'll make the PR if you agree with that !

**Comment by andrewtavis** [comment]
PR away, @llambrecht! 🚀

**Comment by andrewtavis** [comment]
#370 and a6196da close this :) :) a6196da was just minor formatting changes, @llambrecht 🙃 Thanks so much for the contribution here!
