### ISSUE TITLE
Shift to [id]/about on [id] when screen expands

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#365]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We currently have direct redirects to the `[id]/about` page for both events and organizations that is triggered above the medium breakpoint. Below this breakpoint we are directed to a page that has options for navigation. An issue is that if the screen is resized we get a stretched version of this page and are not directed to the `[id]/about` page. Would be great to get this redirect implemented!

### Contribution

Happy to support someone on this. This issue is for now reserved for @felipolis who expressed interest in dev sync 😊

**Comment by felipolis** [comment]
I would love to work on this, @andrewtavis . Could you assign me?

**Comment by andrewtavis** [comment]
Can do, @felipolis! Let me know if you need some support :)

**Comment by andrewtavis** [comment]
Closed by #381 and minor changes in 4df81a4 to fix comment nits 😇 Thanks for the work here, @felipolis! Looking forward to the next issue! 🚀😊
