### ISSUE TITLE
Proposal: enhance development efficiency through customized ChatGPT instructions

### ISSUE THREAD

**Issue by kurtisolo** [activist-org/activist#373]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

ChatGPT is a powerful tool that, when used correctly, can greatly accelerate the development of a project. It's excellent for quickly identifying typos, bugs, structural issues, scalability flaws, and so on.

Recently, the 'custom instructions' feature was introduced, allowing users to provide the tool with a text that serves as background/context, making its responses more accurate and relevant.

It would be interesting to provide the project with a document containing predefined custom instructions. This document would include as much information as possible about the current state of development, along with guidelines and tips for using the tool efficiently. This would be useful for speeding up and simplifying the setup of ChatGPT.

If this idea is positively received, we could further improve this by inserting a comment at the beginning of each file, indicating its exact path, to make ChatGPT even more efficient.

I know many might be skeptical about using AI. However, in my opinion, it is a very useful tool and will inevitably become increasingly essential for developers.

I am also aware that the use of AI could raise ethical concerns, especially in a project like Activist. If this has already been discussed, or is in some way in conflict with Activist's philosophy, I will absolutely not be offended if this issue is deleted.

### Contribution

Happy to support someone on this issue or work on it myself

**Comment by andrewtavis** [comment]
Hey @kurtisolo! Thanks for the suggestion here :) Speaking for myself I'd have no issue with implementing AI for development of activist. Integrating AI into the platform itself is very much a different situation where the feedback has generally been negative, but for these purposes it's definitely worth exploring. Maybe you could bring this up at the dev sync?

**Comment by andrewtavis** [comment]
Hey @kurtisolo 👋 Thinking about this a bit more, maybe the way to go with this is to provide setups for coding assistants like the following:

- [Mentat](https://github.com/AbanteAI/mentat)
- [Cody](https://about.sourcegraph.com/demo/cody?utm_source=google&utm_medium=cpc&utm_campaign=20359643422&utm_term=cody&gad_source=1&gclid=CjwKCAiAu9yqBhBmEiwAHTx5pxVM2TjqoI8C_fd3aJKwTnbKvJa3fU4D-ejwJWk09-xJpeYoKzHGTBoCdsgQAvD_BwE)
- Maybe some others 🤔 

In this way we wouldn't need to edit the code at all for these purposes and we also wouldn't need to maintain a document of the current state of things. Just provide plug and code instructions so people can use whatever coding assistants they want :)

Let me know what your thoughts on this are!

**Comment by andrewtavis** [comment]
Just added in [LLMPROMPT.txt](https://github.com/activist-org/activist/blob/main/LLMPROMPT.txt) that has a basic prompt to format the code correctly. @bharath637462, can you think of other things that could be added to this file?

**Comment by andrewtavis** [comment]
Closing this as I think that we can iterate on [LLMPROMPT.txt](https://github.com/activist-org/activist/blob/main/LLMPROMPT.txt) as we need to :)
