### ISSUE TITLE
Standardize backend validation messages

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#376]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In #295 we added serializers for field validation. The messages that are generated haven't been standardized though based on [Django validation error guidelines](https://docs.djangoproject.com/en/4.2/ref/forms/validation/#raising-validationerror). This issue would standardize the validation messages :)

### Contribution

Reserved for @thiagogquinto who has expressed interest 😊

**Comment by thiagogquinto** [comment]
Hi @andrewtavis, I would like to work on it.

**Comment by andrewtavis** [comment]
Assigned, @thiagogquinto! Thanks for the help here :)

**Comment by thiagogquinto** [comment]
Hi @andrewtavis, if I have an idea for the validators, should I add it to the code, or should I contribute it in future contributions? I am asking because this is not the focus of the current issue. If adding it to the code is appropriate, I'd like to discuss that possibility.

**Comment by andrewtavis** [comment]
Hey @thiagogquinto 👋 We can definitely just work on changing the validators for this issue. You'd be welcome to make the changes for them and open a PR whenever you're ready 😊

**Comment by andrewtavis** [comment]
#385 and e2a6145 close this :) Thanks for the work here, @thiagogquinto! The changes in the commit were just some formatting for the changed files and I also did a swap of some checks like making sure that we use `is None` and `is not None` rather than their `==` and `!=` equivalents as is Python standards :) See this [SO question](https://stackoverflow.com/questions/3257919/what-is-the-difference-between-is-none-and-none) for some info on it 😊
