### ISSUE TITLE
Fix backend variable in docker-compose.yml

### ISSUE THREAD

**Issue by IsaacDMz** [activist-org/activist#377]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Add the backend port in the docker-compose, turning dynamic to run backend in other ports according to .env

### Contribution

I would love to do this

**Comment by andrewtavis** [comment]
Hey @IsaacDMz! Thanks for opening the issue 😊 I'll assign you, and you're welcome to open a PR for this :) We can then discuss the change in there.

**Comment by IsaacDMz** [comment]
Hey @andrewtavis i open a PR for this issue. I just change the docker-compose.yml

**Comment by andrewtavis** [comment]
You're all good on your end, @IsaacDMz, but thanks for checking! We need the TS errors in #260 to be fixed for that test to pass. Once that's done we'll have all the baseline TypeScript errors fixed and that test will fail only when new ones are introduced.

**Comment by andrewtavis** [comment]
Closed via #386 :) Thanks for the careful checking of the code, @IsaacDMz!
