### ISSUE TITLE
Fix: LandingContent component passing ariaLabels to BtnLabeled in a wrong way

### ISSUE THREAD

**Issue by luuu-xu** [activist-org/activist#379]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Currently our `BtnLebeled` takes in props of `label` and `ariaLabel` in the format of i18n key like `"pages.index.get-active-btn-alt-text"`, which needs to be added and found in our i18n files.

But now `LandingContent` has a few usages of `BtnLabeled` which passed in `$t('${btnAriaLabel1}')` as `ariaLabel` prop, which results in console error message:

`[intlify] Not found 'Learn more about getting involved in an activist organization' key in 'en' locale messages.`

The correct way should be directly passing in i18n key into `BtnLabeled`'s `ariaLabel` prop.

This is a good first issue and someone who is interested in i18n features and system.

**Comment by andrewtavis** [comment]
Thanks for checking my work on the aria labels, @luuu-xu! Would be great if someone wants to pick this up :)

**Comment by iagocarmona** [comment]
Hello, I would like to work on this.

**Comment by andrewtavis** [comment]
Hey @iagocarmona! 👋 Thanks for your interest in helping with this! Assigning you now, and please let us know if you need any support with it 😊

**Comment by andrewtavis** [comment]
Closed via #418 :) :) Thanks @iagocarmona! 🚀
