### ISSUE TITLE
Update admin.py

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#383]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Recently the `models.py` files have been updated but the `admin.py` files have not reflected the changes yet. The following files could be updated:

- `backend/authentication/`
- `backend/content/`
- `backend/entities/`
- `backend/events/`

I think the UserAdmin class inside `backend/authentication/` can be used as a guide to generate the rest.

### Contribution

I am happy to help or work on it myself 😄

**Comment by andrewtavis** [comment]
Thanks for creating the issue and offering to work on it, @to-sta! I think it makes sense to combine this with #382 as well, so I'll head over and assign that one as well 😊

**Comment by andrewtavis** [comment]
Closed via #384 :) Thanks for creating and working on the issue, @to-sta!
