### ISSUE TITLE
Add expand functionality to view full text in about cards

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#388]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The [CardAbout](https://github.com/activist-org/activist/blob/main/frontend/components/card/CardAbout.vue) component that's found on [event about pages](https://activist.org/events/123/about) and [organization](https://activist.org/organization/123/about) has a `Click for full text` portion that as of now is not functional. This should function to open a modal with the card's full text as shown in the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2571%3A14078&mode=design&t=GW1iw3V9z44v7AEL-1) :) Code for the current [ModalImage](https://github.com/activist-org/activist/blob/main/frontend/components/modal/ModalImage.vue) component could be used to add the functionality 😊

With this we'd also want to check the length of the about card text and remove the `Click for full text` functionality if it's too short. For mobile this would only expand the height of the card as the idea here is we want consistent layouts for desktop and thus don't want to expand the height of the card and then have it not be even with the map or images component to its right.

### Contribution

Would be happy to work on this myself eventually or support someone with an interest in implementing it! :)

**Comment by ishan9678** [comment]
Hi Andrew, i would like to work on this but i didn't quite understand what you meant for the card in the mobile view.

**Comment by andrewtavis** [comment]
Hey @ishan9678! 👋 Great to be chatting about another issue with you :) What I mean by mobile is that we'd just make the card longer: so all cards would be the same height at the start and should the first few sentences on mobile, and then when the user clicks the show more text it will expand to fit the text. From a Tailwind CSS perspective we'd change the height attribute such that when a boolean for the text being expanded is clicked, the height would then shift from it being a fixed value to `h-fit`. We'd do the same for desktop, but then we also explicitly want the modal to pop out so that we have more space for the height and can maintain the layout 😊

Will assign you now, but please let me know if you have further questions! Happy to discuss this further :)

**Comment by ishan9678** [comment]
@andrewtavis  Thanks for the clear explanation. I'm happy to take this on. I'll keep you posted on my progress and let you know if I have any questions.

**Comment by andrewtavis** [comment]
Glad I was able to help, @ishan9678! Please feel free to reach out, and again the current `ModalImage` component should have a lot of the logic for desktop :)

**Comment by andrewtavis** [comment]
Hey @ishan9678 👋 How's everything going here? Please let me know if there's something I can do to support :)

**Comment by ishan9678** [comment]
Hi Andrew, i've been busy lately and my finals are about to start, feel free to reassign it to anyone else. It would take me some time before i can work on it. Sorry for not clarifying earlier.

**Comment by andrewtavis** [comment]
No stress, @ishan9678! Good luck on finals, and please come back afterwards to pick up a new issue! :) :)

**Comment by andrewtavis** [comment]
I'll be making some more good first issues soon 😊

**Comment by andrewtavis** [comment]
Note that this issue is reserved for @bmartins-42. Send along a message here and I'll assign! :) :)

**Comment by bmartins-42** [comment]
> Note that this issue is reserved for @bmartins-42. Send along a message here and I'll assign! :) :)

Let's go !

**Comment by andrewtavis** [comment]
Thanks @bmartins-42! Let me know if you need any support here :)

**Comment by andrewtavis** [comment]
Hey @bmartins-42 👋 Checking in on this issue 😊 Let me know if there's anything I can do to help! Would be happy to jump on a call at some point to discuss as well :) :)

**Comment by bmartins-42** [comment]
Hello @andrewtavis, I apologize for the delay, I was underwater and just screwed to let you know that I wouldn't work on it as soon as I expected at first. Next week, I will manage to work on it if it's still needed.

I wish you and the team a happy end of the year :)

**Comment by andrewtavis** [comment]
Hey @bmartins-42! 👋 No stress whatsoever! Hope that all's ok and that you have a bit more time coming up. Happy to wait for the contribution, and wishing you a wonderful New Year celebration! Talk soon 😊
