### ISSUE TITLE
Backend-Frontend hydration for event and organization about pages

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#389]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This is the main issue for the Saturday, September 23rd Code Night 🌙 We've been making good progress on creating the needed models and other infrastructure for the backend, and now we need to start sending data from these models to frontend pages. The first ones will be the event and organization about pages at the following URLs:

- https://activist.org/events/123/about
- https://activist.org/organizations/123/about

We'll discuss this issue during the 23/9/23 dev sync and then assign it to Code Night 🌙 participants :) :)

### Contribution

Happy to work on this with people or support where needed!

**Comment by momanyisamuel** [comment]
working on the issue to create a form for organization creation #393 so as to help close this issue

**Comment by andrewtavis** [comment]
@momanyisamuel, I'm going to close this and archive it on the board as technically this is "done". All the work that will be done for it will be for the new event creation flow issue I'll make 😊 Thank you, @momanyisamuel!
