### ISSUE TITLE
Create sign in page

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#391]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create the `pages/sign-in` page that would thus translate to `activist.org/sign-in`. Designs for this page can be found in the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=6481%3A8298&mode=design&t=QtIT1amRX0lQy9zG-1) and are also shown below.

![Sign In - Username, Password and Verification](https://github.com/activist-org/activist/assets/24387426/521e2b7b-49f6-40b7-9b7e-babd7ee0f0e4)

![Mobile Sign In - Username, Password and Verification](https://github.com/activist-org/activist/assets/24387426/fa4d2e8e-35f0-48be-a23f-55b59c134c5d)

This issue could be worked on during the 23/9/23 Code Night 🌙 along with the issue for sign up #392 :)

### Contribution

Happy to work on this or support people who have interest in working on it!

**Comment by ahmedy00** [comment]
Hi @andrewtavis 
I would like to develop this feature, as I will be involved in the project for the first time and as I am not a very experienced developer, I presume that this may take some time. If you don't see this as a problem, could you assign this to me? 
Thanks.

**Comment by andrewtavis** [comment]
Hey @ahmedy00 👋😊 Great to have you here :) You're more than welcome to work on this, and no stress on not being the most experienced. Lots of people are learning by working on activist. I'll assign this issue to you, and please let me know if you need any assistance!

**Comment by andrewtavis** [comment]
Hi @ahmedy00 👋 Wanted to say that @thiagogquinto will be working on the other similar issue to this, #392. Maybe you two could collaborate if there’re any issues 😊

**Comment by ahmedy00** [comment]
@andrewtavis Ok it will be great to work together. Also I'm pushing some changes for this issue and I would like to if you tell me what's the mistakes and next steps

**Comment by ahmedy00** [comment]
@andrewtavis Could you authorise me for contribute to the project

**Comment by andrewtavis** [comment]
Hey @ahmedy00 👋 Checking how it looks so far sounds great! You'll need to make a fork and then send along a PR to this repository :) I can then review and merge it in here.

**Comment by ahmedy00** [comment]
@andrewtavis, I fixed couple problems but I need to make clear some design issues, can we set a meeting for tomorrow

**Comment by andrewtavis** [comment]
Yes by all means, @ahmedy00 :) I'm relatively free tomorrow. Feel free to message me on Matrix via the email that's on my GitHub account and we can figure out a time!

**Comment by ahmedy00** [comment]
Hey @andrewtavis, I am asking for learn the procedure, should I let you know when PR is ready for review?

**Comment by andrewtavis** [comment]
Hey @ahmedy00! Sorry for the wait on this. Was still sick for quite some time and had a lot on my plate. If you have multiple commits that you're still planning, then please do let me know in the PR that there's still work to be done :) Then once the commits are done you can confirm that it's ready for review!

**Comment by andrewtavis** [comment]
Will hop on the review now!

**Comment by andrewtavis** [comment]
b9d1401 does some final adjustments for this, @ahmedy00 :) It includes:

- Minor fixes to the texts for things like capitalization as we normally don't capitalize the words except the first on buttons (i.e. `Sign in`)
- Spacing fixes including making the logo a bit larger and the padding between elements
  - This will need a bit more work to make sure that the 👋 doesn't go to the next line
- Making the FriendlyCaptcha element expand to fit the text

More work to finalize all this will obviously be needed, but this is an amazing leap towards getting the sign in interface up and running! Really am so happy you picked this issue up 😊
