### ISSUE TITLE
Create sign up page

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#392]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create the `pages/sign-up` page that would thus translate to `activist.org/sign-up`. Designs for this page can be found in the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=3228%3A22748&mode=design&t=QtIT1amRX0lQy9zG-1) and are also shown below.

![Sign Up 1 - Username, Password and Verification](https://github.com/activist-org/activist/assets/24387426/f271fe89-6bda-40fa-895c-e5bb698497f4)

![Mobile Sign Up 1 - Username, Password and Verification](https://github.com/activist-org/activist/assets/24387426/8ec03e70-cfa9-436f-a5c9-f3657a5209b7)

This issue could be worked on during the 23/9/23 Code Night 🌙 along with the issue for sign in #391 :)

### Contribution

Happy to contribute to this or support someone who wants to work on it!

**Comment by thiagogquinto** [comment]
Hi @andrewtavis , I would like to work on it.

**Comment by andrewtavis** [comment]
Sounds good, @thiagogquinto! Assigning you now :) Feel free to discuss with @ahmedy00 on what the plans for #391 are 😊

**Comment by thiagogquinto** [comment]
Thansks @andrewtavis, just to be clear, I will  learn *Vue* by the issue, so if the task is important, feel free to assign to somebody else that wants to work on the issue,

**Comment by andrewtavis** [comment]
There are enough examples in the code base for how to use Vue and Tailwind in the frontend that I’m confident you’ll be able to figure it out, @thiagogquinto 😊 Thanks for letting me know though, and ping me if you need assistance! You’re also welcome to send along a PR and we can talk about how it’s looking prior to further commits :)

**Comment by ahmedy00** [comment]
@thiagogquinto Hey friend, If you want, we can have a voice meet about this issue and we can share our experiences with each other.

**Comment by thiagogquinto** [comment]
> @thiagogquinto Hey friend, If you want, we can have a voice meet about this issue and we can share our experiences with each other.

Of course, would be really nice to discuss the issue. Please let me know your availability, and we can choose a time that works for both of us.

**Comment by ahmedy00** [comment]
> > @thiagogquinto Hey friend, If you want, we can have a voice meet about this issue and we can share our experiences with each other.
> 
> Of course, would be really nice to discuss the issue. Please let me know your availability, and we can choose a time that works for both of us.

I will be available nearly every day between 19:00-23:00 GMT+3

**Comment by thiagogquinto** [comment]
Hi @ahmedy00, sorry for the late response, I am free now, if you want to discuss the issue  just let me know and then we meet.

**Comment by thiagogquinto** [comment]
Hey @andrewtavis, I have some questions about some features of the fields, could we talk about it when you are available, please?

**Comment by andrewtavis** [comment]
Yes, would be very happy to discuss, @thiagogquinto 😊 I'll reach out to you on Matrix :)

**Comment by andrewtavis** [comment]
Hey @thiagogquinto 👋 I'm finally feeling better and got the review done for #391. [activist.org/auth/sign-in/](https://activist.org/auth/sign-in/) is generally where we'd like it to be. Feel free to send along your changes, and by all means make suggestions based on how you think both pages can improve!

**Comment by thiagogquinto** [comment]
Hi @andrewtavis. glad to know you are better, I have been busy in the past week, but I am bringing my changes to the latest version and hopefully this next week I can make the PR. The fields are done and the page can adapt it's messages according to the page.  After the update with the *main branch* I will be working on making everything be visible without scrolling. If something comes up I reach out to you,  sounds good?

**Comment by andrewtavis** [comment]
Sounds perfect, @thiagogquinto! Looking forward to checking it out in the PR, and please do reach out if you need some assistance :)

**Comment by andrewtavis** [comment]
Hey @thiagogquinto 👋 Something I'm thinking would be good to fix for both pages is that as of now on [activist.org/auth/sign-in](https://activist.org/auth/sign-in/) the whole left side with the logo is clickable to route to `/`. I think it would be good if we could just have the logo be clickable for that, but not the header colored background as well. I can also make an issue for this, but figured you might have already worked on it for your issue 😊

**Comment by thiagogquinto** [comment]
Hey @andrewtavis I am not being able to find myself time to work on the issue, so I would like to know if I could open a PR with my changes for the *sign-up page* or should I let somebody work 100% on the issue? I am really sorry about it!

**Comment by andrewtavis** [comment]
100% ok, @thiagogquinto :) Myself or @ahmedy00 can finish it up 😊

**Comment by thiagogquinto** [comment]
Thanks for the feedback @andrewtavis ! I acessed the web page of the sign-up page noticed that the title of the pages are switched up:


![Captura de tela 2023-10-11 184142](https://github.com/activist-org/activist/assets/95106865/97a137d7-7141-4e30-aba3-cf8fb0fbcdb3)


And also thre is another thing, the link for the sign-in page, on *Already have an account?* points to the following url:
```https://activist.org/en/auth/sign-up/sign-in```. But I started the project on my machine with the latest changes and when I try access the url it works fine and points tho the right link (```en/auth/sign-in```). Just letting you know.

**Comment by andrewtavis** [comment]
Thanks for the heads up, @thiagogquinto! 5761b4d fixes the page titles :) I wasn't able to see `https://activist.org/en/auth/sign-up/sign-in` either, but let's keep an eye out and please send along a PR if something like that comes up!
