### ISSUE TITLE
Create organization/create page

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#393]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would focus on creating the `pages/organizations/create` page that would then be reflected on the platform as `activist.org/organizations/create`. This page can be found in the [Figma designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=3564%3A23552&mode=design&t=QtIT1amRX0lQy9zG-1) and can further be seen below:

![Organization Creation 1 - Information](https://github.com/activist-org/activist/assets/24387426/b770c739-615f-4a13-8ccb-8fed775e38c8)

Not all the components for the page are complete yet, so just making this page and adding a header and the components that are done would be enough for now. Also making it so that what's included is reactive would be great!

### Contribution

Happy to support someone who wants to work on this! This is a `good first issue` for someone who'd like to learn a bit more about our frontend infrastructure, but can also be picked up by other contributors who are looking for something to work on 😊

**Comment by momanyisamuel** [comment]
I would like to work on this in relation to  #389

**Comment by andrewtavis** [comment]
fe2eb23 closes this for now, @momanyisamuel 😊 Thank you! Can you please pull and check that everything's working for the dev sync?
