### ISSUE TITLE
Create progress bar component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#394]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would be to create `frontend/components/ProgressBar.vue` that would house the progress bar for activist. The component can be seen in the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2056%3A3274&mode=design&t=QtIT1amRX0lQy9zG-1) and further can be seen below:

![Progress Bar](https://github.com/activist-org/activist/assets/24387426/dac551a8-b8cc-47e6-8cf3-09d8619ab6c4)

The bar would have several props including what the label should be, whether it's type is default or it's meant for act or learn events, and would be styled such that it's reactive to dark mode and size changes down to mobile :)

### Contribution

This is could be worked on as a part of activist's 23/9/23 Code Night 🌙 This is a bit of a tough issue, but could be worked on as a `good first issue` by someone who has prior frontend experience. Community members are also welcome to pick it up! Happy to support as needed :blus

**Comment by Lakshman76** [comment]
what is the task i'm not able to understand clearly.
plz elaborate once?

**Comment by andrewtavis** [comment]
We generally want to create the component that's described above. It should be as pictured with a property that takes an array of labels, have a prop for where the close button should route to, and then there should be a prop for what the prophetess is so that we can determine how far the progress should be and change colors of the cells accordingly :) Should further have a height that's on the screen width, with below a medium breakpoint being that we'd have a lesser height and no labels. Beyond that we need to have it be reactive to dark mode using Tailwind and our custom colors 😊

Let me know if you'd have interest in working on this and if there are further questions! Happy to assign if you'd want to help with this, and thanks for the question! 🚀

**Comment by Robert-Kovalcuk** [comment]
Hello, I'm looking for a an good-first-issue for my university class, is this still available?:)

**Comment by andrewtavis** [comment]
Hey @Robert-Kovalcuk 👋 Let's give @Lakshman76 a moment to confirm if he'd have interest on this and for the time being we can focus on #346 :) Thanks for the interest in helping out!

**Comment by Lakshman76** [comment]
@andrewtavis give this to @Robert-Kovalcuk he is needed
Currently I'm working on another project.
Sorry for that. Thank you so much for helping 🙂

**Comment by andrewtavis** [comment]
Happy to help, @Lakshman76! Let me know which of the issues you'd like to work on, @Robert-Kovalcuk :)

**Comment by dipushrestha** [comment]
Hi, @andrewtavis 👋 Is this issue taken? If not, I'd love to work on this.

**Comment by andrewtavis** [comment]
I think that @Robert-Kovalcuk will be working on #354, so you'd be welcome to pick this up @dipushrestha :) Let me know if you need any support! The work that's being done in #398/#415 is a solid basis for this, btw 😊

**Comment by andrewtavis** [comment]
cfd4add closes this up, @dipushrestha 😊 What I did was:

- Added a lower border so it's distinct from the rest of the page
- Made the coloration of the close button match our cta labeled buttons
- Added the word close to the i18n keys
- Added an aria-label and also added its key to i18n
- Swapped out the icon with one that's a bit bigger
- Did `space-x-3` rather than individual right and left padding for the button 

Normally I'd give you a chance to work on some of these things, but I'm really trying to close out some issues right now. Next time! Thanks so much for this. I think it's looking better than the designs, and the mechanics and how you're passing the props is great 😊 Looking forward to the next issue!

**Comment by dipushrestha** [comment]
@andrewtavis thank you for the help and explanation 🙌.
