### ISSUE TITLE
Create documentation card component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#395]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would focus on creating a [card component](https://github.com/activist-org/activist/tree/main/frontend/components/card) `CardDocsEntry.vue` for index documentation pages like those to be worked on in #33 #35 and #42. The designs for this component can be seen [on the Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=6340%3A449&mode=design&t=QtIT1amRX0lQy9zG-1) and further can be seen below:

![Docs Card](https://github.com/activist-org/activist/assets/24387426/ace2d9ed-5580-4cbb-b48f-061905b07943)

This component would hav various props including an image, a title and a short description. It would also be reactive to its contents.

### Contribution

This is going to be a part of a team for the 23/9/23 Code Night 🌙 that will try to finalize our documentation pages 🚀 #33 #35 and #42 will also be included, as well as a grid component in #396. This component is a `good first issue` and could be worked on by someone who's new to the community :blush: Happy to support!

**Comment by 90splayer** [comment]
Hello Andrew, I'd love to help create the documentation card component.

**Comment by andrewtavis** [comment]
Hey @90splayer 👋 Appreciate your willingness to help on this! I actually have this finished and sitting locally on my computer, but am waiting to send it along when I've finished up work on #33, #35 and #42. Happy to assign another issue if there's one that's of interest, and thanks for jumping into more than one issue at the start!

**Comment by andrewtavis** [comment]
Closed via 6ef6da8 🚀 Thanks again so much for your willingness to help here, @90splayer!
