### ISSUE TITLE
Create documentation entry grid component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#396]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue will focus on the creation of a [gird component](https://github.com/activist-org/activist/tree/main/frontend/components/grid) `GridDocsEntries.vue` that would house the `CardDocsEntry.vue` components being worked on in #395. The way that this component would function can be seen in the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=6340%3A449&mode=design&t=QtIT1amRX0lQy9zG-1) and can further be seen in an example page below:

![Docs Index](https://github.com/activist-org/activist/assets/24387426/3055d7a6-d9e0-4867-9963-596e99e3394b)

The component would have props for a title and also an array of `CardDocsEntry` components. It should further be styled in a way that the number of rows and columns of the grid is reactive to the screen dimensions.

### Contribution

This will be worked on as a part of the 23/9/23 Code Night 🌙 that activist is doing 😊 Issues that will be worked on with this as a part of a team are #33, #35, #45 and #395 🚀  This is a `good first issue` for someone who has general knowledge of frontend coding, especially Tailwind and Vue.js :) Happy to support or work on this with people!

**Comment by jakubsimo** [comment]
Hello, can I help you with this issue ? Can you assign it to me ? If task #395 is not done, I can also work on that so I can display it here, when I will have created this documentation entry grid component, so can you also let me know what is current status on task #395 ?

**Comment by andrewtavis** [comment]
Closed via 6ef6da8 🚀 Thanks again @jakubsimo for your willingness to help! Hope to work with you sometime soon 😊
