### ISSUE TITLE
Create privacy marker component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#397]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would focus on making the tag that would be on resources and other items when they're private - `frontend/components/marker/privacy.vue`. The designs for this component can be found [on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=4407%3A31785&mode=design&t=QtIT1amRX0lQy9zG-1) and are further displayed below:

![Private Marker](https://github.com/activist-org/activist/assets/24387426/571df431-3fe7-4dbb-8c3c-97721078e9c2)

This component would be `flex` to hug the contents and include `IconGroup` when dictated by a `type` prop being `"group"` or an [eye icon](https://icones.js.org/collection/bi?s=eye) like `bi:eye-slash` when it's `"default"`. How this would function is up for discussion :)

### Contribution

This is a great `good first issue` for someone who wants to make their first frontend component for us! Other contributors are also welcome to pick this one up 😊 Happy to support if someone needs help with it as well :) :) This is also available to do for our 23/9/23 Code Night 🌙🚀

**Comment by Davidkramer1999** [comment]
Hello I would like to take on this issue.

**Comment by andrewtavis** [comment]
Sure thing, @Davidkramer1999! Thanks for your interest in helping out!

Assigning you now, and let me know if there's anything I can do to help 😊

**Comment by andrewtavis** [comment]
Hey @Davidkramer1999 👋 Doing a quick check of issues :) Is there anything I can do to support here? Please let me know if you're not planning on working on the issue so I can open it up to someone else.

Hope you're well!

**Comment by esslamben** [comment]
Might work on this next @andrewtavis unless @Davidkramer1999 is still working on it?

**Comment by andrewtavis** [comment]
I'm comfortable reassigning, @esslamben :) @Davidkramer1999, I'm about to make a lot of issues in the coming days, so please keep a look out and I'd be happy to assign a new one!

**Comment by esslamben** [comment]
Hey @andrewtavis quick question for you. Where do I find that other icon the hierarchy one. This is all I've found https://icones.js.org/collection/all?s=hiera   

Also in terms of the marker itself, do we want to hide show the text based on width or should it just accept a boolean to show hide the text?

**Comment by andrewtavis** [comment]
Thanks for the question, @esslamben! The icon you're asking for is a custom one: `IconGroup` that's found in the components directory :) As far as the text, I'd say that having it be present only above the medium breakpoint via Tailwind's `hidden md:block` would be fine!

**Comment by andrewtavis** [comment]
990034f finishes this up, @esslamben! I renamed the component `MarkerPrivate` as I realized that the original name wasn't in line with what the others are called. I also made us of the `marker` directory already and moved what's now `MarkerTopic` in there :) :) Thanks for the work here!
