### ISSUE TITLE
Create top selector component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#398]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would be to create the top of page selector that will serve as a sub menu navigation for organization and event pages. The designs for it can be seen [on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2641%3A16666&mode=design&t=QtIT1amRX0lQy9zG-1) and can further be seen below:

![Top Selectors](https://github.com/activist-org/activist/assets/24387426/aee3d54a-0129-4292-a56d-56b08e8f6da7)

The name of this component could be something like `SelectorTopBar`, with it needing to extend the full width of its container. It should take a prop that defines the options, should also be styled for light and dark mode and include hover actions.

### Contribution

This is a great `good first issue` for someone who'd like to work on their first component, and can also be worked on as a part of our 23/9/23 Code Night 🌙😊 Happy to support someone if they'd need some assistance in working on this :) :)

**Comment by sayik** [comment]
Hi Andrew, can I work on this issue?

**Comment by andrewtavis** [comment]
Sure thing, @sayik! Assigning you now :) Let me know if I can do anything to help!

**Comment by andrewtavis** [comment]
```ts
const props = defineProps({
  selectors: {
    type: string[],
    default: [""],
  },
  selected: {
    type: string,
    default: "",
  },
});

if props.selected === "" {
    props.selected = selectors[0]
}
```

**Comment by andrewtavis** [comment]
```html
:class="{
  'bg-light-highlight dark:bg-dark-highlight': s === selected, 'bg-light-header dark:bg-dark-header': s !== selected
}"
```

**Comment by andrewtavis** [comment]
Hey @sayik! fffaec1 finishes this up and also does some variable renames as I decided that this is better named `MenuTopBar` and the other selectors should be moved to a dropdown directory. 

Get well soon my friend! 🍵🌿
