### ISSUE TITLE
Create search tag grid component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#399]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This is a very simple `good first issue` that would focus on creating a grid component that has search tags that the user could select to further filter search results (eventually). The designs can be seen [on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2504%3A14117&mode=design&t=QtIT1amRX0lQy9zG-1) and the tags further are below:

![Search Tag](https://github.com/activist-org/activist/assets/24387426/ff8fb2bb-c2f2-47e6-8789-8b3682786fc5)

This component would be at `frontend/components/grid/GridSearchTag.vue` and would inherently be a grid of words that are in a flex container that reacts to the screen size. The tags themselves would also react to light and dark mode :)

### Contribution

Happy to support someone who wants to work on this! This could also be included in the 23/9/23 Code Night 🌙 that we're doing 😊

**Comment by sayik** [comment]
Hey I'd like to work on this.

**Comment by andrewtavis** [comment]
Welcome, @sayik! Assigning you now :) :) We can talk during Code Night 🌙 about how to get this done :)

**Comment by andrewtavis** [comment]
5b78e41 likely fixes the last line of the file :) Closed in #404 🥳🚀
