### ISSUE TITLE
Create sign in/sign up tooltip (or general tooltip with variants)

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#400]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would be to create a component `TooltipSignIn.vue` that would prompt the user that they need to sign in or sign up. The designs for this can be found [on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2037%3A3102&mode=design&t=QtIT1amRX0lQy9zG-1) and can further be seen below:

![Mode=Light, Type=Sign in](https://github.com/activist-org/activist/assets/24387426/bb493b18-c2da-4efe-a0ab-99658f504a4f)

This component would comprise of a text, two `BtnLabeled` components, would need a shodow and would further be reactive to light and dark mode 😊 What would be even better would be if we could create a base tooltip component that then can be changed based on a passed text and buttons to a `<slot>`, which I'd be happy to discuss with the potential contributor!

### Contribution

This is a great `good first issue` for someone who'd like to make a first component for us, and can also be picked up by a member of the community if they're looking for something to work on 😊 Happy to support someone who has interest in working on this! This can also be worked on as a part of our 23/9/23 Code Night 🌙🚀

**Comment by marcosquadross** [comment]
I would like to work on this issue.

**Comment by marcosquadross** [comment]
I would like to work on this issue.

**Comment by andrewtavis** [comment]
Sounds good, @marcosquadross! Thanks for your interest in activist and your willingness to help 😊 Would you have interest in the base component as well? By that I mean the part I added here:

> What would be even better would be if we could create a base tooltip component that then can be changed based on a passed text and buttons to a `<slot>`

For that we'd make to components, `Tooltip.vue` and `TooltipSignIn.vue` where the latter would just have the appropriate buttons added to a `<slot>` as I described :)

Another tip on this: `card-style` can be used to apply the backgrounds and borders 🙃

Assigning you, and let me know if you want to do `Tooltip.vue` too :) Happy to provide more assistance as well if needed!

**Comment by hoon610** [comment]
Hi! If @marcosquadross is specifically working on the `TooltipSignIn.vue` could i work on a base component?

**Comment by andrewtavis** [comment]
Hey @hoon610! 👋 Thanks for your interest to help out! That would lead to a bit of a block as we'd want to have yours done before @marcosquadross, but if you want to send something along in the coming days I'd be happy to merge it in quickly so it can be used for other components 😊

**Comment by andrewtavis** [comment]
Feel free to confirm and I'll assign you as well :)

**Comment by hoon610** [comment]
I'll try and work on it this weekend!

**Comment by andrewtavis** [comment]
Wonderful! Assigning you now :)

**Comment by hoon610** [comment]
```
<template>
    <div class="">
      <slot></slot>
      <div class="placeholderbuttons">
        <template v-for="(button, index) in buttonData" :key="index">
          <BtnLabeled :label="button.label" :action="button.action" />
        </template>
      </div>
    </div>
  </template>
  
  <script setup lang="ts">
  import { defineProps, computed } from 'vue';
  import BtnLabeled from '../btn/BtnLabeled.vue';
  
  defineProps<{
    buttonData: Array<{ label: string; action: Function }>;
  }>();
  </script>
```

Hi, I'm very new to Vue so I might ask a few questions along the way if thats ok! I was wondering if something like this looks ok for the component. I wasn't sure if you wanted the base tooltip to have the option for varying the number of buttons so I tried writing it like this. Also I wasn't really sure how I would set up the slot for the button components so I set it up with access properties.

**Comment by andrewtavis** [comment]
I was thinking more that we could directly place the `BtnLabeled` into the slot and that we'd have `header` and `text` props that could be null that we'd then format :) We could then use this for all kinds of tooltips like if it's just a simple one with a text notification to the user about something, but then if actions are needed then buttons can be easily passed to the slot :)

How does that sound? Looks great so far though! 🚀

**Comment by hoon610** [comment]
That sounds great! I have restructured the component as you described.

I just had a quick question on what the best way would be for me to add the appropriate styling. I have read the STYLEGUIDE and understand how to write and format it with the CSS classes specific to the project. I just wasn't sure how I could actually visually see the component as I worked on it. I can get the dev build up and running. Should I just temporarily edit one of the pages to show my component? Most of the resources I see for styling components are much simpler in terms of project scope. Just wanted to know if there was a preferred method. Thanks again!

**Comment by andrewtavis** [comment]
Thanks for all the hard work here, @hoon610! 🚀

What I normally suggest is that people just put the component on the [home page](https://activist.org/home/) for now :) With this one though let's actually put it into production. My suggestion would be that we replace the tooltips that are currently found on the [search bar component](https://github.com/activist-org/activist/blob/main/frontend/components/SearchBar.vue) with this one 🤩 You can find the current implementation at [this line](https://github.com/activist-org/activist/blob/6e74f2065995d776dee5c3d196cc03cf6496f3f5/frontend/components/SearchBar.vue#L33C26-L33C26), and can see it in action on the home page that I linked if you hover over the `/` on the search bar. As of now it has a darker background, but I think this should actually switch. The goal from here would be that we'd pass the tooltip component that you're working on with just the `text` prop and that it would generally look like what we have already :) Would also be great if we replaced the tooltips for control and command `k` that are currently commented out.

Let me know if this makes sense!

**Comment by hoon610** [comment]
Thanks for the explanation

**Comment by andrewtavis** [comment]
6cb259b and c6abb50 as well as your two's PRs have closed this up 😊 Thanks so much, @marcosquadross and @hoon610! Really happy with how this worked out in the end :) :) Some minor notes on the most recent changes:

- The shadow and padding are now reactive to whether there's something passed to the slot or not via `useSlots()`
- The sign in tooltip uses the base tooltip as a basis
- I changed the i18n keys for the `BtnLabeled` components so they're in the `btn-labeled` part of the `en-US.json` file as we try to have keys defined on the [lowest level component on which they're used](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md#localization-)

Thank you both again so much for the efforts! Hope to work with either of you again :)
