### ISSUE TITLE
Add all image alt texts to the en-US.json file

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#405]
### Terms

- [X] I have searched [open localization issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+is%3Aopen+label%3Alocalization)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now we don't have all the alt texts for images in the [en-US.json](https://github.com/activist-org/activist/blob/main/frontend/i18n/en-US.json) file such that able to be localized and not hard coded in the platform. It would be good to add these to the JSON file and also to make sure that the images have aria-labels as well. You can find most of the entries that need to be moved in by [searching for `alt=`](https://github.com/search?q=repo%3Aactivist-org%2Factivist%20alt%3D&type=code) in the codebase.

**Comment by hariFED** [comment]
Hello, I am happy to help in this issue. As per the description the issue to solve, is to create alt text for all images that are present in [en-US.json](https://github.com/activist-org/activist/blob/main/frontend/i18n/en-US.json)  file but there is no images in the file. Could you please explain the issue @andrewtavis .

**Comment by andrewtavis** [comment]
Hey @hariFED 👋 Thanks for your interest in activist and helping out! The issue is that some the the alt texts we have for images are not in the `en-US.json` file so we can’t localize them. So we need to take the current text that is hard coded and add it to the JSON file. 

For example, in `pages/help/faq` we have the [line linked here](https://github.com/activist-org/activist/blob/4ea4b1e5a46f8bd917a97b9ddacd9eb72a6ea67d/frontend/pages/help/faq.vue#L16) that has a hard coded string. We need this added to the `en-US.json` file with the key `pages.help.faq.img-alt-text` and then we can assign this key in the file via `:alt=“$t(‘pages.help.faq.img-alt-text’)”`.

Let me know if more explanation would help! Aa stated in the issue, you can find those alt texts that aren’t already localized by looking for `alt=` in the codebase and looking for where it’s not localized yet (a key that starts with `$t`). 

Happy to discuss this a bit more and then I can assign you if you think it makes sense!

**Comment by hariFED** [comment]
Thank you for the explanation. So, I have to add the hard coded alt text in the codebase to en-US.json file and link the alt text to that corresponding Image, is this the issue to be solved.

**Comment by andrewtavis** [comment]
Exactly, @hariFED! Assigning you now :) Let me know if there’s anything I can do to help!

**Comment by andrewtavis** [comment]
23df3e5 and d1e1158 close this, @hariFED 😊 Again sorry for the wait here, but really happy with the results! This is another really important step in preparing for localization of the platform :) :) Hope to work with you again!
