### ISSUE TITLE
Improve PR steps in contributing guide

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#407]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

I'm noticing that as of now the [PR flow within the contributing guide](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#pull-requests) is not specific to this repository and is a bit convoluted. It would be great if we could improve it such that it's specific to activist and we can send it along to people who are having problems making their first commit. Beyond this, the suggestion at the start is to fork the repo and then clone the fork, which isn't what we have in the [environment setup in the readme](https://github.com/activist-org/activist#environment-setup) where they're directed to clone this repo.

**Comment by iagocarmona** [comment]
Hello, I would like to work on this

**Comment by andrewtavis** [comment]
Sure thing, @iagocarmona! Thanks for the offer to help :) Big thing is that we want the steps to be specific to activist and match what we say in the readme. Would be great to get your input on what would make it easy to understand! Let me know if I can help!

**Comment by to-sta** [comment]
#412 in case this gets merged, we should consider add a line to the contrib guideline for "pre-commit install".

**Comment by andrewtavis** [comment]
This should include an inline bash comment and/or an explanation of what's happening :)

**Comment by to-sta** [comment]
> This should include an inline bash comment and/or an explanation of what's happening :)

My suggestion based on @andrewtavis feedback would be:

```bash
pre-commit install
```

This will ensure during development that each of your commits is properly formatted against our linter and formatters.

**Comment by iagocarmona** [comment]
Can I talk to someone to help me on this ? @andrewtavis @to-sta

**Comment by andrewtavis** [comment]
Sure @iagocarmona! We could maybe do a call on the weekend for this and #379?

**Comment by iagocarmona** [comment]
Yes please! It's on element right?

**Comment by andrewtavis** [comment]
We have the dev sync on Element Call on Saturday at 15:00 UTC, if that's what you meant, @iagocarmona, but you and I can also do a call outside of that if you wanted :)

**Comment by andrewtavis** [comment]
Closed via #434 🚀 Thanks @iagocarmona! @wkyoshida, I've made https://github.com/scribe-org/Scribe-iOS/issues/369 to reflect the changes that we want for Scribe 😇

**Comment by andrewtavis** [comment]
Minor changes in 4104d47 to remove the oxford comma and put periods at the end of the full line comments as that's the style we're following 😇 Didn't see it till it was live :)

**Comment by wkyoshida** [comment]
Hallo! :wave: 

Sorry, quick q - 
I've noticed that the ["Development environment"](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#development-environment-) section in the `CONTRIBUTING.md` contains what I believe were the previous instructions in the `README.md` before. Since the ["Pull requests"](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#pull-requests-) section now has the updated instructions for the `CONTRIBUTING.md`, I'm wondering how to marry the two sections. Would it make sense perhaps to copy what is in the `README.md` into the "Development environment" section and remove step `1.` from the "Pull requests" section (since that info is duplicated in the other section)? 

Hopefully this makes sense :grin:

**Comment by andrewtavis** [comment]
Thanks for the thoughts on this, @wkyoshida! Makes sense to me :) @iagocarmona, do you want to do another quick PR? New issues should be coming today 😊

**Comment by iagocarmona** [comment]
Hello, thanks for this thought. I can do a PR to fix that soon! 🚀

**Comment by andrewtavis** [comment]
Reopening this just so we have an eye on it :)

**Comment by andrewtavis** [comment]
79ce9aa closes this, all :) Minor changes to standardize the sections and indentation 😊 Looking great! Thanks for the hard work @iagocarmona and for the feedback/reviews @to-sta and @wkyoshida 🙌
