### ISSUE TITLE
Introducing Pre-Commit Hooks for formatting and linting

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#409]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We could use `pre-commit` to ensure code formatting and linting before commits with the use of the python package [pre-commit](https://pre-commit.com/). 

There are pre-commit hooks available for our development process for the frontend and backend:
1. prettier (frontend)
2. black (backend)
3. ruff, including isort (backend)
4. mypy (backend)

Additionally it could help with .yaml files, trailing whitespaces, end of file (blank line) and mixed file endings (LF, CRLF).

### Contribution

Happy to work on this myself or help someone 😃.

**Comment by andrewtavis** [comment]
I think it makes sense that you work on this, @to-sta :) Assigning you :)

**Comment by sinderoth** [comment]
Might be a good idea to format the entire codebase at once, instead of making gradual changes

**Comment by to-sta** [comment]
@sinderoth pre-commit covers both use cases. It allows us to run thru all files with the cmd `pre-commit run --all-files` but also covers every new commit.

**Comment by RengarajR404** [comment]
Do you have any open issues for working. 
I am available to contribute.

**Comment by to-sta** [comment]
> Do you have any open issues for working. I am available to contribute.

@RengarajR404 it's awesome that you want to contribute! If there are no suitable or availabe [issues](https://github.com/activist-org/activist/issues) for you to work on the at the moment, we will be adding new issues soon 😃

**Comment by andrewtavis** [comment]
Thanks for your interest from me as well @RengarajR404! We're doing a developer sync later today, and doubtless there will be some new issues coming out from that 😊

I'm assuming that #412 closes this, @to-sta, but feel free to re-open and let me know if there are further steps needed :) :)

**Comment by andrewtavis** [comment]
Hey @RengarajR404 👋 FYI I just made #419 that would be a great `good first issue` if you wanted to jump into that :) Feel free to write in there and I'll assign 🙃
