### ISSUE TITLE
Lower case all type declarations in <script> blocks

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#419]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now we have a few cases where we have a type declaration that's capitalized in one place and not in another place. This should be standardized throughout the code base, with the decision being made when the [styleguide](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md) was written to do [lower case types](https://github.com/activist-org/activist/blob/main/STYLEGUIDE.md#vue-single-file-component-vue-file-guidelines).

It would be great if someone would go through and change all the capitalized types to lower case :)

### Contribution

This is a great `good first issue` for someone who wants to help out! I'd be happy to support 😊

**Comment by andrewtavis** [comment]
I'll write in here as well :) @RengarajR404, do you want to work on this one?

**Comment by RengarajR404** [comment]
Sure I will love to work here.
Thank you for assigning me

**Comment by RengarajR404** [comment]
I have opened a pull request regarding the update.
It has passed all the build tests.
Can you please check and reply regarding the further updates.
Thank you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andrewtavis** [comment]
c9d1a38 and 6bebc28 close this, @RengarajR404! Appreciate the quick reaction to the PR review and your interest in helping us out here 😊 This issue was also a great catalyst to really improving TS across the platform :)

Look forward to working with you again!
