### ISSUE TITLE
Add notes on ssh keys in the contributing guide

### ISSUE THREAD

**Issue by wkyoshida** [activist-org/activist#420]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is to add notes to the contributing guide on using ssh keys in a contributors' development/git workflow.

Slightly related to updates also being made as part of #407 

Can take this on :sunglasses:

**Comment by andrewtavis** [comment]
Thanks @wkyoshida! 🙏😊

**Comment by RengarajR404** [comment]
Can you please further elaborate on this issue and if possible assign me to this issue?
I have some practical working knowledge regarding cryptography and encryption.

**Comment by wkyoshida** [comment]
Hey @RengarajR404! :wave: 

Oh, this isn't meant to be technically complex by any means actually :laughing: 
This issue is just doc updates. Might've noticed that the [CONTRIBUTING.md#pull-requests](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#pull-requests-) uses HTTPS in the instructions for git workflow. This issue is just for adding notes for using SSH as an option. 

Actually, I already have this done, I'm afraid @RengarajR404 :sweat_smile: I'm just deciding to wait on #407 to get in to avoid dealing with a merge conflict later.

**Comment by andrewtavis** [comment]
Seems like the changes for #407 should be coming through soon given conversations with I've had with @iagocarmona :) Looking good so far!

**Comment by andrewtavis** [comment]
Closed via #517 and minor formatting that went through in 7bce1bf 🌿 Thanks @wkyoshida! Let's definitely add this in to Scribe repos as well!

**Comment by wkyoshida** [comment]
> ..Let's definitely add this in to Scribe repos as well!

:rocket: 

@andrewtavis For this, were you thinking of just doing a mass update as you've done before or of opening up an issue to allow someone to take a crack at?

**Comment by andrewtavis** [comment]
Let's just do a mass update for the SSH once https://github.com/scribe-org/Scribe-iOS/pull/370 and any updates to other Scribe repos are merged :)

**Comment by wkyoshida** [comment]
Sounds good to me :+1:
