### ISSUE TITLE
Enforce order of Vue SFCs as template-script-style

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#424]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

activist made the decision to use the "old" `template-script-style` block ordering rather than the "new" `script-template-style` ordering. The reason for this is activist's use of Tailwind where` template` blocks thus have both the HTML and CSS logic. The "new" style is pushed for projects where they actively use the `style` block where `template` is used with both `script` and `style`, so it goes in the middle as you'd rarely be going between `script` and `style` during development. As activist components rarely use `style` blocks, it thus makes sense to start with the block that contains most of the component logic.

This issue would look into and implement a `["template", "script", "style"]` order using [vue/block-order](https://eslint.vuejs.org/rules/block-order.html) such that the team will be warned when the block ordering doesn't follow this.

### Contribution

This is a great `good first issue` for someone who wants to do a bit of implementation research. Happy to support!

**Comment by andrewtavis** [comment]
Ping @to-sta and @sayik as this continues the discussion we were having last night :)

**Comment by ahmedy00** [comment]
@andrewtavis could you assign this issue to me

**Comment by andrewtavis** [comment]
Thank you, @ahmedy00! Let me know if there's anything I can do to support :)

**Comment by andrewtavis** [comment]
Thanks for this, @ahmedy00 :) 9c405b8 sends along a new `yarn.lock` file as it wasn't edited in the PR, so I think you added the dependencies to the `package.lock` file without doing `yarn install package_name` :) 

It also adds a line to `eslintrc.js` for the parser as well as `vue/base` as a plugin. I was originally getting errors, but now all's good and there's no error within the `eslintrc.js` file now.

The thing is though that I'm not seeing anything in my dev env in response to these changes. If I go to a component and add an empty `<style>` block above the `<script>` such that we'd have an empty block error and an out of order one, I'm seeing nothing at the moment 🤔 

Any thoughts? Maybe I just have another step I need to do?

**Comment by ahmedy00** [comment]
@andrewtavis There is an extra white space in the `"plugin: vue/base`" code on line 6 of `.eslintrc.js` file, as far as I understand, this is causing the problem, could you also check it?

**Comment by andrewtavis** [comment]
Ya I'm seeing that error now too, @ahmedy00. Issue is that when I fix it I still don't receive a warning about block order, and beyond that then there are a ton more issues/warnings throughout the code base that are really distracting... How does it look for you when you fix that line?

**Comment by ahmedy00** [comment]
@andrewtavis When I fixed this line, block order and empty block rules are working properly, I also realised that the distracting issues you mentioned are caused by the recommended rules, we need to customise them a bit more, we can revert the PR so that this does not cause a negative developer experience

**Comment by andrewtavis** [comment]
Really weird that this isn't working properly on my end as far as the order and empty warnings... Maybe we can open a new issue for the eslint rules? Would you have interest in opening and working on that? We could also loop in @to-sta who's working loads on the dev env 😊

**Comment by andrewtavis** [comment]
This issue was closed by #448 :) Thanks @ahmedy00!
