### ISSUE TITLE
Improve Nuxt Typescript setup

### ISSUE THREAD

**Issue by dipushrestha** [activist-org/activist#435]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Currently, Nuxt auto-imported components have type as any.

Eg. - the `PageDocs` component is showing up as any.
![image](https://github.com/activist-org/activist/assets/36785868/1e345b80-4395-4fd7-b0a1-3ff9374c1326)

The problem is probably with the current Nuxt Typescript setup. Update the TS setup to make sure that the auto-imported components have the proper type information.

**Comment by andrewtavis** [comment]
Thanks for the issue, @dipushrestha! Really appreciate the care for the dev experience 😊 I'll assign you as you said on Matrix that you'd take a look :)

**Comment by dipushrestha** [comment]
Hi, @andrewtavis got busy with work. I will look into this after the holidays.

**Comment by andrewtavis** [comment]
Sounds good, @dipushrestha! Looking forward to your suggestions :)

**Comment by hoang227** [comment]
Hi can I help to tackle this problem!

**Comment by andrewtavis** [comment]
Sure thing, @hoang227! Let us know if you have any questions!

**Comment by andrewtavis** [comment]
@dipushrestha, would be great to get some feedback from you on this as well! Hope all's well with you :)

**Comment by hoang227** [comment]
Hey @andrewtavis, I have a question. I am not quite sure what the type should be. For example, in the screenshot above, what **type** should PageDocs be and what are the **relevant type information**? I have provided the code for the PageDocs component below for reference.

``` ruby
<template>
  <div
    class="text-light-text dark:text-dark-text bg-light-layer-0 dark:bg-dark-layer-0"
  >
    <div
      class="flex flex-col items-center w-full responsive-py-4 responsive-px-5"
    >
      <!-- Note: image on top of content. -->
      <img
        class="h-40 mb-4 md:hidden sm:h-52"
        :src="imgURL + '_' + $colorMode.value + '.png'"
        :alt="$t(imgAltText)"
      />
      <div class="w-10/12 grid grid-cols-1 md:w-full 2xl:grid-cols-2">
        <div class="items-center text-left space-y-4 md:items-start">
          <!-- Note: image floating right of content. -->
          <img
            class="hidden float-right p-4 h-52 md:block 2xl:hidden lg:h-64"
            :src="imgURL + '_' + $colorMode.value + '.png'"
            :alt="$t(imgAltText)"
          />
          <PageBreadcrumbs />
          <slot />
        </div>
        <div class="flex justify-end pr-32">
          <!-- Note: image right of content. -->
          <img
            class="hidden 2xl:block h-72"
            :src="imgURL + '_' + $colorMode.value + '.png'"
            :alt="$t(imgAltText)"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  imgURL: string;
  imgAltText: string;
}>();
</script>

```

**Comment by andrewtavis** [comment]
Hey @hoang227! Thanks for reaching out :) Specifically what we're looking for is the tooltip for `PageDoc` being a bit more verbose with information about the file :) So ideally we'd also have some hints as to which props we can pass and which are required. I figure that you understand this, but wanted to make sure!

**Comment by andrewtavis** [comment]
Hey all 👋 Gonna close this one as on inspection it seems to be solved via the most recent dependency upgrades. We now have very verbose outputs for each of the components including props it takes, etc:

![Screenshot_2024-05-01 01 00 51](https://github.com/activist-org/activist/assets/24387426/2900f546-d75e-4c6a-9600-26634d2f57be)

Thanks all so much for the discussion here!

**Comment by andrewtavis** [comment]
One thing to note here is that you may need to restart the TypeScript server in VS Code or your IDE to get the highlight working :) In VS Code this can be done by going to `tsconfig.json` and then going to the command palette and selecting `TypeScript: Restart TS Server`.
