### ISSUE TITLE
Add notes on pre-commit to readme / contributing guide

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#442]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As mentioned in #407, we should add a note about pre-commit to the readme and the contributing guide. 
I will make a PR right away 😃.

**Comment by to-sta** [comment]
I am closing this issue as it was solved with the PR #443

**Comment by andrewtavis** [comment]
Thank you, @to-sta!
