### ISSUE TITLE
Eslint rules does not gives warning for VS Code

### ISSUE THREAD

**Issue by ahmedy00** [activist-org/activist#445]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

The new rules added in issue #424 work properly in Jetbrains IDEs (Pycharm, Intellij IDEA), but do not show the necessary warnings in VS Code.

**Comment by ahmedy00** [comment]
@andrewtavis Could you assign it to me?

**Comment by andrewtavis** [comment]
Sure thing, @ahmedy00! Appreciate you opening this up and looking into this further! 🙏

**Comment by ahmedy00** [comment]
Hey @to-sta, when you have time I would like to discuss about this bug and benefit from your experience

**Comment by to-sta** [comment]
@ahmedy00 i looked a bit into the issue and found out that when i add the following into the `.vscode/settings.json` file:

```json
{
  "eslint.validate": []
}
```
That vscode is starting to complain about the order. This is not an optimol solution though. 

@ahmedy00 are you on matrix?

@andrewtavis At the moment we run `formatting` and `type` checks on the frontend, might make sense to add a linter as well (to gain independence of the IDE issues 😄).

**Comment by andrewtavis** [comment]
Makes sense, @to-sta! Would you make an issue for that? :)

**Comment by andrewtavis** [comment]
Closed via #448 and #452 🚀 Thanks for this, @ahmedy00 and @to-sta!
