### ISSUE TITLE
Configure eslint

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#449]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The current output for running eslint on the frontend directory.
cmd:  `npx eslint . --ext .js,.vue`

```bash
✖ 379 problems (139 errors, 240 warnings)
  0 errors and 238 warnings potentially fixable with the `--fix` option.
```

This task would involve configuring `eslint` to work with `nuxt` and `prettier`. I found two packages that should do the job [nuxt-eslint-config](https://github.com/nuxt/eslint-config), [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).

After that we still have to go thru the reduced set of warnings and error. For example attribute-hyphenation should be ignored. 
```bash
warning  Attribute 'contentPosition' must be hyphenated  vue/attribute-hyphenation
```

### Contribution

Happy to help someone or i work on this myself eventually 😄

**Comment by andrewtavis** [comment]
Closed via #452 :)
