### ISSUE TITLE
Splitting development and production requirements.txt

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#450]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

## Splitting development and production `requirements.txt`

As part of our testing efforts #432 we want to split development and production enviroments. Part of splitting the enviroments is to create seperate requirements.txt files. 

Here are the steps that are involved with the changes:
1. Filter requirements into `requirements.in` and `requirements-dev.in` (excluding subpackages)
2. Using [pip-tools](https://github.com/jazzband/pip-tools) to compile the requirements into `requirements.txt` and `requirements-dev.txt` files.
3. Testing if the different enviroments work. Since we do not have tests setup yet, running the server and migrations should be sufficient for now. 
4. Adjusting the `pr_backend_formatting_check` and dockerfile in the backend directory, to use the `requirements-dev.txt `

### Contribution

Happy to support someone on this issue or work on it myself :smile

**Comment by andrewtavis** [comment]
Closed via #476 🚀🔥🙌
