### ISSUE TITLE
Add hover coloration to form components

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#453]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to add hover coloration to components in the [form directory](https://github.com/activist-org/activist/tree/main/frontend/components/form). As of now none of these components like checkboxes and buttons change color on hover. This would be achieved by adding `hover:bg-Light-COLOR dark:hover:bg-DARK-COLOR` to components, with the needed colors being determined based on the inactive and active state colors. The forms can be seen in action on pages like [activist.org/en/events](https://activist.org/en/events/) :)

### Contribution

Would be happy to support someone who wants to work on this! We can discuss which colors to choose first and then help find all the places that changes need to happen if needed. This is a great `good first issue` for someone who wants to work on something for activist and learn more about the community 😊

**Comment by andrewtavis** [comment]
Hey @ZuzkaL, pinging you for new issues :) Let me know if this one sounds interesting, or I'll make a few more 😊

**Comment by shubhalgupta** [comment]
@andrewtavis please assign me this issue!

**Comment by andrewtavis** [comment]
Hey @shubhalgupta! Thanks for your interest in activist and wanting to help 😊 Assigning you now, and please let me know if you need any assistance!

**Comment by shubhalgupta** [comment]
@andrewtavis kindly review!

**Comment by andrewtavis** [comment]
Nice @shubhalgupta! Looking forward to checking it out 😊😊
