### ISSUE TITLE
Create topic dropdown component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#455]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to crate a `DropdownTopics.vue` component in the frontend that will be used to select the topics that the user wants to filter by. We'll need this to be a multi selection dropdown that uses [Headless UI](https://headlessui.com) for accessibility - for instance a [combobox](https://headlessui.com/vue/combobox). The component would be made in the [dropdown directory](https://github.com/activist-org/activist/tree/main/frontend/components/dropdown).

The general style for the component can be found [on the designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2719%3A24686&mode=design&t=jTUMfp3ZcqY6KqEK-1), but personally I feel like we can improve this a bit. As far as props are concerned, we'll need to have two sections: one that's at the top that are the saved topics of the user, and one that's below a horizontal separator line that has the rest of the available topics. Each section could have a small header above such as `My topics` and `Other topics`.

This component would then replace the placeholder topics dropdown component on pages such as the [home page](https://activist.org/en/home).

### Contribution

Happy to support someone on this! This can be a `good first issue` for someone, but note that it's a bit more difficult :)

**Comment by iagocarmona** [comment]
Hello, I would like to work on this!

**Comment by andrewtavis** [comment]
Thanks @iagocarmona! Assigning you now 😊 Please let me know if there are any ways I can support! Your feedback and ideas on this would also be very welcome :) Looming forward to this 🙌🙌

**Comment by andrewtavis** [comment]
Closed via #497, with 2437018 doing the refactor as discussed in the PR, @iagocarmona 😊 Thanks for the initial effort on this! Really great to get this done :)
