### ISSUE TITLE
Create FormViewSelector component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#456]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would be to create a view selector component within the [form directory](https://github.com/activist-org/activist/tree/main/frontend/components/form). The designs for this component can be found [here in the Figma designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1922%3A1810&mode=design&t=jTUMfp3ZcqY6KqEK-1), and is also found below:

![View Selector](https://github.com/activist-org/activist/assets/24387426/2a19a41d-f76b-47ed-9430-0da237bf8620)

How the props for this component would be defined is still up for discussion, and ideas would be welcome!

### Contribution

Happy to support someone with this issue! This is a great `good first issue` for someone who wants to join the community and also for a contributor who's looking for something to work on 😊

**Comment by bmartins-42** [comment]
Hello, if this issue is still available, I would gladly work on it :)

**Comment by andrewtavis** [comment]
Hey @bmartins-42! Happy to assign you 😊 Please let me know if there's anything I can do to assist :)

**Comment by bmartins-42** [comment]
Thank you, @andrewtavis.

Maybe you could explain me a little the purpose of this component, so I can understand the usage.

**Comment by andrewtavis** [comment]
Sure thing, @bmartins-42! I'd say on this let's focus on the bottom ten selectors, with that being four options that have list or map view and six that have list, map or calendar view. This would basically be the filter that you would click in the sidebar to change the view of the right side of the screen. So say that we're on a list view of events and we click the map: we'd then switch to a map, and similarly for the calendar. The best place to see this is on [the events page on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2504%3A14117&mode=design&t=1iLaGoS7r2LOTewF-1). For filtering organization results we'd just need a list view and a map view. 

As far as props we can maybe pass selector options? `option1: string`, `option2: string`, and `option3?: string` where if the first option is null then we'd only have two buttons. We then determine the icons and the results based on what the passed option strings are like "list", "map" and "calendar" :)

How does this sound?

**Comment by andrewtavis** [comment]
69dd95d, @bmartins-42! Looking forward to putting this on pages and especially seeing the transition from a list to a map for thigs like events 😊 Thanks for contributing in so many ways so early in the process 🚀
