### ISSUE TITLE
Prevent desktop sign in and sign up page logo area from being clickable everywhere

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#457]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

As of now on the [sign up](https://activist.org/en/auth/sign-up) and [sign in](https://activist.org/en/auth/sign-in) pages for desktop the entire left side is clickable to return to the platform root `/`. We only want the logo to be clickable.

Would be great if a new contributor wanted to work on this! It's a `good first issue`, and I'd be happy to help 😊 This issue is also available for current contributors who are looking for something to work on :) :)

**Comment by GOWTHAM2K1** [comment]
hey is it still open , can I work on it.

**Comment by andrewtavis** [comment]
This one is still open and would be perfect, @GOWTHAM2K1 😊 Assigning you now, and please let me know if there's anything I can do to support!

**Comment by GOWTHAM2K1** [comment]
hello, can i add extra css file for the desired changes to be done??

**Comment by GOWTHAM2K1** [comment]
Hii, I just submitted the pr for the solution of the above problem. If any changes has to be done please do let me know. And sorry for late submission it took time because I had problem in the installation of docker.

**Comment by andrewtavis** [comment]
Hey @GOWTHAM2K1! No stress on it taking time whatsoever. This was actually quite a quick turnover 😊 I'll get to the review later and let you know if there's anything else we need!

**Comment by andrewtavis** [comment]
Hey @GOWTHAM2K1 👋 25e5141 does some reformatting for all this so the Tailwind used is a bit more streamlined and we can revert the logo dimensions back to what they were :) Appreciate the work here! Closing this now 😊
