### ISSUE TITLE
Create TooltipPasswordRequirements component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#458]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would be to create a tooltip that shows the user the requirements for a password on activist on the [sign up page](https://activist.org/en/auth/sign-up/). The designs for it can be found [here on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2037%3A3102&mode=design&t=jTUMfp3ZcqY6KqEK-1), with the light mode designs being found below:

![Mode=Light, Type=Password](https://github.com/activist-org/activist/assets/24387426/60db746d-28d7-4113-b096-258e9d09d6f3)

We'd need the text for this to be added to the [i18n `en-US.json` file](https://github.com/activist-org/activist/blob/main/frontend/i18n/en-US.json). Props for the component would include the red Xs and green checkmarks that would be triggered by the password text field eventually :)

### Contribution

Happy to support someone who wants to work on this! This is a great `good first issue` as well as one that's fitting for current contributors who are looking for something to work on 😊

**Comment by ahmedy00** [comment]
@andrewtavis could you assign the task to me?

**Comment by andrewtavis** [comment]
dad43e8 closes this out, @ahmedy00 😊 Again so awesome! The things I changed:

- Edited the word `blured` as it should be `blurred` :)
- Formatted the spacing and word/icon size a bit
- Edited the i18n to add a thank you (added it to the designs as well)
- Made the password error border act red in light and dark mode so it matches other pages
- Added a condition where the eye icon for showing the password will also change to one that has a slash when the user is able to see the characters in the password field

Let's keep in mind that there are some TS errors introduced by this! Maybe we can try to fix them in the sync today 🤔

Thanks again so much!
