### ISSUE TITLE
Create CardDiscussionText component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#459]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would be the creation of a card for discussion text entries. The designs for this component can be found [here on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2642%3A19285&mode=design&t=jTUMfp3ZcqY6KqEK-1). For this issue we wouldn't necessarily need to add in the tooltip that would be have available options when clicking the `•••` meatball menu, but this could be included if the person has interest. We could also make another issue for that after this one is done 😊

The designs can also be seen below:

![Discussion Text](https://github.com/activist-org/activist/assets/24387426/692167c7-1ded-47ed-8360-466a38cf1b68)

We'd need this to be light and dark most responsive, but in the [components/card](https://github.com/activist-org/activist/tree/main/frontend/components/card) directory, and have a `BtnLabeled` component for the upvote functionality.

### Contribution

Would be happy to support someone on this issue! This is a great `good first issue` and also would be a good one for a current contributor looking for an issue to work on to pick up 🚀

**Comment by dmsmirno** [comment]
Hello, Is this issue still up for grabs? I'm looking to make a first-time contribution and this feature looks cool, so I'd like to work on it if its not taken up by someone else.

**Comment by andrewtavis** [comment]
Hey @dmsmirno! Thanks for your interest in activist and in helping out :) This is free for new contributors, so I'll go ahead and assign you 😊 

Please let me know if there's anything I can do to help!

**Comment by andrewtavis** [comment]
Would be great if this could go in the `components/card` directory of the frontend, and specifically if you could make a `discussion` sub directory that would be perfect 😊

**Comment by andrewtavis** [comment]
44f40bd finalizes this, @dmsmirno! I put an example of the new component on the [home page](https://activist.org/en/home/) for now :) Really appreciate the work and the communication here! I'll be making more issues in the coming days, and hope that you'll pick one up 😊
