### ISSUE TITLE
Create CardDiscussionInput component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#460]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create a component that houses the write a discussion comment UI. It roughly matched the GitHub comment UI, and can be found [here on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2642%3A19615&mode=design&t=jTUMfp3ZcqY6KqEK-1) as well as below:

![Discussion Input](https://github.com/activist-org/activist/assets/24387426/c12dea1a-61c9-4c99-a069-30d4b83cca29)

This issue doesn't necessarily need to include the full functionality of this component! We can certainly separate it into other issues after an initial implementation is created here 😊

### Contribution

This issue is more involved than other issues and should likely be worked on by someone who has knowledge of the code base. Happy to support a new contributor though! Also happy to pick it up myself at some point 😊

**Comment by GOWTHAM2K1** [comment]
hey can i do it??

**Comment by andrewtavis** [comment]
I'm happy to assign you, @GOWTHAM2K1, but before you start working on it can we document the steps we'll take to make this component? This is definitely more involved than other issues and is definitely not easy. How would you go about working on this?

**Comment by andrewtavis** [comment]
Assigned :) Let's please make a plan before coding starts though so we can agree on how best to build this 😊

**Comment by GOWTHAM2K1** [comment]
> I'm happy to assign you, @GOWTHAM2K1, but before you start working on it can we document the steps we'll take to make this component? This is definitely more involved than other issues and is definitely not easy. How would you go about working on this?

So I would firstly build the component as per design and then individually start embedding functionality to the elements in the components Individually.  And also I am a beginner in vue framework so i would like to know the best way to go froward .

**Comment by andrewtavis** [comment]
Maybe it makes sense that for this we just build the component with all the buttons and then we can add the functionality in other issues :) How does this sound, @GOWTHAM2K1?

**Comment by GOWTHAM2K1** [comment]
Yes, it would make the process much quicker.I will submit pr as soon as possible.

**Comment by andrewtavis** [comment]
As noted in the review in #484, let's have this component be `CardDiscussionInput` in the `.frontend/components/card/discussion/` directory :) Would be good if you pull the repo once #463 is closed so that you'll have that directory and can reference the changes. These are turning out nicely though! 🚀

**Comment by GOWTHAM2K1** [comment]
sure, let me know when it will be closed as I have almost completed building the component will submit pr then.
I hav some doubts ,  the CardDiscussionInput component that i am building it simialarly to that of other component with all the similar dependencies and import statement and is currently placed ("en/home") .frontend/components/card/search-result here to check the working . So after completing the component should I move it .frontend/components/card/discussion/ here and remove the component from this page "en/home"??

**Comment by andrewtavis** [comment]
We can check it out on `home` for the PR and then remove it :)

**Comment by GOWTHAM2K1** [comment]
I have completed  what should i do next.
![Screenshot_1](https://github.com/activist-org/activist/assets/97494803/8382bdce-8cb4-45bb-8abc-2313f2acd9e7)

**Comment by andrewtavis** [comment]
Hey @GOWTHAM2K1 👋 Would be great if you could pull the most recent changes to the repository. Aside from that, would be good to include the markdown label in the bottom left as in the designs, and then we're good to go. I'll then review and make other issues for the various parts of the functionality. You can place the `CardDiscussionInput` beneath `CardDiscussionEntry` on the home page for the PR as well 😊

Thank you!

**Comment by andrewtavis** [comment]
a9f33fb sends along the needed changes, @GOWTHAM2K1! Thanks again so much for this. Really exciting start to a lot of work. I'll make the issues for adding functionality sometime this week. You'd be welcome to pick some of those issues up. Again though, it would be great if you could check the [contributing guide](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md) to familiarize yourself with localization practices and some other helpful ways of getting the code you send along formatted correctly. With those steps these will be some pretty great pull requests 🚀

**Comment by GOWTHAM2K1** [comment]
Sure will checkout contributing guidein future. And thank you for guiding me to clear the hacktober fest. Do let me know if you want anything to be done.

**Comment by andrewtavis** [comment]
Keep an eye on the new issues, @GOWTHAM2K1 😊 We'll be making more soon, and it'd be great to work with you again :) :)
