### ISSUE TITLE
Create CardDonate component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#461]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would be to create a `CardDonate` component where organizations could include a link to a page where people could financially support them. This card can be seen in the designs on the [prototypes page](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1998%3A2577&mode=design&t=jTUMfp3ZcqY6KqEK-1). We need a text as well as a `BtnLabeled` CTA that has a right icon prop passed to it for an external link indication. The component can also be seen below:

![Support](https://github.com/activist-org/activist/assets/24387426/35e24ae0-ee1f-4238-be99-d6c77cbfdb0d)

### Contribution

Happy to support someone on this issue! Is a great `good first issue` and also would be open to current contributors looking for something to work on 😊

**Comment by GOWTHAM2K1** [comment]
hello, if it is open can i work on it??

**Comment by andrewtavis** [comment]
By all means, @GOWTHAM2K1 😊 Assigning you now :) Big thing is to use `card-style` for your Tailwind styling here and reference the other components that are similar in the [card components directory](https://github.com/activist-org/activist/tree/main/frontend/components/card).

**Comment by GOWTHAM2K1** [comment]
Hello is there any place in the website where the other card components are used so that I can refer to its working.

**Comment by andrewtavis** [comment]
Yes of course, @GOWTHAM2K1 😊 Sorry I should have mentioned it earlier! You can see cards on all kinds of pages that are within their normal routes, we just don't link it all together yet :) If you go to [activist.org/home](https://activist.org/en/home) you can see the the search result cards, and the donate card would be on an organization about page like [activist.org/organizations/123/about](https://activist.org/en/organizations/123/about) :)

**Comment by andrewtavis** [comment]
Thanks for the question, @GOWTHAM2K1! For now I think it's ok to just make the component. We'll add it in once we start getting the first organizations in there and have a field for it in the backend. 

For the component, big thing is we need to have a `text` prompt and a `url` prompt that determines where the button links to :) Also have the `BtnLabeled` component have a right icon prop for the external link would be great 😊

**Comment by andrewtavis** [comment]
Noticing the issue said left icon, which is why I'm bringing this up. Will fix that now :)

**Comment by GOWTHAM2K1** [comment]
![ui1](https://github.com/activist-org/activist/assets/97494803/0cae032c-8b4a-41bf-a529-eee74206a8c7)
![ui2](https://github.com/activist-org/activist/assets/97494803/32a854f1-f268-4922-b906-ab15bc0491d2)
hey i have completed this much, from the above image if there any changes to be done please do let me know. And for the text component i have typed it in carddonate component itself, shall i move it to it en-US.json or is it enough.

**Comment by andrewtavis** [comment]
cb5d86b closes this, @GOWTHAM2K1 :) Thanks for the help here! I took out the edit mechanics for now as we still need to decide how this will work. Along with this are some other minor edits to formatting, the localization texts and adding a prop for if the organization wants to customize the text of the card 🚀
