### ISSUE TITLE
Create CardOrgApplicationVote

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#462]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create a component in the [components/card](https://github.com/activist-org/activist/tree/main/frontend/components/card) directory where that houses the ability for organization admins to indicate their support for other organizations to join activist. As this is a main component of how the activist community will expand, this issue is very very important 😊 The designs for this can be seen [on Figma on the organizations tab](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2642%3A20194&mode=design&t=jTUMfp3ZcqY6KqEK-1). One prop needs to be whether the vote is closed or not, with this then disabling the `BtnLabeled` components with right icon props passed for an up or down arrow.

### Contribution

This is a bit more of an involved `good first issue`, but I feel like it's definitely something that someone could jump into if they had interest. This component will doubtless evolve over time, but making an initial version now would allow us to start user testing it 😊 It's also of course open to the dev community if they want to pick it up 🚀 Happy to support!

**Comment by rigojr** [comment]
Hi @andrewtavis I would like to take of this issue. I have issues to get into the dashboard, How can I get into?

**Comment by andrewtavis** [comment]
Hey @rigojr 👋 Happy to assign you! Let me know what you mean by the dashboard. As of now we actually don't have the page in question for applications for organizations. That should be at `pages/organizations/[id]/application`, which could be added into this issue? The other parts of that page are the discussion card components that are being worked on right now :) 

Let me know if there's something else you mean though! Nice to hear from you 😊

**Comment by rigojr** [comment]
Hi @andrewtavis, I thought that we have indeed a page were I can add this component and work on it.

I would like to make some questions about the design.
![image](https://github.com/activist-org/activist/assets/22437427/ca76a311-291e-4af5-8842-706eea8aa2ab)

- What does it represent those icons? Last three people that voted? or members of the organization?
![image](https://github.com/activist-org/activist/assets/22437427/9b15f3dc-d035-4b2a-862f-4982425143a0)

- I'm curious about how it works this poll section
![image](https://github.com/activist-org/activist/assets/22437427/900d8a12-0f8e-45fb-8efd-125af75d502b)
    - As the user vote with any of the two options, the client's component will let it know if the bottoms will be disabled or not.
    - The vote count should come as a prop, and it will change as soon as the client's component change it.
    - Why do we have two buttons? I'm curious if the user should have the ability to vote  ⬇️ , Will it be like reddit poll feature?

**Comment by andrewtavis** [comment]
Hey @rigojr 👋 Answers to your questions:

> What does it represent those icons? Last three people that voted? or members of the organization?

These are the organizations that have voted in favor. Whether votes against would be public is also a question, but as of now the thinking is that at least votes in favor will serve as a means to track sources of platform abuse later on.

> I'm curious about how it works this poll section

Admins of organizations would be able to use the up and down votes. Thinking about it though, maybe it's not quite explicit enough for something that has so much importance. We could also do buttons for `Vote in favor` and `Vote against` with the counts. 

> - As the user vote with any of the two options, the client's component will let it know if the bottoms will be disabled or not.
> - The vote count should come as a prop, and it will change as soon as the client's component change it.
> - Why do we have two buttons? I'm curious if the user should have the ability to vote ⬇️ , Will it be like reddit poll feature?

We do need to check if the user is an admin of an organization. If not, then we need a tooltip to tell them that they need these rights in order to vote. The votes would definitely be props, and potentially the organization could be directly passed to the page and then a call to the API would return the votes in favor or against.

Two buttons vs. one is a good question. We are going to be the final people to make the decision of whether they come on given the votes - at least until we figure out a system that people in the community feel is safe and would allow for a smoother process. We'll hopefully get there some day, but there's still lots to think about for that. The whole point though is that we need a barometer of gauging whether the community is ok with an organization, and if an organization has five votes in favor but 20 against, then that's a pretty clear indicator that it's something we need to think more than twice about and likely turn down. We should talk about whether the down votes should be public though. Ideally someone voting down would give some insights into their negative experiences, but then some people might be less likely to down vote if it's going to the public 🤔

Let me know if there are further questions! Fun chatting about this 😊

**Comment by andrewtavis** [comment]
Thanks for the PR, @rigojr! I figured out that we needed `fill:dark-text` on the outer div for it to work. Is something that normally needs to be done for icons that need fill instead of text. The rest of e94848f is just minor unrelated fixes that I noticed when I was looking at the about page 😊 Thanks so much for this! 

We'll have some backend APIs issues up soon, and let me know if you want to add some models to the backend! You could maybe add those for votes and then that'd give you some more awareness of the backend for when a more pressing issue comes along?

**Comment by rigojr** [comment]
Howdy, @andrewtavis sounds like a plan, I'd love to start working at the backend side.
