### ISSUE TITLE
Create ImageAppShield component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#464]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Note that this issue is producing something that's not going to be in use for likely a very long time. If someone would like to though, they'd be welcome to make the shield that we'll eventually use to link to the iOS, Android and F-Droid apps 🙃 The designs for this can be found on [here on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2394%3A8042&mode=design&t=jTUMfp3ZcqY6KqEK-1), with them further being found below:

![Web Badge](https://github.com/activist-org/activist/assets/24387426/6c15fad6-01b2-4be8-bc0f-ea81fd5b5296)

Generally this component could the code for [ImageGithubShield.vue](https://github.com/activist-org/activist/blob/main/frontend/components/image/ImageGithubShield.vue). We could also create a corresponding Grid component for it for later so we can easily put it on the landing page and other places. This can also be another issue though :)

### Contribution

Happy to support someone with interest in working on this! This is a great `good first issue` for someone new to activist, but is also open to current dev community members 😊

**Comment by Phil1999** [comment]
Hi @andrewtavis!

I'm completely new to the open-source environment and I'm looking to make my first contributions. I'd love to give this task a shot! Currently, going through getting my local setup up and running and reading relevant documentation for contributing.

**Comment by esslamben** [comment]
Would it be possible to work on this next?

**Comment by andrewtavis** [comment]
By all means, @esslamben! Please let me know if you need any help with this :)

**Comment by andrewtavis** [comment]
ed529de finishes this up, @esslamben! Appreciate all the hard work and that we were able to do a full review where you took the feedback and executed so well 🙏😊 As mentioned in the PR, we'll be making more issues soon, and it'd be great to have you pick one up!

**Comment by esslamben** [comment]
I'm such a muppet, I forgot to remove the JS on the app gird, my bad. Glad its all sorted, I will keep an eye out for new issue, thank you.

**Comment by andrewtavis** [comment]
Happens, @esslamben! Looking forward to the next one 😊
