### ISSUE TITLE
Create password strength indicator for sign up/in

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#469]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create a progress bar that indicates password strength for the sign up and sign in pages. The designs for this component can be found on the [Sign Up / Sign In page on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=3228%3A22748&mode=design&t=XWA4AC78DOv1Jeo0-1), and can be seen below:

![Password](https://github.com/activist-org/activist/assets/24387426/582b24ed-3848-4dc3-838a-c61ee1610afc)

This component would be active on the first password entry field for signing up and the password entry field for signing in to remind the user of the strength of their password. We'll need to find a Vue/TypeScript extension of some kind to check strings for password strength and then return a percent to the user as the bar being filled in and changing colors from red to yellow to green.

### Contribution

Happy to support someone with this issue!

**Comment by andrewtavis** [comment]
Ping @ahmedy00 who had interest in this 🙃

**Comment by GOWTHAM2K1** [comment]
hey I am new to hacktoberfest can I do it

**Comment by andrewtavis** [comment]
Thanks, @ahmedy00! Let me know if you need some support 😊

And please let me know if there's an issue you'd like to work on, @GOWTHAM2K1! Sorry for the confusion here. I literally started making the issue while we were on a call to split some work we're doing in #458, so this issue technically wasn't open.

**Comment by GOWTHAM2K1** [comment]
> Thanks, @ahmedy00! Let me know if you need some support 😊
> 
> And please let me know if there's an issue you'd like to work on, @GOWTHAM2K1! Sorry for the confusion here. I literally started making the issue while we were on a call to split some work we're doing in #458, so this issue technically wasn't open.

Thank you for the clarification, No worries about the confusion.

**Comment by andrewtavis** [comment]
I really have no idea what's up with those colors, @ahmedy00 🤔

**Comment by andrewtavis** [comment]
I think we can close this and I'll try to assign them directly via hexes later on.
