### ISSUE TITLE
Breadcrumbs component isn't wrapping to next line

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#475]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

As of now the [PageBreadcrumbs](https://github.com/activist-org/activist/blob/main/frontend/components/page/PageBreadcrumbs.vue) component doesn't break to the next line if one of the elements is long. This means that the breadcrumb navigation UI isn't clear, as can be seen on [events/123/about](https://activist.org/en/events/123/about) when the page width is very low. Ideally the elements would continue and break to the next line :)

This would be a great `good first issue` for someone who wants to start working on activist, and is also very open for current contributors 😊 Happy to help!

**Comment by esslamben** [comment]
Hey @andrewtavis I would like to give this a go

**Comment by andrewtavis** [comment]
Awesome, @esslamben! Assigning you now :) :) Please let me know if there's anything I can do to help 😊

**Comment by andrewtavis** [comment]
Closed via #478 😊 Thank you, @esslamben!
