### ISSUE TITLE
CI workflows are running on main, not branch

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#489]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Something that’s been noticed by myself and other contributors is that currently the workflows for the repository are running on the current main branch of the code and not the code of the branch for PRs. This is problematic as we’re getting passed tests that then lead to merged code that then leads to failed tests. Looking through the CI process and deriving what’s causing this is a high priority to assure that no new errors are being introduced :)

**Comment by andrewtavis** [comment]
Ping @rigojr :) Let me know if you have some ideas on this, and thanks for reporting! Also ping @to-sta who might have some ideas 😊

**Comment by to-sta** [comment]
In order to run on the pr branch we need to switch to pull_request but then we lose access to GitHub secrets and variables (for security reasons). 

In order to use pull_request we have to supply env. variables in another way. I will have a look into this.

**Comment by andrewtavis** [comment]
There's definitely more work to be done on testing, but I feel like this issue at the very least is closed at this point. We can reopen if there are further problems, and new issues for anything that's needed for mypy would be welcome 😊
