### ISSUE TITLE
Close meatball menu when a dropdown option is selected

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#49]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The meatball menu within [frontend/components/MeatballMenu.vue](https://github.com/activist-org/activist/blob/main/frontend/components/MeatballMenu.vue) is composed of two different Headless UI components. The first is a [menu](https://headlessui.com/vue/menu), and within that there are two [disclosures](https://headlessui.com/vue/disclosure) that then reveal buttons for changing the theme or language when clicked. When clicking one of the options the menu itself does not close like a normal menu would. This issue is to add this functionality :)

There is a section for Headless UI menus [closing-menus-manually](https://headlessui.com/vue/menu#closing-menus-manually) that likely would be a good reference for this.

### Contribution

I'd be happy to work on this eventually, but others are welcome to contribute or suggest solutions!

**Comment by Guilherme013S** [comment]
Sorry I'm new to contribute to open source, what steps I have to take to get the code in my machine and do these projects?

**Comment by andrewtavis** [comment]
Hi @Guilherme013S :) Thanks for writing! You'd be cloning the repo here `activist-org/activist`. There are [steps to install and run the environment](https://github.com/activist-org/activist#environment-setup-) in the readme 😊 Let me know if you have any questions 🙃

**Comment by andrewtavis** [comment]
You'd first need to fork this repository here with the button at the top right of your screen :) Happy to send along some learning resources for the technologies we use as well 😊

**Comment by andrewtavis** [comment]
One potential for this issue would be to trigger disclosures being closed with a variable on the `@click` of each of the buttons in the drop downs.

**Comment by purupurupu** [comment]
@andrewtavis 
Hello there! It's been a while. I was wondering if I could contribute to this issue?
Also, is this image right?

https://user-images.githubusercontent.com/63239000/232072171-26500cf0-5663-4036-b375-a12beaac4966.mov

**Comment by andrewtavis** [comment]
Hey @purupurupu! 👋 Not too long, and pleasure to hear from you again! :) We'd be happy to get some help with this issue. And yes, this is the component that I was discussing. To me my expectation would be that once you choose something the action occurs and the dropdown is closed, but as of now you need to select and then click outside. Any ideas that you have on this would be appreciated! Should be able to add some kind of trigger to the buttons to also close it.

**Comment by andrewtavis** [comment]
@purupurupu, weird thing is happening with this 🤔 It was working within my local version when I was using `docker-compose up`, but then it's now not working on the website itself... Behavior I'm getting is that the menu can also now not be closed. Can you maybe take a look at this? I'm not too stressed about it at the moment, but would be good to get this figured out 😊

**Comment by andrewtavis** [comment]
4dca565 reverted the changes in #99 so that the user can again close the menu by clicking outside of it. We can still see the old behavior in the [#99 deploy preview](https://deploy-preview-99--activist-org.netlify.app/). I guess I should have checked this before, but then it was working locally and this is the first time that different behavior was occurring between a local docker run and a Netlify preview 🤔

**Comment by purupurupu** [comment]
@andrewtavis 
Thanks for checking.
Sorry for the lack of confirmation, I didn't look at Netlify preview.

I've confirmed the phenomenon, so I'll take a look at it 🤔

**Comment by andrewtavis** [comment]
Hi @purupurupu! No stress whatsoever :) Good to know to always check the preview going forward! 

Hope you’ve been having a nice weekend! 😊

**Comment by andrewtavis** [comment]
Feel free to open a PR and we can check the preview together on any changes you want to try :) :)

**Comment by andrewtavis** [comment]
No stress whatsoever, @purupurupu! This is a really great help and something that’s very important to get done as RG e behavior is so weird. I already tried the preview myself and it’s working great! 😊 I’ll hopefully have some time today or tomorrow to check the code and merge :)

**Comment by andrewtavis** [comment]
Closed by #102 😊 Thanks again, @purupurupu! It's working soooo well! 🚀 So great to have this behavior at a more than presentable level :)
