### ISSUE TITLE
Backend fixture for superuser

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#491]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We also have to create a superuser for the django backend in order to access the django admin dashboard. 

Task:
Create a superuser fixture and adjust dockerfile to read the fixture everytime. 

### Contribution

I will work on this myself.

**Comment by andrewtavis** [comment]
Closed via #492. Thank you, @to-sta!
