### ISSUE TITLE
Fix @ts-ignore and @ts-nocheck errors

### ISSUE THREAD

**Issue by ahmedy00** [activist-org/activist#493]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Fix errors in @ts-ignore and @ts-nocheck comments in code base. Also, check for other bugs that do not have these comments but exist.

**Comment by ahmedy00** [comment]
@andrewtavis could you assign this to me? Also I will be work on this first before issue #469

**Comment by andrewtavis** [comment]
Thanks for offering to help on this, @ahmedy00! Let me know if you want to discuss any of the errors :) :)

**Comment by ahmedy00** [comment]
@andrewtavis, The problem with uuid imports was already solved with the commit sent for issue #260. I checked issue [WEB-61241](https://youtrack.jetbrains.com/issues?q=WEB-61241) about the IDE error when defining props with withDefault and realised that this is a jetbrains IDE bug. This bug has been fixed in the latest version. Maybe necessary to inform the dev's using these IDE's.
I would appreciate your feedback for any other changes I make.

**Comment by andrewtavis** [comment]
Thank you, @ahmedy00! We do have some development environment specific information in the readme and contributing guide for VS Code. Do you think we need to add some for JetBrains?

**Comment by ahmedy00** [comment]
@andrewtavis might be good :)

**Comment by andrewtavis** [comment]
Let me know if you have specific ideas 😊 Would also be fine to open a new issue for this specifically and then we can try to figure out what all should be added :)

**Comment by andrewtavis** [comment]
I tried to do a fix here and then needed to revert it, @ahmedy00. In `FormTextField` I'm getting `Argument of type '"blurred"' is not assignable to parameter of type '"update:modelValue"'.ts(2345)`. Similar for `'focused'`. Any ideas on these?

**Comment by ahmedy00** [comment]
@andrewtavis, we need to define `blurred` and `focused` keywords in define emit line, like that: 
`const emit = defineEmits(["update:modelValue", "blurred", "focused"]);`

**Comment by andrewtavis** [comment]
Thanks @ahmedy00! Did the trick :) Will send it along with some other changes I'm working on now 😊

**Comment by andrewtavis** [comment]
d2ff422 send along the change, @ahmedy00! Thanks for the quick suggestion!! 😊 Closing this up 🙌
