### ISSUE TITLE
Convert CardLegalDisclaimer to Headless UI disclosure

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#498]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue focuses on converting over [CardLegalDisclaimer](https://github.com/activist-org/activist/blob/main/frontend/components/card/CardLegalDisclaimer.vue) so that the opened field functions using [Headless UI Disclosure component](https://headlessui.com/vue/disclosure). This will add a lot of great accessibility functionality to the component and would make it more in line with other components we have that use Headless UI.

### Contribution

This is a great `good first issue` for someone wanting some experience with Tailwind and Headless UI. Would be happy to support! It's also of course available to the dev community if someone's looking for a new issue 😊

**Comment by bmartins-42** [comment]
Hello @andrewtavis 

Could you assign me this task

**Comment by andrewtavis** [comment]
By all means, @bmartins-42! Please let me know if you need any assistance! Should be pretty standard for you though 😊

**Comment by andrewtavis** [comment]
7a08617 finalizes this, @bmartins-42 😊 I thought it was best to have the whole thing as a button as before and to also allow the user to close it by clicking on the text. Also has the `focus-brand` now :) Seems to be working really well! Thanks for the support! 🚀
