### ISSUE TITLE
Convert PageSubPageSelector to Headless UI tabs

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#499]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would focus on converting over [PageSubPageSelector](https://github.com/activist-org/activist/blob/main/frontend/components/page/PageSubPageSelector.vue) to use [Headless UI tabs](https://headlessui.com/vue/tabs) so that we can more easily access the options via the keyboard for increased accessibility. The styling should generally remain the same, but we'd just use Headless UI to make this component more in line with others that make use of Headless. 

### Contribution

This is a great `good first issue` for someone who wants to work with Tailwind and Headless UI! Would be happy to support, and members of the dev community are also of course welcome to work on this 🚀

**Comment by andrewtavis** [comment]
@sayik, is this something you'd have interest in? Am realizing I screwed up the original scope here as we should be using Headless to make sure everything's accessible. Would be a good opportunity for you to check out this library and build on the past issues 😊 We can also do the backend one as well :) Just lemme know 🙃

**Comment by nicholas-vecchio** [comment]
Hello! I am not sure if I am misunderstanding something or if the components have changed but the MenuTopBar component seems to not longer exist? Apologies if I'm simply confused.

**Comment by andrewtavis** [comment]
Hey @nicholas-vecchio 👋 Sorry for the confusion. Had a call yesterday and realized that this component also wasn't particiularly well named. Updated the issue to reflect that we're talking about [PageSubPageSelector](https://github.com/activist-org/activist/blob/main/frontend/components/page/PageSubPageSelector.vue) 😊 Would you want to work on this?

**Comment by nicholas-vecchio** [comment]
Yes I would @andrewtavis ! Thank you for the clarification.

**Comment by andrewtavis** [comment]
Thanks for checking for clarification, @nicholas-vecchio! Assigned :) Please let me know if you need any support!

**Comment by nicholas-vecchio** [comment]
Hello again @andrewtavis. Just for clarification, did you want to simply use the tabs for increased accessibility, and still have selecting the tabs route to a page link. Or would you simply like to use the TabPanels. Thank you again.

**Comment by andrewtavis** [comment]
This is a good question, @nicholas-vecchio! I'd say that generally the increase in accessibility is worth it. What's your opinion on the usability of having a route vs. just a tab that we switch to on a shared route? 

I think both are fine, and the purpose of this component would fit with either. The former wouldn't be using the full extent of the Headless component in that we'd want the user to switch with the arrows and then hit return to go to the route, whereas the latter would take them to the tab directly. 

On a baseline I always consider that it's best to have a route. Easier for people to share specific parts of the platform, and also easier for us in development to share a place where there might be an issue rather than "go to this page and then it's tab XYZ". Plus adding routes with Nuxt is super easy - just sub directories and a default page within. 

Again, thanks for asking!

**Comment by nicholas-vecchio** [comment]
I believe it is possible to control the tabs manually, meaning that if the user moves to the tab and clicks enter, you can write a function to control the behavior of changing the tab. Using the router I could then use router.push('url') to go to the appropriate page.

This approach should work but it would mean using the router instead of the built-in NuxtLink. 

Would there be any issues with using the router itself to push? Thank you @andrewtavis.

**Comment by andrewtavis** [comment]
Keeping it with `NuxtLink` would be important so we maintain the localization route, unless there's a good way to implement that with `router.push('url')`. Do you think that's the case, @nicholas-vecchio>

**Comment by nicholas-vecchio** [comment]
Yes! I believe by making use of useNuxtApp() it would be possible to push to the localePath despite being done outside of the NuxtLink, @andrewtavis .

**Comment by andrewtavis** [comment]
Sounds great, @nicholas-vecchio! Let's go with different routes then :) Feel free to start working on a PR 😊

**Comment by andrewtavis** [comment]
b6502de does some minor fixes, @nicholas-vecchio 😊 Thanks for the help here! I'll be making more issues tomorrow. Would be great to work with you again, so let me know if one's of interest!
