### ISSUE TITLE
Testing API Rate throttling

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#505]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

With PR #421, we merged the settings for drf [rate throttling](https://www.django-rest-framework.org/api-guide/throttling/). The task here is to create tests for the rate throttling settings.

This issue is blocked till PR #496 is merged or another solution for test data is implemented.

This issue is part of our testing efforts and the discussion in #432.

### Contribution

I am happy to help and support someone on this issue.

**Comment by to-sta** [comment]
@sulabhkatila would you like to work on this issue, since you already started implementing the tests in #421.

**Comment by sulabhkatila** [comment]
> @sulabhkatila would you like to work on this issue, since you already started implementing the tests in #421.

I'd love to!

**Comment by andrewtavis** [comment]
Thanks @to-sta for the issue, and thanks @sulabhkatila for jumping in to work on this! 😊

**Comment by andrewtavis** [comment]
#496 is merged, so we're good to go with this 🚀

**Comment by andrewtavis** [comment]
Ping @KyryloKaralyus :) This is the issue I was talking to you about where we're starting with testing for the backend. We can also discuss here what other issues can be opened and go from there 😊

**Comment by andrewtavis** [comment]
Finalized by #573 🚀 Thanks @sulabhkatila and @to-sta!
