### ISSUE TITLE
Transfer mypy settings to pyproject.toml

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#513]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We use [mypy](https://mypy.readthedocs.io/en/stable/index.html) for static type checking in the backend. For backend package configurations we use the pyproject.toml file and since mypy supports pyproject.toml we can transfer the settings. 

Use offical documentation for [guidance](https://mypy.readthedocs.io/en/stable/config_file.html#example-pyproject-toml).

Make sure to test your changes with running mypy in the backend directory. (cmd: `mypy .`)

### Contribution

Happy to help someone with this task

**Comment by sinderoth** [comment]
can give this a try

**Comment by andrewtavis** [comment]
Thank you, @sinderoth! Let us know if there's anything we can do to help 😊

**Comment by andrewtavis** [comment]
Closed via #516 with some minor formatting in f8d8368 :) :) Thanks for all the work here @sinderoth!
