### ISSUE TITLE
Switching backend formatter from black to ruff

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#514]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Ruff just release a new version that includes a python formatter. 

Short summary from the [announcment](https://astral.sh/blog/the-ruff-formatter?utm_campaign=Django%2BNewsletter&utm_medium=email&utm_source=Django_Newsletter_203):
> TL;DR: The Ruff formatter is an extremely fast Python formatter, written in Rust. It’s over 30x faster than [Black](https://github.com/psf/black) and 100x faster than [YAPF](https://github.com/google/yapf), formatting large-scale Python projects in milliseconds — all while achieving >99.9% Black compatibility.

Switching from black to ruff will increase the speed (its blazing fast🔥) what can reduce our workflow time in the future. Since we use black in pre-commit hooks it will also reduce time for every contributor. Other benefits are leaner config files and one less dependency. 

Task:
- test compatibility
- update requirements-dev.in and requirements-dev.txt
- adjust github workflow and pre-commit config

### Contribution

Will work on this myself :smile

**Comment by andrewtavis** [comment]
Closed by #515 😊 Thanks @to-sta! Such good tooling! 🙌
