### ISSUE TITLE
Add functionality to add dot markers to dates on MediaDatePicker

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#522]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Functionality that's needed for [MediaDatePicker](https://github.com/activist-org/activist/blob/main/frontend/components/media/MediaDatePicker.vue) is the ability to pass a set of dates and have those dates be marked as little circles on the date picker dates. This is  available via the [attributes of v-calendar](https://vcalendar.io/calendar/attributes.html). We'd need to provide a prop for the dates to be marked and then have them be reflected. This issue would be finished by passing today's date to the component by default and having it be reflected as a dot on [activist.org/home](https://activist.org/en/home).

### Contribution

Happy to support someone who wants to work on this!

**Comment by andrewtavis** [comment]
Note that for this we may need to update the component from a date picker to a calendar and change the file name and it's reference on `/home` accordingly :)

**Comment by PabloSSena** [comment]
Hello, I'd like to work on this

**Comment by andrewtavis** [comment]
Hey @PabloSSena! Thanks for your interest in activist and the offer to help 😊 I'll assign you now, and please let me know if there's anything we can do to help :)

**Comment by PabloSSena** [comment]
Hello @andrewtavis i'm in doubt about one thing in this issue, i have to import the set of dates that will appear in the calendar from somewhere (Like the user events) or just to create the prop and put some dates there to test it?

**Comment by andrewtavis** [comment]
Hey @PabloSSena :) Just creating a prop to test it would be fine - say have a dot under today's date. And definitely keep in mind that the date picker might need to switch to a calendar for this so we can get the dot. Not sure if the date picker has one. 

Let me know if there are further questions!

**Comment by PabloSSena** [comment]
okayy thanks :D

**Comment by andrewtavis** [comment]
Welcome! Looking forward 😊

**Comment by andrewtavis** [comment]
Hey @PabloSSena 👋 Let me know what your thoughts are to switching this one to a calendar component from v-calendar (i.e. can we get the dots in the date picker?). We could then rename it as `MediaCalendar`. I just made #559, which I think is more in line with a typical date picker as we'll have the time as well and won't have the dots for this one to keep the UI clean.

**Comment by andrewtavis** [comment]
You'd be welcome to work on that issue after this one if you'd have interest!

**Comment by PabloSSena** [comment]
Hello @andrewtavis, I'm trying to switch the DatePicker to a Vcalendar because in the docs says that the dots can be done only in the calendar, but when I switch to Vcalendar the calendar doesn't show up in the home page, I'm trying to figure out why, I'm hopping i can finish this task in this weekend

**Comment by PabloSSena** [comment]
I have interest in working on #559 after this one!!!

**Comment by andrewtavis** [comment]
Great, feel free to write in the issue and I'll assign you 😊

**Comment by PabloSSena** [comment]
hey @andrewtavis, I created a PR for this but forgot to send some pictures, this is how it's looking like 
![calendar](https://github.com/activist-org/activist/assets/58041720/531132e8-9ef0-4c93-bdb1-b2176b2c1e37)

Let me know if you want me to change something

**Comment by andrewtavis** [comment]
Is looking great, @PabloSSena! I'll try to get to the review in the coming days :) :)

**Comment by andrewtavis** [comment]
Closed via #567 🚀 b4d3beb does the switch to orange as I mentioned in the review, @PabloSSena :) We can go through and edit the styles a bit more later on so they match the design system more exactly, but for now getting the base color right is enough :)
