### ISSUE TITLE
Sidebar type not correctly loading for page type (edit: needs a11y controls)

### ISSUE THREAD

**Issue by wkyoshida** [activist-org/activist#532]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

I've noticed that the sidebar type is not loading the correct type if navigating from within the platform. For instance, say we open up the `Events Home` page:

![image](https://github.com/activist-org/activist/assets/15043193/cf456ea4-d3b0-4f90-af3b-b7ce827ded49)

The sidebar shows the specific sidebar for events. However, if we were to navigate to `Organizations Home` from within the platform, e.g. clicking on `Organizations` in the sidebar:

![image](https://github.com/activist-org/activist/assets/15043193/a802a513-7277-4e53-86ad-351aed7975e0)

The sidebar remains as the sidebar type for events. Reloading the page though, actually loads the correct sidebar for the page:

![image](https://github.com/activist-org/activist/assets/15043193/7bd085ad-4424-4560-89c5-e8a966f864b6)

This is likely due to how `sidebar` is set up as a Nuxt layout, which I believe does not do a reload for every page. The fix might involve perhaps something simply as computing the route path on the layout-level so the layout knows to reload, not 100% sure.

I believe this issue would be somewhat related to:
- #346
- #354

**Comment by andrewtavis** [comment]
Thanks @wkyoshida! Ya I was thinking that we'd cover this in #346, but we can leave this open to make sure the fix there addresses this as well 😊

**Comment by andrewtavis** [comment]
The issues in question were taken down by @Robert-Kovalcuk 🥳 Last thing that's needed here is that the page is not updating for mobile when we select an option from the dropdown using the keyboard. Let's get this done before Saturday! I can take a look as well, but let me know if you want to check it out, @Robert-Kovalcuk 😊

**Comment by Robert-Kovalcuk** [comment]
@andrewtavis I will have a look

**Comment by andrewtavis** [comment]
Assigning now, @Robert-Kovalcuk :) Thanks for checking this out!

**Comment by andrewtavis** [comment]
Hey there @Robert-Kovalcuk 👋 How are you doing? Let me know if you're free for a call to chat this and the other issues sometime 😊 Hope all's well!

**Comment by andrewtavis** [comment]
Some notes on this:
- This is specifically because we're in a layout that loads in the sidebar, where the page content is changing, but there's no update of the sidebar aside from the variables that determine what is highlighted
- This is good as it keeps page loads quick
- Switching over to something that's based on a watcher of a route change makes it wayyy slower...
- So we basically get the initial route's sidebar and stick to it

**Comment by andrewtavis** [comment]
Some further information on how this might be solved is [onBeforeRouteLeave](https://router.vuejs.org/guide/advanced/composition-api#Navigation-Guards), which is triggered before a page is changed like so:

```ts
onBeforeRouteLeave((to, from) => {
  alert("Hey! Listen!");
});

```

Specifically though, this can only be used on pages within the `page` directory, components that are used in this directory or within utility TS functions that are then loaded directly onto pages. With this we could derive the page we're going to and emit this to the sidebar to update it :)

**Comment by andrewtavis** [comment]
Alrighty then! 😊 0beb7b6 in all its glory closes this. This along with the work in #831 has us where we need to be as far as navigation is concerned. There's a whole system for this that likely needs to be improved, but in short when we navigate away from any page we emit the page that we're going to, and computed variables within the left sidebar and navigation dropdown then pick up the route and change their props accordingly to show the correct index. Filters are still not in use, but we'll get to those once search is a priority :)

Thanks all!
