### ISSUE TITLE
Create tests for Swagger endpoints in Back End

### ISSUE THREAD

**Issue by keythroy** [activist-org/activist#533]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Create test cases for the Swagger UI endpoints using [PyTest](https://docs.pytest.org/en/7.4.x/). The files should be placed in the folder backend/backend.

### Contribution

I will be happy to work on this issue 👍

**Comment by andrewtavis** [comment]
Thanks for the issue, @keythroy! Please let us know if there's anything we can do to support :)

**Comment by andrewtavis** [comment]
Closed by #534 :) Thanks so much for taking this from start to finish, @keythroy! Hope to see you at the sync on Saturday! 😊 There will be more issues by then 🚀
