### ISSUE TITLE
Links leading to http are not redirected to https

### ISSUE THREAD

**Issue by Solar-Simon** [activist-org/activist#542]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

http://actvist.org/ does not work in mozilla firefox 119 64 Bit Win10
happened here:
https://techfrombelow.de/2023-05-11/

**Comment by Solar-Simon** [comment]
arg sorry, its a wrong spelling at techfrombelow.
Maybe let them know and please delete issue

**Comment by andrewtavis** [comment]
Thanks @Solar-Simon! Just let them know about it :) :)
