### ISSUE TITLE
Documentation for JetBrains IDEs

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#545]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Most of the documentation that we have for activist is for VS Code. This issue would look to add in steps to set up JetBrains IDEs, with information being added to the readme and the [contributing guide](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md).

### Contribution

@Robert-Kovalcuk had mentioned that this was something he could help with 🙃 Would be great if others had suggestions!

**Comment by Robert-Kovalcuk** [comment]
I can work on this, I'll try to mimic the structure of VS code setup suggestion that's in the guide, I haven't seen it just yet

**Comment by andrewtavis** [comment]
Sounds great, @Robert-Kovalcuk :) You can check the current docs [here](https://github.com/activist-org/activist#environment-setup-). Doesn't have to be too expansive :)

**Comment by andrewtavis** [comment]
Hey @Robert-Kovalcuk 👋 ebf9ebd sends along some very minor instructions for getting WebStorm set up :) Closing this, but let me know if you'd add anything else!
