### ISSUE TITLE
Expand backend via new schemas

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#547]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The [backend schemas](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=5377%3A33014&mode=design&t=5FarwjDYK69FNj7p-1) were recently expanded with some new tables including those for tags and votes. Although not a priority for the MVP, the models for these tables could be added to the backend :)

### Contribution

Would be happy to support someone on this! This is a `good first issue` as it can be based off of models that are already there. Sending multiple PRs is also ok 😊

**Comment by andrewtavis** [comment]
@sayik, you'd mentioned this might be of interest? Let me know 🙃

**Comment by sayik** [comment]
Hi @andrewtavis I'd like to work on this. Looking forward to code night.

**Comment by andrewtavis** [comment]
Great, @sayik! Assigning you now :) See you then 😊

**Comment by andrewtavis** [comment]
Tables we could add for this issue:
- Tag tables
- Discussion tables
- Vote tables

**Comment by andrewtavis** [comment]
Hey @sayik 👋 We're going to check this on Saturday as there were some things that weren't included in the schemas, and mixins were also applied incorrectly in some cases beforehand. Hope to see you in the sync and we can work on this together!

**Comment by sayik** [comment]
Will see you on Saturday 🙂, looking forward to dev sync.

**Comment by andrewtavis** [comment]
Heyo @to-sta 👋 The [schemas](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=5377%3A33014&mode=design&t=E1e23fOs8lygKJmO-1) have been updated given what we discussed in the sync. What's been changed:

- We now have "main tables" in there that have lighter grey header/footer pieces so it's easier for us to find tables like `organization`, `event`, etc
  - This is something I thought of for coloration to make it more navigable, and we can do the next bit of indicating which are not implemented after this!
- The `location` table has been linked to others
  - Still not sure what other covariates should go in here besides `name`
  - Coordinates? (latitude and longitude, and then remove them from the `event` table?)
  - Suggestions here would be appreciated!
- The `image` table has been linked to others
- `uuid` has been put in for type for all fields that will have their own pages :)

Let me know if there are further questions on this! And again suggestions for the location table are welcome!

**Comment by andrewtavis** [comment]
Also did a quick coloration for `Not implemented` that just darkens the header and footer of the table. To my knowledge/checks this should apply only to `discussion` and `vote` tables, but we can also potentially just put those in as `discussion` tables will be used before `task` tables that have already been implemented.

**Comment by andrewtavis** [comment]
Closed via #610 🚀 Thanks for the work on this, @to-sta, and thanks all for checking the values in the last sync!
