### ISSUE TITLE
Add deselect to FormRadioGroup

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#551]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The [form-radio](https://github.com/activist-org/activist/tree/main/frontend/components/form/radio) components are used for things like the days ahead component on the platform that can be seen on [events/search](https://activist.org/en/events/search/). One thing that's needed is for us to be able to deselect the option and thus remove the filter. Refactoring this component with [Headless UI's radio group](https://headlessui.com/vue/radio-group) would also be a good step, but we'd again need to check to make sure that we can add in deselect functionality.

### Contribution

Happy to support someone who wants to work on this or get to it myself eventually! 😊 This is a `good first issue` that would be great for someone wanting to join the activist community :)

**Comment by Afeayo** [comment]
Hi, I am intrested

**Comment by andrewtavis** [comment]
Hey @Afeayo 👋 Thanks for your interest in helping out :) Can you do a quick check of [Headless UI's radio group](https://headlessui.com/vue/radio-group) to see if we can do a deselect and then we can decide if we can use that? If not we can also edit the current component 😊

**Comment by andrewtavis** [comment]
Hey @Afeayo 👋 Just checking in on this 😊 Is there anything I can do to help? Would be happy to check if we can do the deselect and then you can implement?

**Comment by andrewtavis** [comment]
Hey @Afeayo 👋 Will close this as I'll take up these changes with others for the filters in #597. Thanks for your interest and let us know if you'd like to pick up another issue in the future!
