### ISSUE TITLE
Create CardFAQEntry component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#552]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This is a very important issue that would be good to finish sooner rather than later. We've recently finished the designs for how FAQ entries will function, with the decision being that we'll do disclosures. Designs for this component can be seen on Figma [here](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=7088%3A92710&mode=design&t=hbrmPFJFE6NT0uV9-1) and further are pictured below:

![FAQ Question](https://github.com/activist-org/activist/assets/24387426/279f7daf-d270-4afa-a272-9997fb1eceaa)

We'd use [Headless UI disclosure](https://headlessui.com/vue/disclosure) for this, with one usage of this already being present on activist for the [CardLegalDisclaimer](https://github.com/activist-org/activist/blob/main/frontend/components/card/CardLegalDisclaimer.vue) component.

### Contribution

Happy to support someone who wants to work on this! 😊 This is a great `good first issue` for someone wanting to contribute to the activist community! 🚀

**Comment by andrewtavis** [comment]
Big thing for this is that we have the Tailwind class `card-style` :)

**Comment by mattburnett-repo** [comment]
writing in here

**Comment by andrewtavis** [comment]
Thanks, @mattburnett-repo! Let me know if there's anything I can do to help :)

**Comment by andrewtavis** [comment]
Hey @mattburnett-repo 👋 Checking in to see if there's anything I can do to support on this :) Hope you're well!

**Comment by mattburnett-repo** [comment]
hey @andrewtavis Thanks for checking in. I've been really ill the past week and have fallen behind on a lot of things. I'll try to get this done before the weekend.

**Comment by andrewtavis** [comment]
Sorry to hear that you've been unwell, @mattburnett-repo! 🍵🌿 Take your time :) Just checking in 😊

Hope to see you for the sync on Saturday!

**Comment by andrewtavis** [comment]
b154659 finalizes this, @mattburnett-repo :) As expected I just needed to add in `w-full` and the a11y formatting worked fine 🥳 Also did some minor changes to add in a loop so we're ready for the backend and give the entries some spacing. 

Thanks for this!

As for as next issue, maybe we can just write about it here :) What might be good to look into would be:

- https://github.com/activist-org/activist/issues/580 (would use the new modal that we were talking about in the sync that will be in with #595)
- https://github.com/activist-org/activist/issues/369 (would be a big help as we need to get some kind of a captcha in soon, and there's been some research for this done already by another contributor)

Let me know if either of those sound good! You'd be welcome to write in either and I can then assign 😊
