### ISSUE TITLE
Add modal to MediaImageCarousel 

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#553]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We already have the component for displaying images on organization pages in [MediaImageCarousel.vue](https://github.com/activist-org/activist/blob/main/frontend/components/media/MediaImageCarousel.vue), but one thing that's needed is a functioning expand to modal button in the top left corner that opens the issues in a similar way that components in the [modal](https://github.com/activist-org/activist/tree/main/frontend/components/modal) directory function. This would open the swiper over the screen with a slight blur as with other modals. Cleaning up the component so it matches [the designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2642%3A20983&mode=design&t=hbrmPFJFE6NT0uV9-1) a bit more could also be a great contribution.

### Contribution

This issue is a bit more difficult, but would be a `good first issue` for a more experienced developer :) Happy to support or get to it myself eventually! 😊

**Comment by nicholas-vecchio** [comment]
Hello Andrew! I would like to be assigned this issue.

If I understand correctly, you want a modal to be added so that the media image carousel can be expanded and come to the fore-front while blurring the rest of the page content? Thank you.

**Comment by andrewtavis** [comment]
Hey @nicholas-vecchio! Thanks for your interest in this one. You described it exactly as it should function, and feel free to reference the [modal](https://github.com/activist-org/activist/tree/main/frontend/components/modal) directory where our other uses of [Headless UI modal](https://headlessui.com/vue/dialog) are :)

Let me know if there are further questions or if I can help somehow!

**Comment by andrewtavis** [comment]
Hey @nicholas-vecchio, just btw, there's been some progress on this and we now have a BaseModal component from #582 that could help with this. Let me know if you have any questions!

**Comment by nicholas-vecchio** [comment]
Thank you for the update @andrewtavis! Apologies for taking so long to progress on this issue.

**Comment by andrewtavis** [comment]
No stress whatsoever, @nicholas-vecchio! Let me know if you need anything from my end :)

**Comment by andrewtavis** [comment]
Hey @nicholas-vecchio 👋 Let me know if there's anything we can do to support on this :) Hope you're well!

**Comment by nicholas-vecchio** [comment]
Hello! I apologies for disappearing off the face of the earth, life happens sometimes.

Next time I'll do my best to give an update before 5 months passes. :D 

The modal is working, right now just getting the design to match the figma designs :)

**Comment by andrewtavis** [comment]
No stress on it, @nicholas-vecchio! Looking forward to the PR when it comes along 😊😊

**Comment by andrewtavis** [comment]
Closed in #764 😊 Thanks @nicholas-vecchio! 🥳
