### ISSUE TITLE
Add Ngnix Docker container

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#555]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add a container and process via Docker to get [Ngnix](https://www.nginx.com/) up and running for the eventual deployemtn.

### Contribution

Happy to support with this if needed. @momanyisamuel mentioned that this would be of interest 😊

**Comment by to-sta** [comment]
Should we include a path to the backend admin site?

**Comment by andrewtavis** [comment]
Makes sense to me :)

**Comment by andrewtavis** [comment]
Just checking on this one, @wkyoshida, we don't need this anymore, right?

**Comment by wkyoshida** [comment]
Yup! We should be good already

We could also do @to-sta 's idea above too, but I'd say that's beyond the scope of this issue. I'll look into it this week along with the other deployment stuff.
