### ISSUE TITLE
Allow MetaTag and specifically MetaTagOrganization to accept more than one organization

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#557]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As events on activist are able to be hosted by more than one organization, we need the [MetaTagOrganization.vue](https://github.com/activist-org/activist/blob/main/frontend/components/meta-tag/MetaTagOrganization.vue) to be able to take more than one organization as an argument. This would require edits also to the base [MetaTag.vue](https://github.com/activist-org/activist/blob/main/frontend/components/meta-tag/MetaTag.vue) component. An example of how this should work is found on the Figma designs [here](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2578%3A14210&mode=design&t=hbrmPFJFE6NT0uV9-1). With two organizations passed both should be listed, and if the number is three then just icons, and more than three then the first three icons with `(+ X more)` for the others.

### Contribution

Happy to support someone or work on this myself! This is a great `good first issue` for someone wanting to get into the community, and is of course welcome to current contributors 😊

**Comment by keythroy** [comment]
I'd like to work on this issue

**Comment by andrewtavis** [comment]
In discussing this in Code Night, it would be great if we actually switch the base component of MetaTag over such that the value is `string[]`, and then the other meta tags are passing an array of length 1. From there we can make the following changes:

- In [MetaTagOrganizations](https://github.com/activist-org/activist/blob/main/frontend/components/meta-tag/MetaTagOrganization.vue) we instead have `organizations` that's an array for a prop
- In [CardAbout](https://github.com/activist-org/activist/blob/main/frontend/components/card/CardAbout.vue) when we are assigning the organization for the event, this need to be switched to `MetaTagOrganization` at [this line](https://github.com/activist-org/activist/blob/f84910bc3cab2b282352ac9ea9c543c71f32457b/frontend/components/card/CardAbout.vue#L19)

**Comment by andrewtavis** [comment]
4aeb58e does some final fixes for this, @keythroy :) Just makes sure that all event instances are `organizations`, adds some padding between the tags, and makes the icons a bit bigger 😊

Thanks for the work here! Let's keep this in mind that we'll need to add in the ability for these tags to link to their entities eventually. Maybe something we could do is link them all to a dummy page for now? Let me know what you think and we can maybe make an issue!

Closed via #566 🚀
