### ISSUE TITLE
Add `isHighRisk` prop to CardDiscussionInput

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#558]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

One of the features that activist will have to keep people safe is to warn people who are using our open discussions about the risks involved. We need to add a property to [CardDiscussionInput.vue](https://github.com/activist-org/activist/blob/main/frontend/components/card/discussion/CardDiscussionInput.vue) that changes the UI of the component to warn users when they mark themselves as high risk or are in high risk organizations. Designs for this can be found below:

![Discussion Input](https://github.com/activist-org/activist/assets/24387426/48a11279-093d-451b-a407-8c3856c1d684)

Feedback for this functionality has been resoundingly good 😊

### Contribution

Happy to support someone on this! This is a great `good first issue`, but those already in the community are also of course welcome to pick it up! 🚀

**Comment by mahasultan** [comment]
@andrewtavis I'm interested in this issue, could you please assign it to me for a university group project

**Comment by andrewtavis** [comment]
Hey @mahasultan! Thanks for your interest and willingness to help 😊 World be so great to get this done as it's something that folks are definitely buying into. I'll assign you, and please let me know if there's anything I can do to help!

**Comment by andrewtavis** [comment]
Hey @mahasultan 👋 Just FYI I wrote the wrong component at the start :) It should be [CardDiscussionInput.vue](https://github.com/activist-org/activist/blob/main/frontend/components/card/discussion/CardDiscussionInput.vue) 😊

**Comment by andrewtavis** [comment]
And I just sent along a minor change to that component, so be sure to pull :) :)

**Comment by shahad1307** [comment]
Hello @andrewtavis, I'm working on the same issue with @mahasultan @Reyali619 @fatimaj21 could you please assign me !

**Comment by Reyali619** [comment]
Hey @andrewtavis, 

I would like to be assigned to this issue along with @mahasultan, @fatimaj21 & @shahad1307, as we will all work on the same issue.

Please let us know.

**Comment by fatimaj21** [comment]
Hello @andrewtavis, I'm working in the same group as @mahasultan @Reyali619 @shahad1307 could you please assign me as well !

Looking forward on working on this!

**Comment by andrewtavis** [comment]
All assigned! Let me know if you all need any assistance :)

**Comment by andrewtavis** [comment]
96636b0 closes this with minor formatting edits and a rework of how focus will be handled via #548 :) Thank you @mahasultan, @shahad1307, @Reyali619 and @fatimaj21 for the contributions! Looking forward to the work in #588 😊
