### ISSUE TITLE
Create date picker component for event creation flow

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#559]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would use [v-calendar](https://github.com/nathanreyes/v-calendar) to create a date and time picker for the event creation flow. This ultimately will be housed in a `CardDatePicker` component, which eventually will include a timeslot component, but for now will not. Designs for this can be seen [on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2001%3A1299&mode=design&t=hbrmPFJFE6NT0uV9-1) and can also be seen below:

![Time Inputs](https://github.com/activist-org/activist/assets/24387426/f0deffaa-5127-4e8d-8742-821a601d3fd1)

Again the time slot selection is not necessary at this time :)

### Contribution

Happy to support someone or work on this myself! Let's discuss how best to implement this, with it likely being best that we have the data picker in a component that then is used in the card 😊

**Comment by PabloSSena** [comment]
Hello @andrewtavis, please assign me to this one :D

**Comment by andrewtavis** [comment]
Nice @PabloSSena! Thanks for jumping on multiple issues! 😊

**Comment by PabloSSena** [comment]
Hello @andrewtavis, the calendar needs to be exactly how it looks like in the figma project? because I saw in the Vcalendar docs that they have a model that attends what we want but it look like this 
![image](https://github.com/activist-org/activist/assets/58041720/319d797d-0be9-408b-8571-cec03f445ec8)

**Comment by andrewtavis** [comment]
Hey @PabloSSena 👋 Let's do out best to style it, but for an initial implementation it's totally fine to use the base structure as it is there :)

**Comment by PabloSSena** [comment]
Okayy I'll do my best here

**Comment by andrewtavis** [comment]
Don't stress too much about it, @PabloSSena :) Big thing is getting the colors right so it's working with the rest of the page elements. We can figure out more exact styling later 😊

**Comment by PabloSSena** [comment]
hello @andrewtavis, what i got untill this point is looking like this 
![image](https://github.com/activist-org/activist/assets/58041720/762e09ad-dff9-40f6-9233-6d4bf6455f7a)

**Comment by andrewtavis** [comment]
Looking good so far, @PabloSSena! We should be ready for a PR soon and we can then discuss functionality? We can remove the 13th/14th highlights from this one and also the dot, as I don't think we'll need this for this component :) Is this using calendar instead of date picker for v-calendar, btw? Just checking as I think I remember that the dots could only go on calendars.

**Comment by PabloSSena** [comment]
yess we can disscus the funcionality, I was doing the template already thinking on how I was going to make it work, about the dots, i started the code using Vcalendar and then when i changed to datePicker the dots continued there, i don't know how this is working lol 
![image](https://github.com/activist-org/activist/assets/58041720/960db1c2-5705-4f9f-afc9-5c2e917f7783)

**Comment by PabloSSena** [comment]
@andrewtavis I opened a PR, if you want something to change just tell me

**Comment by andrewtavis** [comment]
fd75503 has us almosttt done on this, @PabloSSena :) Only thing now is the selection colors are off for the dates after they're clicked. Maybe was in something that I deleted as I was trying to get us to using Tailwind as much as possible for this component. The new version can be found at [activist.org/events/create](https://activist.org/events/create). I also simplified how we're defining light and dark mode for this component and the calendar so we don't need to do the conditional loads anymore 😊

Do you want to try to figure out the last coloration issues for this, or should I look at it a bit more?

**Comment by PabloSSena** [comment]
Hi @andrewtavis, sorry for the late response, i will take a look at the coloration problem, i noticed that the calendar is coming transparent, do you want me to take a look at this too or leave it like this?
![image](https://github.com/activist-org/activist/assets/58041720/3f48545d-cbb3-4cd0-81bf-a6481613c6ce)

**Comment by andrewtavis** [comment]
Hmmmm, interesting @PabloSSena. It's showing up for me, so maybe try pulling the most recent changes?

**Comment by andrewtavis** [comment]
But ya foxes for the calendar colors in general would be great!

**Comment by PabloSSena** [comment]
Hello @andrewtavis I was trapped with come things from college so i wasn't working on this,  but i'm planning to already resolve this today, so tomorrow i can go to our other issue

**Comment by andrewtavis** [comment]
Sounds good, @PabloSSena! I'll check it out 😊 Seems like a solid change to me and matches the date picker. Maybe we'll customize it a bit later, but at least both are changing from the same state :)

**Comment by andrewtavis** [comment]
Resolved by #603 and ab424e8 😊 Thanks @PabloSSena! Looking forward to jumping into #560 now! 🚀
