### ISSUE TITLE
Add event creation flow

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#560]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add in the event creation flow that populates the backend. Designs for this can be seen in the top [prorotype on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2001%3A1299&mode=design&t=hbrmPFJFE6NT0uV9-1) (the one for UNLOCK accelerator). Not all components for this finished at this time, with specifically #559 being a separate issue. 

### Contribution

I'd be happy to work on this or support someone who has interest! 😊 This is a needed flow for release, so getting to this sooner rather than later would be important 💪

**Comment by PabloSSena** [comment]
Hello @andrewtavis i'm interested in this issue but i'm a bit confused about what is to do exactly, it is to implement only the front-end or also the back-end

**Comment by andrewtavis** [comment]
For now just the front end, @PabloSSena :) I can maybe make the routes and the basic buttons at the bottom for navigation and you can add in the other parts for the pages?

**Comment by andrewtavis** [comment]
Will get to that later today, @PabloSSena :)

**Comment by PabloSSena** [comment]
I don't think I will be able to work on this today, but i can start tomorrow

**Comment by andrewtavis** [comment]
Ok, @PabloSSena :) fd75503 added in [activist.org/events/create](https://activist.org/events/create). I changed the designs to not have multiple pages, as I think we'd be fine to have all of this be in one form that transitions from "page" to "page" as the user clicks through. What do you think about this rather than separate pages?

**Comment by PabloSSena** [comment]
Hi @andrewtavis, one more time sorry for the late response,I agree that only one form is better, I worked in a place that we did something very similar to this but we used angular, i can't imagine how to this in vue without studying a little more

**Comment by andrewtavis** [comment]
No stress, @PabloSSena, we have time on this 😎 I'd say we could just do a conditional rendering of the page with `v-if` based on some conditions of the fields being filled out then allowing the buttons at the bottom to be pressed which then triggers a "page" where the next content is brought in from the right. How does this sound? Let's also note that we need some sort of indication to the user that they can go to the next page, which might just be changing the color of the arrows, but that might not be apparent enough given their size.

**Comment by andrewtavis** [comment]
Yes we can change the color of the arrow and the associated string :) That sounds great to me! We'd just need a Boolean for whether all the elements are filled out, and then we can set a conditional class for Tailwind properties with `:class="{}"` with the conditional class assignments inside 😊

**Comment by andrewtavis** [comment]
Hey @PabloSSena 👋 Let me know what the status here is :) Would be great to get this closed up 😊

**Comment by andrewtavis** [comment]
Closed by @Robot8lover in #889 :) Almost done with the initial batch of PRs from you, @Robot8lover. Let me know if you have questions on the project or would like to do a call at some point to discuss next steps/things that you could help with. Really is a great time working with you 😊
