### ISSUE TITLE
Add resource creation flow

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#561]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add in the resource creation flow to that would be activated via `Create -> New resource` from the left sidebar. Designs for this flow can be seen [on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2584%3A16751&mode=design&t=hbrmPFJFE6NT0uV9-1)  and further can be seen below:

![Resource Creation](https://github.com/activist-org/activist/assets/24387426/0153ee27-ddba-4b4e-ab61-24d89cbaeab2)

Components included in this would be the topic selection one, progress bar, and the form element could be custom or work from others in the code base 😊

### Contribution

Happy to work on this myself or support someone who has interest!

**Comment by IsaacDMz** [comment]
Hey @andrewtavis can i work on this issue? I have some difficulties with front-end but i would like work on this.

**Comment by andrewtavis** [comment]
Sure thing, @IsaacDMz! Let me know if there's anything we can do to support you with the issues you're having with the frontend! Assigning you now 😊

**Comment by IsaacDMz** [comment]
@andrewtavis i have a question, this task is to create the Resoures button in the dashboard and redirect to resources page? Like this 
![image](https://github.com/activist-org/activist/assets/94393622/3608710d-f584-4212-9a3d-a28f8d7f76c7)
Or create the resources button and create the page as an example in figma?

**Comment by andrewtavis** [comment]
Thanks for checking in, @IsaacDMz :) We want to have `Create > New resource` in the sidebar link to `/resources/create` with this page then being created as well :) As of now resources won't be enough of a focus to have a slot in the main menu selectors at the top of the sidebar. Thanks for checking in though!

You'd be welcome to do one PR that does the routing and creates a `/resources` directory in the frontend with `index.vue` and `create.vue` being pages that for the first PR just have the sidebar, and then we can do another PR that adds in the page contents to `/resources/create.vue`. All in one PR's also totally fine though 😊

**Comment by IsaacDMz** [comment]
Hey @andrewtavis Firstly, I apologize for the delay in starting to work on this task, I was finishing up some college things.

I started working on this task today and so far I have done it.

![image](https://github.com/activist-org/activist/assets/94393622/eb2494a4-1916-4671-975b-e1751011ac7f)

I'm having problems to understanding how can i use the dropdown of organizations into this code. Can I do the PR without the dropdown? Or do you have any tips for this?

Another question, the endpoint to create resources is /content/resources? Or is it someone else?

**Comment by andrewtavis** [comment]
Hey @IsaacDMz 👋 No stress on the timing :) Hope that things are going well for college! 

You're free to make a PR and we can figure out the dropdown later. No stress. I'd say that the route will likely just be `/resources/create`. Obviously we're accessing `content` from the backend, but I'm not really sure what `/content` would be in app whereas `/resources` could eventually be presentation of popular resources or something like that :)

**Comment by andrewtavis** [comment]
Thanks @IsaacDMz 🙏 Added the template `/resources` page too. If you have interest in editing the filters so that the appropriate filters show up that would be another step for this. Let me know, and I'll make an issue after hearing from you regardless 😊

**Comment by IsaacDMz** [comment]
> Thanks @IsaacDMz 🙏 Added the template `/resources` page too. If you have interest in editing the filters so that the appropriate filters show up that would be another step for this. Let me know, and I'll make an issue after hearing from you regardless 😊

i`ll try to get back-end issues now, actually i don't like to much make front-end. Sometimes i try front-end issues to try learn new things, but is not my preference

**Comment by andrewtavis** [comment]
For sure! We'll be making some new ones later today 😊
