### ISSUE TITLE
Address dev environment TS server not recognizing properties and types

### ISSUE THREAD

**Issue by wkyoshida** [activist-org/activist#568]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is to address reports of contributors sometimes encountering issues setting up their development environment for the frontend. Reports involve the TypeScript server in VSCode not recognizing properties and types. 

Will take this on :sunglasses:

**Comment by andrewtavis** [comment]
Thanks for checking this out, @wkyoshida!

**Comment by andrewtavis** [comment]
Closed via #575 😊 Thanks @wkyoshida! 🚀
