### ISSUE TITLE
Route backend port to the Django admin in dev

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#569]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something we discussed in the most recent Code Night 🌙 is it would be better for those wanting to contribute to the backend if the Django admin panel was routed to directly from `localhost:8000` or whatever the backend port is set to in `.env`.

### Contribution

Happy to work on this or support someone who has interest in working on it!

**Comment by andrewtavis** [comment]
CC @to-sta and @sayik :)

**Comment by sayik** [comment]
Hi @andrewtavis @to-sta, I was trying something but hasn't worked yet, I need your help, I did this in the urls.py file
`urlpatterns = [path("", admin.site.urls)]` but I am not getting to the admin page, Am I on the right direction ? Or I need to a different approach. Thank you.

**Comment by to-sta** [comment]
@sayik I will assign this issue to you, if you do not mind.

The urlpatterns looks alright, should work. You can overwrite the current "v1/admin" with "". That should do the job!

```python
urlpatterns = [
    path("v1/admin/", admin.site.urls),
    path("v1/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "v1/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("v1/auth/", include("authentication.urls", namespace="authentication")),
    path("v1/content/", include("content.urls", namespace="content")),
    path("v1/entities/", include("entities.urls", namespace="entities")),
    path("v1/events/", include("events.urls", namespace="events")),
]
```

**Comment by sayik** [comment]
Thank you @to-sta, that's what I did, I replaced `v1/admin` to `""` in the current file, but I can't get the file updated, it's saved, but won't show the changes in docker, and runs the pre-edited version of urls.py file from backend directory.

**Comment by to-sta** [comment]
@sayik did you run `docker compose up --build`

**Comment by sayik** [comment]
@to-sta no because it runs frontend too, which doesn't work for me, so I didn't think that direction. But I now think if I run `docker compose up --build backend` , it might work, I'll let you know if it works.

**Comment by sayik** [comment]
@andrewtavis @to-sta it did work, thank you for the support.

**Comment by andrewtavis** [comment]
Awesome to hear, @sayik! Looking forward to the results 😊

**Comment by andrewtavis** [comment]
Closing this given a discussion in the dev sync. The route of `v1/admin` can be used 😊
