### ISSUE TITLE
Add a11y checks to repository

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#576]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into adding an accessibility workflow to the frontend checks that we already have in [pr_ci_frontend.yaml](https://github.com/activist-org/activist/blob/main/.github/workflows/pr_ci_frontend.yaml). The general thought would be to go with [axe](https://github.com/dequelabs/axe-core) for this and also add [axe Accessibility Linter](https://marketplace.visualstudio.com/items?itemName=deque-systems.vscode-axe-linter) to the suggested VS Code extensions that we have in the readme and contributing guide. Specifically in looking into it axe has support for Vue, but other options such as [Lighthouse](https://github.com/GoogleChrome/lighthouse) could also be considered :) Lighthouse also offers SEO checks as well that might be something to add.

### Contribution

Happy to work with someone on this!

**Comment by andrewtavis** [comment]
CC @to-sta and @therealhoppi (that [article you sent along](https://www.matuzo.at/blog/building-the-most-inaccessible-site-possible-with-a-perfect-lighthouse-score/) got me thinking that we should check this).

**Comment by thiagogquinto** [comment]
Hi @andrewtavis, I would like to work on it! Could you assign me?

**Comment by andrewtavis** [comment]
Hey @thiagogquinto 👋 You can definitely implement this! :) Do you want to help a bit with the research for it beforehand? It looks like there are no [Lighthouse](https://github.com/GoogleChrome/lighthouse) related VS Code extensions for a11y as all I get for a search for "Lighthouse" is a theme 🧑‍🎨😅

Specifailly we're looking at what the Vue support is as it seems like [axe](https://github.com/dequelabs/axe-core) has it. Could you check if there's a good way to implement Lighthouse checks for Vue with GitHub Actions, and maybe we can make another issue? That new issue can be for adding in anything that Lighthouse has that axe might not like SEO suggestion 😊

**Comment by thiagogquinto** [comment]
Thanks, sounds good! I will make some research about it.

**Comment by andrewtavis** [comment]
Thanks @thiagogquinto! Let us know if there's anything we can do to support :)

**Comment by thiagogquinto** [comment]
Hey @andrewtavis, just so you know it, I am doing research on this, but I did not find yet a way to add the checks, and I have been pretty busy in the past days, so if you want to unassign me from the task, feel free. I will continue the research, but I think it would be really helpfull if someone else could research too. Sorry for that!

**Comment by andrewtavis** [comment]
Hey @thiagogquinto 👋 FYI a friend suggested we look into [testing library](https://testing-library.com/docs/vue-testing-library/intro/) for our a11y tests. We'd be able to use it for other things as well, with it working well with Vitest as the runner :) Let me know what you think!

**Comment by andrewtavis** [comment]
Hey @lucianmurmurache 👋 Would this be something that you'd be interested in working on?

**Comment by lucianmurmurache** [comment]
@andrewtavis I can take a look at this for sure, I would approach this with a combination of [vitest ](https://vitest.dev/) and [axe](https://www.npmjs.com/package/axe-core)

**Comment by andrewtavis** [comment]
Thanks @lucianmurmurache! Let's discuss a bit more on Tuesday and we'll have a better idea of where to take it from there 😊 Great to see you in the call! Hope it was a nice time :)

**Comment by lucianmurmurache** [comment]
I was hoping to implement [vue-axe](https://github.com/vue-a11y/vue-axe) but sadly it's not compatible with vue3/nuxt3

Will be looking into integrating axe-core with vitest instead.

**Comment by andrewtavis** [comment]
Thanks for checking out options, @lucianmurmurache!

**Comment by andrewtavis** [comment]
Closed via #755 with some minor commits for fixes afterwards :) Thanks @lucianmurmurache! 🚀
