### ISSUE TITLE
Add top shadow to sidebar footer when content expands below

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#579]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add a check to the [sidebar footer](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftFooter.vue) for when the content of the [sidebar index](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftIndex.vue) or the [sidebar filters](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftFilters.vue) is scrollable, and if that is the case then we'll want a slight top shadow to be added to the sidebar footer such that it appears over the content.

The shadow should be `shadow-sm shadow-zinc-700`, but we'll need to make sure it's only at the top :)

### Contribution

Happy to support someone on this or get to it eventually myself! This is a great `good first issue` for new contributors, and those already in the community are also welcome to pick it up 😊

**Comment by lchauha** [comment]
Hi @andrewtavis I would like to work on this issue. Please assign this to me.

**Comment by andrewtavis** [comment]
Hey @lchauha 👋 Thanks for picking up two issues already! Will assign, and let me know if there's anything I can do to help 😊

**Comment by andrewtavis** [comment]
Hey @lchauha 👋 Checking in on this and #578 :) Let me know if there's anything I can do to help!

**Comment by arescrimson** [comment]
Hey, @lchauha ! Was just wondering if you needed any help on this, would be happy to try and test things out if you need an extra hand. As I saw that this is also related to issue #578, let me know if you need anything there as well :))

**Comment by andrewtavis** [comment]
Thanks for checking in, @arescrimson :) I'll go ahead and assign you here!

@lchauha, you'd be more then welcome to pick up another issue at another time. Please let me know if you'd like to 😊

**Comment by andrewtavis** [comment]
For this one we can be doing the "top shadow" within [SidebarLeft](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeft.vue), with the goal for this being that the shadow would only appear if the sidebar is scrollable :)

**Comment by andrewtavis** [comment]
Hey @arescrimson 👋 Checking in with you on this and the other issue :) We're still in the dev sync call if you'd like to join and discuss 😊

**Comment by arescrimson** [comment]
Hi, thanks for checking in @andrewtavis! I was actually planning to get this done this weekend, but because of some issues that's kept me busy this past week, I unfortunately had to miss the dev call. However, I'll keep you posted! After this weekend, I should have more time to tackle both of these issues :D

**Comment by arescrimson** [comment]
Also great to see all the latest issues, problems and new contributors added within the last week! Really cool to see how this project is growing 😄

**Comment by andrewtavis** [comment]
We're still in the call if you want to say hi! But ya, let me know and happy to jump on a quick one to discuss 😊

**Comment by andrewtavis** [comment]
Hey @josueemartinezz 👋 I'm seeing there's a commit that references this. Do you want to send along a PR for this?

**Comment by andrewtavis** [comment]
#578 was just closed, but the issue here is that the padding around the footer makes it so that shadows are applied from the container of the footer rather than the menu option. To illustrate what I'm talking about:

![Screenshot_2024-05-18 21 12 01](https://github.com/activist-org/activist/assets/24387426/90c136a3-c1d0-4527-914d-f6831c32c8d4)

There's a `p-1` around the sidebar left footer, and then also `pr-4` is applied in this case as the sidebar is expanded. I've tried to make the background that the padding creates transparent, but it doesn't work. Not really sure where to go from here, but it's not a high priority :)

Unassigning for now, @arescrimson, just in case someone else wants to give it a shot. Hope all's well with you!

**Comment by PustakP** [comment]
Hi @andrewtavis, I tried helping out with this issue, please have a look :)

**Comment by andrewtavis** [comment]
Hey @PustakP! I'll check out the PR! :) Thanks for working on this and the detailed PR commit 😊

**Comment by mstcyr2** [comment]
Hi @andrewtavis! I tried out a possible solution for this. I wasn't sure whether you wanted the background of the footer visible or not based on your previous comment, so right now it looks like this. I'm willing to continue working on it if you have other suggestions. Thanks!
![activist-shadow](https://github.com/user-attachments/assets/9c795e4c-203c-410c-883f-2914fdaffe1f)

**Comment by andrewtavis** [comment]
In 99efd73 - along with other changes - I was able to figure out a relatively good looking shadow for the footer that now appears if the content is scrollable. I also edited the formatting for the header as well in such cases. Thanks all for the communication here and your all's efforts to get this done!
