### ISSUE TITLE
Create base modal component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#582]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This component would create a base `ModalBase.vue` component in the [frontend/components/modal](https://github.com/activist-org/activist/tree/main/frontend/components/modal) that others in this directory would inherit from such that there is a common styling for modals across activist. Note that work for this issue should likely be done before the recently made #580 and #581. The logic for this component could be extracted from the already existing modal components with a `<slot />` included such that the modal content can change :)

### Contribution

Happy to support someone with interest in working on this or work on it myself! 😊 This is a great `good first issue`, or also would be perfect for a current contributor who would like to pick up something new :)

**Comment by andrewtavis** [comment]
Hey there @VinnyHS2 👋 Wanted to check in on if you had interest in this one along with #580 or #581 :) Figured any of these would be pretty easy for you to knock out, but also happy to discuss/do a call!

**Comment by anthonyshibitov** [comment]
heyo, is this still up for grabs? more than happy to do this!

**Comment by andrewtavis** [comment]
Ahhhhh shitttttt 😎 Great to hear from you, @anthonyshibitov! By all means you can work on this :) Lemme know if I can do anything to support 😊

**Comment by anthonyshibitov** [comment]
> You coming to the sync on Saturday?

yessir!! i've got some catching up to do 🤠

**Comment by andrewtavis** [comment]
Sickkkkk! See you there! 😊

**Comment by andrewtavis** [comment]
51e61cb closes it up, @anthonyshibitov :) Image modals can now close on the BG click (the w-4/5 was restricting it, so I assigned it lower in the divs) 😊 I also made it so the slots are single tags as that's a bit more the style we're using. Aside from those some minor formatting. Thanks for this! Great to have you back 🥳

**Comment by anthonyshibitov** [comment]
> [51e61cb](https://github.com/activist-org/activist/commit/51e61cba7356c7cc061962be893ef65a8f2b51b8) closes it up, @anthonyshibitov :) Image modals can now close on the BG click (the w-4/5 was restricting it, so I assigned it lower in the divs) 😊 I also made it so the slots are single tags as that's a bit more the style we're using. Aside from those some minor formatting. Thanks for this! Great to have you back 🥳

i was playing around with for like an hour and i was like u know what... i'll let someone else fix this in like 3 minutes LMAO

**Comment by andrewtavis** [comment]
Was not 3 min, but also not another hour for sure so good choice in sending it along 😊
