### ISSUE TITLE
Add tooltip for high risk discussion warning

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#588]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would implement a tooltip for the warning icon next to the send button for the [CardDiscussionInput](https://github.com/activist-org/activist/blob/main/frontend/components/card/discussion/CardDiscussionInput.vue) component. Designs for this have just been added to Figma and can be found [here in the Tooltip variants](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2037%3A3102&mode=design&t=1ewSdfvBkc7LlTrv-1) as well as below:

![Mode=Light, Type=Discussion Warning](https://github.com/activist-org/activist/assets/24387426/f78ce236-0eb5-41a9-a921-10fd0ee309ec)

This component would be `TooltipDiscussionWarning` and would be within the [components/tooltip](https://github.com/activist-org/activist/tree/main/frontend/components/tooltip) directory. We should use [Tooltip](https://github.com/activist-org/activist/blob/main/frontend/components/tooltip/Tooltip.vue) as the base where the `text` prop would be `Please use usernames and do NOT write any personal information including:` as a localizable string and the options would follow in the `<slot />` by passing the unordered list between `<TooltipDiscussionWarning></TooltipDiscussionWarning>`.

- Note that this issue is blocked by #586 being merged

### Contribution

Happy to support someone (or some people 😉) who have interest in working on this! Some members of the community have already expressed interest in this 😊

**Comment by mahasultan** [comment]
Would love to work on this issue, would you please assign me !

**Comment by shahad1307** [comment]
I would like to take part in working on this issue with almaha , please assign me with her

**Comment by andrewtavis** [comment]
Happy to assign the others if they'd be so kind as to write in here 😊
