### ISSUE TITLE
Focus state of activist logo in footer is broken

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#596]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

There's an issue with how the `LogoActivist` components are being rendered in [FooterFlex](https://github.com/activist-org/activist/blob/main/frontend/components/footer/flex/FooterFlex.vue) and [FooterFlexCol](https://github.com/activist-org/activist/blob/main/frontend/components/footer/flex/FooterFlexCol.vue). When trying to focus the logo the `focus-brand` styling that's inherent within the [LogoActivist component](https://github.com/activist-org/activist/blob/main/frontend/components/logo/LogoActivist.vue) isn't being displayed. This is being caused by `overflow-y-hidden` being applied to the parent `<div>`, which in turn was implemented to solve an issue where the logo was expanding beyond its bounds on mobile Safari in 0d7485e

**Comment by brunopinhal** [comment]
I would like to work on this, could you assign to me?

**Comment by krallowski** [comment]
Hi there :)
What about setting box shadow inside for this specific item with box-shadow: inset ?

**Comment by andrewtavis** [comment]
Hey @krallowski 👋 If you wanted to give it a shot and we can see if this fixes it it'd be very appreciated! Let me know if you'd have interest and I can assign you :)

**Comment by krallowski** [comment]
Hey :)
Yeah, why not, I will try, thanks!

**Comment by andrewtavis** [comment]
Thanks @krallowski! Let me know if there's anything I can do to help 😊

**Comment by andrewtavis** [comment]
Closed via #630 😊 Happy to send along some more issues that need to be worked on if that'd be of interest, @krallowski. Let me know :)
