### ISSUE TITLE
Create reduced versions of search components

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#601]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As part of the process to get groups for organizations up and running we also need to add in the reduced versions of various search results components. Example of these components can be seen on the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1955%3A1111&mode=design&t=EEffIiC8Sm1w5wTq-1), where the main difference is that we do not display topics for reduced versions of the search results and they also have smaller images. A page that has them in the designs is the [groups page for organizations](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=6976%3A37867&mode=design&t=EEffIiC8Sm1w5wTq-1).

We'd need `CardSearchResult` to have a boolean `reduced` prop, and then this would be passed to all of the sub components where their styling would then be simplified :)

### Contribution

Happy to support someone with this or work on it myself 😊

**Comment by andrewtavis** [comment]
Ping @anthonyshibitov, master of search cards 🙃 Does this sound like something you'd want to handle?

**Comment by andrewtavis** [comment]
For context, we made the decision that the full search cards are good for if the results are the whole page, but if we're on an event or an organization page then we need them to take up a bit less space. In these regards, because you already generally know the topic that you're looking into, we don't need to constantly be telling the user that the event for an org or a group for an org is working on the same thing :)

**Comment by andrewtavis** [comment]
Thanks @andrewtavis 🙌 Lemme know if you have any questions :)

**Comment by anthonyshibitov** [comment]
> I'd say we'd be using them first on organization events and groups, so if you're looking for a place to put them then do `organizations/1/events` and `organizations/1/groups`. Similarly for resources 😊

should the reduced search components be new and separate components, or should we have the existing ones accept a `reduced` prop to change their behavior?

**Comment by andrewtavis** [comment]
b32ab89 does some minor formatting to finalize all this, @anthonyshibitov 😊 Big thing was making sure that the organization and event placeholder images look good when we're using the reduced versions of the cards. There are also some minor fixes :)

Thanks for the changes here! 🚀
