### ISSUE TITLE
a11y: close search result kebab tooltip after tabbing out of it

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#608]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that's needed for [menu for search results](https://github.com/activist-org/activist/blob/main/frontend/components/menu/MenuSearchResult.vue) as well as the corresponding [new tooltips for search results](https://github.com/activist-org/activist/tree/main/frontend/components/tooltip/menu-search-result) is the ability to close it when the user tabs into the options and then back out or tabs to the last one and then tabs past it. The expected behavior is that the user has decided that they don't want any of the options, so the tooltip should then be closed. 

These components can currently be found on the example search results on the [home page](https://activist.org/home) for testing purposes and seeing the current version where tabbing away will leave the tooltips there.

If implementing [Headless UI Popover](https://headlessui.com/vue/popover) would help with this, then we could also refactor the component with this instead 😊

### Contribution

Happy to support someone with this or get to it eventually myself!

**Comment by ahmedy00** [comment]
@andrewtavis could you assign it to me

**Comment by andrewtavis** [comment]
Thanks @ahmedy00 for helping with this! Let me know what your thoughts are on #500, but that can be another PR after this one :)

**Comment by andrewtavis** [comment]
85deb37 finalizes this, @ahmedy00! I realized that we also want shift+tab to close the tooltip when we're on the button itself, which I added in. I also did some styling for the BtnLabeled as I realized that a change I made to fix the icons screwed up the alignment in some cases. 

Thanks for the work here! Now to the backend! 🚀
