### ISSUE TITLE
[Safari] header transition flicker

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#61]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

#57 and [6205822](https://github.com/activist-org/activist/commit/6205822debd9fc3cf7f36a9e48de6c4176cca5fb) added a transition to the header where it disappears on scroll down and reappears on scroll up. This transition is performant across major browsers (Firefox, Chrome, Edge) except for Safari. On Safari we have a slight flicker when the transition occurs on the initial scroll down, and then when the scroll up transition happens there's at times a gap between the header and the top of the screen (the header appears and then shifts up after it's half second transition in).

One potential fix would be to potentially get rid of the transition on Safari, but a method to match the performance on other browsers would be best 🤔

**Comment by andrewtavis** [comment]
Looking into this a little bit, there are some resources mentioned in the [browser support](https://tailwindcss.com/docs/browser-support) section of the Tailwind documentation. Installing and configuring [autoprefixer](https://github.com/postcss/autoprefixer) could be a way to solve this 🤔

**Comment by andrewtavis** [comment]
aee3a35 does not fix the problem, but does assure that [autoprefixer](https://github.com/postcss/autoprefixer) is running in the current Nuxt configuration.

**Comment by andrewtavis** [comment]
8953c7d fixes the initial flicker on down scroll. There still is a bit of a jump of the header on Safari when the user scrolls up quickly, but I'd say this is no longer a priority :)

**Comment by andrewtavis** [comment]
A commit to fix this little header transition jump on scroll up for Safari would be appreciated if someone has interest :)

**Comment by anthonyshibitov** [comment]
Hey, could you assign this to me? I'll take a stab at it.

**Comment by andrewtavis** [comment]
Thank you, @anthonyshibitov!! 😊Looking forward to discussing all these issues later tonight :)

**Comment by anthonyshibitov** [comment]
heyo @andrewtavis i can't seem to reproduce this on safari anymore.

i recall when i originally took this issue there was a flicker issue and small 1-2px gap popping up. was this maybe fixed (inadvertently or otherwise) in some other commit? let me know if this still persists on your side :)

**Comment by andrewtavis** [comment]
Heyooo @anthonyshibitov :) Seems to have gotten way better, which for us not having done anything that I can think of means that Safari did some work on their end 😅 I can still see a very quick glimpse of it when I really crank it on desktop on the the landing page, but then it's 1/10 times that it's even noticeable. 

As it has gotten way better and the issue isn't detrimental at all at this point, I'm happy to close 😊 Thanks for checking and communicating the progress on this!!
