### ISSUE TITLE
Move search component menu to the top right corner below medium breakpoint

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#611]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that would be great to have for the three dot kebab menu on search result components would be that it moves to the top right corner when the screen is at the small breakpoint or below (for mobile devices). These search components can be found on the [activist home page](https://activist.org/en/home/). The menu component that we need to move is [MenuSearchResult](https://github.com/activist-org/activist/blob/main/frontend/components/menu/MenuSearchResult.vue). The change would need to happen in all of the [search result components](https://github.com/activist-org/activist/tree/main/frontend/components/card/search-result) where it is used. 

For example:

```
<MenuSearchResult searchResultType="event" />  # we want this to have class="hidden md:block" to show it

# We'd then have another MenuSearchResult component that is at the top right
<MenuSearchResult class="absolute md:hidden" searchResultType="event" />  # including some padding
```

### Contribution

Happy to support someone with interest in working on this!

**Comment by andrewtavis** [comment]
An example of how the final components should look can be found on the [designs in Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=1955%3A1111&mode=design&t=EzhMhrFeHSEWeQVJ-1) 😊

**Comment by bharath637462** [comment]
hey can i work on this?

**Comment by andrewtavis** [comment]
Thank you, @bharath637462! Please let me know if you need any help 😊 Looking forward to working with you on this!

**Comment by andrewtavis** [comment]
Note that for the `MenuSearchResult`, we need the `searchResultType` property to match the search result like event for[CardSearchResultEvent](https://github.com/activist-org/activist/blob/main/frontend/components/card/search-result/CardSearchResultEvent.vue) and the same for organizations, resources and users :)

**Comment by andrewtavis** [comment]
Hey @bharath637462 👋 How's everything going here? Were you able to bring down the current changes and start working on a new implementation? :)

**Comment by bharath637462** [comment]
yes @Andrew McAllister ***@***.***> i am  able to take
the current changes working on new implementation.

**Comment by andrewtavis** [comment]
Hey @bharath637462 👋 Just a quick note that I'd avoid using your email to reply to things or just be careful if you do as your original message sent a notification to the wrong person. I've edited the message to fix it, but it looks like you used the @ functionality of your email, which when translated to a message here broke but still @ notified someone else as the first part matched the user name of a person on GitHub who's not associated with activist.

No stress, but just be careful!
