### ISSUE TITLE
Disable disappearing header on mobile

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#613]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This is quite a simple issue and great for someone who wants to do a first issue for activist. In a recent product sync we decided that we do not want the header to disappear on mobile as it does for desktop. The disappearing header can be seen on the landing page at [activist.org](https://activist.org), and the mobile header can be seen in application pages like [activist.org/home](https://activist.org/home) beneath the medium breakpoint.

As we have the page navigation dropdown for mobile, it no longer makes sense for the header to disappear. The change would need to happen within the [frontend/components/header/HeaderAppPage](https://github.com/activist-org/activist/blob/main/frontend/components/header/HeaderAppPage.vue) component, with the goal being to find where the header is being hidden beneath the medium breakpoint and removing it.

### Contribution

Happy to support someone who wants to work on this! Let me know if there are any questions. Would be great if we could get to this soon 😊

**Comment by VTPrince** [comment]
Hey @andrewtavis  , I would like to get started on this issue, can i open a PR for this?

**Comment by andrewtavis** [comment]
Sure thing, @VTPrince! Assigning you now, and feel free to send along a PR :)

**Comment by andrewtavis** [comment]
Hey @VTPrince 👋 @mikemumford sent along a PR for this and given the simplicity of the issue and wanting to get things closed I chose to merge it in. You can see the PR in #638. Thanks for your offer to help, and hope that we can find a new issue to work on soon 😊
