### ISSUE TITLE
Documentation: add directions for getting dev env up without Docker

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#617]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

From a [discussion on Matrix](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org/$0MkXg1BqAZXzpiA7hEirZ9uEWae9H8bkgu4oZTg_nLY?via=matrix.org&via=acter.global&via=chat.0x7cd.xyz) :)

A common issue that people have been having is that Docker doesn't work as well on certain machines. Specifically Windows computers at certain levels need to run a Linux virtual machine in order to get Docker up and running, basically making the process to expensive for it to function.

Our suggestions to community members till now have been to split the development environment and just run the frontend via Yarn or the backend with Django. We should include directions for this in the [Development environment section of the contributing guide](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#development-environment-) and also direct users to this section in the note to contact the team on Matrix in the [Environment setup section of the readme](https://github.com/activist-org/activist?tab=readme-ov-file#environment-setup-). 

Re the original discussion, I don't think we need docker compose specific processes for the frontend or backend as those won't address Windows users, and I don't think we need two processes for getting the frontend (Yarn + docker compose) and backend (Django + docker compose) respectively. 

Happy to discuss and help someone implement!

**Comment by rstfari** [comment]
Hey, seeing if I could help!

**Comment by andrewtavis** [comment]
You'd be welcome to help, @rstfari! Let me know if you have any questions about what to put in there. Happy to discuss here first, or also send along a PR and we can discuss in there 😊

**Comment by rstfari** [comment]
Hey, so before I update the documentation, I just wanted to make sure that I am writing a step-by-step guide for the split development environment. Also, I am not familiar with docker yet but wanted to know where I could learn the steps so I could write the documentation correctly.

**Comment by andrewtavis** [comment]
CC @to-sta: can you check the steps for the backend and verify that this is what we'd be looking to add?

**Comment by andrewtavis** [comment]
Note that someone can set their ports differently in the `.env` file, but let's maybe ignore that for this as if they change it they should know that they did that? Also this is related to #570 where these steps might change.

**Comment by andrewtavis** [comment]
96fbc75 sends along some final touches for this issue. Specifically puts the sections within `summary` tags so that they need to be expanded. Thank you for the dedication to the issue, @rstfari, and thanks for the help with the backend, @to-sta!
