### ISSUE TITLE
Add discussion models to the backend

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#619]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would go through and add in the discussion models to the backend as we'll be needing them for eventual organization application discussions and those for event pages and organization blogs. The schemas can be found in the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=7279%3A7778&mode=design&t=eKjevthu2v68bHHV-1), with the `discussion` and `discussion_entry` logic being needed. These changes should be made in [content directory](https://github.com/activist-org/activist/tree/main/backend/content) of the backend 😊 

### Contribution

Happy to discuss and support as needed! Note that @ahmedy00 has expressed interest in this 🙂

**Comment by andrewtavis** [comment]
Ping @ahmedy00: can you write in here so I can assign?

Also ping @to-sta: I figure adding the logic for these two tables is ok as again we'll need these before the task ones. I'll also make an issue for the vote tables, and from there the last thing is tags, which I think we can hold off on for now. I've also marked the tag tables in the schemas as not implemented 😊

**Comment by ahmedy00** [comment]
@andrewtavis, thank you, I'd be happy if you assign it to me.

**Comment by andrewtavis** [comment]
Happy to assign, @ahmedy00! Let us know if there's anything we can do to help 😊

**Comment by andrewtavis** [comment]
@to-sta, I'm realizing that we also have a similar problem for discussion votes that we have for flags. In the schemas it's just an int, but we need this to be linked to the user who did it so we have a unique association. How do do this 🤔 

I don't think we need a `vote` table?? @to-sta, @ahmedy00, can you two think of anything else that we're voting for? Nothing comes up in the search of votes for the schema except for the actual tables for vote entities in the top right. We also have the organization application, but then I think that it having its own table would be fine. Maybe we should combine with vote entities if there are other things though.

**Comment by andrewtavis** [comment]
For now I'll make a `discussion_upvote` table that we can also include in this, but please let me know what else we could consider!

**Comment by andrewtavis** [comment]
I made [discussion_upvote](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=8124%3A8317&mode=design&t=hNXVijyV1rCwwTiC-1) that has a column for the `discussion_id`, `user_id` and also `entry_id` for a comment itself that can be `NULL`. Maybe we can also do `NULL` for the `discussion_id` as we don't need to explicitly always associate a discussion entry with its discussion, but then I'm not sure.

Just to go through this a bit more: organizations and groups would have multiple discussions, and events would have a single discussion. Within each there would be discussion entries :)

**Comment by andrewtavis** [comment]
Just synced with @therealhoppi on this and edited the table after our discussion/decisions. We were thinking that upvoting the first entry in the discussion is equivalent to upvoting the discussion itself, so we don't need two different columns for `discussion_id` and `entry_id`. It's now just  `entry_id` 😊

**Comment by IsaacDMz** [comment]
@andrewtavis can i work on this task?

**Comment by andrewtavis** [comment]
Thanks for jumping in and working on this, @IsaacDMz! Let us know if there's anything we can do to support :)

**Comment by anthonyshibitov** [comment]
heyo, is this open?

**Comment by andrewtavis** [comment]
Hey @anthonyshibitov 👋 Let's check in with @IsaacDMz first, but you'd be welcome to pick this up :)

**Comment by IsaacDMz** [comment]
Hi guys, i has some problems to build the project in my new PC, the virtualization is not working and docker is not running, I'm trying but I can't solve it. I don't know when i will solve this.

So, you can pass it on to him, and when I manage to solve these problems I will return to work in other tasks.

**Comment by andrewtavis** [comment]
Thanks for the update, @IsaacDMz! Hope it all works out soon and we can get you on the next issue ASAP :) 

@anthonyshibitov, assigning to you, and let us know if there's anything we can do to help 😊

**Comment by andrewtavis** [comment]
Closed by #688 🥳 Thanks for the continued contributions, @anthonyshibitov! We'll be sure to get them in a bit quicker the next time around. Has just been hectic :)

Hope to see you at a sync soon! Next one's the 20th 😊
