### ISSUE TITLE
Add error page to activist

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#62]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now we're use using the default error pages for activist. It would be great if we could add a custom 404 not found page as well as some others, which could be different issues. The documentation on Nuxt error handling can be found [here](https://nuxt.com/docs/getting-started/error-handling). Looks like at the very least we'll need a `layouts/error.vue`, and then this can be customized with the logo, a message, a return home button as well as the header and footer.

### Contribution

I'd be happy to work on this, but am also very happy to support someone!

**Comment by 5ud03r5** [comment]
#76

**Comment by andrewtavis** [comment]
@5ud03r5, sorry for the delay in reacting to all this :) I was away on a vacation and just got back last night 🌔 Am checking the PR now 🙃

**Comment by andrewtavis** [comment]
@5ud03r5, thanks so much for the initial contribution here 😊 Really great first work! In looking at it a bit, there are a few changes that could improve the design 🤔 I wanted to merge the initial work so you get credit right off the bat. Generally what I'm thinking is:

- The back button needs rounded corners on the right
- I think we can just display the error rather than it being something that's shown on click
- It'd be good include the activist logo in the top left of the page and on the top centered on smaller screens
- The text colors should be reactive to light and dark mode

Most of this is work that could be done with Tailwind CSS. Does this sound like something you'd like to do, or would you like me to do these final edits?

Thanks again so much! 🙏

**Comment by 5ud03r5** [comment]
Sure, i will do it! Can you please assign this issue to me?

**Comment by andrewtavis** [comment]
Assigned! Thanks @5ud03r5! 🚀

**Comment by andrewtavis** [comment]
@5ud03r5, a8eb48c edits the error page, with all lines being changed because of formatting. The big things I changed were:

- Removing the fade in
- Making the error number larger
- Setting up the breakpoints to work without `max-` as I'd like to use a consistent style of the breakpoint triggering the changes as they increase rather than for those sizes beneath them
- Used a `LabeledBtn` component so it's easier to maintain in case that component changes
- Removed some Tailwind classes that were repeated or seemed to be unneeded

There's also a change to the Docker file that allows for hot-reloading again as discussed in #55.

Thanks again for your efforts on this issue! I'll close it, but happy to continue the discussion if you have some ideas 😊
