### ISSUE TITLE
Add image table and referencing columns to backend

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#620]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue focuses on adding in the image table to the backend in the [content directory](https://github.com/activist-org/activist/tree/main/backend/content). The schema for this can be found in the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=7917%3A1375&mode=design&t=eKjevthu2v68bHHV-1), with the `image` table being needed as well as changes to the other tables to add in the columns that it is linked to via foreign keys.

### Contribution

Happy to discuss and support with this as needed!

**Comment by andrewtavis** [comment]
Ping @rigojr: would this be a backend issue that would be of interest? Feel free to write in here if so and I can assign! We'd talked maybe you working on the votes tables, but that feature is pretty far off at this point. This issue would give you a good orientation to the backend models though 😊

Also ping @to-sta: I figured adding this one in made more sense. We can do votes, tags and movements later next year. The only other table that's `Not implemented` now is location, and I'll make an issue for that now too :)

**Comment by rigojr** [comment]
Let's do it, I can handle it.

**Comment by andrewtavis** [comment]
Awesome, @rigojr! Let us know if there's anything we can do to support 😊

**Comment by andrewtavis** [comment]
Closed via #363 🎉 Thank you, @rigojr! Let us know if you have any ideas on #670 😊
