### ISSUE TITLE
Add tag tables to backend content models

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#637]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Please note that as of now this issue is `blocked`. I'm mostly making it to check whether the changes in 
ff0f8b0 fixed #622 :)

Tags will be in integral part of how events are defined on activist. Topics allow for a more granular segmentation for more easily finding related events and organizations, whereas tags will be fine grained to find content directly related to trending ideas and events in the world.

This issue will implement the [tag tables as found in the Figma designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=7279%3A7990&mode=design&t=phI7ebKrE49zDQOU-1) in the [content directory of the bakend](https://github.com/activist-org/activist/tree/main/backend/content).

### Contribution

Happy to assist with this when we start to work on it! There's lots of things that still need to be discussed on how tags will work and how they'll appear on the platform, but we'll get to that in dev syncs in the New Year!

**Comment by IsaacDMz** [comment]
Hey @andrewtavis this task is still blocked?

**Comment by andrewtavis** [comment]
Hey @IsaacDMz 👋 As of now, yes, but we actually need someone to take over on #619 as @ahmedy00 said he's too busy right now. If that one's of interest, feel free to write in there and I'll assign 😊

**Comment by thiagogquinto** [comment]
Hey @andrewtavis, in the latest [etherpad ](https://etherpad.wikimedia.org/p/activist-dev-sync-2024-2-24)is written that this issue can be unblocked, if that is the case, could I try to work on it?

**Comment by andrewtavis** [comment]
Sounds good, @thiagogquinto! I'll open this up and you can work on it.

@sayik, hope it's alright that we assign @thiagogquinto here as you have a different issue now :) 

Let us know how we can support!

**Comment by thiagogquinto** [comment]
Hey @andrewtavis, to be sure, this issue is only about updating the _models.py_ file, and the rest of the files will be update in future issues, or along with this issue the other files will be updated?

**Comment by andrewtavis** [comment]
You can focus on the models in this one and then we can make some more for the other parts, @thiagogquinto :)

**Comment by andrewtavis** [comment]
Closed via #734 😊 Thanks for the help here, @thiagogquinto! Your consistency on the project is super appreciated. Please let us know if you ever have some questions on what you're working on or have some suggestions! Would be happy to hop on a call if need be :)
