### ISSUE TITLE
Add `/` hotkey to search bar

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#64]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to add the functionality that when a user types `/` the sidebar will be focussed for text entry. The component for this can be found in [frontend/components/SearchBar.vue](https://github.com/activist-org/activist/blob/main/frontend/components/SearchBar.vue).

### Contribution

I'd be happy to work on this eventually, or also would support someone if they'd be interested in working on this feature 😊

**Comment by andrewtavis** [comment]
The sidebar that has the search bar can be found at https://activist.org/home/ for testing purposes :)

**Comment by andrewtavis** [comment]
[VueUse/useMagicKeys](https://vueuse.org/core/useMagicKeys/) would likely be the thing to use for this 😊

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis! I would like to give this issue a try. I am still reviewing the Vue documentation. But from what I have read so far, I think this will require to focus the sidebar input field by watching for an event which is triggered when '/' is pressed. Is that correct?

Might take me some time to figure the exact changes. Web dev is very new to me. I'll work on this one as fast as possible but just a small heads-up haha 😅

**Comment by SaurabhJamadagni** [comment]
@andrewtavis could you help me troubleshoot this problem. The nuxt_frontend container is failing when I run `docker-compose up`. Here's a screenshot of the error:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/68957712/221546380-d86d37a5-4c52-4851-b3de-7ca66b9de140.png">

Do you have any idea what could be causing this?

**Comment by andrewtavis** [comment]
Hey @SaurabhJamadagni! Yes I think this issue would be ideal for jumping in to the project :)

> I think this will require to focus the sidebar input field by watching for an event which is triggered when '/' is pressed. Is that correct?

That would be the method that I would use. If you want to install [VueUse/useMagicKeys](https://vueuse.org/core/useMagicKeys/) in the eventual branch and go with that method, then that'd also be fine :) The main maintainer of that is deep in the Vue community, so we should be fine with adding it as a dependency. Take your time and let me know if you're running in to any issues 😊

>  The nuxt_frontend container is failing when I run docker-compose up. Here's a screenshot of the error:

This is a known issue in #55... I've been trying to figure it out and for the initial poster it was fixed, but then now you and one other person are having issues. Let me check in on this more :)

**Comment by andrewtavis** [comment]
I'll assign you for now and get back when I have a better idea of the docker issues :)

**Comment by SaurabhJamadagni** [comment]
>  I've been trying to figure it out and for the initial poster it was fixed, but then now you and one other person are having issues. Let me check in on this more :)

Okay no problem @andrewtavis. I'll read up a bit more on Vue till then. Thanks 😊

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, Will from Scribe gave the #55 bug a look and has it figured out. Changes should be along in the coming days and we can then get started on this 😊 Sorry for the delay. Hard to fix a bug I can't reproduce 😅

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, #74 should fix the docker issue :) Can you give it a try and then we can start on this?

**Comment by SaurabhJamadagni** [comment]
Yup all working @andrewtavis. Thank you 😄

**Comment by andrewtavis** [comment]
Great to hear, @SaurabhJamadagni 😊😊

**Comment by mud1tx** [comment]
@andrewtavis I can work on this issue today only please assign it to me.

**Comment by andrewtavis** [comment]
Hey @mud1tx :) Thanks for your interest in activist! @SaurabhJamadagni would need to be open to you taking over. Happy to get your contribution if it’s alright with him, but the go ahead might not happen today 🤔

Again, appreciate your interest! 🚀

**Comment by andrewtavis** [comment]
@mud1tx, assigning you now :) Let me know if you have any questions!

**Comment by mud1tx** [comment]
@andrewtavis If I want to install a dependency what commands do I have to use npm install <package-name> or yarn install <package-name>?

**Comment by andrewtavis** [comment]
@mud1tx, it'd be `yarn install` within the `/frontend` directory :) Are you installing [VueUse/useMagicKeys](https://vueuse.org/core/useMagicKeys/)?

**Comment by mud1tx** [comment]
@andrewtavis First I am trying for [vue-shotkey](https://www.npmjs.com/package/vue-shortkey) as it has a single command for focusing 

You can point the focus with the shortcut easily. The code below reserves the ALT + I key to set the focus to the input element.

<input type="text" v-shortkey.focus="['alt', 'i']" v-model="name" />

**Comment by mud1tx** [comment]
@andrewtavis Everything is working fine but there is only one problem as I click the "/" button input box gets the focus(which is fine as this is what I have to create) but the input box also gets the value "/".I have to click backspace first then have to type whatever I want to search.

**Comment by mud1tx** [comment]
`<script setup lang="ts">
import { ref } from "vue";
import { useMagicKeys, whenever } from "@vueuse/core";
const sidebar = useSidebar();
const input = ref();
const keys = useMagicKeys();

whenever(keys.slash, () => {
  input.value.focus();
  if (input.value.value.startsWith("/")) {
    input.value.value = "";
  }
});
</script>`

This is what I have added.

**Comment by andrewtavis** [comment]
Sounds promising, @mud1tx! 🚀 We don’t have to be perfect at this point, so a basic fix for this would simply be to call something that deletes once right after you press `/` :) We do it in a [keyboard app](https://github.com/scribe-org/Scribe-iOS) that @SaurabhJamadagni and I work on all the time 😅😅😊 It looks like you already did that though :) :)

**Comment by andrewtavis** [comment]
As of now a user won’t be able to type `/` at the start of the search bar, which would be unexpected behavior. Maybe to avoid this we could add a little thing that triggers this deletion right after `input.value.focus()`?

**Comment by andrewtavis** [comment]
> Do I have to create the EventListener manually?

Sorry for not replying to this, btw! Must have slipt my mind. Looks like you figured it out though 😎

**Comment by mud1tx** [comment]
> As of now a user won’t be able to type `/` at the start of the search bar, which would be unexpected behavior. Maybe to avoid this we could add a little thing that triggers this deletion right after `input.value.focus()`?

Giving this a try😀

**Comment by mud1tx** [comment]
> > Do I have to create the EventListener manually?
> 
> Sorry for not replying to this, btw! Must have slipt my mind. Looks like you figured it out though 😎

I didn't, using MagicKeys only😂.

**Comment by andrewtavis** [comment]
All good! I’ll check what you added and we’ll see :)

**Comment by mud1tx** [comment]
https://user-images.githubusercontent.com/89539376/231997870-12cd1a79-162c-4a3b-b2b8-8cd8c38642d5.mp4

This is how it is working

**Comment by mud1tx** [comment]
One test case was not running in above code I will send another PR by the end of the day.

**Comment by andrewtavis** [comment]
Thank you, @mud1tx! Looking forward :) :)

**Comment by andrewtavis** [comment]
Closed via #98 🚀  Thank you, @mud1tx! Looking forward to the work in #82 😊
