### ISSUE TITLE
Remove Sidebar hotkey indicators for mobile

### ISSUE THREAD

**Issue by mattburnett-repo** [activist-org/activist#641]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Relates to #580. From a discussion with Andrew:

"Also something I’m realizing: we do not need the / and ^k hotkey indicators when we’re on mobile. Would you want to add in hidden md:block to those to hide them? Can also be a different issue 😊"

### Contribution

I can work on this after #580 is done and merged.

**Comment by andrewtavis** [comment]
Thanks @mattburnett-repo! Will assign to you so we have a record for it :)

**Comment by andrewtavis** [comment]
Realizing that this has been finished, so closing it up 😊 Thanks for making it, @mattburnett-repo! 🥳
