### ISSUE TITLE
Add Vue and Vite to package.json to silence frontend warnings

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#643]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

A consistent question that we get from new developers in the community is where there are so many errors in the frontend when they start Docker. One such error is:

```
warning "nuxt-icon > @nuxt/devtools-kit@1.0.6" has unmet peer dependency "vite@*".
```

I believe this is happening as we don't technically have Vue or Vite in the [package.json](https://github.com/activist-org/activist/blob/main/frontend/package.json) file as they're being added by Nuxt. Adding these in would potentially silence the errors and improve the developer experience.

Thoughts on this and an implementation welcome are!

**Comment by andrewtavis** [comment]
CC @ahmedy00 and @rigojr 👋 Would be nice to get either of your two's opinions on this!

**Comment by arescrimson** [comment]
Hi! I saw this issue and was wondering about it; looks like the error messages new developers like me are receiving looks like this(with a few more lines of errors): 
![image](https://github.com/activist-org/activist/assets/66581240/b0d98038-dc6d-4450-97d0-4cbb60cb8e79)
With this, I noticed that activist is currently using nuxt version 3.8.2, so I looked at what versions of vite and vue is specified: 
![image](https://github.com/activist-org/activist/assets/66581240/1c7b3656-503f-4433-84f5-71fb71fd2464)
I then added these specific versions in to the package.json, and restarted the frontend. This time with the build, these errors were no longer visible: 
![image](https://github.com/activist-org/activist/assets/66581240/4349e4ec-8643-4382-923f-3afafa0878ce)
However, I'm still not too sure if this is the correct way to go about this, but I'm very welcome to more experienced opinions for any guidance/confirmation. The vue/vite versions seem to be correct, but I have not tested this extensively with the new specified packages yet.

**Comment by arescrimson** [comment]
Investigating more, it looks like the Vue version is actually 3.4.5, and the Vite version is 5.0.11 for Activist Frontend usage. 

![image](https://github.com/activist-org/activist/assets/66581240/f542b1cb-5d24-4fe5-b5a5-6db8182c62b6)

Changing package.json values to these versions seems to have the same result; the errors are still not showing:

![image](https://github.com/activist-org/activist/assets/66581240/a479cf43-d3cb-4e88-9a93-c77e2b92634a)

Builds seem to be completed successfully. However, still hesitant on whether I'm going about this the right way or whether this will break things; do let me know if I'm on the right track or if you find this helpful.

**Comment by andrewtavis** [comment]
Hey @arescrimson! I got a message from @rigojr on this that there's a more intuitive way of achieving this :) Just needs to get tested a bit and then we'll know if it also works 😊 Thanks for checking my assumptions! 

For your other PR it'd be good to not include the `package.json` and `yarn.lock`. If we decide that the original idea was the best one, you'd also be welcome to send those along in a PR to close this one :)

**Comment by andrewtavis** [comment]
Hey @rigojr: realizing that we didn't talk about this in the sync. Do you have any suggestions on how else we could fix this?

**Comment by rigojr** [comment]
Hi @andrewtavis, I forgot to mentioned, the solution advised by @arescrimson is the best, for now.

My idea was similar. Some libraries used got my attention, I'll DM you about it to know more about.

**Comment by andrewtavis** [comment]
Thanks for the feedback, @rigojr! Will look out for that DM then :)

@arescrimson, do you want to work on this one too and send along a quick PR for it? Let me know and would be happy to assign!

**Comment by andrewtavis** [comment]
Feel free to send along a PR even if I haven't assigned yet, @arescrimson :)

**Comment by arescrimson** [comment]
For sure! 

> Investigating more, it looks like the Vue version is actually 3.4.5, and the Vite version is 5.0.11 for Activist Frontend usage.
> 
> ![image](https://private-user-images.githubusercontent.com/66581240/294736843-f542b1cb-5d24-4fe5-b5a5-6db8182c62b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxODE2NTksIm5iZiI6MTcwNTE4MTM1OSwicGF0aCI6Ii82NjU4MTI0MC8yOTQ3MzY4NDMtZjU0MmIxY2ItNWQyNC00ZmU1LWI1YTUtNmRiODE4MmM2MmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDIxMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMjQxYjY1NDliOGJkOTllZWY0MDVjZjBmNTk5OWEyZDI4NWRhMTVlNTUwODE2YWM1OGRhNzUzYWQ0ZGRlY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wz4NaNiZnV-lcTWjuxMpjfpCorw9HVHRCLBcgUBIrzM)
> 
> Changing package.json values to these versions seems to have the same result; the errors are still not showing:
> 
> ![image](https://private-user-images.githubusercontent.com/66581240/294736832-a479cf43-d3cb-4e88-9a93-c77e2b92634a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxODE2NTksIm5iZiI6MTcwNTE4MTM1OSwicGF0aCI6Ii82NjU4MTI0MC8yOTQ3MzY4MzItYTQ3OWNmNDMtZDNjYi00ZTg4LTlhOTMtYzc3ZTJiOTI2MzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDIxMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYmRhNTUyNTg3ZWYyMDZkOGI3YmRmNTExZDg3MTJkOWJkYTk4NTllZTM5ZDc1NGFjNTk0ZmIyYjgxODVlNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3aH8ucVQ1hRo426nqkQ4UPJz0WnnW7eehp3TmHj6PyA)
> 
> Builds seem to be completed successfully. However, still hesitant on whether I'm going about this the right way or whether this will break things; do let me know if I'm on the right track or if you find this helpful.

From this, it looks like simply having Vite and Vue in the package json itself resolves any errors logged; however I do want to double check that these are the correct versions even if Nuxt may be using its own versions instead. Once I've double checked that these are the versions that Activist is currently using, I'll put in that PR :)))

**Comment by andrewtavis** [comment]
🙌🙌 Thanks @arescrimson! Looking forward to checking it out :)

**Comment by andrewtavis** [comment]
We still have one final one from `rollup`, @arescrimson:

```
nuxt_frontend   | warning "@nuxtjs/i18n > @miyaneee/rollup-plugin-json5@1.1.2" has unmet peer dependency "rollup@^1.20.0 || ^2.0.0 || ^3.0.0".
```

Do you think this makes sense to also include?

**Comment by arescrimson** [comment]
For sure! Didn't look into this one, but if it is also another dependency that Nuxt is installing, I think that putting the version in the package/yarn lock will suppress that error as well.

**Comment by andrewtavis** [comment]
Feel free to send along a PR, @arescrimson! We can close this one up then after merge :) Already so much better without the Vue/Vite errors!

**Comment by andrewtavis** [comment]
Closed via the above referenced PRs and the commits from me to finalize `yarn.lock`. Thanks for the support here, @arescrimson! Really great to have these errors handled. Have had many discussions with people about them, so definitely will improve the dev experience.
