### ISSUE TITLE
Persistent highlight from `focus-brand` custom class

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#644]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Something that we've been noticing recently is that the [focus-brand](https://github.com/activist-org/activist/blob/fe68c9b895da943cde0034cda2ec311fcb8834ac/frontend/assets/css/tailwind.css#L46) class that determines how page elements look on focus is persistent - meaning that an item's focus indicator isn't disappearing (usually after the next interaction it goes away).

A simple way to reproduce this is:
- Go to the [help section of the documentation](https://activist.org/en/help)
- Click any option in `Resources` or `Organization` including `Help` again to reload the page
- See that the clicked option is still focused when the page is reloaded

Thoughts on this and a fix would be much appreciated!

**Comment by Jayraj-R** [comment]
If this issue is still open, I would like to give it a try

**Comment by andrewtavis** [comment]
Hey @Jayraj-R 👋 Checking in with you on this :) Is there anything I can do to support?

**Comment by devaggarwal-1** [comment]
If this issue is still not solved, I would like to work on it.

**Comment by andrewtavis** [comment]
Hey @devaggarwal-1 👋 I'd be fine with switching it over to you :) Thanks for checking in!

@Jayraj-R, please let us know if there's another issue you'd like to work on some time!

**Comment by lucianmurmurache** [comment]
@andrewtavis I can take a look at this ✋

**Comment by andrewtavis** [comment]
Thanks @lucianmurmurache!

**Comment by andrewtavis** [comment]
Closed via #756 🥳 Thanks @lucianmurmurache! :) :)
