### ISSUE TITLE
Discussion and implementation of fonts for activist

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#65]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

There hasn't been much work done for fonts for activist, so this issue would be talking about potential fonts that we could use for the project as well as implementing them once some have been chosen. My personal preference would be that we'd be using open-source fonts in line with the rest of our tooling and that for implementation we'd use Tailwind.

A big question is where we would use different fonts across the website. What makes sense to me at a minimum is that section taglines on the landing page would have a different font, with this transferring over to taglines for organizations and events in general. Page headers could also have a different font. 

Note that I'll also check with the logo designer on this as he said he might have some ideas 😊

### Contribution

Happy to discuss and implement once we have some decisions!

**Comment by rufaida99-k** [comment]
I usually look at this website for open-source fonts: [The League of Movable Type](https://www.theleagueofmoveabletype.com/)

Some fonts that are cute (and also web accessible) are:
1. [Raleway](https://www.theleagueofmoveabletype.com/raleway) 
2. [Sorts Mill Goudy](https://www.theleagueofmoveabletype.com/sorts-mill-goudy)
3. [Fanwood](https://www.theleagueofmoveabletype.com/fanwood)
4. [Linden Hill](https://www.theleagueofmoveabletype.com/linden-hill)

 :)

**Comment by andrewtavis** [comment]
Thanks for the link and the suggestions, @rufaida99-k :) :) Let me check these out and look into how to apply them with Tailwind 😊 I’ll get back to you on it all, I can update the designs for us to check, and then we can apply the new fonts 🚀

**Comment by andrewtavis** [comment]
Based on some research I decided on [Red Hat Text and Red Hat Display](https://www.redhat.com/en/about/brand/standards/typography) for the current fonts. I think that using open-source and free fonts from Red Hat fits with the overall identity of activist :)

**Comment by andrewtavis** [comment]
Closed via ad38a13 :)
