### ISSUE TITLE
Create FAQ API

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#661]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Another API that's needed for the MVP release is for FAQs for organizations. The schema for this can be found [on Figma here](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=8394%3A1496&mode=design&t=Sc1jTAYNUytljuAF-1). This would be in the [content directory of the backend](https://github.com/activist-org/activist/tree/main/backend/content).

### Contribution

Would be happy to support with this or get to it when I can :) This issue would also be great for the upcoming Code Night 🌙 on Saturday 😊

**Comment by UnknownSean8** [comment]
Hi @andrewtavis, I will be happy to take this up or #662, whichever needs to be completed first.

Thanks. :D

**Comment by andrewtavis** [comment]
Hey @UnknownSean8 👋 Are you planning on joining the dev sync later in three hours? Details are in the [Development channel on Matrix](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org?via=matrix.org&via=utwente.io&via=matrix.pierre-couy.fr). We could discuss there :) #662 would be great to get some help with, and I just sent along a first commit on that that I'll explain in there shortly 😊 We could then move over here!

**Comment by andrewtavis** [comment]
Looking forward to meeting you! 😊

**Comment by UnknownSean8** [comment]
Hi @to-sta, I implemented the Faq API in the backend, however, I couldn't access the endpoint through Postman even though it is registered in the URLs. Do you know why is it causing this?

UnknownSean8/activist@a548e13

Thanks!

**Comment by to-sta** [comment]
@UnknownSean8 You can also test your endpoint with our swagger ui implementation:

`localhost:8000/V1/schema/swagger-ui/`

What URL did you use for postman?

**Comment by UnknownSean8** [comment]
@to-sta  Sorry for the late reply. I can access swagger ui page, but I don't see my faq endpoint.

`router.register(r"faq", views.FaqViewSet)`

I registered it in the urls file, so I assume the URL should be

`localhost:8000/v1/content/faq`?

Thanks.

**Comment by to-sta** [comment]
@UnknownSean8 the URL looks fine to me. 
If you want to make the PR and I can have a look at it.

**Comment by UnknownSean8** [comment]
Okay, sure! I will make a PR, but then it won't contain the full schema of the FAQ yet.

Thanks!

**Comment by andrewtavis** [comment]
Closed via #689. Thanks for this, @UnknownSean8! Hope to see you at the sync on Saturday 😊
