### ISSUE TITLE
Refactor dropdowns and apply to SidebarLeftFooter and mobile burger menu

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#663]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The [sidebar footer](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeftFooter.vue) component has many options to create new organizations and events, find documentation, and will also enclose the user actions like signing out. We need these options to move to [HeaderWebsite](https://github.com/activist-org/activist/blob/main/frontend/components/header/HeaderWebsite.vue) for the version below the medium breakpoint (mobile) and [HeaderMobile](https://github.com/activist-org/activist/blob/main/frontend/components/header/HeaderMobile.vue) also needs a [SidebarRight](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/right/SidebarRight.vue) with these options :)

### Contribution

@tatianakharitonovich has expressed interest in working on this in #656. Please write in here so I can assign! 😊

**Comment by tatianakharitonovich** [comment]
Hi @andrewtavis! I would be happy to solve this issue!)

**Comment by andrewtavis** [comment]
Thanks @tatianakharitonovich! Let me know if there's anything I can do to support :)

**Comment by tatianakharitonovich** [comment]
H! @andrewtavis  @rigojr !
I have a counteroffer.

If I create an `index.ts` in the `contents` folder, move conts `menu` (I'll have to think of a better name) and then import that directly into the components that needs it? What do you think?

**Comment by andrewtavis** [comment]
For that directory we need to consider that that's a default Nuxt directory that's meant for CMS files. See:

https://nuxt.com/docs/guide/directory-structure/content

Maybe `types`?

**Comment by andrewtavis** [comment]
But I'd say `index.ts` would be fine :)

**Comment by rigojr** [comment]
I'd prefer `configurations` folder with the `indext.ts` and what about `navigationOption/NavigationOpiton`

**Comment by andrewtavis** [comment]
This sounds good, @rigojr, but then we should also consider whether these elements could go into one of the default folder for Nuxt so we can take advantage of auto imports. Those can be seen here: https://nuxt.com/docs/guide/directory-structure.

**Comment by tatianakharitonovich** [comment]
I am thinking about how this component `SidebarLeftFooter`  looks  in the mobile version...
I mean, what we can see when we tap the boorger? I tried to find this design but I could not :( . Could you please help me with it? 
I am just saying maybe we don't need this data in different places and can leave it here, but we need more a abstract component `SidebarLeftFooter` to use it on desktop and mobile versions.

**Comment by andrewtavis** [comment]
You can see the burger menu in the mobile view of the default route - the landing page :) We also need to add the burger menu into [HeaderMobile](https://github.com/activist-org/activist/blob/main/frontend/components/header/HeaderMobile.vue) in the same way that it's in [HeaderWebsite](https://github.com/activist-org/activist/blob/main/frontend/components/header/HeaderWebsite.vue) 😊

**Comment by tatianakharitonovich** [comment]
Thanks @andrewtavis 

As I can see this menu is very similar to `SidebarLeftFooter` so what about my suggestion: "we don't need this data in different places and can leave it here, but we need more a abstract component `SidebarLeftFooter` to use it on desktop and mobile versions"?

![image](https://github.com/activist-org/activist/assets/81374919/cdec3488-d83d-4e70-a38f-2369155feb0b)
![image](https://github.com/activist-org/activist/assets/81374919/823ca000-275d-41e1-a47c-f374469b8395)

**Comment by andrewtavis** [comment]
I'd say that it makes more sense to abstract the logic for this and then use it in both the sidebar left footer and the right sidebar for the mobile burger menu. The styling is similar enough, but the components themselves are different even in the most baseline way that for the sidebar the menus open up and for the burger menu we're dealing with a more traditional Headless UI menu.

**Comment by tatianakharitonovich** [comment]
> I'd say that it makes more sense to abstract the logic for this and then use it in both the sidebar left footer and the right sidebar for the mobile burger menu. The styling is similar enough, but the components themselves are different even in the most baseline way that for the sidebar the menus open up and for the burger menu we're dealing with a more traditional Headless UI menu.

Thanks @andrewtavis!

May I know what this menu (see attached file) looks like in the mobile version in Figma?

![menu](https://github.com/activist-org/activist/assets/81374919/8e07e6a8-ad1d-4b6b-b127-4daded33d0f2)

**Comment by andrewtavis** [comment]
Honestly I haven't designed it out yet, @tatianakharitonovich :( With that being said, we basically want the menu options to look exactly the same as those for localization and theme :) Take those options in the current right side menu and make three more for create, help and the user options, then put their options inside and we'll be good 😊 

I can also throw together a design for you if that would be helpful!

**Comment by tatianakharitonovich** [comment]
Now I got! 
Thanks a lot @andrewtavis for your explanation!

I'm very sorry for the large number of questions however it is important for me to understand the logic of what's going on 😊.

I have one more question...
Why do we want to implement different baseline ways to implement the same components?
As for me we can use the same component in desktop and mobile versions and the only difference is whether to use logic to hide the label or not.
Or maybe I am missing something important?

**Comment by andrewtavis** [comment]
Note that I do think there there will continue to need to be some minor differences based on their location. For the left sidebar footer the icons should continue to be up facing chevrons, and for the header and right sidebar they should be down facing. Also for the three new menus their colors will need to change based on locations. The left sidebar menu has `menu-selection` as the color whereas the header has `content`. I'm open for discussion on this, but I just tried changing colors for the left sidebar footer and it did not look good... Maybe we can switch the colors though 🤔

**Comment by andrewtavis** [comment]
Following up on the directory for this, @momanyisamuel was saying during the later portions of Code Night 🌙  that we will be needing a `configurations` directory for some of the things that he's working on, so let's keep that in mind as an option for a place to put some of this :)

**Comment by tatianakharitonovich** [comment]
Hi @andrewtavis!

As I see the objective of this issues have been changed a lot)
I suppose we should keep the current desig.

>Instead these three options for create, info and and the user options could simply be menu components in the [dropdown directory](https://github.com/activist-org/activist/tree/main/frontend/components/dropdown) that are then just dropped into the sidebar footer and the right sidebar for mobile. We could also make some common styling to be shared between the theme, language, and three new dropdown components 🤔

I could implement all these changes. Should it be done in this issue?

**Comment by andrewtavis** [comment]
Hi @tatianakharitonovich 👋 Sorry that the scope here has gotten so crazy. Really didn't expect some of the good points that are coming out of the discussion. I think that the above refactoring would be best if you'd agree that this is the appropriate plan forward 😊

**Comment by tatianakharitonovich** [comment]
Great!

This refactoring will take some time).
But I think that this issue should be renamed).
Oh, and one more thought, I would make an abstract generic `Dropdown` component and use it to develop  [DropdownTheme](https://github.com/activist-org/activist/blob/main/frontend/components/dropdown/DropdownTheme.vue), [DropdownLanguage](https://github.com/activist-org/activist/blob/main/frontend/components/dropdown/DropdownLanguage.vue), `DropdownCreate`, `DropdownInfo`, `DropdownUserOptions`.

**Comment by andrewtavis** [comment]
Agreed and renamed! I'd very much support a `DropdownBase` component that's then loaded in to the others, @tatianakharitonovich! Thanks for the willingness to take this on! 

Another minor thing that I noticed during some coding just now, I [reverted some of the label changes that you made](https://github.com/activist-org/activist/commit/a3fd3eef7f4690e0e49c22daa2f3ab9e6d98ede6#diff-57c594961d068830105d9be01c8203254dd82bd4e123cec457af7dafd01a39d4) in the PR just now to something that isn't quite as nice. Wanted to explain this really quick :) In [frontend/i18n](https://github.com/activist-org/activist/tree/main/frontend/i18n) there are two Python scripts that run in a [PR workflow](https://github.com/activist-org/activist/blob/main/.github/workflows/pr_ci_i18n.yaml) that check i18n keys for us. We need all the keys to appear in full in the code, so we sadly can't split them up and apply only the last parts of the keys as variables :( Is a bit of a drag, but we'll need these functions later once we start with localization to make sure that people who are helping with i18n don't need to translate things that don't exist in the codebase or aren't translating the same string more than once. Hope this makes sense! 😊

**Comment by rigojr** [comment]
Howdy, sorry, forgot to participate early. I'm down for the abstraction approach for the dropdown, @tatianakharitonovich let me know if you need any help.

**Comment by tatianakharitonovich** [comment]
Hi there! @andrewtavis , I have sent PR for review.
All styles are saved)

Looking forward to hearing from you)

**Comment by andrewtavis** [comment]
Really grateful for the work here, @tatianakharitonovich! I'll get to the review in the coming days :)

**Comment by andrewtavis** [comment]
Minor changes that went through in 0fb9a0a:
- I made the dropdown styling consistent where we get an orange background even in the left sidebar footer as I felt like the consistency would be nice and overall felt like it looked better :)
- Removed some word spacing that was effecting sidebar right's menu options
- Added focus brand to the left sidebar footer menu dropdown so it's consistent with the rest
- Added the theme and language options to sidebar right (maybe they'll move to settings eventually)

Thanks for all the work and discussion here, @tatianakharitonovich and @rigojr! Really happy to have this finished up and it's going to help the usability/maintainability so much 😊

- Note that #741 was made for a final touch here for easier access of other page elements :)
