### ISSUE TITLE
[Deleted] Implement SSR / SSG for FAQ Pages

### ISSUE THREAD

**Issue by mattburnett-repo** [activist-org/activist#668]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Investigate options / possibly implement server side rendering (SSR) and / or static site generation (SSG) for FAQ pages. The assumption is that content for FAQ pages will not change very often, and SSR / SSG is likely a better approach to create / deliver FAQ content.

Do this once the FAQ API is operational.

**Comment by andrewtavis** [comment]
Blocked by #661 :)

**Comment by andrewtavis** [comment]
Closing this for now, @mattburnett-repo, as I think that it is fine that we have FAQs function the same as the rest of the text content for an organization, etc :)
