### ISSUE TITLE
Create route to organization vote via accepted icon

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#669]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now we can see the votes that an organization receives to get onto activist by setting the status of the organization to pending. We also need to add in a route to the organizations application, which would be within the `About` route, but would be visible if the user clicks the accepted icon. Designs for this page can be seen [in the designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2642%3A20194&mode=design&t=RdDHojCud6Kv6mvh-1). We can go in and edit the [about page for organizations](https://github.com/activist-org/activist/blob/main/frontend/pages/organizations/%5Bid%5D/about.vue) to then display this.

### Contribution

Happy to support someone who has interest in working on this 😊 This is a bit difficult for a first issue, but could be doable. The big thing is that we need to display the [CardOrgApplicationVote](https://github.com/activist-org/activist/blob/5d8dac27f4163a2cbd82033e4605ce93ae49695b/frontend/pages/organizations/%5Bid%5D/about.vue#L66) that's displayed on pending and also need to add in some of the [discussion components](https://github.com/activist-org/activist/tree/main/frontend/components/card/discussion).

**Comment by andrewtavis** [comment]
CC @rigojr who has interest in the voting process :)

**Comment by rigojr** [comment]
I could help with this, let's talk more about it to see the challenges over here.

**Comment by andrewtavis** [comment]
You've got a lot on your plate right now, @rigojr, so let's not worry about this as much for now. Just wanted to make you aware of related work 😊 The scrollbar would definitely be the highest priority now that the images api is merged :)

**Comment by UnknownSean8** [comment]
Hi, I could work on this if it's still available. Thanks.

**Comment by andrewtavis** [comment]
Sounds good, @UnknownSean8! Happy to discuss this async, or we can also look into it in the sync 😊

**Comment by UnknownSean8** [comment]
@andrewtavis, maybe we could discuss this async first as I am not so sure if I will be able to join the sync this weekend as something came up 😟. But I will still be able to work on it over the weekends 😃.

**Comment by andrewtavis** [comment]
No stress and hope all's well, @UnknownSean8! Hope to see you soon then :) As far as the work here, let me know if you have any questions on the designs!

**Comment by UnknownSean8** [comment]
Hi @andrewtavis, quick question, is it okay if I change the component a bit? 😄

**Comment by andrewtavis** [comment]
Yes, by all means, @UnknownSean8! It's gonna be actively worked on in #564 anyway :) Just let us know what you're thinking, but should be good!

**Comment by UnknownSean8** [comment]
Okay @andrewtavis! I just wanted to add a list rendering for the CardDiscussionText so that we can just provide a list of objects and it will render each text appropriately.

<img width="697" alt="Screenshot 2024-02-13 at 2 21 59 PM" src="https://github.com/activist-org/activist/assets/45751604/9bdbadeb-e77c-4429-9dd8-9bb020fbedcb">
The current discussion looks like this.

1. Is it better to make it as a component itself? As in the whole Discussion section.
2. I don't see any place for the CardDiscussionEntry component in Figma. Where should it go?
3. For now all the data is hard-coded, do I need to implement the voting increment, and etc.?

As of now I will work on the route change first. Thanks!

**Comment by andrewtavis** [comment]
Hey @UnknownSean8 👋 Thanks for the image and the communication here. Looking great, and makes sense to send them along in a list! Answers to your questions to document what we'd talked about in the call + what we didn't cover:

1. Maybe it does make sense to make a component for all of this. You could call it `DiscussionSection.vue`:)
2. There's no discussion entry when the application has been accepted
3. No stress on the voting increment for now, but we can make an issue for that after (you'd be welcome to work on that!)

Thank you for all of this! 😊

**Comment by andrewtavis** [comment]
Heyo @UnknownSean8 👋 As we discussed in the sync, here's a bit more information about the new way we're thinking about this page:

- We'll need to add in an application menu selector (we can talk further on where this change should happen)
  - This will be the first option above `About`
- For the application page, we need a conditional rendering based on when the organization is verified or not
  - If yes, it's just the disabled conversation and the votes (no card to write in the discussion)
  - If no, then there are other elements from the `About` page as shown in the [designs on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2642%3A20983&mode=design&t=0EvydBm82e1zMogf-1)

I could maybe send along the change for the side menu that makes the page, and then you could add in the components and the conditional rendering? How does this sound? 😊

**Comment by UnknownSean8** [comment]
Sounds good to me! I don't mind working on the side menu too actually.

Thanks.

**Comment by andrewtavis** [comment]
Hey @UnknownSean8 and @GrandSuccess87 👋 

In talking about this a bit just now with @therealhoppi, how do we feel about switching the functionality such that on clicking the green check we see a tooltip that says something like "{OrgName} joined activist on {DateJoined} based on the support of {NumberOfUpdates} organizations already on activist. Click here to see their application." with "Click here" being link text that then closes the tooltip and opens a modal with the votes and the discussion beneath it? That would save us from having applications as a menu bar item that many people wouldn't need 🤔

Feedback would be appreciated! 😊

**Comment by UnknownSean8** [comment]
I think it sounds good!

Maybe instead of click, we can change it to hover for tooltip. Then a modal will pop out when clicked?

But I'm fine with both click or hover.

Thanks!

**Comment by GrandSuccess87** [comment]
Hello, this sounds great! 

I'm definitely still a fan of the tool tip popping up on hover and I think "click here" instead being a hyperlink to the application is a nice touch 👌 

The verbiage in the tool tip + modal content sounds good too!

**Comment by andrewtavis** [comment]
On hover for the tooltip sounds good to me 😊 Thanks both for the input! Let us know if you need any more direction on this, @UnknownSean8 :)

Note that I fixed a typo above: `{NumberOfUpvotes}`, not `{NumberOfUpdates}` 🙃

**Comment by UnknownSean8** [comment]
I think it's okay for now.

Just to clarify, we will not be implementing a new application page, but a tooltip on hover + a model with the application infos.

Thanks!

**Comment by andrewtavis** [comment]
> Just to clarify, we will not be implementing a new application page, but a tooltip on hover + a model with the application infos.

Exactly 😊 Thank you, @UnknownSean8!

**Comment by andrewtavis** [comment]
Lots of changes from the original plan, but this component is now merged via #742 and ln aa00072 😊 Thanks all for the discussion and especially @UnknownSean8 for the implementation!
