### ISSUE TITLE
Add MapLibre custom map option to clear directions

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#673]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The new map component can be seen at the [about page for events](https://activist.org/en/events/123/about). We're using [MapLibre GL JS](https://github.com/maplibre/maplibre-gl-js) for it, which is a fork of MabBox (some examples can be used). The user is able to click on the map to get directions, and the points and lines can also be dragged to change the route. One problem is that if the user clicks too much then the map gets messer, and there's no way to remove points. It would be great if we created a custom map option in [the MediaMap component](https://github.com/activist-org/activist/blob/main/frontend/components/media/MediaMap.vue) that would then call the following function:

```ts
function clearDirections() {
  directions?.clear();
}
```

### Contribution

Happy to discuss and help with implementation!

**Comment by andrewtavis** [comment]
This option should appear clearly in the bottom left corner of the map as soon as someone starts making a route :)

**Comment by andrewtavis** [comment]
01b82e3 adds the needed code for a button that says `Click to clear directions` on mobile screens, but it's been commented out as the button isn't clickable. Would be great if someone wanted to add this event listener functionality to this!

**Comment by andrewtavis** [comment]
@GrandSuccess87, here's the next issue we were talking about for the map :)

**Comment by nicholas-vecchio** [comment]
I'm happy to work on this @andrewtavis :)

So if I understand correctly, all that's left is to allow the clear all directions functionality to be clickable/touchable?

**Comment by andrewtavis** [comment]
Exactly, @nicholas-vecchio :) We need to be able to click it, and from there the code to show the clear directions button on mobile should be uncommented. Thanks for picking this up!

**Comment by andrewtavis** [comment]
Just checked on mobile, and all's good, @nicholas-vecchio! So amazing! Thanks again so much 😊😊

If you're interested in continuing to work on the map, the work you did here just unblocked #718 🥳 I'll write a bit more into that one now as I've just finished the designs for it 🧑‍🎨
