### ISSUE TITLE
MediaMap mobile fullscreen cut off

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#676]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

There's a general problem with the [MediaMap component](https://github.com/activist-org/activist/blob/main/frontend/components/media/MediaMap.vue) that the map is cut off at the top on mobile and we still see the the mobile header. Image of this can be seen below:

![IMG_0065](https://github.com/activist-org/activist/assets/24387426/2be167bb-543b-4b09-b168-a5df273a9391)

The map can be found on [activist.org/events/123/about](https://activist.org/events/123/about). The hard thing about this is that not reproducible on desktop as the full screen does the whole of the computer's screen...

It would be great if someone would investigate and we can then have it cover the entire screen. We use [MapLibre GL JS](https://github.com/maplibre/maplibre-gl-js) for our mapping service, so their documentation and code related to it or [MapBox](https://github.com/mapbox/mapbox-gl-js) that it was forked from would be where to look.

Happy to support or get to this myself eventually!

**Comment by andrewtavis** [comment]
Looking at it, the map seems to be shifted down completely as the attribution is also cut off.

**Comment by andrewtavis** [comment]
Hey @joaogdfaero! Would be really grateful for the support! :) Assigning you now, and please let me know if there's anything I can do to help.

**Comment by andrewtavis** [comment]
Hey @joaogdfaero 👋 Checking in to see how you're doing on this issue :) Let us know if there's anything we can do to help!

**Comment by hoang227** [comment]
Hello, it's my first time contributing to open-source! Can i try this?

**Comment by andrewtavis** [comment]
Hey @hoang227! You'd be welcome to! Thanks for your interest in helping out :) 

This one has proven to be a bit tough, so please let me know if you need some support. You can also give it your best shot and switch to another issue later if need be. Big thing is don't stress about this 😊

**Comment by andrewtavis** [comment]
It worked, @hoang227! 🥳🥳🥳🥳 Thanks so much for the contribution :) Just wasn't able to see it, but definitely exactly what we needed. Hope to work with you again 😊
