### ISSUE TITLE
Add transition to sidebar collapse

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#68]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to add a transition to the collapse of the activist sidebar. I'm not sure what the exact timing and bezier should be, but generally this would be to make the shift that happens from `sidebar.collapsed` and `sidebar.collapsedSwitch` combinations not instantaneous and have an appealing effect. We can start with 200-300 ms and test from there.

Note that the sidebar can be tested at https://activist.org/home/ :)

### Contribution

Happy to work on this eventually or support someone with interest in implementing it!

**Comment by momanyisamuel** [comment]
Hi again @andrewtavis, I would like to help with this issue.

**Comment by andrewtavis** [comment]
Great, @momanyisamuel! Thanks for your willingness to help 😊 Will assign you now, and please let me know if you need any assistance!

**Comment by momanyisamuel** [comment]
@andrewtavis I was just about to ask a question on this actually glad you brought this up! I agree it makes sense as the behavior of the expand button is tied to the side bar I will factor this into the transition as well.

**Comment by andrewtavis** [comment]
Thank you, @momanyisamuel! Looking forward to the result, and again let me know if I can help somehow :)

**Comment by momanyisamuel** [comment]
@andrewtavis so far there is no issue adding the transition however some elements are affected, i.e the `SearchBar` and `MenuSelector` they both have text that overlaps the sidebar as the transition occurs - see image below. Before i proceed i just wanted to know if these components are being reused elsewhere and you can also advise accordingly

![image](https://user-images.githubusercontent.com/4663177/226129580-fd93fcff-aaa0-4a2d-8a13-e587d33e8b28.png)

**Comment by andrewtavis** [comment]
I’d say the best thing to do would be to hide the text elements that are there are replace them once the transition has finished. How does that sound? Because as of now we also have the activist logo shrinking, which also doesn’t look great. So remove the the texts above and replace them with the new ones, but then how to do that 🤔 

This would need to be triggered on the components themselves likely. Do you want to send a PR and I can take a look, then we discuss from there?

**Comment by momanyisamuel** [comment]
sure lemme send a pull request, my worry was that the components seem to be used in other places so i was unsure about adding any CSS

**Comment by andrewtavis** [comment]
I’ll check the PR tomorrow, @momanyisamuel :) The only component that’s used in other places right now is the logo. The search bar would also translate to a different place on the screen for mobile as the plan is that it’s in the top left corner. Aside from that the components there are specific to the left side bar, and worst comes to worst we can make unique ones for this if it’s necessary 😊

**Comment by andrewtavis** [comment]
I also just made #85 that will be where the sidebar content will be kept :)

**Comment by momanyisamuel** [comment]
yeah i agree altering the speed is correct here is a gist that you can run to see an implementation of the sidebar with all the changes mentioned above 

https://gist.github.com/momanyisamuel/35249ecb24b29f63b11f1c62d7013ad6

if you run it it should show the expected behavior - if this is okay then it can be used to refactor and fix the sidebar issues.

**Comment by andrewtavis** [comment]
I really like how it's working, @momanyisamuel! Wonderful 😊

I'll go ahead and make the three issues above then and we can get started 🚀

**Comment by andrewtavis** [comment]
@momanyisamuel, I made #86, #87 and #88 just now for the above. I figure we can do the speed of it all at the end once everything's finished and we can fully see how it's all working :) Will close this one now. Thanks for the help on all this so far!

**Comment by momanyisamuel** [comment]
Glad i was able to help even if a little, reading up on Vue so i can be able to assist more.

**Comment by andrewtavis** [comment]
Looking forward to the contributions to Vue! 🚀😊
