### ISSUE TITLE
Creating a custom_settings file in the backend

### ISSUE THREAD

**Issue by kurtisolo** [activist-org/activist#683]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

I usually create a `custom_settings.py` file in the backend directory of my projects, and then import everything in `settings.py` simply using `from backend.custom_settings import *`

In this way it's much easier to manage more granular settings. For example I'm working on issue #361 and it would be good to have in the `custom_settings.py` file different values for the caching.

Example: 

```
PURPOSE_1_CACHE_DURATION = 10 #minutes
PURPOSE_2_CACHE_DURATION = 30 #minutes
```

Then in the whole backend, when caching is necessary, we can always import and use the values from the settings. For example:

```
from django.core.cache import cache
from django.conf import settings

def my_view(request):
    data = cache.get('my_data')
    if not data:
        data = calculate_heavy_data()
        cache.set('my_data', data, timeout=settings.PURPOSE_1_CACHE_DURATION*60)  #600 seconds
    return data
```

It's very practical and scalable having more granular settings in a single file, for example we can also put there the number of the pagination elements, or the imports from the .env file.

I use this approach in big projects and saves me a lot of time once it's done. Also it helps a lot keeping the `settings.py` file more clean.

### Contribution

Happy to support someone on this issue or work on it myself (I can also put this together with issue #361 )

**Comment by andrewtavis** [comment]
Hey @kurtisolo 👋 All sound good to me. Feel free to combine this with #361 :) I'll assign you now!
