### ISSUE TITLE
Make the directions for the map directions api be for walking

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#685]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Since #332 we have directions on the MediaMap component that can be found at [activist.org/events/123/about)](https://activist.org/events/123/about) :) One problem is that the directions look to be for cars, and would ideally be by foot by default. 

We use [MapLibre GL JS](https://github.com/maplibre/maplibre-gl-js) for our mapping service, so their documentation and code related to it or [MapBox](https://github.com/mapbox/mapbox-gl-js) that it was forked from would be where to look. The extension we're using [maplibre-gl-directions](https://github.com/maplibre/maplibre-gl-directions) states that it:

> Supports any [OSRM](http://project-osrm.org/) or [Mapbox Directions API](https://docs.mapbox.com/api/navigation/directions/) compatible Routing-provider.

Specifically there are some [OSRM](http://project-osrm.org/) directions for walking as seen in [their demo](https://map.project-osrm.org/). It would be great if we could make the default directions that the user receives be walking directions. Even better if it's just the default and they can select from biking or driving!

### Contribution

Happy to support with this!

**Comment by GrandSuccess87** [comment]
Hey @andrewtavis, I'm happy to work on this one!

**Comment by andrewtavis** [comment]
This would be great to get some help with, @GrandSuccess87! Let me know if you need more information for the work 😊

**Comment by andrewtavis** [comment]
I guess we can leave this open for now, @GrandSuccess87? I don't really see another viable dependency than the one we have, and it's actively maintained and really nice overall 😊 We can just hope that the interactive directions for bikes and walking will get there some day :)

This brings up though that for #718 we really can only do the layers right now, as switching the routing profile isn't gonna change anything anyway :)

**Comment by andrewtavis** [comment]
Assigning myself as well for monitoring purposes :)

**Comment by andrewtavis** [comment]
Wrote in the [maplibre-gl-directions discussions](https://github.com/maplibre/maplibre-gl-directions/discussions/228) asking about whether this is currently possible/on the roadmap :)

**Comment by andrewtavis** [comment]
Closed via de5578e, which was figured out in the [maplibre-gl-directions discussion](https://github.com/maplibre/maplibre-gl-directions/discussions/228) 🎉🥳

Thanks for the initial work here, @GrandSuccess87! We're basically already ready for events 😊

I'm going to make a new issue for changing the profiles/api via map options. Will ping you in there! Would be great to continue to work with you on this :)

**Comment by GrandSuccess87** [comment]
Hii @andrewtavis, thank you so much for assisting with this issue and reaching out to them via the discussion board to get the solution! 

I'll keep an eye out for the new issue you've mentioned!
