### ISSUE TITLE
Add Signal to Modal Share Page Component

### ISSUE THREAD

**Issue by GrandSuccess87** [activist-org/activist#694]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue will focus on adding support to share activist pages (event/organization/group) on Signal via the modal share page component.  

This component lives in [frontend/components/modal](https://github.com/activist-org/activist/tree/main/frontend/components/modal). 

Icons would ideally come from one icon source on [Icones](https://icones.js.org/) such as [CoreUI Brands](https://icones.js.org/collection/cib).  

You may also find the icons you need on [Bootstrap](https://www.figma.com/file/p0nFlH6k1C9rTBjYjjiAUV/Bootstrap-Icons-(Community)?type=design&node-id=0-1&mode=design&t=vUxUgAs8hBzCRHYc-0).

### Contribution

Happy to pair up with someone on this or tackle it myself :))

**Comment by GrandSuccess87** [comment]
Note: [Modal Share Page Component #581](https://github.com/activist-org/activist/issues/581) is in progress

**Comment by Mister-Tofu-tech** [comment]
@andrewtavis @GrandSuccess87 I created the pull request to add the icon. But am not sure what URL we are linking to from it.

**Comment by andrewtavis** [comment]
Hey @Mister-Tofu-tech 👋 Thanks for sending along the PR. I'll make some comments as there are things that would need to change, and then maybe we can figure out what URL it should point to and you can implement that as well :)

**Comment by UnknownSean8** [comment]
Hi, I would be happy to work on this. Thanks!

**Comment by andrewtavis** [comment]
@UnknownSean8 will be helping a bit on the share part of this once I bring in @Mister-Tofu-tech's PR :) Thanks, @UnknownSean8!

**Comment by andrewtavis** [comment]
Ping @UnknownSean8 👋 With ea8f4fe and #855 being merged we're ready to work on the share functionality :) Thanks for the work here, @Mister-Tofu-tech!

**Comment by andrewtavis** [comment]
Closed via #955 🚀 Thanks for the all the efforts here, all, and especially for the great execution, @UnknownSean8! We're not able to directly open Signal with a message, but copying the URL and opening the app should work well 😊
