### ISSUE TITLE
Add Mastodon to Modal Share Page Component

### ISSUE THREAD

**Issue by GrandSuccess87** [activist-org/activist#697]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue will focus on adding support to share activist pages (event/organization/group) on Mastodon via the modal share page component.  

This component lives in [frontend/components/modal](https://github.com/activist-org/activist/tree/main/frontend/components/modal). 

Icons would ideally come from one icon source on [Icones](https://icones.js.org/) such as [CoreUI Brands](https://icones.js.org/collection/cib).  

You may also find the icons you need on [Bootstrap](https://www.figma.com/file/p0nFlH6k1C9rTBjYjjiAUV/Bootstrap-Icons-(Community)?type=design&node-id=0-1&mode=design&t=vUxUgAs8hBzCRHYc-0).

### Contribution

Happy to pair up with someone on this or tackle it myself :))

**Comment by GrandSuccess87** [comment]
Note: [Modal Share Page Component #581](https://github.com/activist-org/activist/issues/581) is in progress

**Comment by andrewtavis** [comment]
Quick check on this, @GrandSuccess87, can we close this? :)

**Comment by andrewtavis** [comment]
Ah this didn't get merged as we did a v2 PR for it 😊 Closing now given #720 🥳
