### ISSUE TITLE
Add Facebook Messenger to Modal Share Page Component

### ISSUE THREAD

**Issue by GrandSuccess87** [activist-org/activist#698]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue will focus on adding support to share activist pages (event/organization/group) on Facebook Messenger via the modal share page component.  

This component lives in [frontend/components/modal](https://github.com/activist-org/activist/tree/main/frontend/components/modal). 

Icons would ideally come from one icon source on [Icones](https://icones.js.org/) such as [CoreUI Brands](https://icones.js.org/collection/cib).  

- You may also find the icons you need on [Bootstrap](https://www.figma.com/file/p0nFlH6k1C9rTBjYjjiAUV/Bootstrap-Icons-(Community)?type=design&node-id=0-1&mode=design&t=vUxUgAs8hBzCRHYc-0).

### Contribution

Happy to pair up with someone on this or tackle it myself :))

**Comment by GrandSuccess87** [comment]
Note: [Modal Share Page Component #581](https://github.com/activist-org/activist/issues/581) is in progress

**Comment by UnknownSean8** [comment]
Hi, I can work on this issue together with the other social media icons for the modal share page since I've worked on the Signal icon. Thanks!

**Comment by andrewtavis** [comment]
Thanks @UnknownSean8! Let us know if we can support somehow :) :)

**Comment by UnknownSean8** [comment]
Hi, sorry for the delay, I will finish this by this weekend.

**Comment by andrewtavis** [comment]
Nice, @UnknownSean8! Looking forward to the PR :)

**Comment by UnknownSean8** [comment]
Mhm, question: i18n checks doesn't support formatted strings?

For example: `toast(t(`components.btn_share_icon.opening_${props.text.toLowerCase()}`));`

**Comment by andrewtavis** [comment]
No they don't. It is a drawback of the system, but it's the only way to do it without getting into some really weird code parsing.

**Comment by andrewtavis** [comment]
Closed by #1070 🚀 Thanks for the dedication to getting the share modal up to a great level, @UnknownSean8! Really great to see this taking shape 😊 Would you have interest in looking into #904 now that we have a component to easily slot this styling into?
