### ISSUE TITLE
Add Facebook to Modal Share Page Component

### ISSUE THREAD

**Issue by GrandSuccess87** [activist-org/activist#699]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue will focus on adding support to share activist pages (event/organization/group) on Facebook via the modal share page component.  

This component lives in [frontend/components/modal](https://github.com/activist-org/activist/tree/main/frontend/components/modal). 

Icons would ideally come from one icon source on [Icones](https://icones.js.org/) such as [CoreUI Brands](https://icones.js.org/collection/cib).  

You may also find the icons you need on [Bootstrap](https://www.figma.com/file/p0nFlH6k1C9rTBjYjjiAUV/Bootstrap-Icons-(Community)?type=design&node-id=0-1&mode=design&t=vUxUgAs8hBzCRHYc-0).

### Contribution

Happy to pair up with someone on this or tackle it myself :))

**Comment by GrandSuccess87** [comment]
Note: [Modal Share Page Component #581](https://github.com/activist-org/activist/issues/581) is in progress

**Comment by andrewtavis** [comment]
I see you took my advice to do them all at once, @GrandSuccess87 😅😊 Thank you for all of these and spearheading such an important feature!

**Comment by GrandSuccess87** [comment]
Of course! Hahaha! It was the better option indeed 😆

**Comment by thiagogquinto** [comment]
Hey @andrewtavis, I was thinking in trying to work on the issue, and because of that I took a look on the code and noticed that there is already a code for the facebook, and to work I only had to import the ```SFacebbok```, and looks like it's working, so could I make a PR for it or is there something that we can't use in the code mentioned?

**Comment by andrewtavis** [comment]
I'll let @GrandSuccess87 give some feedback on what the status is here, @thiagogquinto :) Would be great if you could help out here though!

**Comment by GrandSuccess87** [comment]
Hii @thiagogquinto, although there's pre-existing code, you may find you run into an issue with one of the expected properties when you test it. It may just be a small one that's easily fixable.

**Comment by andrewtavis** [comment]
PR is merged, but let's not close this quite yet. Currently when I try to use it I get the following:

![Screenshot_2024-04-14 18 21 01](https://github.com/activist-org/activist/assets/24387426/d480ef86-e063-4360-b5fe-e580942282fb)

Can we play around with this a bit so we're not blocked? All the same, I wouldn't necessarily call this a bug 😅😊

**Comment by andrewtavis** [comment]
Any thoughts on this, @thiagogquinto or @GrandSuccess87? Also, with the new eslint upgrades we were getting errors for `@popup-close` instead of `popup-close`, so I changed it, but let me know if I'm not seeing something!

Thanks to you both!

**Comment by andrewtavis** [comment]
Checking this again really quick with @wkyoshida and it now actually is working to get to the login page of Facebook, so maybe there was just something with the original request coming from Netlify deploy previews. Regardless, all good 🥳 Thanks @thiagogquinto, and thanks for the issue, @GrandSuccess87!
