### ISSUE TITLE
Put exterior link icons on text baseline in /supporters and /supporter/join

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#70]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to reposition the exterior link icons found on the [supporters page](https://activist.org/supporters) and [join supporters page](https://activist.org/supporters/join) that we get via `bi:box-arrow-up-right` to be on the baseline of the text in which they're included. As of now they're a little bit lower, but it would be great if their baseline was inline with the that of letters without tails and punctuation. This change would be Tailwind based, with the corresponding page `.vue` files being [frontend/pages/supporters/index.vue](https://github.com/activist-org/activist/blob/main/frontend/pages/supporters/index.vue) and [frontend/pages/supporters/join.vue](https://github.com/activist-org/activist/blob/main/frontend/pages/supporters/join.vue :)

### Contribution

Happy to work on this eventually if no one else has interest, or also very happy to support someone if need be :)

**Comment by momanyisamuel** [comment]
Hi, I would like to help fix this bug, I would love it to be my first contribution.

**Comment by andrewtavis** [comment]
Hey @momanyisamuel! Sounds great :) :) I’ll assign you now, and please let me know if you need any assistance!

**Comment by momanyisamuel** [comment]
Hi @andrewtavis ran into an issue after running `docker-compose up`  See screenshot below
![image](https://user-images.githubusercontent.com/4663177/223654964-00bdebae-9484-43a4-a1d8-9340e3c0148f.png)

Any idea how to fix this??

**Comment by andrewtavis** [comment]
Closing this given the commit in [b70478e](https://github.com/momanyisamuel/activist/commit/b70478e629782786919e4ca833c93ef93699189d) :) Thanks, @momanyisamuel!
