### ISSUE TITLE
Add discernible name to links

### ISSUE THREAD

**Issue by lucianmurmurache** [activist-org/activist#705]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

The `activist` logo and some of the menu/navigation links do not have a clear context for screen readers. According to WCAG 2.1, under [success criterion 2.4.4](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html#dfn-programmatically-determined-link-context), links must have a purpose that can be determined by the link text alone or through the link text together with its programmatically determined link context. 

Solution:
- Adding a hidden element with more context satisfies this criterion by being descriptive enough on its own.

- Example:

  ```ts
  <a href="/">
    <p>
      <span class="sr-only">Navigate to</span> home page
    </p>
  </a>
  ```

This solution does not affect the UI or users that do not use a screen reader, the element being hidden. However, for users with a screen reader, the hidden element will be captured and provide enough context so that the user can better understand the navigation menu and/or what the logo link does.

**Comment by andrewtavis** [comment]
Really grateful to have you finding these issues and working on them, @lucianmurmurache 😊 Will get to the review in the coming days!

**Comment by andrewtavis** [comment]
Closing this as it's all finalized by #706 :) Thanks @lucianmurmurache!
