### ISSUE TITLE
API endpoints for accounts. Login, Update password, forgot password,

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#719]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We need endpoints for accounts related actions. 

- ~~signup (POST)~~ seperate issue #736 
- ~~login (POST)~~ #826
- logout (GET)
- pwreset (POST) 
- confirm-account (optional)

These API endpoints should be created via `APIView` rather than a `ViewSet`.

### Contribution

I am happy to help :)

**Comment by to-sta** [comment]
@sayik if you want to work on a endpoint the login would be good. 

The endpoint should be `/login` and you should use an `APIView` with a post method.

```python
LoginView(APIView):
     def post(self, request):
```

The serializer should only use password and email.

**Comment by to-sta** [comment]
@andrewtavis what about the email confirmation? Should we send a confirmation email after signup and disable the login till the user has confirmed his email?

**Comment by sayik** [comment]
@to-sta disabling login untill user confirms email, is supposed to reduce bot activity right ? but also at the same time its very easy to have fake email id's.

**Comment by sayik** [comment]
hi @to-sta yeah I'd like to work on /login endpoint.

**Comment by to-sta** [comment]
> @to-sta disabling login untill user confirms email, is supposed to reduce bot activity right ? but also at the same time its very easy to have fake email id's. 

Yeah, that's right and it's also simple to implement. Let's not worry about fake emails just yet.

**Comment by to-sta** [comment]
Hi @sayik do you have any update for us? Also let me know if I can help you with anything 😃

**Comment by to-sta** [comment]
We still have to work on logout and pwreset. 

@andrewtavis I would suggest we wait with pwreset till we have established a authentication method for the procedure (email, or something else.)

@sayik are you interested in working on the logout? Otherwise I would work on it by the end of the week.

**Comment by andrewtavis** [comment]
Suggestion makes sense, @to-sta!

**Comment by andrewtavis** [comment]
Hope you're well, @sayik! Let me know if you want to do a call soon :)

**Comment by sayik** [comment]
Thank you @andrewtavis  ,  Yes I would like to come on a call.

**Comment by andrewtavis** [comment]
❤️❤️❤️
