### ISSUE TITLE
[Safari] mobile hit area shifting

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#72]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Safari is currently having issues with the landing page on mobile. Specifically some of the page elements’ hit areas are not coinciding with their positioning on the page. `LabeldBtns` at times aren’t clickable within their boundaries, and the elements of the supporters section at times have hit areas that extend beyond their boundaries and interfere with other elements on the page being accessible.

**Comment by andrewtavis** [comment]
Note that the `Learn more` buttons on the landing page are working fine, so this might be an avenue for us to figure out the difference between them and the malfunctioning buttons :)

**Comment by anthonyshibitov** [comment]
Strange. This issue doesn't occur when emulating an iPhone using Safari on a Mac 🤔 but the bug does persist on my actual iPhone.

**Comment by anthonyshibitov** [comment]
Could you assign this to me? I think I might be able to fix this!

**Comment by DaniKline** [comment]
I couldn't emulate it either -- unfortunately I cannot assign, but feel free to take it on. I'm so sorry for not getting to it yet. Unfortunately life got a lot hectic this month.

**Comment by andrewtavis** [comment]
Would be awesome if you could! Obviously it’s a major priority, but then not being able to text for it I needed to focus on other things :) Assigning now. Thanks, @anthonyshibitov! 😊
