### ISSUE TITLE
Backend Logging

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#721]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We have not setup logging in our backend yet. The task would be setup the configruation for logging. 

Requirements: 
* Logs should be formatted (should be detailed enough to help discover bugs)

Here is the [django documentation](https://docs.djangoproject.com/en/5.0/topics/logging/) that can be used as a guide.  

### Contribution

I am happy to help :)

**Comment by to-sta** [comment]
@wkyoshida should we make a volume in docker-compose to map the log file location?

**Comment by wkyoshida** [comment]
I'm actually thinking we may not need to. The application could simply write out the logs as normal. We could then set up how to store the logs on the Docker side.

i.e. abstract log storage away from the application. 

Figuring out how we would like to format the logs though sounds great to me :+1:

**Comment by andrewtavis** [comment]
Closed via #735 🥳 Thanks @to-sta for the issue/change and also @wkyoshida for the input :) :)
