### ISSUE TITLE
Home screen is defaulting to the system color theme and isn't following user set preferences

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#725]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Something that was noticed during the most recent dev sync is that the [home page](https://activist.org/en/home/) is defaulting to dark mode. How to reproduce this is:

- Go to the page and see that it's in dark mode
- Go to the landing page and switch the color mode to light mode
- Go to any other page and see that the color mode selection is maintained
- Go back to the home page and it will switch to dark mode

Would be great if someone wanted to support with this! Happy to support or get to this eventually 😊

**Comment by lucianmurmurache** [comment]
@andrewtavis I can take a look at this issue ✋

**Comment by andrewtavis** [comment]
Thanks for this, @lucianmurmurache! 🎉🎉

**Comment by andrewtavis** [comment]
Closed via #733 🥳🥳🥳🥳 So happy to have this fixed as it was really annoying for a bit there 😊
