### ISSUE TITLE
Update the copyright year on the website footer dynamically

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#726]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now in the [footer components](https://github.com/activist-org/activist/tree/main/frontend/components/footer) we have 2023 as the copyright year, but it would be great if this was dynamically change using TS. The goal of this issue would be to change the current way the copyright is displayed such that the localizable text is still there, but broken into three parts where the first is `Copyright ©`, the second is the dynamic year, and the third is `activist`.

### Contribution

Happy to support someone who has interest in working on this or getting to it myself at some point!

**Comment by lucianmurmurache** [comment]
@andrewtavis I can take this one ✋

**Comment by andrewtavis** [comment]
Thanks @lucianmurmurache! Will review later tonight odds are :)

**Comment by andrewtavis** [comment]
Closed via #732 🙌 Thank you for this, @lucianmurmurache! Writing it here as well, please let us know if there are some improvements to the i18n strings that you can see that would benefit from a variable being passed to them (considering though that word orders might change in some locales).

On to the next pr 😊
