### ISSUE TITLE
Add sentence about the main project board to the roadmap

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#727]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that was realized in the last dev sync is that we need a reference to the project board on the [roadmap page](https://github.com/activist-org/activist/blob/main/frontend/pages/about/roadmap.vue). This would be added as a localizable string and would include a link to `https://github.com/orgs/activist-org/projects/1` in one of the parts :)

### Contribution

Happy to help someone who wants to work on this via providing what the text should say! Can also get to this myself eventually 😊

**Comment by thiagogquinto** [comment]
Hey @andrewtavis, could I work on it?

**Comment by andrewtavis** [comment]
Thanks for checking this, @thiagogquinto. Just didn't see it clearly with all that's going on :)

**Comment by andrewtavis** [comment]
I'm going to expand it out a bit as there likely should be some text about good first issues and the like, but I'll get to it. Great to hear from you!

**Comment by andrewtavis** [comment]
I expanded out the roadmap description in e62a6a5. We now have sections for good first issues, feature requests and bug fixes :) Thanks for the help, @thiagogquinto!
