### ISSUE TITLE
Add public copyright license for the website

### ISSUE THREAD

**Issue by nemobis** [activist-org/activist#728]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

The website contains a footer "Copyright © 2023 activist", meaning it's all rights reserved. Instead it should provide a free license like CC BY-SA 4.0 (in keeping with the AGPL license of the repository), and receive contributions under the same license.

It's also unclear what it means that the copyright belongs to "activist" given https://activist.org/it/about/impress says no legal entity exists yet, so copyright assignment is presumably not possible.

**Comment by andrewtavis** [comment]
Very good points across the board, @nemobis! Appreciate you opening the issue. Different licenses for code and content is actually something that was brought up at work recently, so I'd planned to look into it for activist. Would you say that replacing the copyright in the future as well, or once we have the legal entity we can have points on the code license, content license and copyright?

**Comment by progressive-galib** [comment]
want it done ? i can change the front end for you...

**Comment by andrewtavis** [comment]
Ya I think that it makes sense to do it, @progressive-galib :) Appreciate you bringing this back up. Can we include both AGPL and CC-BY-SA separated by a semicolon with AGPL first? From there we'd need to remove the localization key for copyright from all the `frontend/i18n` files, but I can also do that in the PR 😊

**Comment by progressive-galib** [comment]
ohh not done i will fix it tomorrow

**Comment by andrewtavis** [comment]
> btw can i talk about something else here @andrewtavis ?

Happy to chat, @progressive-galib :) Either here or in the Matrix chats that we have (link in the readme) or also email's fine (my first name @ the url).

**Comment by andrewtavis** [comment]
Result of this was changing the copyright line to localized equivalents of `License: AGPL-3.0; CC BY-SA 4.0`. Thanks for taking this on, @progressive-galib, and really appreciate you opening the issue here, @nemobis! Sorry this one took so long to close up. Please let us know if you see anything else in the platform, and I'd also say the same for Scribe as well. Really is great having your feedback on making sure that we're making the right decisions in our participation in open source!
