### ISSUE TITLE
Add animation to sidebar icon

### ISSUE THREAD

**Issue by lucianmurmurache** [activist-org/activist#729]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Currently we are replacing the icon based on the open/close state. A slightly better approach would be to rotate the icon on open/close instead, this will avoid the icon re-render while at the same time, add a little animation.

**Comment by andrewtavis** [comment]
Thanks for the issue, @lucianmurmurache! 😊

**Comment by andrewtavis** [comment]
30619ab send along some minor fixes to the transition, @lucianmurmurache 😊 I found that adding in a `pb-1` on rotation fixed the issue that the icon looked like it was moving a bit, and I slowed the duration down to 200ms. Also added in `motion-reduce:transition-none` to the one in the left sidebar header 🥳 Hope the changes make sense to you :) Thanks for the issue and the implementation!
