### ISSUE TITLE
signup API endpoint

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#736]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We need endpoints for accounts related actions. This issues is about the signup / registration endpoint. 

- signup (POST, DELETE) 

The POST and DELETE methods should be used to create and delete an account.

The API endpoints should be created via `APIView` rather than a `ViewSet`.

### Contribution

I am happy to help someone to work on this or work on this myself.

**Comment by jaymeklein** [comment]
Hey @to-sta, i would love to help in this issue and this project!
You can assign me to this issue if you want to, and if there's no one else with this in hands.
If so, could you give me some directions on the already built API? Where should i create this `signup (POST, DELETE)` endpoint? i couldn't find anything in the [CONTRIBUTING.md](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md) file about this specific topic.

I already have some experience with APIs (mostly with [Flask](https://flask.palletsprojects.com/en/3.0.x/)), but i can learn Django in no time.

Best regards.

**Comment by andrewtavis** [comment]
Assigning you here now, @jaymeklein 😊 Thanks for the interest in helping out! @to-sta is busy today, but he'll get back to you soon on directions for the API endpoint! Looking forward to working with you further :) :)

**Comment by jaymeklein** [comment]
Hey @andrewtavis , thanks for assigning me this issue.
I'm gonna wait until he is available to make everything here as clear as possible.

Best regards.

**Comment by to-sta** [comment]
@jaymeklein thanks for taking on this issue 😃. 

All account related API's are inside the directory `backend/authentication`. We use the [django restframework](https://www.django-rest-framework.org/) to create API's. 

You can find the User model [here](https://github.com/activist-org/activist/blob/main/backend/authentication/models.py#L49). 

We want to use the APIView class for the implementation of the post and delete method. That should look like:
```python
class SignupView(APIView):
    def post(self, request):
         pass
     
    def delete(self, request, pk):
         pass
```

I would suggest to create a seperate serializer for the API as well (instead of using UserSerializer):

```python
class SignupSerializer(serializers.ModelSerializer[User])
     ...
```

Here is the [signup form](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=3228-22748&mode=design&t=eWP7o53XZCH7blnM-4). There you can see that we are expecting a user_name, password and password_confirmed (or password1 and password2 as you see fit). 

Btw @andrewtavis shouldn't there be an email as well for the signup form?

Let me know if you have any other question 😄.

**Comment by andrewtavis** [comment]
For now, yes @to-sta we'll need an email for this. I'll add that in at some point. Eventually we do want to move away from an email signup/verification as the only option, but I guess it should still be the base :)

**Comment by jaymeklein** [comment]
Just finished setting up the development environment, and I'll be exploring the project backend so i can do it as close as possible from what you guys already built.

Your way to build APIs is kinda different from everything i've done before, so i may struggle a little bit with all that abstraction.

**Comment by andrewtavis** [comment]
Here are the rules for the password from the frontend, via a discussion with @to-sta:

![Screenshot_2024-03-16 21 09 49](https://github.com/activist-org/activist/assets/24387426/526975fc-38fd-4cd0-a208-10f2ebce1d2d)

**Comment by andrewtavis** [comment]
Closing this via #769 😊 Appreciate the help here, @jaymeklein! Hope to see you at the next sync :)

@to-sta will write an issue to do the tests (and potentially do it himself).
