### ISSUE TITLE
Switching to uv python package manager

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#737]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

A new python package manager emerged called [uv](https://astral.sh/blog/uv) from the team behind [ruff](https://docs.astral.sh/ruff/). Main benefit of switching to uv are the performance improvements (this will also reduce ci backend workflow time).

Switching would involve:

- adjustments to the readme / contrib guide 
- ci backend workflow
- updated requirements files 

There are no compatibility issues for us. It is a drop in replacement for virtualenv, pip, pip-tools (pip-compile and pip-sync). 

### Contribution

I am happy to help :)

**Comment by andrewtavis** [comment]
Let's discuss this on Tuesday, @to-sta! Thanks for looking into it :)

**Comment by to-sta** [comment]
As discussed today with @andrewtavis we are going use uv in the ci backend workflow for now.

**Comment by andrewtavis** [comment]
Closed via #745 as I figure we can open another issue for future developments for this, @to-sta 🥳 Thank you!
