### ISSUE TITLE
Rename background color custom Tailwind classes

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#739]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In discussion with a new contributor, we were thinking that it made sense to rename the background colors in a way that is indicative of their placement on the page in terms of layers. The current names we use now are `content`, `distinct` and `header`, but this does not adequately explain the usage of these classes. The decision that was made was to rename these to `layer-0`, `layer-1` and `layer-2` respectively.

### Contribution

Happy to review and bring these changes in when the PR comes through 😊

**Comment by bozmen** [comment]
I can help with that and sounds like a good first issue!

**Comment by andrewtavis** [comment]
Hey @bozmen, also we should rename the text over header classes such that they're `text-over-layer-2` and `distinct-text-over-layer-2`. Maybe we can remove these, but they are specifically used in cases where the opacity was causing an element below to be visible :)

**Comment by andrewtavis** [comment]
07ed4af also sends along the changes to the text over header layers, @bozmen 😊 Thanks for the help here! Hope to see you at the sync so we can discuss this with the team!
