### ISSUE TITLE
Go to next page element on tab when in open dropdowns

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#741]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

One minor change that would be great to have now that #702 is merged is that we should jump to the next option in item on the page when the user hits tab within a dropdown in SidebarLeftFooter. So on [activist.org/home](https://activist.org/en/home/), if the user tabs to `Create` and then hits down or return to open the menu, and then afterwards hits tab, then `Info` should then be focussed.

### Contribution

Happy to support on this or get to it myself a bit later if need be 😊

**Comment by andrewtavis** [comment]
Note that this change could likely occur on [DropdownBase](https://github.com/activist-org/activist/blob/main/frontend/components/dropdown/DropdownBase.vue) so that it would also take effect in the right sidebar menu :)

**Comment by andrewtavis** [comment]
@tatianakharitonovich, would this be something you'd have interest working on? Should be a bit quicker than the last issue 😊

**Comment by andrewtavis** [comment]
Thank you @tatianakharitonovich! Assigning you now, and please let me know if there's anything needed on my end 😊

**Comment by tatianakharitonovich** [comment]
Hi @andrewtavis!
For now I have found out that if we remove the transition wrapper of `MenuItems` everything work properly. I guese this is a bug of @headlessui, so I wrote to them)
Or maybe you have any idea on how to solve this?)

**Comment by andrewtavis** [comment]
Thanks for checking with the folks at Headless UI on this, @tatianakharitonovich! Want to send along a PR and we can take a look at how it's functioning without the transition? Or could we also try to do a custom tab function for them that then moves the focus one element further?

**Comment by tatianakharitonovich** [comment]
> Thanks for checking with the folks at Headless UI on this, @tatianakharitonovich! Want to send along a PR and we can take a look at how it's functioning without the transition? Or could we also try to do a custom tab function for them that then moves the focus one element further?

Hi @andrewtavis ! I have sent PR #771 to check behavior without the transition.

**Comment by andrewtavis** [comment]
Closed via #771 🥳 Thank you, @tatianakharitonovich! It's working really well 😊 Let me know on issues/a call/the sync!
