### ISSUE TITLE
Upload image functionality for the organization page images

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#746]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

A missing element for [MediaImageCarousel](https://github.com/activist-org/activist/blob/main/frontend/components/media/MediaImageCarousel.vue) is the ability to upload images. Ideally there would be an option for this in the bottom left corner of each image for those users who have edit rights to the organization `About` page. A basic plus icon that's styled similar to the expand image icon for the modal in #553 would be ideal. Note that this issue is also linked to #670 where we're discussing the necessary precautionary steps to upload an image.

As this functionality will doubtless be used in other places, it would be great if we could make a separate component for it that can then be linked to a button in `MediaImageCarousel`.

### Contribution

Designs for this are forthcoming. For initial work, it would be great if we could find a Vue library for this type of interface 😊 Happy to work on this and support!

**Comment by bozmen** [comment]
I think I can have a look at this too

**Comment by andrewtavis** [comment]
Thanks @bozmen! Assigning you now :)

**Comment by bozmen** [comment]
Hey @andrewtavis, what kind of a vue interface do you mean here?

**Comment by andrewtavis** [comment]
@bozmen, I'm honestly not even sure, so don't worry about it :) I'm assuming that there's some kind of Vue or preferably Nuxt library that we can plug in for this functionality, but I've never implemented something like this, so I'll trust your judgement on how it should be composed 😊

**Comment by andrewtavis** [comment]
Closed via #768 and uploading a new `yarn.lock` in b81fb06. All's looking really great, @bozmen! Now we just need to get the backend hooked up and do some validation for the frontend :)

Hope the weekend's going well!

**Comment by bozmen** [comment]
Hey @andrewtavis, sorry, could barely have a look here yet. I will push already what I have for the frontend, is there an existing issue for that?

**Comment by andrewtavis** [comment]
All good, @bozmen! I've done loads of styling for the frontend, but unsure what else you'd be wanting to do for it :)
