### ISSUE TITLE
Check and load in env variables for backend/db only builds

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#747]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

An issue that a contributor faced recently was that for builds that are not the full Docker build, but rather only the backend and database separately, that the environment variables within [.env.dev](https://github.com/activist-org/activist/blob/main/.env.dev) were not loaded in. Ideally we would check what the build situation is, and then in [settings.py](https://github.com/activist-org/activist/blob/main/backend/backend/settings.py) for the backend we would pass an argument to `dotenv.load_dotenv()` to load them in. Specifically, the line should be changed to:

```py
dotenv.load_dotenv(override=True, dotenv_path=Path(__file__).resolve().parent.parent.parent / ".env.dev")
```

This again should be triggered via an if clause that determines the Docker state and whether it would be necessary :)

### Contribution

Happy to look into this or support as needed!

**Comment by to-sta** [comment]
@andrewtavis I think best practice in the django world is to split the settings file into:

* base.py (shared settings amongs all enviroments)
* local.py (this would include the line above)
* development.py (development specific settings)
* production.py 

Then include the line above inside the local.py settings file. Determine the appropriate settings file based on an environment variable (e.g., mode="Production"). If the mode is neither set to `Production` nor `Development`, default to the `Local` settings.

**Comment by bharath637462** [comment]
@to-sta @andrewtavis can i work on this issue?

**Comment by to-sta** [comment]
Sure, @bharath637462. Please name the env. variable `DJANGO_ENV`.

**Comment by bharath637462** [comment]
@to-sta 
when i run the docker it does not read the env variables.
if i add DJANGO_ENV in env and 

settings.py
if DJANGO_ENV:
dotenv.load_dotenv(override=True, dotenv_path=Path(__file__).resolve().parent.parent.parent / ".env.dev")

how will it work? i Think it cant read DJANGO_ENV


i have put statically the var true and false

docker_build_condition = False  # Example: Set to True for demonstration

django_stubs_ext.monkeypatch(extra_classes=(viewsets.ModelViewSet,))
if docker_build_condition:
    dotenv.load_dotenv(override=True, dotenv_path=Path(__file__).resolve().parent.parent.parent / ".env.dev")
    
    
    still is not working

**Comment by bharath637462** [comment]
i have changed .env.dev to .env now docker compose working

**Comment by andrewtavis** [comment]
Ping @anthonyshibitov for an issue that you could pick up :)

**Comment by cquinn540** [comment]
Does this still need work?

**Comment by andrewtavis** [comment]
Hi @cquinn540 👋 Yes this does still need to be done :) Would you like to work on it?

**Comment by kiran7902** [comment]
I will work on this if cquinn540 is not available

**Comment by andrewtavis** [comment]
@cquinn540, let us know on if you'd like to work on this :) Thanks for you interest, @kiran7902!

**Comment by cquinn540** [comment]
I played around with it on Tuesday, and I'm pretty sure I have a fix
