### ISSUE TITLE
Replace motion-reduce tailwind classes with reduced-motion package

### ISSUE THREAD

**Issue by lucianmurmurache** [activist-org/activist#748]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

A more simplified approach to handling `prefers-reduced-motion` user preference. Instead of always having to manually add `motion-reduce:transition-none` or `motion-safe:animate-wiggle`, we can use this [npm](https://www.npmjs.com/package/reduced-motion?activeTab=readme) (shameless plug) package that handles this if the user preference is detected.

**Comment by andrewtavis** [comment]
47bac0f is the edit of the changelog for this, @lucianmurmurache 😊 Thanks for the consideration and implementation here!
