### ISSUE TITLE
Use MetaTagSocialMedia in LandingCommunityBanner and footers

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#750]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

A simple change to make the code a bit more maintainable would be if we use [MetaTagSocialMedia](https://github.com/activist-org/activist/blob/main/frontend/components/meta-tag/MetaTagSocialMedia.vue) in [LandingCommunityBanner](https://github.com/activist-org/activist/blob/main/frontend/components/landing/LandingCommunityBanner.vue) such that the presentation of social media sites is consistent. We could also use it in the [footer components](https://github.com/activist-org/activist/tree/main/frontend/components/footer/flex). For this we'd need to add some properties to text and icon sizes.

### Contribution

Happy to support someone who has interest in working on this! 😊

**Comment by SukhOberoi** [comment]
Hi, can i try to work on this?

**Comment by andrewtavis** [comment]
Thanks for your willingness to help and your interest in activist, @SukhOberoi! Perfect timing too as I was just talking about this issue in our developer sync as something that would be good for someone to work on 😊 Please let me know if there's anything I can do to help!

**Comment by andrewtavis** [comment]
Closed via #754 🚀 Thanks for the hard work and great first contribution, @SukhOberoi! 🙌
