### ISSUE TITLE
Prevent map directions when clicking on a map marker

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#767]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Since #332 we have directions on the MediaMap component that can be found at [activist.org/events/123/about)](https://activist.org/events/123/about) :) One problem is that the directions are started even when a user is clicking on a map marker.

We use [MapLibre GL JS](https://github.com/maplibre/maplibre-gl-js) for our mapping service, so their documentation and code related to it or [MapBox](https://github.com/mapbox/mapbox-gl-js) that it was forked from would be where to look. The extension we're using for directions is [maplibre-gl-directions](https://github.com/maplibre/maplibre-gl-directions).

### Contribution

Happy to discuss, support or eventually work on this myself! 😊

**Comment by nicholas-vecchio** [comment]
Hello :) I'd like to be assigned this issue.

Just from a quick look, the most straightforward method I can think of is to simply add a html event listener to the marker. I'm not sure it's possible to use maplibre events if the icons are not custom/on their own layer, but I'd have to look into the library more first.

**Comment by andrewtavis** [comment]
Sounds good, @nicholas-vecchio! And makes sense to me :) Let me know if there's anything we can do to help 😊

**Comment by andrewtavis** [comment]
Thanks so much for this, @nicholas-vecchio 😊 Really takes the directions feature to the next level as it's now not an annoyance. Would you have interest in taking a look at #673? On desktop we have the option to clear the directions with `x`, which was implemented in that issue as well, but the last part of also clearing them on a click action such that we can also have `Click to clear directions` on mobile. As of now this code has been commented out :)

Let me know in that issue if it sounds interesting! Allowing us to click on custom elements on the map will also open up us adding in some layers components in the future :)
