### ISSUE TITLE
Add TailwindCSS prettier plugin and reorder classes

### ISSUE THREAD

**Issue by lucianmurmurache** [activist-org/activist#770]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

A great way to ensure that tailwind behaves exactly the way we intend it to, is to add this [plugin](https://www.npmjs.com/package/prettier-plugin-tailwindcss) which follows the recommended [class sorting](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted).

The PR will be a bit annoying to review as a lot of files will change, however I argue that it would be a worthwhile investment into ensuring that the styles are always applied correctly and that there are no unexpected overrides.

**Comment by lucianmurmurache** [comment]
@andrewtavis if you think headwind would be enough here, we can also keep it as is. I would be in favour of adding the plugin instead as it enforces the rules pretty much out of the box and not relying on an extension that someone can omit to add. If you agree here, I can have it ready by the end of today.

**Comment by andrewtavis** [comment]
Sounds perfect, @lucianmurmurache! I'll get it merged by the sync :)

**Comment by andrewtavis** [comment]
Closed via #772 🥳 Thank you, @lucianmurmurache!
