### ISSUE TITLE
Transparent dropdowns are difficult to read under certain circumstances

### ISSUE THREAD

**Issue by lucianmurmurache** [activist-org/activist#774]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

A bit of an edge case, but in some cases, the right sidebar dropdown menu items are not very easy to read. A possible fix here would be to add a background colour.

![Screenshot 2024-03-23 154147](https://github.com/activist-org/activist/assets/48526455/dd4486fd-ec49-4735-8208-5b9ccca78956)
![Screenshot 2024-03-23 154207](https://github.com/activist-org/activist/assets/48526455/f33b4c12-ca1d-4b78-9ddb-1e238679ba70)

**Comment by andrewtavis** [comment]
As mentioned in the call, this was definitely just introduced. I'll pick it up so that the correct color is set 😊

**Comment by andrewtavis** [comment]
Closed via #780 🥳 Thanks for the issue, @lucianmurmurache!
