### ISSUE TITLE
Prettier Tailwind sorting breaks pre-commit

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#781]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

An issue that has come up since #772 is that [pre-commit](https://pre-commit.com/) is failing for some contributors. From what we understand, some unix contributors (Mac/Linux) cannot run pre-commit with the Prettier as we're getting an error for the [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) plugin. It's expected that there could be issues for Windows users as well. The current error is:

```bash
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

[error] Cannot find package 'prettier-plugin-tailwindcss' imported from /PATH_TO_PROJECT/activist/noop.js
```

As of now the Prettier run within [.pre-commit-config.yaml](https://github.com/activist-org/activist/blob/main/.pre-commit-config.yaml) has been commented out so that people can continue to contribute.

**Comment by andrewtavis** [comment]
CC @wkyoshida, @to-sta :)

**Comment by lucianmurmurache** [comment]
Current output during commit in #782
```bash
ruff.................................................(no files to check)Skipped
ruff-format..........................................(no files to check)Skipped
prettier.............................................(no files to check)Skipped
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
check for added large files..............................................Passed
```
The **soLucian** seems to have been converting the pretier config file into `js` as well as using `module.exports = config;` instead of `export default config` I am not sure exactly why it caused any errors with the plugin declaration in `.prettierrc` or `export default config` but at this point I am not sure I want to know. Hopefully it works on your side @andrewtavis & @wkyoshida

**Comment by andrewtavis** [comment]
394cc2d ultimately closes this as [pre-commit/mirrors-prettier](https://github.com/pre-commit/mirrors-prettier) that we were using for this was archived as changes in Prettier broke it beyond maintenance capacity. In looking a bit into this, if we do want Prettier running in pre-commit hooks, then the current method is apparently to use Husky for this, but this'd be out of scope. I think we're fine with the current setup of checking it in CI for now 😊
