### ISSUE TITLE
Implement organization_image and group_image tables

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#793]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As discussed in the last dev sync, we need to include two more tables in the entities section of the backend. The first is [organization_image](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=9506%3A18406&mode=design&t=tqhftmm0YSGb3bGC-1) and the other is [group_image](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=9506%3A18406&mode=design&t=tqhftmm0YSGb3bGC-1) (links are to schemas on Figma). Along with this, we can remove the array columns in the `organization` and `group` tables that were originally meant to contain the image references.

### Contribution

Happy to assist on this as needed!

CC @bozmen so you have some overview of it for the image upload, CC @to-sta

**Comment by thiagogquinto** [comment]
Hey @andrewtavis, can I work on this?

**Comment by andrewtavis** [comment]
Please do, @thiagogquinto! Let us know if you need any assistance :)

**Comment by andrewtavis** [comment]
Closed via #796 🚀 Thanks, @thiagogquinto!
