### ISSUE TITLE
Implement group_text and organization_text tables

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#801]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In the last dev sync we had a long conversation about how to do localization for user generated content to build on #284. It was decided that we'll go towards a system where the edit icon for each editable card on each page will bring up a modal where the text for this page is able to be localized into multiple languages. For this we needed to bring out the text fields from entities like groups and organizations into separate tables, namely [group_text](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=9506%3A18406&mode=design&t=bE3ZCuXDnBOokXnF-1) and [organization_text](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=9506%3A18406&mode=design&t=bE3ZCuXDnBOokXnF-1) (links are to schemas on Figma).

This issue is to implement both of these tables and the needed infrastructure around them in the backend. Included could also be the work for [event_text](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=9506%3A18409&mode=design&t=bE3ZCuXDnBOokXnF-1), but the entities tables are most important :) 

### Contribution

Happy to support as I can in explaining what the fields are and discussing other aspects of their usage.

CC @to-sta and @thiagogquinto for awareness on this :)

**Comment by andrewtavis** [comment]
Hey @thiagogquinto, would you be able to look into this?

**Comment by thiagogquinto** [comment]
Hey @andrewtavis, I will be able to work for this probably on next week, maybe earlier. when I be available I check igf the issue is still free so I con take it. Sounds good?

**Comment by andrewtavis** [comment]
Hey @thiagogquinto, @to-sta is gonna take this over so that we can get it in sooner rather than later. @to-sta, as discussed, it'd also be great to include `iso_code_map` in this so that we can link any text that's in there to `en` :)

**Comment by to-sta** [comment]
@andrewtavis I assume you will fetch the ISO lang. codes. But should there be anything else than a GET request that returns a list of language codes?

**Comment by andrewtavis** [comment]
Not that I can think of for now, @to-sta :) Thank you!

**Comment by andrewtavis** [comment]
Closed by #827 🎉 Thanks, @to-sta!
