### ISSUE TITLE
Modal view for all organizations involved in an event

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#802]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In line with the general designs of activist where modals are used to show further information, it'd be great if we could create a modal `ModalOrganizationOverview.vue` that would house a scrollable flex col list of all organizations that are involved in an event. This modal would be triggered by clicking `(+# more)` on events on the About page as seen in the [Figma designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2578%3A14210&mode=design&t=bE3ZCuXDnBOokXnF-1). 

Testing for this can be done on the test events page at [events/ANY_NUMBER/about](https://activist.org/en/events/123/about). This component would use [ModalBase](https://github.com/activist-org/activist/blob/main/frontend/components/modal/ModalBase.vue) as its base, with the `(+# more)` being the `normalDisplay` and the flex col display of organization names and their icons to the left would be the modal.

### Contribution

Happy to discuss the implementation for this or get to it myself eventually 😊

**Comment by tasawar-hussain** [comment]
I would like to pick this up

**Comment by andrewtavis** [comment]
Thanks, @tasawar-hussain! Would be great to get some help here :) Do your best with the styling, and I'll clean it up in review if need be 😊 Let us know if there's anything we can do to help!

**Comment by andrewtavis** [comment]
Hey @tasawar-hussain 👋 Let us know if there's anything we can do to support here :) There's no pressure on this for the coming weeks, but it will start to be more pressing in July 😊

**Comment by andrewtavis** [comment]
Hey @tasawar-hussain 👋 I'm going to unassign this one and #870 so that others can try, but please let me know if you'd like to be reassigned one of them. Hope you're well!

**Comment by rahulharpal1603** [comment]
Hello @andrewtavis  can I take up this issue?

**Comment by andrewtavis** [comment]
Sure thing, @rahulharpal1603! Please let us know if there are any questions 😊 As of now you'll likely need to create an event in the DB to test this, but hopefully in the coming days we'll get fixtures up so that you can work directly without creating events yourself. You can start orienting yourself to the project, and hopefully the events will be there for you to start working on this?

**Comment by rahulharpal1603** [comment]
> Sure thing, @rahulharpal1603! Please let us know if there are any questions 😊 As of now you'll likely need to create an event in the DB to test this, but hopefully in the coming days we'll get fixtures up so that you can work directly without creating events yourself. You can start orienting yourself to the project, and hopefully the events will be there for you to start working on this?

I would be starting to work on this soon.
I was busy with some pending PRs and college work.

**Comment by andrewtavis** [comment]
Sounds good, @rahulharpal1603! We're quite close on the fixtures. Was a bit held up with other projects, but moving back here now :)

Let me know if you have any questions setting the project up!

**Comment by Siddharthgup** [comment]
Hi @andrewtavis , Can I take up this issue ?

**Comment by andrewtavis** [comment]
@rahulharpal1603 is working on this one, @Siddharthgup :) Do you want me to suggest other issues you could check out?

@rahulharpal1603, the fixtures will be merged in with # ! Let us know if there are any questions 😊

**Comment by rahulharpal1603** [comment]
@andrewtavis I finished setting up the local environment using Docker, but how to enter the actual website from this page:

![image](https://github.com/user-attachments/assets/c6670986-3204-4c57-8717-552ecb68a32b)

**Comment by andrewtavis** [comment]
It'll be more clear after this evening, @rahulharpal1603 :) I'll bring in the PR, which will also include directions for how to access the platform 😊

**Comment by rahulharpal1603** [comment]
Okay,  thanks🙏

**Comment by rahulharpal1603** [comment]
> It'll be more clear after this evening, @rahulharpal1603 :) I'll bring in the PR, which will also include directions for how to access the platform 😊

Now can I access the page?

Also, I wanted to ask if this project can have the "hacktoberfest" topic attached to it. Also a "hacktoberfest" label to this issue?
I have registered for Hacktober Fest and this PR could help me complete one of my 4 open-source contributions 😃.

https://hacktoberfest.com/participation/#maintainers

**Comment by andrewtavis** [comment]
> Now can I access the page?

Not quite yet, but hopefully this evening :)

We are participating in Hacktoberfest, and I'll update the repo now with the Hacktoberfest topic. We don't need to add the label to this issue, but your PR will be marked with it. Remember to open it after October starts though!

**Comment by rahulharpal1603** [comment]
> > Now can I access the page?
> 
> Not quite yet, but hopefully this evening :)
> 
> We are participating in Hacktoberfest, and I'll update the repo now with the Hacktoberfest topic. We don't need to add the label to this issue, but your PR will be marked with it. Remember to open it after October starts though!

Okay 😃

**Comment by andrewtavis** [comment]
Hey @rahulharpal1603 👋 The factories have been loaded in, and there are now `View organizations` and `View events` buttons on the landing page to take you to the app. There is event page content that you can get to by click on the events, but it's not populated by the backend just yet. With that being said, maybe you can start working on the component on `frontend/pages/events/[id]/about.vue` and from there we can make sure that that page is getting data hydrated as soon as we can 😊

**Comment by rahulharpal1603** [comment]
> Hey @rahulharpal1603 👋 The factories have been loaded in, and there are now `View organizations` and `View events` buttons on the landing page to take you to the app. There is event page content that you can get to by click on the events, but it's not populated by the backend just yet. With that being said, maybe you can start working on the component on `frontend/pages/events/[id]/about.vue` and from there we can make sure that that page is getting data hydrated as soon as we can 😊

I synced my fork with this repo and ran the docker command again, but the command line is stuck in an infinite loop, displaying this from the django backend:

![image](https://github.com/user-attachments/assets/f4d2252c-39a5-4384-9dc8-1ff21328a464)

I also deleted the fork and forked again to start afresh but still the same issue :(

**Comment by andrewtavis** [comment]
Note @rahulharpal1603 that the component should be its own file and should be within gridEventOrganizations.vue, but it will appear on the page I specified :)

**Comment by andrewtavis** [comment]
Edited the above as that grid component doesn't exist. It should be in CardAboutEvent.vue :)

**Comment by rahulharpal1603** [comment]
@andrewtavis 

Is there a way to create an event in my local dev. environment.?

**Comment by andrewtavis** [comment]
Yes, @rahulharpal1603 :) I was also noting that the new generated events don't work for you as they're all one organization events. Go to localhost:8000, the backend port, and then log in with admin admin for the dev user and pass. From there you can add things into the backend via the Django admin UI 😊

**Comment by rahulharpal1603** [comment]
> Yes, @rahulharpal1603 :) I was also noting that the new generated events don't work for you as they're all one organization events. Go to localhost:8000, the backend port, and then log in with admin admin for the dev user and pass. From there you can add things into the backend via the Django admin UI 😊

I tried accesssing that, but it returns this error:
![image](https://github.com/user-attachments/assets/7524d722-edbe-4b01-9ef7-d23dd3d90201)

Although the backend is running: 
![image](https://github.com/user-attachments/assets/bfcd544a-45be-4c7d-b2a4-83aac8e9cf90)

**Comment by andrewtavis** [comment]
Can you check that you have [topics.json](https://github.com/activist-org/activist/blob/main/backend/fixtures/topics.json) locally? You've pulled the most recent changes and update your branch with them?

**Comment by rahulharpal1603** [comment]
> Can you check that you have [topics.json](https://github.com/activist-org/activist/blob/main/backend/fixtures/topics.json) locally? You've pulled the most recent changes and update your branch with them?

Yes, I have the topics.json locally: 
![image](https://github.com/user-attachments/assets/5e500a86-eb43-4db8-833e-139bc096c778)

**Comment by andrewtavis** [comment]
How are you building the project? Can you try:

```bash
docker compose --env-file .env.dev up --build
```

**Comment by andrewtavis** [comment]
This will rebuild the project and hopefully also load in the topics :)

**Comment by rahulharpal1603** [comment]
> This will rebuild the project and hopefully also load in the topics :)

Yeah, got it. I was not running with --build

**Comment by andrewtavis** [comment]
Nice! Would you suggest maybe changing the directions to with `--build` and including a comment that says that build isn't required if there are no new dependencies? As of now we have the `--build` command in a comment below the base one 🤔

**Comment by andrewtavis** [comment]
Also considering the backend, I'm not sure if more than one organization is allowed just yet, so you can make the modal for it showing just one :)

**Comment by rahulharpal1603** [comment]
> Nice! Would you suggest maybe changing the directions to with `--build` and including a comment that says that build isn't required if there are no new dependencies? As of now we have the `--build` command in a comment below the base one 🤔

Yes, I am confused when to use --build and when to not. 
What are the type of changes which would require to call the command with --build?

**Comment by andrewtavis** [comment]
New frontend dependencies or new files on general would require a rebuild :) Do you want to send along a change for this in the readme and the corresponding place in CONTRIBUTING.md? We'd change the uncommented command, add a comment that build can be removed, and remove the commented lines discussing build below :)

**Comment by rahulharpal1603** [comment]
> New frontend dependencies or new files on general would require a rebuild :) Do you want to send along a change for this in the readme and the corresponding place in CONTRIBUTING.md? We'd change the uncommented command, add a comment that build can be removed, and remove the commented lines discussing build below :)

Sure, I can add those changes in CONTRIBUTION.md

**Comment by andrewtavis** [comment]
Also in README.md :)

**Comment by andrewtavis** [comment]
Note on this as well, we should add a note that people may need to reset their browser cookies for changes to be displayed :)

**Comment by rahulharpal1603** [comment]
@andrewtavis 

![image](https://github.com/user-attachments/assets/3db5afec-762d-430e-ab19-9dcb35c0803f)


The above type of behaviour is not implemented right? As far as I have looked up, the current behaviour is: 

![image](https://github.com/user-attachments/assets/bcb498b4-fc9e-4986-a417-faf9927e8b79)

(I changed the testTechEvent to include more orgs. to see if I can get the (+# more) to display, but it isn't displaying)

**Comment by andrewtavis** [comment]
Hey @rahulharpal1603 👋 I think the (+2 more) was pre-hydration where we had just strings instead of the full organizations 🤔 You'd be free to also code that in and then use it as the target for the modal :)

**Comment by andrewtavis** [comment]
Hey @rahulharpal1603 👋 I went ahead and updated the docs really quick as this was something I felt was important to just get done for others as well. Thanks for the discussion on it!

**Comment by rahulharpal1603** [comment]
@andrewtavis Please check out the PR that I created.

**Comment by andrewtavis** [comment]
Thanks for it, @rahulharpal1603! I'll check it out and also do any needed changes as we're also quite close on the backend updates 😊
