### ISSUE TITLE
Remove scrollbar from loading screen

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#806]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

A general problem we're experiencing is that the loading screen has a scrollbar. There are a couple of different reasons for this, but overall what we're dealing with is likely Tailwind classes getting mixed or not being applied. The files in question for this are likely [Loading.vue](https://github.com/activist-org/activist/blob/main/frontend/components/Loading.vue) and [app.vue](https://github.com/activist-org/activist/blob/main/frontend/app.vue). This could also be something having to do with the [spa-loading-template.html](https://github.com/activist-org/activist/blob/main/frontend/app/spa-loading-template.html).

How to reproduce: go to any page and reload to see the activist a and a scrollbar.

Expected behavior that would close this: the activist a is still centered for the loading screen, but we don't see the scrollbar.

Happy to support on this!

**Comment by BaasanbayarOverflow** [comment]
Hello, can I be assigned to this issue?

**Comment by andrewtavis** [comment]
Sure thing, @BaasanbayarOverflow! Just assigned, and  please let us know if you need any help :)

**Comment by andrewtavis** [comment]
@BaasanbayarOverflow, quick note that I sent a large commit to the frontend just now, so it'd make sense that you branch from the most recent copy (in case you've already brought the code down locally).

**Comment by BaasanbayarOverflow** [comment]
Thank you @andrewtavis
