### ISSUE TITLE
organizations[id] sub pages are x-axis scrollable on mobile

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#809]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Currently an issue for the frontend is that most pages in the [organizations[id]](https://github.com/activist-org/activist/tree/main/frontend/pages/organizations/%5Bid%5D) route are x-axis scrollable. It's reproducible by going to a page like [activist.org/organizations/ID_NUMBER/about](https://activist.org/en/organizations/1/about) on mobile, with the content extending past the right bounds of the screen.

It's unclear which component is expanding like this. It seems like all pages except for the index are affected, with this issue also not being present on `event[id]` pages.

Would be great to have someone help out here! This is a great `good first issue` for someone who wants to jump into activist development :)

**Comment by andrewtavis** [comment]
@therealhoppi, do you know of other pages that are right scrollable?

**Comment by therealhoppi** [comment]
@andrewtavis I have surely seen this, but I personally think it is not something we would want to have on our web app. Stable up and down is the way to go for scrolling IMO :)

**Comment by andrewtavis** [comment]
What I mean is that we have this as a bug on the `organization[id]` pages and I want to fix it. Have you seen it anywhere else so I know to keep it in mind? :)

**Comment by andrewtavis** [comment]
Closed via c83b685 🥳🙌
