### ISSUE TITLE
Make docs buttons equal widths

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#82]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to make the width of the `Return home` button equal to that of the `Request access` button on pages like [activist.org/docs/get-active](https://activist.org/en/docs/get-active). On desktop it's not as much of a problem, but for mobile it would be best if both buttons were the same width.

### Contribution

Happy to work on this eventually, or also very happy to assign someone and support them 😊

**Comment by shivvamm** [comment]
can you please assign it to me i figured it out both are having the same width space but the Return Home is taking just 90 percent of it

**Comment by andrewtavis** [comment]
Hi @shivvamm 👋 Thanks for your interest in activist! Assigning you now 😊

**Comment by shivvamm** [comment]
Thank you I'll send the pr asap

**Comment by mud1tx** [comment]
@shivvamm are you still working on this issue?

**Comment by shivvamm** [comment]
No im having hard time setting up the project

**Comment by mud1tx** [comment]
@shivvamm what is the issue you are facing?

**Comment by mud1tx** [comment]
@andrewtavis Can I give this issue a try?

**Comment by andrewtavis** [comment]
Hey @mud1tx :) We’d need @shivvamm to ok transferring the issue over. 

@shivvamm, again let us know if you have questions about the environment 😊 Happy to help! Also let us know soonish as I’ll need to transfer it in a few days if we don’t hear from you. All the best!

**Comment by shivvamm** [comment]
> Hey @mud1tx :) We’d need @shivvamm to ok transferring the issue over. 
> 
> @shivvamm, again let us know if you have questions about the environment 😊 Happy to help! Also let us know soonish as I’ll need to transfer it in a few days if we don’t hear from you. All the best!

Hey yes sure its ohk you can transfer it

**Comment by andrewtavis** [comment]
Ok, will transfer it, @shivvamm :) Again please let me know if I can help you with the installation steps!

**Comment by andrewtavis** [comment]
@mud1tx, let me know if you have an questions!

**Comment by shivvamm** [comment]
> Ok, will transfer it, @shivvamm :) Again please let me know if I can help you with the installation steps!

Sure I'll let you know just trying one more time

**Comment by 1shubhankar9** [comment]
Hey @andrewtavis 
If this issue is still on and @mud1tx is not currently working on it can you assign it to me

**Comment by andrewtavis** [comment]
Hey @1shubhankar9 :) Thanks for your interest in activist! Let's give @mud1tx a moment to reply and if he's ok with it being transferred I'd be happy to assign you 😊

**Comment by andrewtavis** [comment]
Btw @mud1tx, random thing that I added to your codes for the `/` hotkey from #97 is that if the sidebar is collapsed the hotkey will now also expand it before focussing the view 😇

**Comment by mud1tx** [comment]
> Btw @mud1tx, random thing that I added to your codes for the `/` hotkey from #97 is that if the sidebar is collapsed the hotkey will now also expand it before focussing the view 😇

That's great😀

**Comment by mud1tx** [comment]
> Hey @1shubhankar9 :) Thanks for your interest in activist! Let's give @mud1tx a moment to reply and if he's ok with it being transferred I'd be happy to assign you 😊

@andrewtavis please assign it to @1shubhankar9 as I am working on some other stuff.

**Comment by mud1tx** [comment]
@andrewtavis How can I contact you.

**Comment by andrewtavis** [comment]
Reassigned to @1shubhankar9 :) Let me know if you need any help!

> @andrewtavis How can I contact you.

You can send me an email at the address in my GitHub or also reach out via a personal message in the [public matrix chats for activist](https://matrix.to/#/#activist_community:matrix.org) 😊

**Comment by andrewtavis** [comment]
79825bd was a final minor change to get a minimum viable fix for this :) Thanks all for your interest and @1shubhankar9 for the fix!
