### ISSUE TITLE
Reflect login state in UI and allow for log out

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#821]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

A large feature that's needed for the release is to reflect the login state of the user in the frontend and also allow them to log out. This would be activated via the [auth/sign-in](https://activist.org/en/auth/sign-in) page or [auth/sign-up](https://activist.org/en/auth/sign-up) page, with logout being possible via the user options in the bottom left of the screen/bottom of the left sidebar on mobile or the user options within the right sidebar menu on mobile.

### Contribution

Happy to discuss, implement or help implement!

**Comment by khushaal-nandwani** [comment]
Just getting started with activist, I think I can pick this one shall it be a good first issue

**Comment by andrewtavis** [comment]
Hey @khushaal-nandwani 👋 Sorry for the late reply here :) I've been finishing up some work for Google Summer of Code mentoring and just coming back in to work over here :)

Would be great to get some support here! Will assign you, and please let me know if there's anything we can do to support 😊

**Comment by andrewtavis** [comment]
Closed by #950 :) Thanks so much for the support, @khushaal-nandwani! Hope to see you around activist again when you've got a bit more time 😊
