### ISSUE TITLE
Typo in section "Our goals"

### ISSUE THREAD

**Issue by lioba-s** [activist-org/activist#822]
### Terms

- [X] I have searched [open and closed issues](https://github.com/activist-org/activist/issues?q=is%3Aissue)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Hi, I just had a look at the page and noticed a typo in the section "Our goals". As it's right in the beginning, it might be worth the time to change it, in the name of a great user experience. I'm only now starting out on Github and unsure of the conventions still, so creating an Issue seemed the right choice. I hope that's alright.

"The activist community is creating a global platform where movements grow and people are inspired [to] join in political actions."
There is a "to" missing here.

**Comment by andrewtavis** [comment]
Closed via #823 🎉 Thank you, @lioba-s! 😊
