### ISSUE TITLE
Implement base Playwright testing for the frontend

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#829]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In #775 we were implementing a baseline Cypress integration with the project, but the decisions was ultimately made to switch over to [Playwright](https://playwright.dev/). The goal of this issue would be to remove all files and dependencies brought in by #777, and then implement a base route test with Playwright. Once this issue is closed, we'd then create individual issues for first making tests to check that needed elements are appearing on pages in the needed forms, and from there individual tests for interactions on the platform being possible.

The work for this issue would also include adding the run of the tests to [pr_ci_frontend](https://github.com/activist-org/activist/blob/main/.github/workflows/pr_ci_frontend.yaml) 😊

Work for this generally falls within #432 as an epic :)

### Contribution

CC @aasimsyed :) Happy to discuss further and help as I can!

**Comment by andrewtavis** [comment]
@aasimsyed, feel free to write in here and I'll assign 😊

**Comment by aasimsyed** [comment]
ok. thanks, @andrewtavis

**Comment by andrewtavis** [comment]
Closed via #838 😊 Thanks so much for the immense effort into making this happen, @aasimsyed! Let me know if any of the following issues would be of interest:

- #724
- #871 
- #872

We can then schedule a call for after the 13th when I'm back to discuss making further testing issues 🚀
