### ISSUE TITLE
Create/apply margin spacing and style classes

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#83]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create a custom class within [frontend/assets/css/tailwind.css](https://github.com/activist-org/activist/blob/main/frontend/assets/css/tailwind.css) that comprises all of the Tailwind components that normally make up the margin controllers for content. `desktop-x-margins` should be added that is `@apply px-6 lg:px-10 xl:px-14`, which can then be applied to all the margins that use it in the website :)

In a similar way some other classes should be created to assure that all the headers of pages are always the same style and in the same position, as well as others to assure that the y-margins for pages are consistent for desktop and mobile.

### Contribution

Happy to work on this eventually, or if someone would like to help I'd be grateful to assign and then discuss what all needs to go into these custom Tailwind classes 😊

**Comment by momanyisamuel** [comment]
Hi @andrewtavis I would like to tackle this issue

**Comment by andrewtavis** [comment]
Sounds great, @momanyisamuel! Will assign you now, and will look into the PR you sent later today :)

**Comment by andrewtavis** [comment]
And btw, great to see you in the Matrix space! I actually was just about to invite you and then saw you were in there already 😇

**Comment by momanyisamuel** [comment]
Thanks, glad i can be of assistance. Hoping to contribute as much as I can 🙌

**Comment by momanyisamuel** [comment]
Hi @andrewtavis from your description above did you mean padding instead of margin??

**Comment by andrewtavis** [comment]
Hi @momanyisamuel 👋 Padding would be the main part of it. Sorry I said margins by mistake. The main goal is to get everything in the same place by just applying a few custom classes. Similarly the size of headers should also just be a class, which can also be for mobile as well whereas for mobile the padding is generally controlled by `w-10/12` or something similar. 

I think we’re generally using `px` and `py` for most positioning tasks, so just classes that collect all of these and allow us to apply them easily :)

Happy to answer further questions!

**Comment by momanyisamuel** [comment]
added the following classes 

```
  .responsive-px-2 {
    @apply px-6 lg:px-8 xl:px-10
  }
  .responsive-px-4 {
    @apply px-6 lg:px-10 xl:px-14
  }
  .responsive-py-2 {
    @apply py-6 lg:py-8 xl:py-10
  }
  .responsive-py-4 {
    @apply py-6 lg:py-10 xl:py-14
  }
```

not sure if this is okay, please let me know

**Comment by andrewtavis** [comment]
I like your naming criteria more than my own :) Feel free to send those along, and then we just need the sizing for the headers 😊

**Comment by momanyisamuel** [comment]
So far i have an error loading the application `[ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`
not sure what this could be about??

**Comment by andrewtavis** [comment]
You're now getting this on `docker-compose up` or the like? A bit confused myself on how this suddenly showed up 🤔

**Comment by momanyisamuel** [comment]
not using docker i just npm install and run the frontend, yeah not sure either whats causing the error

**Comment by andrewtavis** [comment]
I’m in a Mac, so I’m thinking I sadly won’t be of much help :( Can you try with Docker to see if it can work that way?

**Comment by momanyisamuel** [comment]
its okay it works on docker ill see how to fix it later.

added these styles for headings

.responsive-h1 {
    @apply py-2 lg:py-4 xl:py-6 text-2xl sm:text-3xl md:text-4xl xl:text-5xl
  }
  .responsive-h2 {
    @apply py-2 lg:py-4 xl:py-6 text-xl sm:text-2xl md:text-3xl xl:text-4xl
  }
  .responsive-h3 {
    @apply py-1 lg:py-2 xl:py-4 text-lg sm:text-xl md:text-2xl xl:text-3xl 
  }
 hope these are okay

**Comment by andrewtavis** [comment]
@momanyisamuel, I'll go through the codes and apply the new styles to the places I think they should be applied to. We can close this issue afterwards 😊

**Comment by momanyisamuel** [comment]
Glad i could be of help @andrewtavis

**Comment by andrewtavis** [comment]
Sorry for the wait on this, @momanyisamuel! I finally got around to jumping back into the margin sizes, and the work that you did really helped 😊 I reworked the baseline sizes that you made a bit so we have easy gradations just in case they're needed, and applied what I could in the project. There are doubtless some more places they could be added, but we can just keep it in mind moving forward if we see some repeated styles over breakpoints 🙃

I'll be making some more issues soonish once we're mostly done with what's here, which hopefully will be this week 🥳 The issues I'll be making are for actual components for the platform, so the work will really begin then! Thanks for the support till now! 🚀

**Comment by momanyisamuel** [comment]
@andrewtavis Its okay I have been caught up here and there too but I am really glad to see these issues closing up and happy the contributions could help. Looking forward to more work to contribute to as well. I'll keep checking this week to see what else i can help with in the meantime.

**Comment by andrewtavis** [comment]
I’m really glad to see the issues closing too 😊 Thanks for your continued dedication to activist :) :)
