### ISSUE TITLE
Map option to switch from walking to biking directions

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#832]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Now that work has been finished on #685, we're now ready to provide an option for the user to choose their routing options. The code to switch the profile is currently [commented out in the MediaMap component](https://github.com/activist-org/activist/blob/de5578e26f81c7593729f838879e4505da92d01c/frontend/components/media/MediaMap.vue#L140), with the base designs for this being found [on Figma](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2673%3A20111&mode=design&t=0Y3ZLuQIW8ks96uu-1). For this first issue, it'd be great if we gave the user the option to switch between walking and biking direction services, with another issue then following that would then add the full functionality of switching between walking, biking and driving. The default would be walking, and if the user clicks the walking icon, then the api and directions profile would be switched to the biking directions.

- Note that we can add a MediaMap option to clear the directions via the work done in #791, with the code for this starting [here](https://github.com/activist-org/activist/blob/de5578e26f81c7593729f838879e4505da92d01c/frontend/components/media/MediaMap.vue#L191). The big challenge for this will be to add in a menu option that also has an icon that's also reactive to light and dark mode.

### Contribution

Happy to support with this or get to it myself eventually! 😊

**Comment by andrewtavis** [comment]
CC @GrandSuccess87, would you have interest in working on this?

**Comment by andrewtavis** [comment]
Thanks, @GrandSuccess87! Let me know if there's anything I can do to help :) And have fun working on the map! 🗺️😊

**Comment by andrewtavis** [comment]
Further question that I have on this for maybe another issue, @GrandSuccess87: 

What about adding in a tooltip or something to the second waypoint that would show the time estimate for how long it'd take to get there? I'm realizing that the route is often times going to be the same for biking and walking, but having a time estimate would be a major distinction for it 😊

Beyond that, let's keep in mind that we'll likely want to clear there directions when the profile is changed to make sure that the user redraws the path and gets accurate directions with the new one. Would likely be ideal if we were able to reroute, but that's a separate issue. 

And a quick check on your opinion on something: should we add the route directions to the path, so the little arrows that are on the path? Might be obvious, but I'm seeing that Organic Maps does this :)

**Comment by andrewtavis** [comment]
Hey @GrandSuccess87 👋 Checking in with you on the issue :) Let me know if you want to do a call at some point to discuss the status! Hope you're well! 😊

**Comment by GrandSuccess87** [comment]
Hii @andrewtavis! Apologies! I've had some unexpected work demands popup over the last several months and as such I'm just now getting started on this + caught up on all the latest updates from the past dev syncs 🥲 

I do like the idea of adding a tool tip to the second wave point to show the time estimate as a means of distinguishing the walking / biking routes.

I also like the idea of showing the arrows in the route directions since it'll promote clarity to the user 💯 

Do we want the tool tip + addition of route directions to the path in separate tickets or part of this one? If separate tickets, I can create those too :))

**Comment by andrewtavis** [comment]
Great to hear from you, @GrandSuccess87! We're still in Code Night if you'd want to stop in and say hi :) You can probably guess who all's still in the call 😊

**Comment by andrewtavis** [comment]
> Do we want the tool tip + addition of route directions to the path in separate tickets or part of this one? If separate tickets, I can create those too :))

I think that making separate tickets would be great for that :) Feel free to create them, and thank you!

**Comment by GrandSuccess87** [comment]
Wonderful! I'm at the cafe, I'll pop in and say hello!

**Comment by GrandSuccess87** [comment]
Hey @andrewtavis! Would you happen to have a solo bike icon image I can use by any chance?  I checked the Figma, and I'm  see it's actually grouped with the others that we plan to add later.

![Screenshot 2024-05-23 at 10 45 23 PM](https://github.com/activist-org/activist/assets/32423168/4c6d0a50-d16b-4a10-846a-83f9e37d631f)

**Comment by andrewtavis** [comment]
Hey @GrandSuccess87 👋 The bike icon there can be found at [icones.js.org/collection/bi?s=bic&icon=bi:bicycle](https://icones.js.org/collection/bi?s=bic&icon=bi:bicycle) :) In case you'd like the walking one too, that's [icones.js.org/collection/bi?s=walk&icon=bi:person-walking](https://icones.js.org/collection/bi?s=walk&icon=bi:person-walking), but then I flipped it over the y-axis so the person's walking to the left 😉 Attaching an SVG for that as well :)

![bi_person_walking_left](https://github.com/activist-org/activist/assets/24387426/5bf92351-773c-4d84-8731-8940d14458dd)

**Comment by GrandSuccess87** [comment]
Got it! Tanks for sending those over!

**Comment by andrewtavis** [comment]
Closed by #901 🥳 Thanks so much for the dedication here, @GrandSuccess87! Really is such a great feature, and is only gonna get better 😊 Let me know if you have ideas for a next issue. Also happy to suggest if need be :)

**Comment by GrandSuccess87** [comment]
@andrewtavis So happy to have been a part of working on this feature 😀 I'm happy to work on #894 next or if there's another ticket you have in mind, happy to check that out!

**Comment by andrewtavis** [comment]
That'd be a good one to check out, @GrandSuccess87 :) Want to write in there so I can assign?

**Comment by andrewtavis** [comment]
Hehe nvm, you made the issue :) Assigned, and let me know if I can help!
