### ISSUE TITLE
Add GitHub Action for "ZAP Action Full Scan"

### ISSUE THREAD

**Issue by aasimsyed** [activist-org/activist#840]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

include the action for OWASP ZAP full scan:

https://github.com/marketplace/actions/zap-full-scan

**Comment by andrewtavis** [comment]
Closed by #863 with minor edits like adding a name in 883a6df :) Thanks @aasimsyed!
