### ISSUE TITLE
Base sidebar component for menu/index content

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#85]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that’s needed for the various index issues (#33, #35 and #42) is a component to house these index values. This should contain a place for an icon that will change sizes depending on whether the sidebar is collapsed as well as a list area that will have elements that link to other pages within the website.

The general thought on this component is that it will house all the logic for that content that will be inside of it, and changes in its items can then just be triggered by pages passing an argument to the [Sidebar](https://github.com/activist-org/activist/blob/main/frontend/components/Sidebar/Sidebar.vue) component :)

### Contribution

I’ll work on this after work is finished on #68 and the new issues that will come from that :)

**Comment by jpw3667** [comment]
Hello @andrewtavis, I would like to work on this issue. One question first though: do you want a base component structure that can be reused for each one, or just the three requested?

**Comment by andrewtavis** [comment]
Hey @jpw3667! Would be very helpful to get some work done on this! Thanks for your interest in activist 😊 

Generally the thought is that we’re making one component and it reacts to the page. I don’t know if portal mentioned above is something to consider right now as it should be easy enough without it. The component will also be eventually reacting to organization and event pages and thus include images, but for now let’s just get some links under as navigation options.  

Let me know if you have other thoughts/questions on this! Will assign you now as well. Let’s be in touch and I’d say focus on getting elements into the component and I can do some fine tuning at the end 😊

**Comment by jpw3667** [comment]
Is there any way for me to test my code from my computer without pushing to the main? It would be very difficult to create this new component without constant tests.

**Comment by jpw3667** [comment]
@andrewtavis ?

**Comment by andrewtavis** [comment]
@jpw3667, we're also deploying with [Netlify](https://www.netlify.com/), so when you do a PR a deployment preview will be made that we can then check on various browsers :)

> The only issue I've found is that the button to hide the size bar is inconsistent.

Firstly what's the inconsistency here?

Secondly ya this issue was poorly written out as it's something I was planning on getting to (you're of course welcome to work on it as I said 😊), but generally what we're talking about in this issue is making the following part of the sidebar as seen in [the designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=805%3A231&t=nMSPpVYOBNyzOXzm-1) (I highlighted the part in orange):

![sidebar_example](https://user-images.githubusercontent.com/24387426/236662919-70edf828-d22d-4abd-b2dd-d8cf57b4d93c.png)

This is what I mean by index content. The component is the part of the sidebar that reacts to the page. If it's an event page we see an event image and the options for different pages about the event. Similarly for organizations. For docs, help and legal we'd add an icon on top and then below would be a group of links to the content pages within each of those sections based on where the user finds themselves.

**Comment by andrewtavis** [comment]
> and put the related links in each of these pages

If you want to do an initial PR that adds what links we can into the [SidebarFooter.vue](https://github.com/activist-org/activist/blob/main/frontend/components/Sidebar/SidebarFooter.vue) component that'd be great 😊 From there let me know if you have any questions on the above!

**Comment by jpw3667** [comment]
Alright, so I'll create that new large documentation component and have it take you to the documentation page. I already see a documentation tab in the info tab, so should I replace it with the new legal page and change the info tab to the help tab like in the image you sent?
![image](https://user-images.githubusercontent.com/90777748/236693660-6865ae7f-2687-4bb1-8954-a22f091a798b.png)

**Comment by andrewtavis** [comment]
Let’s start with the links PR and then go from there :) The documentation icon should take you to `/docs` as you said, and under it there will be links to the various pages. Similarly for the help section there would be another icon and it would be populated with different options in the menu below. There should be no edits to the footer of the sidebar where the menu options are. All the changes should go into the center of the sidebar in a new component :) I can make a better mock-up in the coming days to show you 😊

I’m not sure on the PR to your fork. PRs to this repo will produce a preview, and you don’t actually need an Netlify account to see them as we have activist set up to use it. You should be able to check the local changes using the `docker-compose up` command in the root directory so long as you’ve gone through the setup, but let me know if that’s not working :)

And I’ll try out the sidebar a bit and see if I can reproduce what you described above with it timing out. Thanks for mentioning it!

**Comment by jpw3667** [comment]
Alright, I'm trying to get the docker-compose up command to work and once that gets done I'll create the documentation component in the middle. I won't worry about the footer for now.

**Comment by andrewtavis** [comment]
Sounds good! Sorry there doesn’t need to be any change to how the footer looks, but if you want to do a small PR with changing some of the links in the footer component to go to their respective pages then that’d be great 😊 That way you can also see how the PR preview works :)

**Comment by jpw3667** [comment]
I'm having some issues. I added the links to the help page and I'm trying to commit and push to try the PR preview, but when I try to git commit it thinks I've deleted all the files. 
![image](https://user-images.githubusercontent.com/90777748/236699126-b42f73db-c661-4172-afc0-7ad284642784.png)
I also downloaded docker desktop and followed the instructions, but it keeps giving me this long error. 
![image](https://user-images.githubusercontent.com/90777748/236699280-cfabdb5f-18cf-41cd-b539-0c8023530993.png)

**Comment by andrewtavis** [comment]
Hmmmm, I’m really not sure on the files being deleted 🤔 Should just be pushing to the main branch here: `git push -u origin name-of-branch`. 

Can you try running `docker-compose up —build` and let me know if the error persists? We’re apparently having issues with our docker setup as seen in #113.

**Comment by jpw3667** [comment]
Ok so the commiting issue fixed itself and I made a pull request, but the page I edited isn't linked on the main page so I don't know how to get to it from the preview. That docker command did not work, so nothing changed.
![image](https://user-images.githubusercontent.com/90777748/236702438-021c4863-2590-4ec3-9d67-18282c3b632f.png)

**Comment by andrewtavis** [comment]
You can get to the page that you edited through the directory tree. When you open the PR preview just add `/help` to the end. The link to that page is specifically [here](https://deploy-preview-115--activist-org.netlify.app/help/) though. 

Let me think on the Docker issues a bit more. Did you follow the installation steps in the readme?

**Comment by jpw3667** [comment]
I thought I did but looking at it now it says I need to install docker and docker compose. I went to the install website and docker compose took my to the regular desktop docker download, is there somewhere else to download this?

**Comment by andrewtavis** [comment]
The two links in the readme should be the ones you’re looking for. You might need to uninstall and reinstall to make sure that everything is being referenced correctly. And there’s a great chance that docker desktop also gives you docker-compose, so based on that you might just need to download Docker and Docker Desktop :)

**Comment by jpw3667** [comment]
I uninstalled and reinstalled it and it gave me the same error. The website said that docker desktop give you docker compose, but is docker itself different than docker desktop? On the website that says download docker it linked me to the docker desktop download.

**Comment by jpw3667** [comment]
Sorry, but this is for a school project and I need something tangible to submit by midnight tonight. With the discrepancies in the firefox web editor and vscode, it will be difficult to create a unique component for the documentation tab with the current issues. If we can't figure out the issues in docker soon, then I'll create a simple tab and add the links on the other pages. I can finish this task in the future once we sort it out, but I'm just letting you know that I need to submit a sizeable pull request by midnight (its 5:52pm for me). Sorry I didn't say this sooner, but I didn't think testing the page would be this much of an issue. I saw your message on the PR and can try to edit those links, but I can't find where the empty ones are supposed to link to.

**Comment by andrewtavis** [comment]
@jpw3667, glad that you have this kind of a project for school. I agree that it would have been better for you to make this clear earlier in the process. I'm a relatively responsive maintainer, but it's only me right now and I can't help with this stuff when it's early in the morning before a day of work on Monday. Some things to better understand this on my end:

1. Have you met the requirements for your project?
2. What does "sizeable pull request" mean? Number of lines of code? Number of commits?
3. If there are edits to your PR would that effect the state of your project? Specifically do you fail if in my review I request changes?
    - I'm going to write into the PR on this, but there are some baseline things that I'd need you to do before merging

For the future I definitely would make a deadline clear to a maintainer of a project so that we can communicate if we don't have the ability to help you meet the deadline. I'd also note that for something like a school project you should be looking for a GitHub issue that's marked as a `good first issue` or at the very least `help wanted`. I was planning on doing this as it's not a simple task and is further something I have specific domain knowledge of. I was happy to help you figure it out, but then had I known we were dealing with a Sunday deadline I would have suggested that we look for a different issue (I would have even made an easier one for you that's better defined).

I hope that the above doesn't come across as harsh! Just trying to use this as a teachable moment from my side as well :) I'll let you know the big thing that needs to happen in the PR and we can go from there.

**Comment by jpw3667** [comment]
Thanks for the advice. I said "sizeable pull request" because this project was on a full contribution. We had an earlier project on a bug fix, so most issues labeled good first issue would only have counted for that one. I'm honestly not sure if I met the full requirements for this project, but it was already due so it doesn't really matter anymore. Getting my pull request merged was not required for the project. Also don't worry about being harsh, I agree with everything you said. I definitely should have told you right off the bat, but I didn't think testing my code would be such an issue so I thought I'd be able to finish in time. I'll make sure to be more transparent in the future with these types of projects.

**Comment by andrewtavis** [comment]
Don’t be too harsh with yourself as well though :) This stuff happens with school, and again I’m glad to be able to work with you! Was just kind of a weird thing to wake up to on a Monday morning 😅😅😊 Thanks for the info on what’s needed for the project. Will check in in the PR :)

**Comment by andrewtavis** [comment]
@jpw3667, 9813b9a and 249a5f8 created a very baseline component that will close this issue so that #134 and #135 can be worked on and add the rest of the behavior. Please write me in #115 for adding the page links :) Would be great to get that rebased and in to the codebase 😊 

Hope you're well!
