### ISSUE TITLE
Share button text not updating reactively on screen size change

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#857]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

On the about pages for [organizations](https://github.com/activist-org/activist/blob/main/frontend/pages/organizations/%5Bid%5D/about.vue), [groups](https://github.com/activist-org/activist/blob/main/frontend/pages/organizations/%5Bid%5D/groups/%5Bid%5D/about.vue) and [events](https://github.com/activist-org/activist/blob/main/frontend/pages/events/%5Bid%5D/about.vue) we have a `BtnAction` that has functions to update the text from `Share organization`, etc to just `share` depending on the screen width. This was meant to be reactive such that button text would update on screen resize, but it's not working. This would be a great issue for someone new to the activist community to pick up and tackle! Happy to support with more context as needed 😊

**Comment by nicomaz** [comment]
I'm happy to have a go at this!

**Comment by andrewtavis** [comment]
Closed by #861 🚀 Thanks for this, @nicomaz! Let us know if there's another issue you'd have interest in! Happy to make suggestions as well 😊

**Comment by nicomaz** [comment]
No problem! I'd love to have a look at #845.
