### ISSUE TITLE
Remove Tailwind based component hiding in favor of TS breakpoint v-if conditional rendering

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#864]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Original issue:

Something that's come up is that it seems that [SidebarLeft](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeft.vue) and [MenuMobileNavigationDropdown](https://github.com/activist-org/activist/blob/main/frontend/components/menu/mobile/MenuMobileNavigationDropdown.vue) are running concurrently regardless of them being hidden at compliment breakpoints in the [sidebar layout](https://github.com/activist-org/activist/blob/main/frontend/layouts/sidebar.vue).

Further context:

The reason that this is happening is that just because the component is hidden via CSS doesn't mean that it's not loaded along with it's TS. What needs to happen is we need to switch the instance of `hidden md:block` and the like to conditional rendering based on [breakpoints in breakpoints.ts](https://github.com/activist-org/activist/blob/main/frontend/types/breakpoints.ts). With this, these components will then not be rendered at all, and we'll get dramatic speed increases for the platform 🚀

**Comment by Robot8lover** [comment]
@andrewtavis Hi, is this just a matter of switching `hidden md:block` and `md:hidden` to `v-if` (with appropriate conditionals based on breakpoint) in the [sidebar layout](https://github.com/activist-org/activist/blob/main/frontend/layouts/sidebar.vue) or is there more to it?

**Comment by andrewtavis** [comment]
Closed by #890 🚀 Thanks again for all of these amazing changes, @Robot8lover! The contributions have really been amazing, and specifically you chose some extremely important things to work on. Really hope that we can work with you again in the future, and I'd be more than happy to discuss the project with you at some point on a call if you have questions :)

Thanks again, and all the best!
