### ISSUE TITLE
Combine index menu option definitions

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#870]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The definitions for index menu options were copied in some cases, and it would be great if they could be combined. Specifically on the following two pages:

- [frontend/pages/organizations/[id]/index.vue](https://github.com/activist-org/activist/blob/main/frontend/pages/organizations/%5Bid%5D/index.vue)
- [frontend/pages/events/[id]/index.vue](https://github.com/activist-org/activist/blob/main/frontend/pages/organizations/[id]/index.vue)

we have `organizationButtons` and `eventButtons` respectively that should likely be using the logic in [useMenuEntriesState](https://github.com/activist-org/activist/blob/main/frontend/composables/useMenuEntriesState.ts).

### Contribution

Would be great if someone wanted to help with this! Happy to assist as needed or get to it myself eventually 😊

**Comment by tasawar-hussain** [comment]
I would like to take it up!

**Comment by andrewtavis** [comment]
Thanks for checking the issues and writing in so many, @tasawar-hussain! Assigning you here, and please let us know if there's something we can do to help!

**Comment by andrewtavis** [comment]
Hey @tasawar-hussain 👋 Checking in with you here :) Is there something we can do to support?

**Comment by tasawar-hussain** [comment]
Nothing right now, will start this week, and get back to you if there is something

**Comment by andrewtavis** [comment]
Sounds great, @tasawar-hussain :) Looking forward to it!

**Comment by t3azr** [comment]
Hello!! I'd like to try at this if that's okay : ). If I'm understanding/reading it right -- in both the pages, the organisation menu buttons are being manually created, and instead you want it to be done through useMenuEntriesState? Please feel free to correct me // add anything on !!

**Comment by andrewtavis** [comment]
Yes, exactly that, @t3azr! Thanks so much for your willingness to work on this! :)

**Comment by andrewtavis** [comment]
Give the contribution guide a Quick Look for the sections you'll need for this, and please let us know if there's anything you can do to help!

**Comment by t3azr** [comment]
could i just ask , in the pages provided , i can only see organisedButtons , no eventButtons . did the original post mean to also change it to eventButtons in the event page or am i missing something ? :)

**Comment by andrewtavis** [comment]
Hey @t3azr 👋 There's a chance that the original `eventButtons` got deleted, but we can take a look at this later. Do you want to implement for `organizationButtons` and we can check further in the PR once that's ready? :)

**Comment by t3azr** [comment]
Hello !! I've gotten most of it done now, I think. Just final checks. However: I came across something and I can't tell if I've misunderstood the code or if it's a bug. 

When menu entries are created it Numbers() the route value to create the ID. However, for projects and events, the route is an alphanumeric string - so this was outputting NaN. This was causing issues as the routeURL and such use that ID to create the full link/route. 

To kind of bandaid this, I've just added an intermediary idStr, which is the same as the ID, but without the Number(), as I didn't want to remove it entirely in case it's important/used elsewhere. 

However: I'm not sure where else this function is used, so I wanted to make you aware of it in case it breaks any other sites where Number() is needed!! 

The ID for each entry is left as NaN, and afaik, this hasn't caused any issues -- the buttons still redirect to its respective page. Thanks!!

**Comment by andrewtavis** [comment]
Hey @t3azr 👋 Really sorry for the delay here. I've been traveling/seeing friends and family and just barely getting to critical issues and reviews. I do have this in mind, and am on my way back home today!

Hope all's well :)

**Comment by t3azr** [comment]
thanks for your response ! no worries - i’ve just been on holiday as well  :) hope all is well for you too !

**Comment by andrewtavis** [comment]
> To kind of bandaid this, I've just added an intermediary idStr, which is the same as the ID, but without the Number(), as I didn't want to remove it entirely in case it's important/used elsewhere. So the routeURL uses idStr instead of the normal id.
> 
> However: I'm not sure where else this function is used, so I wanted to make you aware of it in case it breaks any other sites where Number() is needed!!

Am doing well, thanks :) In regards to this, I'm very happy to check out a PR with these changes and can do any cleanup that's needed 😊 Thanks so much for detailing what you're changing!

**Comment by andrewtavis** [comment]
Closed by #940 :) Thanks so much for the work here, @t3azr! Really appreciate it :) Let us know if another issue sounds appealing!
