### ISSUE TITLE
Add forget password route and link to auth pages

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#884]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

One important step that's needed for the auth pages is the route `auth/reset-password`. This should be added to the platform using the same layout as the `auth/sign-up`/`auth/sign-in` pages. Designs for this can be seen in the Figma designs [here](https://www.figma.com/design/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?node-id=9982%3A4664&t=LDNPlvnYafnH4rZP-1). We'll also need an `auth/set-password` route modeled on the designs [here](https://www.figma.com/design/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?node-id=9982%3A4763&t=LDNPlvnYafnH4rZP-1), and links to the `reset-password` page should be added to `auth/sign-in`.

A minor note on this: if the captcha failed, then the link to `auth/reset-password` on `auth/sign-in` should be disabled :)

### Contribution

This would be a great issue for someone to pick up. Most of what's needed will be handled by the [auth layout](https://github.com/activist-org/activist/blob/main/frontend/layouts/auth.vue). Would be happy to work on this myself as well, but can also support as needed!

**Comment by ahmedy00** [comment]
Hey @andrewtavis, If you assign it to me, might be a good task to comeback for a while :)

**Comment by andrewtavis** [comment]
Could not think of a better person for this task, @ahmedy00! Let me know if there's anything I can do to support :)

**Comment by andrewtavis** [comment]
Closed by #888 🥳 Thank you for your consistent work on all things authentication, @ahmedy00! Really are leaving your mark on the platform 😊
