### ISSUE TITLE
Testing for password reset in backend

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#898]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As discussed in the review for #719, the last thing that's needed is to add in testing for the password reset API. This would be added to [backend/authentication/tests.py](https://github.com/activist-org/activist/blob/main/backend/authentication/tests.py) :)

### Contribution

Happy to support and review as needed! 😊

**Comment by thesarfo** [comment]
I should be able to get this done, if it isn’t being worked on

**Comment by andrewtavis** [comment]
Thanks for offering to help, @thesarfo! Assigned :) Let us know if we can support somehow!

**Comment by andrewtavis** [comment]
Closed by #907 🚀 Thanks @thesarfo! Would be great to have you in the [Matrix chats](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org?via=matrix.org&via=utwente.io&via=matrix.pierre-couy.fr) if you're not already in there :)

**Comment by thesarfo** [comment]
Sure thing. joining right away :)

**Comment by andrewtavis** [comment]
The full space with multiple rooms is here: https://matrix.to/#/#activist_community:matrix.org. Looking forward to seeing you there!
