### ISSUE TITLE
Adjust org API create method  

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#915]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We want to create the organization_text when we create a orginization. For this the create method in the OrginizationViewSet need to be adjusted. 
 

### Contribution

I will work on this myself :)

**Comment by andrewtavis** [comment]
#916 was brought in, @to-sta, so you're good to work on this now :) Do you want to also add in the toast notification to the org creation if it's not successful?

**Comment by andrewtavis** [comment]
Closed by #921 :) Thanks, @to-sta! 🚀
