### ISSUE TITLE
Implement page checks that rely on UUIDs

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#920]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Till now the page check mechanisms we were using were based off of route parameters that just check for `organizations`, `groups`, etc, but not necessarily the full page route. Now that we're moving forward with hydration, we're now able to check for URLs based on the full route including UUIDs for the given pages. Such changes should be made to the page check mechanisms for components like the breadcrumbs and sidebar :)

### Contribution

I'll be working on this soon! 😊

**Comment by andrewtavis** [comment]
CC @mattburnett-repo - this will cover the changes we were just discussing 😊

**Comment by Aya-Abdel-Hamid** [comment]
If I understand correctly, the issue you're facing is that you cannot see the full route?
My team and I are working on a course project, and would like to help you out with this issue. Do you think it will be doable in 2 weeks?

**Comment by andrewtavis** [comment]
Hey @Aya-Abdel-Hamid 👋 I think this can be doable within a few weeks, sure :) #963 is also related to this, which could be another one you all could look at? The function in question for finding these routes is in [frontend/utils/routeUtils.ts](https://github.com/activist-org/activist/blob/main/frontend/utils/routeUtils.ts), and as you can see this really is not a robust way of checking the routes to determine key interface elements like filters and sidebar menus.

For #963 we have the issue that we used to be able to prefix all the routes, but this isn't working with Netlify now because of a bug on their end. The original logic for things like breadcrumbs was that we'd always have localized routes, and now we need to factor if they're not.

Happy to discuss this further, and let me know if you all have any ideas!

**Comment by Aya-Abdel-Hamid** [comment]
Can you please assign us this issue?

**Comment by Aya-Abdel-Hamid** [comment]
@andrewtavis Excuse me I'm really confused what you mean by your previous response, do you want us to work on this issue alone, or do you want us to work on the linked issue #963?
If possible, could you please provide us with your email address?

**Comment by andrewtavis** [comment]
You're welcome to work on this issue or #963, @Aya-Abdel-Hamid :) And my email is on my GitHub profile if you'd like to contact me there, but I'd suggest discussing here as much as we can. Does the person your working with also have GitHub? Maybe they can write in here as well?

**Comment by shgxshg** [comment]
Hi @andrewtavis . We're a group of five students contributing to this repo as part of a project. One of my teammates (@Aya-Abdel-Hamid), reached out earlier about this.

We have a week to work on our contributions and would appreciate your help in clarifying and suggesting how we could divide the work for this issue among our team members to contribute effectively.

Thanks for your time and for maintaining this project!

**Comment by andrewtavis** [comment]
Hey @shgxshg 👋 Thanks for writing in and also for letting me know what the timeframe is for this :)

For one of the contributions, we should definitely check [frontend/components/page/PageBreadcrumbs.vue](https://github.com/activist-org/activist/blob/main/frontend/components/page/PageBreadcrumbs.vue). You'll see at [this line](https://github.com/activist-org/activist/blob/d99d86749927acda272244fa98af84c316401885/frontend/components/page/PageBreadcrumbs.vue#L100) that the checks that we're doing for the check there is extremely rudimentary - just checking if `/organizations/` etc is in the URL. It'd be better if we used regex for this to check that we're on routes given exact structures, so `pageType = "organization"` would be for routes that are like `/organization/HAS_FORM_OF_A_UUID`.

The other place that we're working on these other sorts of routes is [frontend/utils/routeUtils.ts](https://github.com/activist-org/activist/blob/main/frontend/utils/routeUtils.ts) as I mentioned above, which could be another contribution? Functionality that's built via saving the route to a URL an splitting it is similarly not robust, so the goal would be to fix `isRouteActive` and `isCurrentRoutePathSubpageOf`. We could similarly use regex for this, or I'd be open to your two's suggestions!

In the review of the PR(s) I'd then check to see if we can make sure that the work for #963 is included :)

Let me know how this sounds! Happy to make further suggestions, and I'll have time to help over the weekend if we wanted to hop on a quick call.

Thanks for the communication here, both of you :)

**Comment by hkkubais** [comment]
Hello @andrewtavis, I'm part of the group working on this issue, could you please assign me to it?

**Comment by aadityanairaaq** [comment]
Hello @andrewtavis, could you please assign myself and @mohtelsayed to issue #963

**Comment by andrewtavis** [comment]
Hi @aadityanairaaq 👋 You'd need to write in #963 to be assigned :) You too, @Mohtelsayed :) #963 would ideally be fixed by [frontend/utils/routeUtils.ts](https://github.com/activist-org/activist/blob/main/frontend/utils/routeUtils.ts) changes to `isRouteActive`. There shouldn't be any changes to the backend, but fixing `isRouteActive` should be enough 😊

**Comment by andrewtavis** [comment]
@shgxshg: An issue we're dealing with here is that we can't deal with the merge conflicts for your PR likely because your GitHub account is not set up properly. You need to check that the [email you use for GitHub](https://github.com/settings/emails) matches `git config user.email`. Without this we can't see the merge conflicts on GitHub, and you further didn't give us edit access to your branch, so we can't help right now.

**Comment by andrewtavis** [comment]
Please fix your email and open a new PR or ideally get the most recent version of main and send along a new PR.

**Comment by andrewtavis** [comment]
Hey @shgxshg 👋 I replied to your message on element with a call link that you can use to join us to get some help :)
