### ISSUE TITLE
Fixtures / Factories

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#938]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We use [factory_boy](https://factoryboy.readthedocs.io/en/stable/) to create fixtures and test data. I've set up a custom management command to create random users: python manage.py populate_db --users=100.

Our plan is to extend this command to include organizations, events, and more.

TODOs:

 Add organizations
 Add events
 ...
As we add new data types, we should also validate and improve the corresponding factories.

You can find the factories in the ../factories.py files, which should accurately reflect the database models.

Note: This issue is dependent on PR #933.

### Contribution

I am happy to help :smile

**Comment by andrewtavis** [comment]
Unblocked as #933 is now merged :)

**Comment by andrewtavis** [comment]
@to-sta, maybe we can do this next so we can get back to a bit of what we had when we just had the integer routes and people could directly see the org pages, etc?

**Comment by andrewtavis** [comment]
Closed by #947 🚀🚀🚀🚀🚀🚀🚀
