### ISSUE TITLE
Add toasts for apps being opened to share modal

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#956]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to add functionality to [ModalSharePage.vue](https://github.com/activist-org/activist/blob/main/frontend/components/modal/ModalSharePage.vue) such that when another app will be opened, that the user will be notified so they're expecting it. It's up for discussion, but I'd say that displaying it for a second should be fine. So in the case of Signal, we'd show `URL copied` and at the same time show a toast for `Opening Signal` to the user.

### Contribution

Happy to support with this! If we wanted to hard code "Opening application" at fist, I'd also be happy to do the i18n key for it :)

CC @UnknownSean8 😊

**Comment by UnknownSean8** [comment]
Hi yes, I would like to take up this issue. Thanks.

**Comment by andrewtavis** [comment]
Thanks @UnknownSean8! Let us know if there are any questions :)

**Comment by andrewtavis** [comment]
Closed by #985 😊 Thanks, @UnknownSean8!
