### ISSUE TITLE
Check and fix routing based on non-localized routes

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#963]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Because of the necessary change in #962, we now have non-localized routes for English as Netlify was breaking on them. We thus need to rework the way that routes are done to allow for non `/en` routes as well, so routes that lack any localization at all.

I'll look into this!

**Comment by aadityanairaaq** [comment]
Hello @andrewtavis, could you please assign me to this issue?

**Comment by Mohtelsayed** [comment]
Hello @andrewtavis, could you please assign me to this issue as well? Thank you!

**Comment by andrewtavis** [comment]
Closed by #1059 and other related commits :) Thanks all for the great work! 🚀
