### ISSUE TITLE
map: refactor to use localized strings within map controls/interactions

### ISSUE THREAD

**Issue by wkyoshida** [activist-org/activist#968]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Like elsewhere in the application, it would be good for the map controls/interactions to also make use of localized strings.

### Contribution

Happy to support someone on this or get to it myself 😁

**Comment by akdave2003** [comment]
Hi this is Ansh, Zach and I are ready to be assigned!

**Comment by andrewtavis** [comment]
Nice! Thanks for writing in, @akdave2003 :) Let us know if there's anything we can do to support!

**Comment by akdave2003** [comment]
Hey I had a question. So in the file I started out by refactoring these strings: FOOT, BIKE, DRIVING, CAR. I also added the corresponding variables to the json file. My partner and I were wondering, would this apply to every string in the file or are there some strings we should leave alone. For example, there are two strings called api and profile, do those need to be refactored?

**Comment by andrewtavis** [comment]
Those would not need to be refactored, @akdave2003 :) The big thing is that we need `Change profile` also localized, as well as `hosted by` :) Those look to be the main ones that are needed 😊

**Comment by andrewtavis** [comment]
The API request is coming out of the component anyway, and it will be replaced with loading in the event object and then gettin the bounding box, latitude and longitude from it :)

**Comment by andrewtavis** [comment]
Hey @akdave2003 👋 I just did some major changes to how events work, so I'd suggest pulling them in. You can now navigate to an event page and see the results of your localized controls via `View events` on the development home screen and then selecting an event 😊

Please let us know if there's anything that we can do to support!

**Comment by andrewtavis** [comment]
Closing this issue because of the work in #1045, with further work to localize the preloaded Maplibre GL GS controls happening in #1071 :)

Thanks for the great contribution, @akdave2003! Hope we can work with you again soon :)
