### ISSUE TITLE
BUG: Language translation issue in Portugese

### ISSUE THREAD

**Issue by Sushil010** [activist-org/activist#987]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

When clicking on Portugese language from dropdown the main page language should change to portugese but it is still in English.

![image](https://github.com/user-attachments/assets/4cb413b2-2a67-4763-8db5-b4861352cfab)

The language on main page after clicking on "PT" dropdown should be in portugese but is still in English language. But it works for other language dropdown options.

**Comment by andrewtavis** [comment]
Hey @Sushil010 👋 This isn't so much of a bug in so far as we just don't have Portuguese localizations right now. Might make sense to remove the option at this point. Would you want to do that and then we can start including languages in the localizations only when we have the localizations?

**Comment by Sushil010** [comment]
I am fine with that and there seems to issue with spanish translation also. Only some heading and some part has been translated. Is the reason with Spanish translation also same?

**Comment by andrewtavis** [comment]
Spanish is only partially translated. We can maybe remove that one as well for now :)

**Comment by andrewtavis** [comment]
Closed by #988 :) Thanks for the issue and the quick fix, @Sushil010!
